### ISSUE TITLE
Fastest and quietest routes

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#10]
Rename 'fastest and quietest' as 'direct and quieter'.
Above 'direct and quieter' add 'direct'- this would just show the direct routes (previously fastest)

**Comment by usr110** [comment]
In the popup menu four route lines, the "Type of Route" needs to represent the changed values (direct and quieter instead of fastest and quietest)

**Comment by usr110** [comment]
@nikolai-b 
That's a neat solution - instead of changing the data, you introduced a lookup table for the new labels.

**Comment by nikolai-b** [comment]
Thanks :)
