### ISSUE TITLE
Communicate the % by car information

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#105]
This should be reported when you click on a line.

**Comment by JDWoodcock** [comment]
@audev would you be able to look at this? @usr110 should be able to help.

**Comment by audev** [comment]
@JDWoodcock  Sure. Looking into this today.

**Comment by Robinlovelace** [comment]
Great - info should be displayed for each centroid and per line if possible.

**Comment by Robinlovelace** [comment]
Closing now thanks to @audev.
