### ISSUE TITLE
Greater Manchester

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#107]
I am suggesting this as a separate issue as it is one of our test cases.
Is http://geo8.webarch.net/gm/ the correct url ? this is not the url that links from the welcome page.
http://geo8.webarch.net/gm/ does not crash :) but I was finding it very slow and 

When I change the number of line for the route network I dont seem to get a change in what is being displayed- when I have zoomed in but because of the speed it is not always clear what is  a lag and what is a final result.

**Comment by Robinlovelace** [comment]
Duplicate of this - we've discussed a fix and know how to implement it. Yes gm is the url for Greater Manchester at the moment.

**Comment by JDWoodcock** [comment]
oh cool and happy new year! Where is this duplicate of?

**Comment by Robinlovelace** [comment]
@JDWoodcock and thanks for getting on it in 2016! Updated the (initially poor) response to answer your question.

**Comment by JDWoodcock** [comment]
thanks :)
