### ISSUE TITLE
Don't display 'orphaned lines' in rnet

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#110]
This will probably involve writing a function.

Will mean we don't need to use the 'toptail' function to stop the lines going to the centroids.

**Comment by AnnaGoodman1** [comment]
I think this is now fixed? Or at least superseded?

**Comment by Robinlovelace** [comment]
Neither - but happy for this to be closed - we need to rethink `overline()` which is a more fundamental issue, possibly for the stplanr issue tracker: https://github.com/ropensci/stplanr/issues
