### ISSUE TITLE
Re-add increase, perhaps with a radio button

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#111]
The Scenario Increase in Cycling (SIC) has been removed. We now only show Scenario Level of Cycling (SLC). Anna suggests that we re-include SIC via a on/off button. This is not a priority issue.

**Comment by JDWoodcock** [comment]
@Robinlovelace this isn't clear to me

**Comment by Robinlovelace** [comment]
@JDWoodcock agreed - wasn't lucid. Added description.

**Comment by Robinlovelace** [comment]
We're displaying this in the popups - so closing for now...
