### ISSUE TITLE
crashing when go to routes

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#113]
@Robinlovelace 
it is crashing for every region I tested when ask to view routes (it works for straight lines)
"The application unexpectedly exited.

Diagnostic information has been dumped to the JavaScript error console."

**Comment by Robinlovelace** [comment]
This is precisely the reason I'm suggesting PRs and testing before merges. Could it be due to this? Tested on 1a26e892466db35b6cbb29691f240eeb91b78831 - reverted to that for now.

**Comment by Robinlovelace** [comment]
Fixed with https://github.com/npct/pct-shiny/commit/7444fbb2e2190518bc5d0a1e2836d73f20020222 - I think. Please confirm.

**Comment by JDWoodcock** [comment]
thanks Robin
I agree we need PR from now.
