### ISSUE TITLE
hour glass or similar to show people that they need to wait

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#116]
Waiting a few seconds for data to load is not a disaster but if people think it is not working they will tend to click or press back button. If they realised they were waiting they might show more patience? 

This is an issue to be experimented with and see if users like it.

**Comment by Robinlovelace** [comment]
This looks like a good summary of the work - to emphasise James's point, not a priority but worth looking at. Suspect it's an upstream https://github.com/rstudio/shiny issue - Not sure if NB or AA have kept an eye on development there but we could look that way and the proliferation of increasingly complex apps using shiny for inspiration.

**Comment by Robinlovelace** [comment]
Closing for now as the better solution is to make the tool fast.
