### ISSUE TITLE
empty line boxes for links and areas

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#118]
@Robinlovelace @audev 
no info in the info boxes for each link. Something to do with adding car % data?
James

**Comment by audev** [comment]
@JDWoodcock  @Robinlovelace 
If you tried for Liverpool and worked, then I think it should be fine. As said, to not crash it needs the underlying data there. Otherwise probably better to keep it on hold.

**Comment by Robinlovelace** [comment]
Yes this is a data issue - it will be resolved when I build and push new data.
