### ISSUE TITLE
suggest merge zone attribute & line attribute

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#12]
I just stupidly wondered why lines not changing whilst playing with zone attribute- others may also be so stupid! I suggest we simplify and have only one set of options that covers both zones & lines- usually you would want to see both.
James

**Comment by Robinlovelace** [comment]
We debated this already at the early stage. It's good to be able to choose the area-based attribute to see what may be affecting the line attribute - e.g. hilliness.

**Comment by nikolai-b** [comment]
I'm with James that this makes the UI cluttered. How about by default they
are linked (with only one select dropdown) but with an unlink options?

**Comment by Robinlovelace** [comment]
@nikolai-b that sounds like a more complex UI than what we've got already - let's keep them as separate menus for now.

**Comment by nikolai-b** [comment]
Ok, so I'm happy to look at adding 
![rdserver_link_and_unlink_buttons_2](https://cloud.githubusercontent.com/assets/6289830/7045983/8c26b452-ddfa-11e4-8136-c97f4f5f73d4.jpg)
buttons but if your happy with the UI as it is then can someone else ( @Robinlovelace or @JDWoodcock )  confirm and close this?

**Comment by JDWoodcock** [comment]
I don't understand your comment Robin- could you explain?
"We debated this already at the early stage. It's good to be able to choose the area-based attribute to see what may be affecting the line attribute - e.g. hilliness."

**Comment by Robinlovelace** [comment]
Not a priority for now - hence closing (can always re-open).
