### ISSUE TITLE
add % after aboslute numbers for cycle commutes scenarios and give % increase for increase in commute

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#122]
@audev 
e.g 
Total commutes 	810
Cycle commutes 	55 (7%)
Cycle commutes (scenario) 	175 (_22%)_
Increase in commutes   	120 _(218%)_
Route Distance 	2.6 km
Estimated Time 	17.6 min
Hilliness (average gradient) 	0.3%
Route Type 	Dire

**Comment by JDWoodcock** [comment]
please can replace 'Car drive commutes' with 'Car commutes 
please can we also see the car numbers for the other scenarios too

Total commutes   	810
Cycle commutes   	55 (7%)
Car drive commutes   	58 (52%)
Distance (km) 	1.4

**Comment by audev** [comment]
@JDWoodcock  I'm self assigning this; still my understanding from Anna is that scenarios are still changing.

**Comment by nikolai-b** [comment]
Moved to #140
