### ISSUE TITLE
Go Dutch scenario numbers are wrong

### ISSUE THREAD

**Issue by RachelAldred** [npct/pct-shiny#123]
@Robinlovelace  Hi, I just noticed that the Dutch scenario numbers must be wrong for Liverpool City Region - for short OD pairs they are higher than the total number of commutes.
![image](https://cloud.githubusercontent.com/assets/11818218/12702737/fcc3fc9c-c828-11e5-956b-4906a810e565.png)
I'm not sure if the image has pasted correctly but here is an example output for 'straight lines'
Total commutes	808
Cycle commutes	10 (1%)
Cycle commutes (scenario)	866
Increase in commutes  	856
Distance (km)	1.1
Just checked Kent and the same is true - the Dutch figures for cyclists exceed the total commuters.

**Comment by Robinlovelace** [comment]
Thanks for this Rachel - I had noticed these issues in Liverpool and discussed them with @nikolai-b. The updated model should solve these - more soon.

**Comment by Robinlovelace** [comment]
Closed by https://github.com/npct/pct-load/commit/ec70ef96e2496ec7c74c8177372611a90e320c7b , tested for kent.
