### ISSUE TITLE
Restrict zoom level when IMD map layer is selected

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#125]
I believe we can restrict the maximum zoom level when IMD layer is selected. I don't know if you noticed this or not, but after a certain zoom level, the screen goes grey - see the image below:
![zoom-level-imd](https://cloud.githubusercontent.com/assets/10958628/12755737/97eea604-c9c8-11e5-908d-b115bcc8dc68.png)

It's not a priority issue, but I believe is useful. What do you guys @Robinlovelace and @nikolai-b think?

**Comment by Robinlovelace** [comment]
Not a priority issue but yes this is an issue - cheers for spotting.

**Comment by nikolai-b** [comment]
Nice work but we need one still a related issue.  If you are zoomed in and change to IMD then you aren't zoomed out so can end up with a grey screen.  We could zoom the user out or give a warning.  I don't like either option, any thoughts?

Zooming a user out feels intrusive but a warning would just get in the way.

**Comment by Robinlovelace** [comment]
Give a warning that you can close (e.g. a popup with an x)? 

BTW I just found this on progress bars: http://shiny.rstudio.com/articles/progress.html

Don't think we need it but useful to know...

I'd prefer not to change zoom.
