### ISSUE TITLE
Refactor html

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#128]
This will remove raw html code like [this](https://github.com/npct/pct-shiny/blob/master/pct-shiny-funs.R#L100-L111).

**Comment by Robinlovelace** [comment]
@audev are you up for this?

**Comment by audev** [comment]
@Robinlovelace  Happy to add this to #137, but I probably won't see it till Thursday; so it'd be good idea to merge now the PR (tested already).  Team sees the changes, @JDWoodcock  confirms all OK, and we get all in one last go.

**Comment by Robinlovelace** [comment]
Agreed - will test and merge.

**Comment by nikolai-b** [comment]
Moved to #140

**Comment by Robinlovelace** [comment]
Reopening as the method of generating the popups is different from their content.

**Comment by Robinlovelace** [comment]
Made a start here: https://github.com/npct/pct-shiny/pull/150

**Comment by Robinlovelace** [comment]
Update: @usr110 (I think you're best skilled for this) + @audev to 'double team' this one on Monday!
