### ISSUE TITLE
welcome page- move text back to side from bottom

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#130]
for some reason text is now at the bottom of the screen instead of the side. It is harder to read at the bottom, particularly on smaller screens. Please could someone move it back.
thanks

**Comment by Robinlovelace** [comment]
@usr110 you up for this?

**Comment by JDWoodcock** [comment]
superseded by new issue Robin has created

**Comment by Robinlovelace** [comment]
Thanks James for keeping these issues in order!
