### ISSUE TITLE
Tunbridge Wells numbers

### ISSUE THREAD

**Issue by RachelAldred** [npct/pct-shiny#133]
@Robinlovelace Tunbridge Wells numbers along key routes under Go Dutch seem rather low compared to the numbers of  people working in the town - is this perhaps to do with minimum flow between OD pairs being set at 100? It would be good in the short term to have a sense of how much we're likely to be underestimating numbers by, if so. (I guess this may be particularly important for somewhere like here, perhaps, compared to e.g. Greater Manchester?)

**Comment by Robinlovelace** [comment]
Hi Rachel - agreed. I'll do a build with higher numbers of flows this evening. We're still doing prototype testing so all this info is useful and feedback is great.
