### ISSUE TITLE
the +/- zoom button

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#136]
on my screen (surface pro 4) the top of the button (ie the +) is not visible- too high up. So please can we try lowering it in the screen. Although how useful button is as one can just do it with keyboard +/- button is not clear to me.

**Comment by Robinlovelace** [comment]
Thanks for flagging this but I think these device-specific requests should not be prioritised unless they can be reproduced. How about adding something about the recommended devices/screens for using the PCT in the FAQ/about. We should say, for example, that it's not designed to work on smartphones for example.

**Comment by JDWoodcock** [comment]
I agree it doesnt work on smart phones and doesn't have to. Tablets - would be useful to run a few tests.
But surface is really a laptop- would be worth seeing how it looks on a few laptops.

**Comment by Robinlovelace** [comment]
OK so what's the issue? It helps to make clear, objective and actionable issues otherwise they just accumulate. So will close unless we get a concrete 'action point' out of this, at present it's not clear precisely what is to be done to address the issue.

**Comment by JDWoodcock** [comment]
My issue is too lower the button

**Comment by Robinlovelace** [comment]
OK - @usr110 are you up for having a look? A screenshot would be useful but suspect it will be better to speak face to face.

**Comment by JDWoodcock** [comment]
thanks, I can show to Alvaro- but as @Robinlovelace indicates this is not a top priority issue

**Comment by audev** [comment]
@JDWoodcock I guess screen resolution plays a role in all this, the aspect ratio in particular.  Right now it's fine for average user setup, but surely some configs will have issues.

**Comment by Robinlovelace** [comment]
OK so are we going to do anything about this? If not I suggest we close this.

**Comment by JDWoodcock** [comment]
I still suggest slightly lowering the button. 
At the next user session we could go round and make a note of any machines and set ups that are not performing well.
