### ISSUE TITLE
% cycling not working in popup

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#139]
@nikolai-b  you up for looking at this? I think Ali would be too when he's back. Should be a simple fix (see image). 

![selection_075](https://cloud.githubusercontent.com/assets/1825120/13201864/38a00fd2-d87b-11e5-90a4-622eeaa4eb95.png)

**Comment by Robinlovelace** [comment]
@audev you may want to look at this at the same time. Also not comments on kable here: https://github.com/npct/pct-shiny/pull/137#issuecomment-186863012 - may help to just redo all popup tables with `knitr`'s fantastic `kable` function.

**Comment by nikolai-b** [comment]
moved to #140
