### ISSUE TITLE
'No zones' option has disappeared

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#14]
With the closure of #9 we've removed a superfluous option: to show LSOAs.

However it's also removed a useful option: to show no zones.

The plan was to re-add this option in the 'zone attribute' menu:

" Instead have option 'none' under zone attribute."

Should be an easy addition, that will enable people to focus on the map rather than the colourful zones.

**Comment by nikolai-b** [comment]
[Fixed](38dc944e)

**Comment by Robinlovelace** [comment]
Thanks @nikolai-b , but the hyper link takes me to outer space! https://github.com/npct/pct-shiny/issues/38dc944e but works perfectly on master. Gr8 work :)

**Comment by nikolai-b** [comment]
I wounder why GitHub can't cope with 38dc944eb1d7d0db135d010f3bd5066d2b8ec594 anyway, glad its fixed.
