### ISSUE TITLE
Label consistency 

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#140]
![selection_076](https://cloud.githubusercontent.com/assets/1825120/13204175/3e0fecb2-d8c1-11e5-9bfb-6dd9fc406931.png)
Currently it only shows the absolute number. Who's up for this @npct/admin?

**Comment by audev** [comment]
@Robinlovelace 
I'll have a look today

**Comment by Robinlovelace** [comment]
Thanks @audev let us know if you've any questions.

**Comment by Robinlovelace** [comment]
Half way there @audev - we just need to add % cycling in the scenarios and % driving in the scenarios now - note the inconsistency below (please add to my new `rename-cols2` branch if you can).

![selection_080](https://cloud.githubusercontent.com/assets/1825120/13282605/aeed8968-dae1-11e5-8c5f-e0d0fcaf7b67.png)

**Comment by Robinlovelace** [comment]
Note all this will be easier when we use `kable` to create the html.

**Comment by audev** [comment]
@Robinlovelace  @JDWoodcock  Well this is the reason why you two need to check the new labels and agree on something. 

For me 'Cyclists' is clearer than 'Cycle commutes (Census 2011)'; but this is the text agreed a week ago.  Let's circulate the version, agree on a final one and implement it.

**Comment by JDWoodcock** [comment]
thanks @audev and @Robinlovelace - so will the final version be pushed for us all to check?

**Comment by Robinlovelace** [comment]
Yes - assuming we agree that the (16%) label should be added just after Cyclists (scenario): 70 in the above image? @audev are you up for fixing this? I also think it would be useful to add percentages next to the number of Drivers. However, all this should be much easier when we use kable, as I've said - I can have a go at this if you don't get round to it this week @audev. Sound good?

**Comment by audev** [comment]
I'm up for it, but not today. Happy to try Thursday and you check it's fine.

**Comment by nikolai-b** [comment]
From @audev:

Latest format and wording of the labels (not seen in pct.bike till code is committed). Notice all % are rounded except to 0 decimals, except hilliness which is too small.

In **bold**: changes already agreed to be added in the code next commit, no need to comment.

STRAIGHT LINES | CENSUS 2011 CYCLING (Baseline )
--- | --- 
Total commuters:  | 491
Cycle commuters (2011): |36 (7%)
Car commuters (2011): | 345 **(70%)**
Distance (km):| 3 

STRAIGHT LINES | SCENARIOS (All)
--- | --- 
Total commuters: | 491 
Cycle commuters (2011): | 36 (7%)
Cycle commuters (scenario): | 61 **(12%)**
Distance (km): | 3 

Suggested changes:  shorter labels | adding Car% to scenarios too

ROUTES (FASTEST & QUIET) | CENSUS 2011 CYCLING (Baseline )
--- | --- 
Total commuters: | 491 
Cycle commuters (2011): | 36 (7%)
Car commuters (2011): | 345 **(70%)**
Route Distance: | 3.5 km
Av. Route Time: | 29 min
Hilliness (av. gradient): | 1.8%
Route Type: | Direct

Suggested changes: shorten labels (e.g. Cyclists (2011) ) | Shorter list (e.g. delete Route type)

ROUTES (FASTEST & QUIET) | SCENARIOS (All)
--- | --- 
Total commuters: | 847 
Cycle commuters (2011): | 86 (10%)
Cycle commuters (scenario): | 141 **(17%)**
Route Distance: | 1.6 km
Av. Route Time: | 14.5 min
Hilliness (av. gradient): | 1.1%
Route Type: | Direct

Suggested changes: same as before  + add Car%

ROUTE NETWORK | CENSUS 2011 CYCLING (Baseline )
--- | ---
Cycle commuters (2011): | 99 **(5%)**

ROUTE NETWORK | SCENARIOS (All)
--- | ---
Cycle commuters (2011): | 99 **(5%)**
Cycle commuters (scenario): | 192 **(10%)**

ZONES/CENTROIDS | CENSUS 2011 CYCLING (Baseline )
--- | ---
Zone: | Central Bedfordshire 010
Cycle commuters (2011): | 23   **(2%)**
Car commuters (2011): | 646 **(63%) **
Hilliness (av. gradient): | 1°

ZONES/CENTROIDS | SCENARIOS (All)
--- | ---
Zone: | Central Bedfordshire 010
Cycle commuters (2011): | 23 **(2%)**
Cycle commuters (scenario): | 59 **(5%)**
Hilliness (av. gradient):  | 1°

Suggested changes: add Car%

**Comment by nikolai-b** [comment]
Looks good @audev 

We don't have the total number of traffic passing though a section of the route network so we can't do percentages there (and it wouldn't be easy, that would require us to estimate car routing as well).

> Suggested changes: shorter labels | adding Car% to scenarios too

How would we estimate car percentage from the scenarios?  Assume that all the new cyclists were car users?  I'm not sure about that.  We can certainly put the 2011 level of car usage (like we put the 2011 cycle usage) if you were suggesting that. 

I would like to remove hilliness, the av time is more valuable in my mind.  Happy with all the other changes.

**Comment by audev** [comment]
@nikolai-b I'll add whatever is agreed, fine by me. 
The aggregate model estimates new cyclists come proportionate to the different modes totals. From there we get the remaining car% per scenario. But do we want to answer tricky questions on its level of accuracy?

Not that I advocate for it; just raising the issue before someone else quickly asks to add/delete it.

**Comment by nikolai-b** [comment]
Great, I didn't realize the model estimated which modes of travel the new cyclists came from.  If we have the data from the model that is fine, then go for it.  

For the route network I am pretty sure we don't have that data.

**Comment by Robinlovelace** [comment]
Confirmed, we have the % car data per desire line but not at the route network level. Thanks for clarifying the issues.

**Comment by Robinlovelace** [comment]
This is the final version of the lines popup spec which has been agreed. This will be a lot of work to implement but will look awesome when it's done:

[160229_PCT Labels_v8.pdf](https://github.com/npct/pct-shiny/files/150694/160229_PCT.Labels_v8.pdf)

**Comment by Robinlovelace** [comment]
I made a start with using kable on this branch: https://github.com/npct/pct-shiny/pull/150

I think creating we can make these updates faster, easier, and easier to understand on update using this method.

Please let me know and I'll merge the PR asap.

**Comment by JDWoodcock** [comment]
apart from the new issue on "all scenarios" I think we can now close this too?
