### ISSUE TITLE
Fix front page

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#141]
Setting this as a priority as the the front page does not create a good impression ATM:

http://pct.bike/

**Comment by JDWoodcock** [comment]
thanks, the text needs to be moved back to the right hand side.
I have circulated revised text - when this is agreed please can someone upload it

**Comment by nikolai-b** [comment]
Can you put the text up here?  I don't think I got the revised text

**Comment by nikolai-b** [comment]
c988796c5fc1741 fixes the styling and is live already

**Comment by Robinlovelace** [comment]
Great work.
Yes - I'll add the revised text.
