### ISSUE TITLE
geowebarch site - needs redirect banner

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#143]
the old site http://geo8.webarch.net/ can be used by us as a test site, so we need some kind of banner/warning to people not to use it and go to pct.bike instead

**Comment by nikolai-b** [comment]
I've added a redirect so if you go to any of the old links you will get sent to http://pct.bike

You can still access the testing site by appending test in the url, e.g.

http://geo8.webarch.net/test/

So http://geo8.webarch.net/master is now at http://geo8.webarch.net/test/master

cc @Robinlovelace

**Comment by JDWoodcock** [comment]
@nikolai-b great to see all these issues being done
