### ISSUE TITLE
Integrate about from front page and the regions

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#148]

**Comment by Robinlovelace** [comment]
I think it's OK just to link to http://pct.bike/about.html

Thoughts @npct/owners ?

This would have the benefit of reducing the number of tabs from 7 (which is overwhelming) to 6 (still to many but better IMO).

**Comment by JDWoodcock** [comment]
I dont see 7 as overwhelming. Suggest we leave as is until either we have feedback it is a problem or we need to create more. If you were going to link where would it be from ? Front page isn't enough I fear. Perhaps if also from FAQ page and other places?

**Comment by Robinlovelace** [comment]
At present there are 2 'about' pages. This duplication is bad practice and potentially confusing as agreed today in the meeting. One to discuss with @annagoodman1 and @audev I think. Look forward to discussing this.

**Comment by JDWoodcock** [comment]
Which do you consider the 2nd 'about' page?

**Comment by Robinlovelace** [comment]
There's one inside each region, e.g:

![selection_086](https://cloud.githubusercontent.com/assets/1825120/13408990/86b0f502-df28-11e5-95ce-5a52d2195c25.png)

And there's now another one on the home page:

http://pct.bike/about.html

I propose only using 1, the second one and linking to it from the FAQ page under the question: What is the PCT? Then it could say:

For more information, please see the [about page](http://pct.bike/about.html).

**Comment by JDWoodcock** [comment]
I agree the first two should definitely be the same but don’t see why we can’t see it when on each region as we do with ‘how to use it’?

James

**Comment by usr110** [comment]
Have left the two pages separate. I agree with @JDWoodcock on this. Not only the two pages outline is different, they both served their purpose. I personally won't combine the two together.
Fixed it by: https://github.com/npct/pct-shiny/commit/96182a02cfc650e816c8ba150ad3ce27f23777fd
