### ISSUE TITLE
Don't delete new data when running the app

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#156]

**Comment by audev** [comment]
@Robinlovelace  Freudian massages
It's Friday afternoon....

**Comment by Robinlovelace** [comment]
??

**Comment by Robinlovelace** [comment]
Re-opening as it doesn't throw a warning. Happy to close but we should change the title first. Just wanted to check if you're happy with it not throwing a warning first @nikolai-b.

**Comment by nikolai-b** [comment]
I'm happy with it staying closed.
