### ISSUE TITLE
Tool slows down when many people use it

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#16]
In my experience when ~10 people connect to the tool at the same time it slows down.

Can we reproduce this? More importantly, can we monitor what is going on?

Hypothesis: it's a processor issue that is partly resolved by cb83e702e42d318b0b40a404182a0876bcd01164

Each shiny instance seems to require ~100MB (please confirm @nikolai-b ) - I'll reduce this in data mkII.

**Comment by JDWoodcock** [comment]
The tool also goes very slow when you try and go up to 100% of route network

**Comment by Robinlovelace** [comment]
Another duplicate of https://github.com/npct/pct-load/issues/4
