### ISSUE TITLE
rq layer is showing straight line l data

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#169]
![selection_107](https://cloud.githubusercontent.com/assets/1825120/13903724/2d6ddd0a-ee7f-11e5-933e-1b2a769b7a31.png)

I've checked this (for west-yorkshire, shown above) and this is not a data issue, e.g.

```
# Part 1: testing for Leeds
rq = readRDS("../pct-data/west-yorkshire/rq.Rds")
nverts = n_vertices(rq)
summary(nverts)
sel = nverts < 3
summary(sel)

mapview::mapview(rq)
```

And you get this - no straight lines:

![selection_108](https://cloud.githubusercontent.com/assets/1825120/13903737/64af40a6-ee7f-11e5-8891-2c07414ad22d.png)

Please try to reproduce and let me know if it works on your computer.

**Comment by usr110** [comment]
@Robinlovelace Just reproduced it, and yes, you are right this problem exists.
I have further investigated the issue. It seems like a data issue. 
Have printed the line's ID and it seems that the line exists in /pct-data/west-yorkshire/rf.Rds. Specifically the row number: 6397 shown below.
![sl-in-route](https://cloud.githubusercontent.com/assets/10958628/13928393/58945216-ef8d-11e5-92c7-585d33fcd005.png)

Here's more info of the row:

> 'data.frame':	1 obs. of  106 variables:
 $ plan                    : int NA
 $ start                   : int NA
 $ finish                  : int NA
 $ length                  : num NA
 $ time                    : num NA
 $ waypoint                : int NA
 $ change_elev             : num NA
 $ av_incline              : num NA
 $ co2_saving              : num NA
 $ calories                : num NA
 $ busyness                : num NA
 $ id                      : chr "E02006852 E02006875"
 $ id                      : chr "E02006852 E02006875"
 $ Area.of.residence       : chr "E02006852"
 $ Area.of.workplace       : chr "E02006875"
 $ All                     : num 1240
 $ Rail                    : num 18
 $ Bus                     : num 518
 $ taxi                    : num 14
 $ motorbike               : num 13
 $ Car_driver              : num 402
 $ Car_passenger           : num 51
 $ Bicycle                 : num 105
 $ Foot                    : num 119
 $ Other                   : num 0
 $ avslope                 : num NA
 $ dist                    : num 4.39
 $ cirquity                : num NA
 $ dist_fast               : num NA
 $ dist_quiet              : num 6.42
 $ distq_f                 : num NA
 $ govtarget_slc           : num 140
 $ govtarget_sic           : num 34.6
 $ govtarget_slw           : num 115
 $ govtarget_siw           : num -3.63
 $ govtarget_sld           : num 390
 $ govtarget_sid           : num -12.2
 $ gendereq_slc            : num 149
 $ gendereq_sic            : num 44.2
 $ gendereq_slw            : num 114
 $ gendereq_siw            : num -4.6
 $ gendereq_sld            : num 387
 $ gendereq_sid            : num -15.4
 $ dutch_slc               : num 242
 $ dutch_sic               : num 137
 $ dutch_slw               : num 105
 $ dutch_siw               : num -14.4
 $ dutch_sld               : num 353
 $ dutch_sid               : num -49.1
 $ ebike_slc               : num 434
 $ ebike_sic               : num 329
 $ ebike_slw               : num 84.4
 $ ebike_siw               : num -34.6
 $ ebike_sld               : num 285
 $ ebike_sid               : num -117
 $ base_sldeath_webtag     : num -0.0383
 $ base_slvalue_webtag     : num 71047
 $ govtarget_sldeath_webtag: num -0.0509
 $ govtarget_slvalue_webtag: num 94411
 $ govtarget_sideath_webtag: num -0.0126
 $ govtarget_sivalue_webtag: num 23364
 $ gendereq_sldeath_webtag : num -0.0478
 $ gendereq_slvalue_webtag : num 88641
 $ gendereq_sideath_webtag : num -0.00948
 $ gendereq_sivalue_webtag : num 17594
 $ dutch_sldeath_webtag    : num -0.0994
 $ dutch_slvalue_webtag    : num 184480
 $ dutch_sideath_webtag    : num -0.0611
 $ dutch_sivalue_webtag    : num 113433
 $ ebike_sldeath_webtag    : num -0.117
 $ ebike_slvalue_webtag    : num 216188
 $ ebike_sideath_webtag    : num -0.0782
 $ ebike_sivalue_webtag    : num 145141
 $ base_sldeath_heat       : num -0.025
 $ base_slvalue_heat       : num 80767
 $ govtarget_sldeath_heat  : num -0.0332
 $ govtarget_slvalue_heat  : num 107334
 $ govtarget_sideath_heat  : num -0.00823
 $ govtarget_sivalue_heat  : num 26567
 $ gendereq_sldeath_heat   : num -0.0312
 $ gendereq_slvalue_heat   : num 100772
 $ gendereq_sideath_heat   : num -0.0062
 $ gendereq_sivalue_heat   : num 20005
 $ dutch_sldeath_heat      : num -0.065
 $ dutch_slvalue_heat      : num 209891
 $ dutch_sideath_heat      : num -0.04
 $ dutch_sivalue_heat      : num 129124
 $ ebike_sldeath_heat      : num -0.0769
 $ ebike_slvalue_heat      : num 248451
 $ ebike_sideath_heat      : num -0.0519
 $ ebike_sivalue_heat      : num 167684
 $ base_slco2              : num -9297
 $ govtarget_slco2         : num -12469
 $ govtarget_sico2         : num -3172
 $ gendereq_slco2          : num -13277
 $ gendereq_sico2          : num -3980
 $ dutch_slco2             : num -22028
 $ dutch_sico2             : num -12731
 $ ebike_slco2             : num -39772
  [list output truncated]

**Comment by usr110** [comment]
BTW, in the code fast and straight lines data get cbinded at here: https://github.com/npct/pct-shiny/blob/master/server-base.R#L63

**Comment by Robinlovelace** [comment]
Hi guys apologies for this - it's a data issue and I'm close to a resolution. This should be in pct-load.
