### ISSUE TITLE
Zone layer overlaps lines (straight and route)

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#170]
Once a zone popup is displayed, the underlying routes/straight lines become inaccessible. 

![zone-overlap-routes](https://cloud.githubusercontent.com/assets/10958628/13927000/aa96b312-ef86-11e5-968e-2aa3a97eb2d9.png)

**Comment by usr110** [comment]
@nikolai-b @Robinlovelace if you two can suggest a better solution, that will be great.

**Comment by usr110** [comment]
@nikolai-b @Robinlovelace Solved it myself. See here: https://github.com/npct/pct-shiny/commit/85dc3f049c4b6eecb45a74bfdef7660b457ae15c

**Comment by Robinlovelace** [comment]
Great work @usr110
