### ISSUE TITLE
Allow the user to select new layers

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#172]
In the first instance this will only be done on the Manchester branch. Eventually we could use the same code to switch to national layers (e.g. train and school commute layers).

**Comment by Robinlovelace** [comment]
Bump. It seems @usr110 has a good plan for this.

**Comment by jf1** [comment]
Please can you confirm that all users will be able to see these layers at pct.bike/greater-manchester/ or if there's a separate TfGM install (that I can ask them about directly)

**Comment by Robinlovelace** [comment]
Fantastic work @usr110 - basic functionality can be seen here so closing to now: http://npct0.vs.mythic-beasts.com/pct-shiny-all-layers/greater-manchester/
