### ISSUE TITLE
Reduce text in area level key

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#173]
At the moment there is too much text in the key for the scenarios (it is okay for baseline) and depending on browser settings it is not all visible.

I suggest we replace text with "Number of cyclists"- this could be for baseline & for all scenarios.

Also suggest we reduce size of numerals as on some settings one of them is missing.
ta.

**Comment by Robinlovelace** [comment]
I agree the text is too bulky - please let us know of any ways to shrink it @usr110 and @audev

**Comment by JDWoodcock** [comment]
Fewer words is probably sufficient (though agree could also be lighter font)

**Comment by usr110** [comment]
What about changing it to "Number of Cycling Commuters"? As for one of them being missing, I believe once we reduce the size of the legend, it will be sorted out.

**Comment by JDWoodcock** [comment]
Yes agreed that is fine

**Comment by usr110** [comment]
Please share your feedback - have pushed it onto the old server. 

http://geo8.webarch.net/test/essex/

**Comment by usr110** [comment]
On James suggestion, changed the title into "Number of Cycle Commuters"
