### ISSUE TITLE
Kable is creating problems

### ISSUE THREAD

**Issue by nikolai-b** [npct/pct-shiny#175]
https://github.com/npct/pct-shiny/blob/master/pct-shiny-funs.R#L7

Kable is trying to make HTML simple for us but has caused quite a few issues:

£ was a pain,
super and sub text is a pain,
it hasn't removed the `sprintf` (and looks like it can't)

It would be much simpler to just write HTML.

**Comment by Robinlovelace** [comment]
Yes I've come round to this view also. It should allow us to use `paste0` instead of `sprintf`.

Sorry guys I was hoping it would make life easier but seems it's made it harder!

**Comment by usr110** [comment]
@nikolai-b Thanks for the fix. It looks great with all the symbolks, but yes, I agree with you that Kable isn't that great. Was just searching for alternatives (if pure HTML is too big of a problem to others). Found this:

https://cran.r-project.org/web/packages/htmlTable/vignettes/tables.html

I've tested it with dummy values for our app, and it seems to be working quite well. Has nice features like footnotes as well.

**Comment by Robinlovelace** [comment]
Thanks for doing the background research Ali, perhaps that could provide a solution that is both elegant and works! Thought: Perhaps we need a list of tables. What do you reckon? I suspect that leaflet expects inputs which have the same length as the spatial object being represented, but may well be wrong.

**Comment by Robinlovelace** [comment]
@nikolai-b yes but you've not pushed to geo8. We agreed to always push to the test server unless there was a reason not to. Now James et al. cannot see the changes you've made, making our workflow less agile! Summary: push to the test server!!!

**Comment by nikolai-b** [comment]
I had pushed

**Comment by Robinlovelace** [comment]
Apologies - must have been slow to update.
