### ISSUE TITLE
Death / Lives saved values

### ISSUE THREAD

**Issue by nikolai-b** [npct/pct-shiny#179]
From @JDWoodcock 
Deaths per 1000 and money £1000- this has been added in but it is not right for deaths. The deaths are absolute numbers for that flow- they are not per 1000 & times it by 1000 does not make it per 1000. I agree some users may find the small numbers confusing- although how many deaths do they expect to save per flow? I dont see an easy solution to this- we could do per 10 years but then we need to discount. I suggest we revert back and then user test. Money can be in units of £1000.

**Comment by nikolai-b** [comment]
Zone only labels updated in 536934a, are you happy with that?

**Comment by JDWoodcock** [comment]
on the test server the deaths and money are no longer visible. Was that the intention?

**Comment by nikolai-b** [comment]
Yes, the label is now 
> Lives saved/yr (in £1000s)
My thinking was these are two ways of expressing the same things so made sense for them to be linked.

**Comment by JDWoodcock** [comment]
I suggest we revert to Change in no. deaths/year: and Change in deaths (£1000/yr). These were both agreed in the style guide v8. and I think the current wording is worse. If the argument is that it is too long then we can Anna & I can come up with alternative.

**Comment by nikolai-b** [comment]
I'm proposing this as an improvement.  The labels have become very long and fill up the entire screen on smaller devices (and even on some smaller sized desktops).  It is easy to overwhelm users and we now have information overload.

Are these two figures are expressing the same number?  If so then I think it makes sense that they should be on the same line as we do with `%` figures.  Would you mind reconsidering?

**Comment by JDWoodcock** [comment]
Appreciate your input but it is now less accurate. And this does need to feed in to the document on labels so we have a standard reference. I will discuss with wider group and come back to you. Please check before making labels changes as we have spent a lot of time thinking about them and subtleties do matter.

**Comment by nikolai-b** [comment]
If you and Anna can find a way to reduce the labels length and size then that's great.  I've change in back.

We need to constrain the labels to ~7 rows and the titles to ~ 25 chars, I'll add a separate issue.
