### ISSUE TITLE
Reduce popup size

### ISSUE THREAD

**Issue by nikolai-b** [npct/pct-shiny#181]
For the popups to be useful they need to not fill too much of the screen.  A smaller sized desktop can be:
width x height (in px)
768 x 800
Currently our max popup width is 335 so more than 50% of the width (on the zone popup) and the max height is 172 (on the fastest route).

We need to constrain the popup rows to ~7 rows and the titles to ~ 25 chars for the tool to be useful, this could be wording reduction or removing the plentiful duplication.  I know I'm late to the popup discussions but overwhelming users is a bad idea.

Refs #179

**Comment by JDWoodcock** [comment]
to me this is now okay- I know Ali worked more on it- Can I close?
