### ISSUE TITLE
Add 'Transparent zones' radio button

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#184]
Just discussed with James and Rachel (happy for more discussion here). The opacity of the colour means it's hard to identify road names and other important features of the underlying map. Clicking it would make the zones see-through.

@usr110 would you be up for taking a look - suspect it could be a 2 liner.

**Comment by RachelAldred** [comment]
Hi @Robinlovelace this came up again while going over London and I agree this would be a useful feature :)

**Comment by usr110** [comment]
I had a brief talk with Nikolai about it. Like me, he too, doesn't seem very keen on adding an additional control. However, I am now fixing the issue. We can discuss more in the technical meeting.
