### ISSUE TITLE
automated checking procedure to see if tool crashes for any region and scenario

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#188]
would be nice. We can't manually check every region & every combination of display and scenarios

**Comment by Robinlovelace** [comment]
Agreed - will save us loads of time. Seems someone's made a package to make that easy: http://stackoverflow.com/questions/36338779/unit-testing-shiny-apps @nikolai-b you up for taking a look?

**Comment by Robinlovelace** [comment]
This is a duplicate of https://github.com/npct/pct-load/issues/27
