### ISSUE TITLE
Clicking on lines and getting areas instead

### ISSUE THREAD

**Issue by RachelAldred** [npct/pct-shiny#191]
I've been finding it a bit of a struggle to manage to click on route network lines and have been getting the zone data instead. I realise with so many potentially clickable links it might be hard to improve this, so wondered if one option might be for when we're showing links, to turn off the area information by default (?) @Robinlovelace @JDWoodcock @nikolai-b

**Comment by JDWoodcock** [comment]
or could the lines be given an invisible buffer so that nearly clicking on them works?

**Comment by usr110** [comment]
@RachelAldred @JDWoodcock Or how about increasing width of lines? I already have done that here: https://github.com/npct/pct-shiny/commit/e6d9e9ef1bf0a6c76d93e50a0afdfa908a36bcd0. Will soon push the changes on the server, so that you may have a look at it.

**Comment by nikolai-b** [comment]
I'd be happy to remove the zone data popup when lines are show, would that be ok?

**Comment by usr110** [comment]
@nikolai-b That's a good solution. Let's see what others think about it.

**Comment by JDWoodcock** [comment]
I find the wider lines Ali did are working okay. @RachelAldred what do you think?
