### ISSUE TITLE
red centroids

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#193]
they make it harder to see the lines changing in some areas- suggest either 1) we make them more opaque, 2) we consider if we should only the top x as we do with lines

**Comment by Robinlovelace** [comment]
I would suggest reducing the oppacity of the centroids relative to the straight lines. Could also alter the colour but don't think that's necessary. Not in favour of showing the 'top n' centroids.

**Comment by usr110** [comment]
Fixed in https://github.com/npct/pct-shiny/commit/1e84392059555340197141381b9e83b1019e0880
