### ISSUE TITLE
Allow ordering of lines by scenario level of increase and health economic value

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#194]
at the moment we select lines by top no. of cyclists but we could select by top health economic gain (so giving more weight to longer routes and ones replacing fewer pedestrians). This could be an alternative. 

This needs consideration but want to flag it for now

**Comment by Robinlovelace** [comment]
Technically, this means adding a dropdown menu that appears when line scenarios are shown (not rnet) for SIC and HEAT saving to order the lines.

**Comment by Robinlovelace** [comment]
Or @usr110 depending who gets there first (Ali works closer with the source of the HEAT results so should have some input).

**Comment by nikolai-b** [comment]
Order by
`slvalue_heat`, `sic` and the original `slc`

**Comment by JDWoodcock** [comment]
this is great HEAT looks very nice but CO2 looks wrong- showing thin lines with 0 CO2

**Comment by usr110** [comment]
I too noticed it. CO2 has negative values and when taking the maximum value of it, it considers '0' as the highest value. I've fixed it (in https://github.com/npct/pct-shiny/commit/316d40e3142ad96a52e3ed862e6d6653b602631e and https://github.com/npct/pct-shiny/commit/05d05895c3c06ca7129131ebf0b141afb6e33946) by taking the absolute values. Please try again.

**Comment by usr110** [comment]
Closing it now

**Comment by Robinlovelace** [comment]
Thanks for testing it - will open up a PR before pushing this to production.

**Comment by usr110** [comment]
Great, thanks Robin.
