### ISSUE TITLE
Zone Transparent makes the routes unclickable

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#196]
Once you select 'zone transparent' the routes become unclickable

![zone-trasnparent-switch](https://cloud.githubusercontent.com/assets/10958628/14562320/e0fda05a-0313-11e6-9ae0-514b092623f8.png)

**Comment by Robinlovelace** [comment]
Thanks @usr110 - didn't realise I had to put that in an observe. Any further explanation welcome but if not I'm just happy it's fixed.

**Comment by usr110** [comment]
When the zones become transparent, it is essentially removing the old zone layer with the new one - transparent. Hence it's being drawn on top of route layer, hence you can't click on routes any more. 
What I've done is: created a reactive relationship with 'zone transparent' checkbox, so that whenever it is changed, all the lines are redrawn.

**Comment by nikolai-b** [comment]
Both @usr110 and me didn't want an additional control https://github.com/npct/pct-shiny/issues/184 so I've moved it out of master into #197 where we can discuss it.
