### ISSUE TITLE
Bespoke aggregation of areas

### ISSUE THREAD

**Issue by RachelAldred** [npct/pct-shiny#198]
Something for the future, but I wanted to put it here as it was raised recently by Tunbridge Wells stakeholders and others have mentioned this too. MSOAs are the same size roughly as wards but mean little to locals, including councillors who may be lobbied/lobby for cycle infra/area schemes in their ward. So while they were interested in the area data, they didn't connect to the MSOAs as meaningful in terms of  local policy/political processes.

With LSOA-level data, the gap between LA/region level info and LSOA-level info will be large. The LSOAs will make the flows work much better, which will be great, but this will then mean that at an area level, we're reporting on very small areas individually, which may be less meaningful for people than MSOA-level info. Tunbridge Wells stakeholders suggested that if ward-level information wasn't possible, being able to aggregate areas and see results for those would be a good alternative -they were imagining e.g. clicking on a range of LSOAs near a town centre and then getting the results from the combined area. @Robinlovelace @nikolai-b @JDWoodcock

**Comment by JDWoodcock** [comment]
we may want the option of showing at different levels @audev

**Comment by jf1** [comment]
+1 from me. We've wanted to campaign using per-ward, per-LA and per-MP figures for some time. I appreciate the boundaries for these and LSOAs don't align but it should be straightforward to use values at LSOA level to compute reasonably accurate ward, LA and Westminster constituency values.

Do you plan to estimate values for all 4 (origin, destination, internal, through) types of journey?
Perhaps this is a separate issue, but I can't currently can't see this info at MSOA level - it looks like only the 'origin' and 'internal' values are considered, and shown as a single figure.

**Comment by Robinlovelace** [comment]
Closing for now as I don't think it's actionable at the moment. I think this is a great idea and am happy for it to be re-opened. Preferably once this becomes actionable and assigned. My approach would be to make it easier for others to re-build the PCT for custom regions on their own computers but reluctant to assign myself to this issue ATM! Further imput/re-opening welcome.
