### ISSUE TITLE
Add end points information on lines

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#199]
@JDWoodcock suggested that it'd nice to have information on end points of lines (straight and routes), when a user clicks on them. I agree it's a good addition. What do you guys think? @Robinlovelace and @nikolai-b

**Comment by usr110** [comment]
Just added basic infrastructure here: https://github.com/npct/pct-shiny/commit/c6cd5696c4d6895e6436910f3f4f50a800786440. However, instead of codes, just like zones, we need a geo label here.

**Comment by usr110** [comment]
![endpoints](https://cloud.githubusercontent.com/assets/10958628/14611896/62db23b6-058c-11e6-8d38-2725f343534f.png)

The change is live on the test server - http://geo8.webarch.net/test/kent/

**Comment by Robinlovelace** [comment]
We could also say 'Two-way flow between E0... and E0..." - Perhaps use the zone label not just it's code? Overall I think it's fine but those long numbers could confuse people. Could you test with the zone label instead to see how it looks?

**Comment by usr110** [comment]
There are no zone-labels in l object; otherwise would've used them. These are the variables:

> 'data.frame':	3114 obs. of  95 variables:
 $ id                      : chr  "E02003314 E02003315" "E02003314 E02003316" "E02003314 E02003317" "E02003314 E02003319" ...
 $ Area.of.residence       : chr  "E02003314" "E02003314" "E02003314" "E02003314" ...
 $ Area.of.workplace       : chr  "E02003315" "E02003316" "E02003317" "E02003319" ...
 $ All                     : num  86 446 187 89 148 129 43 44 140 72 ...
 $ light_rail              : num  0 0 0 0 0 0 0 0 0 0 ...
 $ Bus                     : num  0 11 6 6 3 3 5 2 6 1 ...
 $ Taxi                    : num  0 1 0 2 0 0 0 1 1 0 ...
 $ Motorbike               : num  0 5 0 0 0 2 1 1 0 1 ...
 $ Car_driver              : num  78 334 163 69 96 111 27 36 118 61 ...
 $ Car_passenger           : num  6 38 12 8 9 8 4 3 6 6 ...
 $ Bicycle                 : num  0 12 0 1 7 2 0 1 2 1 ...
 $ Foot                    : num  1 43 4 2 31 3 5 0 7 2 ...
 $ Other                   : num  0 0 0 0 0 0 0 0 0 0 ...
 $ govtarget_slc           : num  1.76 28.01 3.3 2.22 8.28 ...
 $ govtarget_sic           : num  1.76 16.01 3.3 1.22 1.28 ...
 $ govtarget_slw           : num  0.98 41.42 3.93 1.97 30.71 ...
 $ govtarget_siw           : num  -0.02 -1.58 -0.07 -0.03 -0.29 ...
 $ govtarget_sld           : num  76.4 321.7 160.1 68.1 95.1 ...
 $ govtarget_sid           : num  -1.6 -12.33 -2.88 -0.95 -0.86 ...
 $ gendereq_slc            : num  0 12.87 0 1.52 7 ...
 $ gendereq_sic            : num  0 0.87 0 0.52 0 ...
 $ gendereq_slw            : num  1 42.94 4 1.98 31 ...
 $ gendereq_siw            : num  0 -0.06 0 -0.02 0 ...
 $ gendereq_sld            : num  78 333.3 163 68.6 96 ...
 $ gendereq_sid            : num  0 -0.7 0 -0.41 0 ...
 $ dutch_slc               : num  7.46 88.3 15.37 5.27 8.61 ...
 $ dutch_sic               : num  7.46 76.3 15.37 4.27 1.61 ...
 $ dutch_slw               : num  0.91 35.27 3.67 1.91 31 ...
 $ dutch_siw               : num  -0.09 -7.73 -0.33 -0.09 0 ...
 $ dutch_sld               : num  71.2 275.5 149.6 65.7 94.6 ...
 $ dutch_sid               : num  -6.77 -58.46 -13.39 -3.35 -1.45 ...
 $ ebike_slc               : num  15.8 141 34.8 13.7 13.7 ...
 $ ebike_sic               : num  15.77 129.03 34.8 12.66 6.67 ...
 $ ebike_slw               : num  0.82 30.07 3.26 1.72 30.59 ...
 $ ebike_siw               : num  -0.18 -12.93 -0.74 -0.28 -0.41 ...
 $ ebike_sld               : num  63.7 234.9 132.7 59.1 90.4 ...
 $ ebike_sid               : num  -14.3 -99.08 -30.34 -9.92 -5.61 ...
 $ base_sldeath_webtag     : num  0 -0.01011 0 -0.00152 -0.00336 ...
 $ base_slvalue_webtag     : num  0 18758 0 2829 6234 ...
 $ govtarget_sldeath_webtag: num  -0.00282 -0.02303 -0.00468 -0.00342 -0.00492 ...
 $ govtarget_slvalue_webtag: num  5222 42731 8691 6349 9124 ...
 $ govtarget_sideath_webtag: num  -0.00282 -0.01292 -0.00468 -0.0019 -0.00156 ...
 $ govtarget_sivalue_webtag: num  5222 23973 8691 3520 2890 ...
 $ gendereq_sldeath_webtag : num  0 -0.01076 0 -0.00221 -0.00336 ...
 $ gendereq_slvalue_webtag : num  0 19952 0 4109 6234 ...
 $ gendereq_sideath_webtag : num  0 -0.00064 0 -0.00069 0 ...
 $ gendereq_sivalue_webtag : num  0 1194 0 1280 0 ...
 $ dutch_sldeath_webtag    : num  -0.01169 -0.07104 -0.02134 -0.00809 -0.00695 ...
 $ dutch_slvalue_webtag    : num  21690 131801 39598 15004 12891 ...
 $ dutch_sideath_webtag    : num  -0.01169 -0.06093 -0.02134 -0.00656 -0.00359 ...
 $ dutch_sivalue_webtag    : num  21690 113043 39598 12175 6657 ...
 $ ebike_sldeath_webtag    : num  -0.016 -0.0659 -0.0309 -0.0139 -0.0111 ...
 $ ebike_slvalue_webtag    : num  29651 122270 57294 25751 20643 ...
 $ ebike_sideath_webtag    : num  -0.01598 -0.05579 -0.03088 -0.01236 -0.00777 ...
 $ ebike_sivalue_webtag    : num  29651 103512 57294 22922 14409 ...
 $ base_sldeath_heat       : num  0 -0.00703 0 -0.00103 -0.006 ...
 $ base_slvalue_heat       : num  0 13051 0 1903 11135 ...
 $ govtarget_sldeath_heat  : num  -0.00184 -0.01621 -0.00309 -0.00228 -0.00726 ...
 $ govtarget_slvalue_heat  : num  3409 30065 5740 4236 13462 ...
 $ govtarget_sideath_heat  : num  -0.00184 -0.00917 -0.00309 -0.00126 -0.00125 ...
 $ govtarget_sivalue_heat  : num  3409 17014 5740 2333 2327 ...
 $ gendereq_sldeath_heat   : num  0 -0.00748 0 -0.00149 -0.006 ...
 $ gendereq_slvalue_heat   : num  0 13875 0 2764 11135 ...
 $ gendereq_sideath_heat   : num  0 -0.00044 0 -0.00046 0 ...
 $ gendereq_sivalue_heat   : num  0 824 0 861 0 ...
 $ dutch_sldeath_heat      : num  -0.00764 -0.05068 -0.01413 -0.00537 -0.00797 ...
 $ dutch_slvalue_heat      : num  14176 94032 26209 9962 14794 ...
 $ dutch_sideath_heat      : num  -0.00764 -0.04365 -0.01413 -0.00434 -0.00197 ...
 $ dutch_sivalue_heat      : num  14176 80981 26209 8059 3659 ...
 $ ebike_sldeath_heat      : num  -0.01054 -0.05039 -0.02077 -0.00937 -0.01193 ...
 $ ebike_slvalue_heat      : num  19554 93493 38538 17386 22134 ...
 $ ebike_sideath_heat      : num  -0.01054 -0.04336 -0.02077 -0.00835 -0.00593 ...
 $ ebike_sivalue_heat      : num  19554 80442 38538 15483 10999 ...
 $ base_slco2              : num  0 -4000 0 -531 -3360 ...
 $ govtarget_slco2         : num  -1084 -9163 -1770 -1177 -4167 ...
 $ govtarget_sico2         : num  -1084 -5163 -1770 -646 -807 ...
 $ gendereq_slco2          : num  0 -4294 0 -810 -3360 ...
 $ gendereq_sico2          : num  0 -294 0 -279 0 ...
 $ dutch_slco2             : num  -4594 -28475 -8243 -2805 -4726 ...
 $ dutch_sico2             : num  -4594 -24475 -8243 -2274 -1366 ...
 $ ebike_slco2             : num  -9712 -45479 -18671 -7265 -8632 ...
 $ ebike_sico2             : num  -9712 -41479 -18671 -6734 -5272 ...
 $ Rail                    : num  1 2 2 1 2 0 1 0 0 0 ...
 $ dist                    : num  9.75 6.55 10.55 11.61 9.52 ...
 $ dist_fast               : num  13.34 8.22 12.09 13.34 18.49 ...
 $ dist_quiet              : num  12.31 8.72 13.04 14.61 19.69 ...
 $ time_fast               : num  5598 3776 5646 6388 8876 ...
 $ time_quiet              : num  7232 4070 6612 7452 10822 ...
 $ cirquity                : num  1.37 1.25 1.15 1.15 1.94 ...
 $ distq_f                 : num  0.923 1.061 1.078 1.096 1.065 ...
 $ avslope                 : num  1.18 1.42 1.93 2.18 2.13 ...
 $ co2_saving              : num  2487 1532 2254 2486 3447 ...
 $ busyness                : num  32801 27452 34639 45943 56269 ...
 $ avslope_q               : num  0.0132 0.0157 0.0133 0.0168 0.0177 ...
 $ clc                     : num  0 2.69 0 1.12 4.73 ...

**Comment by usr110** [comment]
I can use 'Area.of.residence' and 'Area.of.workplace', but then again, they are only codes - not geo labels.

**Comment by Robinlovelace** [comment]
Thanks Ali, you're right there. Will look to update l with that data. In the meantime I guess those codes are the next best thing.

**Comment by usr110** [comment]
ok great, Robin.

**Comment by usr110** [comment]
@Robinlovelace Have now written some code to get geo_labels from zones data (see https://github.com/npct/pct-shiny/commit/fb508d3f1f528669c92e3d9c7291dc3da6fb5b31)
Once the geo_label is going to be furnished for both end points of line data, this code will be removed. Hence I am not closing the issue.

**Comment by Robinlovelace** [comment]
OK - do we *need* to add this to the line data? If it just works, and doesn't slow things down, I suggest we use your solution. Thoughts?

**Comment by usr110** [comment]
I haven't tested it whether it slows the performance or not, but as a _general principle_, I don't think it is wise to create variables on the fly. So yes, I believe, these variables should already be there in the data. In terms of data itself, if you think it's redundant to include "geo_label" in all of the lines, zones and cents objects, I guess, there can be a separate lookup table which can be recalled whenever a geo_code's label needs to be displayed - and remove the column 'geo_label' from all of the objects. What do you think?

**Comment by Robinlovelace** [comment]
I think it would be simpler to just include them in the lines to minimise complexity. I'm just not sure adding the line labels is that useful - have others in @npct/owners got views on this? One to discuss Friday probably.

**Comment by nikolai-b** [comment]
I'm happy to include them in the line data, about as useful as `Area.of.residence` but only if we want to display them.  @usr110 looks very clever but fully agree that doing spatial transformations on all the lines on-the-fly isn't great.

Currently we are displaying lots of information and personally I find the map tells me more about where the line starts and ends than a geo label so pinging this back to @JDWoodcock and @usr110?  If they are very keen they we should add them to the lines data.

**Comment by Robinlovelace** [comment]
My view is this: there's already a risk of TMI (too much information) so we should reserve what we show to what is necessary. Looking at the lines on the main site my view is that this is not essential information (you can see that by clicking on the centroids) and risks confusing people so should be removed (see below - seems an example of TMI to me).

![screenshot from 2016-04-22 11-41-53](https://cloud.githubusercontent.com/assets/1825120/14739457/8b5b2f16-087f-11e6-831e-a497cb266186.png)

**Comment by JDWoodcock** [comment]
I think it is very useful as sometime lines over lay each other and you can't see which is which without it.

**Comment by Robinlovelace** [comment]
Fair enough. If most people think it's a good idea I'm happy to be overriden.

**Comment by Robinlovelace** [comment]
Suggest we close for now, unless it seems to be an issue computationally. There are only 200 lines max in this so doubt it is.

**Comment by nikolai-b** [comment]
If we are keeping them can they be moved into the lines data please?

**Comment by Robinlovelace** [comment]
I would prefer that also - just closed as specific issue was solved.

**Comment by usr110** [comment]
Agree with @nikolai-b  on this. Close this issue once the new variables are added to the line object (l.Rds).

**Comment by usr110** [comment]
It should now be closed, since Robin added the [variables](https://github.com/npct/pct-load/commit/b26693de8980e4fcbfe75cf86a79aa7ae2d4865f) to the lines data

**Comment by Robinlovelace** [comment]
Yay, another one bites the dust :-)
