### ISSUE TITLE
Update name of FAQ to "User Manual and FAQ"

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#202]
I think it should be clear that this is a user manual.

The FAQ can go after.

I also suggest we remove the about page for the tool and link to it in a FAQ - worth discussing.

**Comment by nikolai-b** [comment]
Agree about combining but can we have a shorter name, i.e. just "User Manual".
Longer names take up valuable space in a prominent space and cause issues with small screen sizes.

**Comment by Robinlovelace** [comment]
Yes I agree with this suggestion.

**Comment by nikolai-b** [comment]
Looks done
