### ISSUE TITLE
Add 'How to report issues' section in User Manual

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#203]

**Comment by nikolai-b** [comment]
Rachel and I can do this one.

**Comment by Robinlovelace** [comment]
Great stuff - I've generalised this issue to build an updated User Manual for all regions, assuming we call it that. Idea: add basic data integrity tests in https://github.com/npct/pct-load/blob/master/model_output.Rmd . Suggest we double team it during a PCT power hour.
