### ISSUE TITLE
Lines/Network initial opacity is very low

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#208]
For some reason when you open the application and select any of the lines, the opacity of them becomes very low.

![initial-opacity](https://cloud.githubusercontent.com/assets/10958628/14780819/a79e6ac2-0ad6-11e6-9db9-170bd92537c4.png)

I've found it in all cases (straight, routes and route network).
This problem is resolved once you move around the screen or change the number of lines.

**Comment by usr110** [comment]
I've investigated this a bit and found that the conditional popups somehow are responsible. 

https://github.com/npct/pct-shiny/blob/master/server-base.R#L241

If you remove conditional popups for zones, then this issue is resolved. May be @nikolai-b you might want to look at it.

**Comment by Robinlovelace** [comment]
I also noticed this - thanks for reporting. You up for it Nikolai?
