### ISSUE TITLE
Index file takes you to the live server: pct.bike

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#209]
Whether you run index.html file locally or on the test server, it always takes you to the live server (pct.bike). I am talking about when you select a region in the map, and then click on it. The URL should not be hard-coded, but rather be relative. 
I believe the URL is being assigned in `mapgen.R` at:

https://github.com/npct/pct-shiny/blob/07fa2f9c424570e3a24436a2a335cf563f9e8d0e/scripts/mapgen.R#L27

@Robinlovelace correct me if I am wrong.

**Comment by Robinlovelace** [comment]
@usr110 yes this is right. Could you have a first bash at fixing it (you've found the right line to modify!)?

Well spotted - will help when others deploy pct-shiny on new servers.

**Comment by Robinlovelace** [comment]
Great work @usr110 - that's way better - pushed to npt1.
