### ISSUE TITLE
Lines are frozen to the current map extent when first initiated

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#210]
Reproducible example:

1: Start with a region:

![screenshot from 2016-04-26 12-10-55](https://cloud.githubusercontent.com/assets/1825120/14816322/0dbed4f0-0ba8-11e6-9ba1-5ceda0419d64.png)

2: Zoom in:

![screenshot from 2016-04-26 12-11-09](https://cloud.githubusercontent.com/assets/1825120/14816368/5f5d4ef4-0ba8-11e6-94d5-5c12eeb6551c.png)

3: Select lines:

![screenshot from 2016-04-26 12-14-32](https://cloud.githubusercontent.com/assets/1825120/14816397/95b4e462-0ba8-11e6-9472-7490389bac11.png)

4: Zoom out and they are stuck in the original place.

![screenshot from 2016-04-26 12-14-52](https://cloud.githubusercontent.com/assets/1825120/14816404/a184d496-0ba8-11e6-9d95-ae5909fffd83.png)

I think by default the lines should be frozen at the level of the the entire region first time, to minimise confusion (many people will never choose to unfreeze the lines). I think the fact that lines become unfrozen when the map unexpectedly jumps to another region (as illustrated below) is also an issue, but a separate one a this stage.

![screenshot from 2016-04-26 12-15-20](https://cloud.githubusercontent.com/assets/1825120/14816415/acf1f322-0ba8-11e6-997c-63251f3411c0.png)

**Comment by jf1** [comment]
I don't comprehend "I think be default the lines should be frozen the the entire region first time to minimise confustion" but agree with the principle of setting the default options to suit first-time and/or casual users. (And for info I haven't experienced "the fact that lines become unfrozen when the map unexpectedly jumps to another region").

My preference and suggestion would be for the following initial defaults:
Cycling flows: Route network
Freeze Lines: Off
N. Lines: 50%

If straightforward, I think displaying an [UPDATING] indicator somewhere would also help as it's not always immediately obvious if the map has started the process of updating itself. Ideally any existing lines would disappear immediately too.

**Comment by Robinlovelace** [comment]
Hi @jf1 thanks for your input. I've updated my comment to smooth over those typos.

We have discussed having the Route Network displayed by default but decided against it because it takes time to load and also because we want to show people the simplest and easiest to understand data first. That's the area level data. Also by showing the Route Network by default (without users seeing the line data options) it's possible that there's a misunderstanding about the provenance of the data - they could easily assume it's passively collected location data from a service such as Strava or Google Maps.

And regarding not have lines frozen by default, are you sure? When they are unfrozen they jump around lots when zooming or panning the map which can be surprising to the user. But we welcome input and acknowledge there are a range of views about what's best to for the project. Welcome to the discussion!

**Comment by nikolai-b** [comment]
I agree I'd prefer the default to be frozen off.  I expect a map to change when I zoom in but I'd also be happy to fix the zoom.  It would be easy to pin the bounds from when the map first opened if we showed either lines, routes or the network as default.  Would you be happy with one of these?

**Comment by Robinlovelace** [comment]
I'd be happy if it were initially pinned to the region's extent :) but unhappy if we confuse the **** out of people by allowing it to jump around freely by starting with the lines unfrozen, an extremely un-useful setting when one actually wants to zoom in to a specific road.

**Comment by nikolai-b** [comment]
I can see you don't want to have frozen on :smile: 

> It would be easy to pin the bounds from when the map first opened if we showed either lines, routes or the network as default. Would you be happy with one of these?

?

**Comment by Robinlovelace** [comment]
Yes I'd be happy with the 'pinning' option :)

**Comment by jf1** [comment]
I understand the computing reasons for not showing networks/lines on the initial display, but as the per-MSOA totals aren't that useful for most people (unless I'm missing something) I do feel it's worth trying to present a more informative 'lines' view on initial display. 

> they could easily assume it's passively collected location data from a service such as...

If this is an issue then showing the Census Flows as the initial default should address it, whichever of the lines views is displayed.

Could configuration parameters be passed to the map? If so, PCT's index page could have links for both the current (MSOA) view and another (eg Census, Network). Ideally the URL would also change if the map is moved or parameters are altered, as per OSM etc, so people can share a link to a specific view. eg #map=11/53.5/-2.3&scenario=census11&flows=network

[Also, I can't share a link to eg http://pct.bike/greater-manchester/#tab-8315-4 which isn't a problem but could also be addressed if you're updating the URL as above]

> I can see you don't want to have frozen on

I'm now more confused! In the post above @Robinlovelace suggests unfrozen would be un-useful. For the record I'm with @nikolai-b - I expect an online map to react to me moving and/or zooming it. For info, I don't suffer performance issues when 'freeze lines' is off, using a mobile i5 with 4GB and on-board graphics.

+1 for initially freezing the entire area's lines, although this introduces another under-reporting issue...

Here's an area within GM, that was zoomed-in to after the lines were frozen when zoomed-out:
![image](https://cloud.githubusercontent.com/assets/4711363/14854164/7d076604-0c86-11e6-9029-222011d962e7.png)

And here's the same area without the lines frozen, so more are displayed:
![image](https://cloud.githubusercontent.com/assets/4711363/14854240/d46fe7e0-0c86-11e6-8d1d-c676ce78407a.png)

Would that final concern be a non-issue if 100% of the lines could be shown (and frozen) ?

**Comment by jf1** [comment]
As feedback, I've just been caught out by the 'freeze lines' option being automatically switched on, exacerbated by the fact - or maybe I only noticed because - it was switched on with only 30% of the route network displayed.

Am I correct in thinking that if 100% of a route network was displayed when the 'freeze lines' option was selected then there'd be no need for any unfreezing as there'd be nothing for the map to react to when moved and/or zoomed?

**Comment by Robinlovelace** [comment]
Yes that's correct, although currently the route network only goes up to 50%.

**Comment by nikolai-b** [comment]
> Ideally the URL would also change if the map is moved

I've done this, I agree the URL should update.  Adding tab fragments sadly will not be possible as that would mean going deep into shiny code.

After the general meeting I'm not sure I want to freeze the map extent to when the map is first opened unless we want to show lines or routes (which we don't).  Without a bit more clarity on what we are after I'm going to deprioritize this.

**Comment by nikolai-b** [comment]
Re open if this becomes an issue
