### ISSUE TITLE
geojson export

### ISSUE THREAD

**Issue by jf1** [npct/pct-shiny#211]
Hi all, Jonathan from @GMcycling here.

The geojson export works fine as-is, but is there any way to export 100% of the data for an area, or is this already what's exported when viewing the entire area regardless of what "Percent (%) of Network" is set to?

I don't see the benefit of the export being limited by either the slider for N. Lines (most cycled) / Percent (%) of Network or the visible area. The former could lead to people working with an incomplete dataset, and while the latter may occasionally be useful I feel anyone dealing with an export is likely to be able to crop it themselves if required.

**Comment by Robinlovelace** [comment]
Agreed - I think there's a strong argument to export the entirety of the Route Network and other layers as a GeoJSON by default. You up for this one @nikolai-b ?

**Comment by Robinlovelace** [comment]
@nikolai-b re-opened as it fails for downloading the fastest routes, with the following error:

`Non-unique field names`

This sounds like a data issue but when I look at rf for west-yorkshire I get:

```r
names(rf)
 ## [1] "plan"        "start"       "finish"      "length"      "time"        "waypoint"    "change_elev" "av_incline"  "co2_saving" 
## [10] "calories"    "busyness"    "id"          "nv"         

unique(names(rf))
## [1] "plan"        "start"       "finish"      "length"      "time"        "waypoint"    "change_elev" "av_incline"  "co2_saving" 
## [10] "calories"    "busyness"    "id"          "nv"  
```

So suggest it's perhaps a replicated column name added in `server-base.R`. Thoughts?

Reproduced for West Yorkshire on npt1 and locally. Please test.

**Comment by usr110** [comment]
For an explanation, ldata already contained the latest lines/routes data described at:

https://github.com/npct/pct-shiny/blob/master/server-base.R#L338

**Comment by usr110** [comment]
Ah sorry. I get it. I need to revert it. If you would like to export all lines/routes, then it needs to be reverted.

**Comment by usr110** [comment]
Fixed in: https://github.com/npct/pct-shiny/commit/f49227cb1f97566a6eac648e3bc9ff8e3537970d

**Comment by Robinlovelace** [comment]
Great fix Ali - tested and pushed to production and now running on npt1.

**Comment by jf1** [comment]
This appears to be working as expected - thanks - and sorry to comment on a closed issue, but please can someone confirm that any route network export from eg http://pct.bike/greater-manchester/ will include all of that area's route network, regardless of the current map view or menu slider settings?

When in 'fast & quiet routes' mode it seems to download an infinite number of fast/quiet route lines for the whole of the area - is this the case?

Finally, I can't spot any reference to a line being from a fast or quiet route - am I missing something or is this something that could be added to the export?
