### ISSUE TITLE
Routing engine splits cycle flows on dual carriageways

### ISSUE THREAD

**Issue by jf1** [npct/pct-shiny#212]
This can only be spotted when zoomed-in (top two pictures). If a user clicks on what looks like a single line when zoomed-out (bottom picture), the pop-up only displays the flow details for one side of the dual carriageway, so the user may think a route has less cyclists or potential cyclists than the number PCT has calculated for the whole of that section of highway.

I understand cyclestreets has some code that runs on its regular OSM imports to 'combine' related ways that are alongside each other and within the same highway/corridor.

![image](https://cloud.githubusercontent.com/assets/4711363/14818079/f32c9a72-0bb2-11e6-99de-f894dd907c70.png)
![image](https://cloud.githubusercontent.com/assets/4711363/14818091/0607455c-0bb3-11e6-8a43-259e149c8f09.png)
![image](https://cloud.githubusercontent.com/assets/4711363/14818095/0cea6a48-0bb3-11e6-9596-a0c9f10bc9b8.png)

**Comment by Robinlovelace** [comment]
Thanks for this but we do not develop the routing engine. We could pre-process the 'rnet' layer to merge lines that are close together but I suspect that this is rare enough and that the process will be fiddly enough (with the potential of adding unwanted side effects) that it's not worth it. Thanks for flagging this in any case - could be useful as a 'watch out' issue in our documentation.

**Comment by jf1** [comment]
I wouldn't describe it as a rare issue, it happens on every dual carriageway. Pre-processing the layer to combine adjacent lines would remove the problem of lines that don't fully report the (potential) usage of that corridor.

**Comment by mvl22** [comment]
Interesting issue.

I do think this is best handled at a client (i.e. PCT) level - in such streets there can be significant distances between sides of the road, and I think any sensible routing engine will not try to change the geometry to a centre-point that doesn't exist, because that's not what a cyclist actually cycles on. Combining based on the road name and proximity would seem sensible.

This is I think actually a generic issue with the OSM model of representing the world. OSM tries to represent streets as individual lines, whereas in fact they are areas that often have multiple flows with differing characteristics within them. We see the same issue in other cases: things like a segregated cycleway alongside a road are represented separately, whereas they are conceptually part of the concept of the road as a whole, just separated by concrete. The same applies to dual carriageways - people conceptually think of them as a road which goes in two directions, whereas OSM represents them as the physical case of two lines.

OSM has a sort-of mechanism for dealing with this general issue: relations, but that is hard work to do that for every street in the world.

**Comment by mvl22** [comment]
> I wouldn't describe it as a rare issue, it happens on every dual carriageway. Pre-processing the layer to combine adjacent lines would remove the problem of lines that don't fully report the (potential) usage of that corridor.

Bear in mind though that, in many cases, a dual carriageway will be sufficiently wide, and therefore physically imposes a signficant movement barrier between two sides of the urban realm (however much crossing infrastructure a Local Authority might build) that they can end up being _de facto_ quite different routes in practice.

E.g.
http://www.openstreetmap.org/#map=16/51.4875/-0.2517&layers=C

**Comment by Robinlovelace** [comment]
Agreed - in some cases (York Road in Leeds is another example) it is advantageous to see the flow on either side of the primarily impermeable dual carriageway. Marking this as 'for the future' for now and parking unless someone comes up with a neat script to merge approximately parallel lines within some threshold distance (e.g. 10 m).

**Comment by jf1** [comment]
I'm aware that large dual carriageways can create severance but was considering what I understand to be PCT's primary focus: suggesting where a high quality cycling environment would be valuable. If PCT doesn't report all of the (potential) flow on a corridor then investment in that corridor may be considered less valuable than it would actually be.

Your dual carriageway examples highlight the benefit of 2x 2-way cycleways alongside such large roads, but for roads that currently have nothing we need PCT to help justify the investment required for any cycleway, even if just on one side initially, hence my concern about its potential under-reporting.

The image below highlights how this issue affects large junctions too - I'd really like to be able to see a single figure for all (potential) cycle journeys through the junction.
![image](https://cloud.githubusercontent.com/assets/4711363/14853598/16523936-0c84-11e6-95f5-069b2ec6898b.png)

Fully agree with Martin on the generic issue within OSM. Another example is that shared-use footways need to be standalone OSM ways while standard footways usually aren't recorded in OSM at all. It's unlikely that we'd benefit from every footway being in OSM but I believe there are benefits in eg being able to separate single carriageway roads to assign different numbers of lanes or CEAT scores for each direction, while we'd also benefit from a grouping system so all elements of that section of highway can be treated as one link when that's more apt - but I appreciate this wouldn't be a PCT matter.

**Comment by Robinlovelace** [comment]
Thanks for another example. What it shows clearly is that users can clearly see when and where this is happening. This 'known unknown' is much preferable to 'unknown unknowns'. In terms of where people *actually travel* I suspect the dual routes may be more accurate which has some advantages that all people are together travelling down the middle of the road. Practical suggestions of how to deal with this without creating a load of knock-on issues would be useful. I suspect at this stage the known and unknown costs of tackling it will be greater than the known and unknown benefits of representing dual carriageways as a single line.

**Comment by jf1** [comment]
Be mindful that users can only see this clearly when zoomed in a lot, and even then the implications of multiple lines might not be obvious to all users. Also, many (most?) users might not be as determined as me to get the data they're after.

> I think that representing people travelling down the middle of a dual carriageway has disadvantages

This makes me think you're missing my point - it's not about what it looks like, especially not when fully zoomed in; my concern is that people are being presented with a value that is lower than the total value for that entire highway route, and they possibly wouldn't be aware of this factor. If they use this lower value in their work it could negatively affect efforts to secure investment for the route.

I agree that a practical solution free of side-effects would be desirable, so will keep considering.

**Comment by Robinlovelace** [comment]
Great stuff - what I meant is that if people using the tool know about the danger with dual carriageways they can take action to interpret the results accordingly. Look forward to any proposed solutions.

**Comment by Robinlovelace** [comment]
This is essentially the same as this: https://github.com/npct/pct-shiny/issues/333 . We found that by adjusting the parameters in `ms_simplify()` we can make parallel paths join. That's the solution for now, this is no longer actionable so closing for now.
