### ISSUE TITLE
Data in frontpage map seems wrong

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#216]
North Yorkshire says it has 5% of trips by cycle, for example:

![percent-cycling-wrong](https://cloud.githubusercontent.com/assets/1825120/14902023/567c32d4-0d90-11e6-9e93-a6526c7a4acb.png)

**Comment by Robinlovelace** [comment]
Also make names consistently capitalised.

**Comment by jf1** [comment]
Just a heads-up on Capitalisation - I don't think all words eg of Cornwall-and-isles-of-scilly should be capitalised. The Government does have (several) 'definitive' lists that cover this (and hopefully one day they'll publish a single definitive registry!)
