### ISSUE TITLE
Give more meaningful names to geojson exports

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#217]

**Comment by Robinlovelace** [comment]
Great - tested, works. Quietest routes are so much clearer now. See below for West Yorkshire - 70 MB download though...
![screenshot from 2016-05-12 15-20-11](https://cloud.githubusercontent.com/assets/1825120/15217850/4cd13bce-1855-11e6-9a48-d9ab82d5ff76.png)

**Comment by Robinlovelace** [comment]
@nikolai-b I've pushed to production but not npt1. Can you push there? I don't want to as worried new **shinyjs** dependency may crash it. Thoughts @usr110? Safe to push?

**Comment by usr110** [comment]
@Robinlovelace For this @nikolai-b is the right person. It works fine on the testing server, btw.
