### ISSUE TITLE
Make popups for straight and route lines the same

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#22]
At present they look like this:

![selection_176](https://cloud.githubusercontent.com/assets/1825120/7116402/4c263970-e1e9-11e4-8ccc-43592d8b2ca8.png)

and this...

![selection_177](https://cloud.githubusercontent.com/assets/1825120/7116404/524d7a48-e1e9-11e4-94cc-7300fb0d78f0.png)

It would be easier and preferable for the popups to be the same, including route and euclidean distance for each, as well as other attributes.

**Comment by nikolai-b** [comment]
Moved to https://trello.com/c/5XuwjmBL/63-harmonize-route-and-straight-line-pop-ups
