### ISSUE TITLE
Wrong route data showing on test server for WY

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#222]
As illustrated here:

![screenshot from 2016-05-06 11-21-00](https://cloud.githubusercontent.com/assets/1825120/15070575/f687ef10-137c-11e6-8a42-b10d98247738.png)

I suspect this was re-added here: https://github.com/npct/pct-data/commit/5e8311380108a46c3e8d4ed8e62e2d44e37174ce

@nikolai-b I think checking out the penultimate versions of the data will fix this. Not quite sure where it's breaking in pct-load. Are you using the latest version of the binary versions I saved in the release of pct-bigdata?

**Comment by nikolai-b** [comment]
Your right, using an old version will hide this but we need to solve it in pct-load.  My pct-bigdata is upto date with github but I guess the rf and rq has been updated, is this the right version
https://github.com/npct/pct-bigdata/releases/tag/0.2 of them?

**Comment by Robinlovelace** [comment]
Yes.
