### ISSUE TITLE
Route Network % is too incremental

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#223]
Before it was either 10, 30 or 50% which is good because it prevents people from moving it lots which makes the map slow down. Now it can be any %, probably a regression added in this commit: https://github.com/npct/pct-shiny/commit/ea653aeb1963e16b0f22ae56ff6758d6396f9670

Please can you revert it to its original behaviour for the Route Network @nikolai-b but leave it in 1% increments for the straight lines (which works great btw).

**Comment by nikolai-b** [comment]
Nice one @Robinlovelace , thanks!
