### ISSUE TITLE
logos

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#225]
please add University of Cambridge, CEDAR, University of Leeds, and University of Westminster logos to front page below map & text

**Comment by JDWoodcock** [comment]
here are the logos please put UofC, CEDAR, Leeds, Westminster
![cambridge](https://cloud.githubusercontent.com/assets/11028720/15267746/2f8358a4-19c2-11e6-9f3e-d6d994fe9e93.jpg)
![leeds](https://cloud.githubusercontent.com/assets/11028720/15267747/2f84df30-19c2-11e6-9bc4-e600b9a3220f.png)
![cedar-690](https://cloud.githubusercontent.com/assets/11028720/15267745/2f827c2c-19c2-11e6-8d17-16f8e28c801a.png)

**Comment by RachelAldred** [comment]
Here's Westminster
![uni-logo](https://cloud.githubusercontent.com/assets/11818218/15267757/5596f0f0-19c2-11e6-95d8-f39d2c4cc6e7.jpg)

**Comment by JDWoodcock** [comment]
this isn't looking right on test site for me.

**Comment by Robinlovelace** [comment]
Try on the main site - had a mini teething issue which is now resolved.

**Comment by JDWoodcock** [comment]
i suggest they are much smaller - particularly dft- and dft is on same line as the rest

**Comment by Robinlovelace** [comment]
I've tweaked it. We can discuss how to arrange these further but for now they are in there and they are smaller. Not making any further changes to this - close if happy. Suggest creating a 'megalogo' if you'd like complete control over where these lie in relation to each other as a png - then we can put that up but I think this is fine for now.

**Comment by JDWoodcock** [comment]
okay I made a metalogo- suggest keep it small
![combined logos](https://cloud.githubusercontent.com/assets/11028720/15269377/9495a224-19f4-11e6-99f8-51c248f8f270.png)

**Comment by JDWoodcock** [comment]
![logos](https://cloud.githubusercontent.com/assets/11028720/15291145/57a33648-1b74-11e6-9cb7-5e3de2f31bfd.png)

**Comment by JDWoodcock** [comment]
I hope that looks better

**Comment by usr110** [comment]
@JDWoodcock Fixed it in - https://github.com/npct/pct-shiny/commit/4bc7a828ba5430488b9f2e475070124a6f1afe44

See here: http://geo8.webarch.net/test/

**Comment by JDWoodcock** [comment]
thanks

**Comment by JDWoodcock** [comment]
I think it still needs to be a bit smaller and more spaced- i had another go 
![logos](https://cloud.githubusercontent.com/assets/11028720/15325024/d5e38f7c-1c40-11e6-9dd3-4567edaba8d5.png)

**Comment by usr110** [comment]
Fixed it: https://github.com/npct/pct-shiny/commit/c376a83010088e5f11d2cd3138f04cb91365398c
Not closing it for now. Test it and then share your feedback.
You can see it live on the [test server](http://geo8.webarch.net/test/).

**Comment by Robinlovelace** [comment]
Looks great - pushed to production. Fairly uncontroversial so closing for now.

**Comment by JDWoodcock** [comment]
new suggested layout by Oliver and example of how it should look on page- not this is apparently the right CEDAR logo to use
![logo](https://cloud.githubusercontent.com/assets/11028720/15588691/fdae60ca-2386-11e6-9b98-6b796efdfc52.jpg)
![example of page](https://cloud.githubusercontent.com/assets/11028720/15588692/fdaf8acc-2386-11e6-9f88-72f0d372e37e.jpg)
