### ISSUE TITLE
Change regional boundaries

### ISSUE THREAD

**Issue by nikolai-b** [npct/pct-shiny#228]
There should be a Combined Authority for the North East. This covers Northumberland, County Durham and Tyne and Wear.

Moved from https://github.com/npct/pct-load/issues/7

**Comment by jf1** [comment]
The latest ONS data include Combined Authority information.
Available [here](https://geoportal.statistics.gov.uk/geoportal/catalog/search/resource/details.page?uuid=%7B1AC0D632-38B9-4E08-8AC8-6D87DCF10421%7D) and [here](https://geoportal.statistics.gov.uk/geoportal/catalog/search/resource/details.page?uuid=%7B5F424985-A5B2-49F8-AB2C-20CE9E64691C%7D). They're only small files so pasted below...

CAUTH16CD,CAUTH16NM
E47000001,Greater Manchester
E47000002,Sheffield City Region
E47000003,West Yorkshire
E47000004,Liverpool City Region
E47000005,North East
E47000006,Tees Valley

LAD16CD,LAD16NM,CAUTH16CD,CAUTH16NM
E08000001,Bolton,E47000001,Greater Manchester
E08000002,Bury,E47000001,Greater Manchester
E08000003,Manchester,E47000001,Greater Manchester
E08000004,Oldham,E47000001,Greater Manchester
E08000005,Rochdale,E47000001,Greater Manchester
E08000006,Salford,E47000001,Greater Manchester
E08000007,Stockport,E47000001,Greater Manchester
E08000008,Tameside,E47000001,Greater Manchester
E08000009,Trafford,E47000001,Greater Manchester
E08000010,Wigan,E47000001,Greater Manchester
E08000016,Barnsley,E47000002,Sheffield City Region
E08000017,Doncaster,E47000002,Sheffield City Region
E08000018,Rotherham,E47000002,Sheffield City Region
E08000019,Sheffield,E47000002,Sheffield City Region
E08000032,Bradford,E47000003,West Yorkshire
E08000033,Calderdale,E47000003,West Yorkshire
E08000034,Kirklees,E47000003,West Yorkshire
E08000035,Leeds,E47000003,West Yorkshire
E08000036,Wakefield,E47000003,West Yorkshire
E06000006,Halton,E47000004,Liverpool City Region
E08000011,Knowsley,E47000004,Liverpool City Region
E08000012,Liverpool,E47000004,Liverpool City Region
E08000013,St. Helens,E47000004,Liverpool City Region
E08000014,Sefton,E47000004,Liverpool City Region
E08000015,Wirral,E47000004,Liverpool City Region
E06000047,County Durham,E47000005,North East
E06000057,Northumberland,E47000005,North East
E08000021,Newcastle upon Tyne,E47000005,North East
E08000022,North Tyneside,E47000005,North East
E08000023,South Tyneside,E47000005,North East
E08000024,Sunderland,E47000005,North East
E08000037,Gateshead,E47000005,North East
E06000005,Darlington,E47000006,Tees Valley
E06000001,Hartlepool,E47000006,Tees Valley
E06000002,Middlesbrough,E47000006,Tees Valley
E06000003,Redcar and Cleveland,E47000006,Tees Valley
E06000004,Stockton-on-Tees,E47000006,Tees Valley

**Comment by Robinlovelace** [comment]
Bump re. Coventry

**Comment by jf1** [comment]
The West Midlands CA is currently described as 'emerging' and devolution is only a proposal 
(although likely to proceed).

It's certain that the CA will include the 7 'constituent' LAs but I'm not sure how the other 5 'non-constituent' LAs and 3 LEPs fit, either geographically or legally. https://westmidlandscombinedauthority.org.uk/about/whos-included/

When LA and LEP boundaries don't align (as is the case in West Mids) then I'm not sure which boundaries PCT should use. https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/229400/121115_Enterprise_Zones_map.pdf https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/252793/bis-11-768-local-enterprise-partnerships-boundary-map-august-2013.pdf

Creating a downloadable UK-wide dataset would enable QGIS users to avoid any negative impacts of area boundaries, and also satisfy the verbal request made by @awjreynolds on Saturday.

**Comment by Robinlovelace** [comment]
From @JDWoodcock "please can we have Cov back in Warwickshire please"

**Comment by Robinlovelace** [comment]
From @JDWoodcock: "I realise Change regional boundaries #228 covers this but this was something we agreed with the planners in Cov. I realise a Metro region is planned but it won't involve much cycling between Cov & Birmingham area as there is a green belt. However, there is cycling between Cov and Warwickshire. The current bondaries do look wrong."

**Comment by JDWoodcock** [comment]
Okay move it here but in that case I have removed the for the future label

**Comment by Robinlovelace** [comment]
:+1:

**Comment by AnnaGoodman1** [comment]
James, Robin and I have discussed this and we were bit confused – Coventry is in Warwickshire in the current version of the build, both on PCT bike and on the test server.  So perhaps this is now resolved?

**Comment by Robinlovelace** [comment]
Update: just Cleveland.

**Comment by Robinlovelace** [comment]
Update: method to re-generate them all if needs be is here: 


    Take all County and Unitary Authorities
    Group all those in Combined Authorities
    Of the remainder, group all those into Metro counties
    Of the remainder, group these into non-metropolitan counties
    Merge any remaining Local Authority outliers that seem too small into counties they share the largest border with (e.g. York into North Yorkshire)
    Keep unusual LAs separate (e.g. Isle of Wight)

This is based on the excellent pdf here:

https://www.google.co.uk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiCh96tptDPAhVsBcAKHYtvCA4QFggeMAA&url=http%3A%2F%2Fwww.ons.gov.uk%2Fons%2Fguide-method%2Fgeography%2Fbeginner-s-guide%2Fmaps%2Fregions-and-their-constituent-counties---unitary-authorities-as-at-2011.pdf&usg=AFQjCNGGt1D9nJVKgsJ3axhDzWqAteFhWg&sig2=E-_x9GkJ45Um7NCK0x3ZIg

Option A would be easier but I suspect option B may be what the DfT prefers. We would look to you or your colleagues for judgement calls about edge cases (e.g. Cleveland).

Many thanks for looking into it, look forward to decisive guidance on this tricky issue.
