### ISSUE TITLE
Create test lsoa level data for V1.5

### ISSUE THREAD

**Issue by nikolai-b** [npct/pct-shiny#233]
https://github.com/npct/pct-load/issues/49

**Comment by mem48** [comment]
There is now some test LSOA data for Cambridge at https://github.com/npct/pct-lsoa-test/tree/master/data currently it is rf and rq do we need anything else?

**Comment by mem48** [comment]
I've done some initial playing with the LSOA data and thought I would report some early findings

1) There is a lot more data 103.2 Mb for Cambridge vs 8.8 Mb for Cambridgeshire - n.b. different areas
2) R crashed repeatedly when trying to plot the LSOA in leaflet and was very slow with built in plot
3) Aggressive simplification "gSimplify(lsoa,0.5,TRUE)" helped reduce file size to 55.7 Mb and stopped the crashes but is a poor match for the actual road network.
4) Number and type of roads used is significantly different

![lsoa_vs_msoa](https://cloud.githubusercontent.com/assets/15819577/19597224/3283268c-978b-11e6-8c68-a9b76210b882.png)

Image shows just the centre of Cambridge, MSOA rf in blue LSOA rf (simplified) in Red. The MSOA lines are on top of the LSOA lines so Blue+Red would reflect the whole LSOA route network.

**Comment by mem48** [comment]
For interest (and for a possible paper) I ran a small amount of OA to WorkZone.

![oa vs lsoa_vs_msoa](https://cloud.githubusercontent.com/assets/15819577/19603439/0743d3f4-97a9-11e6-8aca-4a7911553bb2.png)

The OA level routes are in Green and don't make a significant difference to the routes, mostly adding small deviations off main roads onto residential roads, we may have found the evidence we need of how much spatial disaggregation is needed.

**Comment by Robinlovelace** [comment]
Done - thanks @mem48
