### ISSUE TITLE
Add cycling under each scenario to front page map

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#239]
Proposed by me, advocated by @RachelAldred and tested here:
http://pct.bike/map-test.html

@JDWoodcock if you sign-off on this as tested + suggest any changes I can implement it.

**Comment by JDWoodcock** [comment]
looks good to me

**Comment by jf1** [comment]
The extra values are useful and appreciated - it's very effective to see the national colours change from census 2011 to Go Dutch scenario.

The pop-up inconsistently uses `,` and `linefeed` as can be seen in:
![image](https://cloud.githubusercontent.com/assets/4711363/15250784/3deb419e-191e-11e6-92e8-4bf51c4747db.png)
I'd suggest this should be either:
`Greater Manchester, 2.2% cycle to work in 2011 Census, 20.9% cycle to work in Go Dutch scenario`
Or:
`Greater Manchester:`
`2.2% cycle to work in 2011 Census`
`20.9% cycle to work in Go Dutch scenario`

Finally, just as a heads-up as it may only affect the test html, I can't get the new popup to appear on my mobile (Dolphin on Android) which has no such problem with popups on the main pct.bike map.

**Comment by jf1** [comment]
2 requests...

If supported by @JDWoodcock @RachelAldred, could there be a third layer called `potential uplift` or similar?

And please can you provide a csv listing `2011 Census` and `Go Dutch` cycling ttw rates for each area?
I'd also be interested to see each area's `Government target`, `Gender equality` and `Ebikes` figures too.

**Comment by jf1** [comment]
I've since thought about this further and now suggest 9 layers in two groups:

**Scenario** (as % Cycling to work)
2011 Census
Government Target
Gender equality
Go Dutch
Ebikes

**Potential Uplift** (scenario/census, as %)
Government Target
Gender equality
Go Dutch
Ebikes

Even if all 9 views are available I'd still like an option to download a csv with the 9 values for each area.

**Comment by JDWoodcock** [comment]
the legends could be a bit bigger @Robinlovelace
