### ISSUE TITLE
Include walking in popups & make them collapsable

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#240]
1) it would be very useful to show change in walking as that would make the HEAT calculation reproducible- some places have suprising numbers that will be due to high shift from walking but..
2) we dont want more things to display so I suggest we have minimum pop up that can be expanded

**Comment by Robinlovelace** [comment]
Another one to test and discuss before deciding whether or not to implement on production I think.

**Comment by Robinlovelace** [comment]
Closing for now - happy for this to be re-opened but preferably when it becomes actionable.
