### ISSUE TITLE
replace pop ups by boxes at side

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#241]
@usr110 please add some more text to describe your issue

**Comment by Robinlovelace** [comment]
To clarify, this is one to test on a new branch before it's agreed as an addition to production as it's difficult to imagine how it will affect the UI/aesthetics without testing it first.

**Comment by usr110** [comment]
Explained it here - https://github.com/npct/pct-shiny/pull/249
Also now the new branch can be tested as well.

**Comment by usr110** [comment]
@nikolai-b If you get the time, could you please re-test the [PR](https://github.com/npct/pct-shiny/pull/249)? I believe I've fixed all the errors.

**Comment by Robinlovelace** [comment]
Hi @usr110 sorry this has taken so long to test - please could you confirm if this is ready to test again? Note this is now possible without any JS hacks: http://rpubs.com/bhaskarvk/polygon-highlight - issue: https://github.com/rstudio/leaflet/issues/195

**Comment by Robinlovelace** [comment]
Low priority job - closing for now, perhaps to re-open in Phase III.
