### ISSUE TITLE
Add download csv functionality

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#243]
- [ ] For lines
- [ ] For areas

I envision this looking something like this in the lines data tab (text can be smaller):

![screenshot from 2016-05-14 17-47-32](https://cloud.githubusercontent.com/assets/1825120/15269613/5630eeb4-19fc-11e6-89d0-098090c8e9ad.png)

**Comment by Robinlovelace** [comment]
Discussed with @nikolai-b who may be up for adding the sha to the download link in pct-shiny.

**Comment by JDWoodcock** [comment]
Can we also have shape file option @RachelAldred

**Comment by Robinlovelace** [comment]
That's already in there as geojson. @JDWoodcock geojson is the open source equivalent of a shapefile and is more portable: 

![screenshot from 2016-05-16 19-47-00](https://cloud.githubusercontent.com/assets/1825120/15300142/0584e41c-1b9f-11e6-9dd8-271138f95174.png)

I think the main issue is communicating *how* to download the data and what you can do with it. @RachelAldred and I are on it, as described here: https://github.com/npct/pct-shiny/issues/244
