### ISSUE TITLE
Manual is missing higher resolution figures/pictures

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#248]
Just noticed that manual is missing higher resolution figures/pictures. 
Before the new structure of the application, when there was a 'master' folder, the figures were hosted at two different locations:
- Lower resolution were saved at [master/assets](https://github.com/npct/pct-shiny/tree/6d772919271081675fdacb8ea58b30590b09504a/master/assets).
- Higher resolution at [master/www/assets/FAQs/](https://github.com/npct/pct-shiny/tree/6d772919271081675fdacb8ea58b30590b09504a/master/www/assets/FAQs)

This allowed users to see the lower resolution in the FAQs, and when clicked, higher resolution figures were displayed.

For instance, the higher resolution of Fig0 looked like [this](https://raw.githubusercontent.com/npct/pct-shiny/6d772919271081675fdacb8ea58b30590b09504a/master/www/assets/FAQs/Fig0.png)

Somehow with the new structure, these two folders got merged. Now users can not see the higher resolution figures/pictures.

**Comment by Robinlovelace** [comment]
Thanks for the report. This relates to the proposal to port the manual to an Rmd, making it easier for others to contribute, as described here: https://github.com/npct/pct-shiny/issues/201 - are you happy for the shift to the [Rmd format](https://github.com/npct/pct-shiny/blob/master/static/manual-markdown.Rmd) - I think it does everything the raw html file did.

Please test and let me know if you're happy to be the new manual.

**Comment by Robinlovelace** [comment]
I.e. I propose this is fixed in the new file.

**Comment by usr110** [comment]
Robin, good work. I am fine to switch to the Rmd file. Just for a test, I tried to knit the `manual-markdown.Rmd` file but it doesn't seem to run. I receive this error:

> pandoc.exe: Could not fetch ./assets/help/scenario-selection.png
./assets/help/scenario-selection.png: openBinaryFile: does not exist (No such file or directory)
Error: pandoc document conversion failed with error 67
In addition: Warning message:
running command '"C:/Users/aa797/AppData/Local/Pandoc/pandoc" +RTS -K512m -RTS manual-markdown.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output "C:/RStudio Projects/pct-shiny/static/../regions_www/manual.html" --smart --email-obfuscation none --self-contained --standalone --section-divs --template "C:\PROGRA~1\R\R-32~1.5\library\RMARKD~1\rmd\h\DEFAUL~1.HTM" --variable "theme:bootstrap" --include-in-header "C:\Users\aa797\AppData\Local\Temp\RtmpovUJl2\rmarkdown-str26b42733a01.html" --mathjax --variable "mathjax-url:https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" --no-highlight --variable "highlightjs=C:\PROGRA~1\R\R-32~1.5\library\RMARKD~1\rmd\h\HIGHLI~1" --variable "navigationjs=C:\PROGRA~1\R\R-32~1.5\library\RMARKD~1\rmd\h\NAVIGA~1.0" --include-in-header header-other.html --include-after-body doc_afix.html' had status 67 
Execution halted

It seems knit is unable to find the `www` folder. Any guess what might be going on there?

**Comment by Robinlovelace** [comment]
Works fine form me (see below). Suggest it's an issue with your pandoc setup - please try running from a unix-like system to reproduce. In any case I'll switch to this markdown version and delete the old one as it's easier to edit and maintain.

![selection_116](https://cloud.githubusercontent.com/assets/1825120/15387358/a78033be-1da4-11e6-8d0b-e58886553588.png)

**Comment by usr110** [comment]
Three things:
- Don't have access to a linux system, so sorry can't test it. If it works on your system, then go ahead.
- If you are going to change the `Manual.html` file, please test it first (by including it in the ('ui-base.R')[https://github.com/npct/pct-shiny/blob/master/ui-base.R#L161]. I have a feeling that it won't smoothly work; the added CSS introduced by knit will try to change the layout.
- Also please remove all unused files for the manual.

**Comment by nikolai-b** [comment]
@usr110 when you load the app it downloads all the files in the assets folder so was downloading  https://github.com/npct/pct-shiny/blob/9762bd71234e2d128416e1a3322e4226626a5f3b/www/assets/FAQs/Route.png
i.e. a 7Mb file!  This slows down the site so I scaled it in 
03815c01 but may have gone to far in ba85d61

**Comment by Robinlovelace** [comment]
Seems fixed here so closing for now: http://pct.bike/manual.html

**Comment by usr110** [comment]
I spent a lot of time generating high resolution figures, based on the suggestions of @RachelAldred and @AnnaGoodman1. Let's close it when the wider team agrees that they are not needed any more. I still feel the figures don't have enough resolution.

**Comment by Robinlovelace** [comment]
OK - please could you specify which ones need higher res images when you click on them? That way I can updated the manual. Last time I checked they seemed fine, e.g. http://npct0.vs.mythic-beasts.com/kent/assets/FAQs/Fig0.png from here: http://npct0.vs.mythic-beasts.com/manual.html

**Comment by Robinlovelace** [comment]
Closing for now as we're updating the manual.
