### ISSUE TITLE
Zone popup only shows baseline's variables irrespective of the underlying scenario

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#25]
I don't know if it is intentional or not, but I was trying to compare the values of the legend with the zone popup and found an anomaly. It seems the zone popups only show the baseline zone attribute values - don't change according to the selected scenario.

You can see the code here: 

https://github.com/npct/pct-shiny/blob/master/master/pct-shiny-funs.R#L59

This, of course, makes the legend having different values than the popup values.

**Comment by usr110** [comment]
I've fixed it - https://github.com/npct/pct-shiny/commit/5c378bcbaaf104491fe8f13ed10788905b93ea74

You may revert if it is needed.

**Comment by Robinlovelace** [comment]
Many thanks Ali, you can close the issue as you fixed it. Props for the initiative :+1:

**Comment by nikolai-b** [comment]
LGTM, as a corollary I've done the same with the line popups (waiting for https://trello.com/c/5XuwjmBL/63-harmonize-route-and-straight-line-pop-ups before I do the same with the route popups)
