### ISSUE TITLE
Add a more readable map base

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#251]
It is hard to read names of the cities/town especially when the zone-layer is displayed

**Comment by usr110** [comment]
Added a new layer in [this](https://github.com/npct/pct-shiny/commit/99c532e10f9047c0316c30b77762fdd169ed3171) commit.

![thunderbird-tile](https://cloud.githubusercontent.com/assets/10958628/15432526/82f5823a-1ea6-11e6-802e-9d2f56405bd2.png)

Pushed onto the [test server](http://geo8.webarch.net/test/greater-manchester/)
We can discuss if it is useful. If it is, then what name should be given to the base? 
`Thunderbird` isn't a useful name.

**Comment by Robinlovelace** [comment]
I don't like that particular basemap - we can usually assume users know where things are so don't think large city names is vital. Good to have more basemaps but not sure what this commit is trying to solve - more explanation please from a user perspective @usr110. Agreed, Thunderbird is not an appropriate name and I think this is a really ugly basemap! Any more beautiful *and* useful ones out there?

**Comment by Robinlovelace** [comment]
@usr110 Could you provide an image that shows when city names can't be seen in a way that will be problematic to transport planners (who generally know the region).

**Comment by Robinlovelace** [comment]
Looks like that's been fixed.

**Comment by usr110** [comment]
Have reverted the commit [here](https://github.com/npct/pct-shiny/commit/65a3605b287402feccb7bb8a8f93841c7f95d17d), but the issue is already there. It has got slightly better by reducing the opacity of zones in the [commit](https://github.com/npct/pct-shiny/commit/0f2b9fbc6c088cb65ff69cbd55cc3f166af9245a), but still the names of towns/cities can be further improved. We need a better map base.

**Comment by Robinlovelace** [comment]
> We need a better map base.

I'm not sure we do based on user testing and demonstrations where this is my 'go to' map when I want to highlight data we have demonstrated - I selected that one due to its unobtrusive colour and word scheme. Also I think planners - the target audience - know the names of settlements in their regions. Will discuss offline and get back to you.

**Comment by usr110** [comment]
Have already browsed through examples mentioned at [leaflet-extra](leaflet-extras.github.io/leaflet-providers/preview/), but didn't find any better. I guess since you @Robinlovelace deal with geography more in depth, you might want to take this task up.

**Comment by Robinlovelace** [comment]
OK - closing for now - we can re-open if and when people come up with a constructive solution. For now I'm happy with the base maps, just would like more on business (heads up @RachelAldred ) and other info about the transport network.
