### ISSUE TITLE
FTP login/being able to install Wordpress plugins

### ISSUE THREAD

**Issue by RachelAldred** [npct/pct-shiny#257]
Hi Nikolai, it would be great to have the FTP login or a work-around so I can activate Statcounter and update plugins like spam catching software etc. on the PCT blog :) Thanks.

**Comment by nikolai-b** [comment]
@RachelAldred I believe I've done this but let me know if it isn't working.  I've added the details to wordpress internally so it _should_ work automatically.

**Comment by RachelAldred** [comment]
Thanks - Statcounter still isn't working so I've emailed them for advice. Other updates seem to be happening.

**Comment by Robinlovelace** [comment]
Duplicate of this https://github.com/npct/pct-shiny/issues/267
