### ISSUE TITLE
Show zones checkbox

### ISSUE THREAD

**Issue by nikolai-b** [npct/pct-shiny#258]
Change `Zone transparency` to `Show zones` (with default on).
Remove the satellite transparency auto change.
Reduce the opacity to `0.5`

**Comment by usr110** [comment]
Doesn't hide the 'show zone' when the satellite map base is selected.

**Comment by Robinlovelace** [comment]
Thanks for the fast update Ali but I'm not sure that was an issue: I think the principle of least astonishment is important here and don't the advantage of a UI button disappearing for one basemap but not others. Thoughts @nikolai-b and @JDWoodcock please... Not sure we agreed this.

**Comment by usr110** [comment]
To my understanding this was agreed. Let's see what others think.
As for the principle you've mentioned, we have used quite a bit of conditional inputs for a variety of inputs. For instance, for drop-down menus of scenarios and flows. So I don't think that's a good measure to judge new developments.

**Comment by Robinlovelace** [comment]
Yes we do have some but that doesn't mean we should add more. My thinking is keeping conditionality in the UI to a minimum - the ones that appear when lines are selected make sense but I'm not sure this one does. Why not make it disappear when the IMD layer is selected, from example? That would seem consistent.

**Comment by nikolai-b** [comment]
I prefer it without the conditional.  Why allow people to remove the zones on some maps but not on others?  We initially removed it on satellite because it was hard to see the layers underneath but we the show zones option we are handing the control to the users so it is up to them, what if someone wants satellite and zones?

**Comment by usr110** [comment]
I still think it was a better idea. In fact I would do the same thing for 'IMD' base as Robin suggested. Since @nikolai-b too seems like hiding `show-zone` dropdown menu isn't that good of an idea, I've reverted the changes (see [here](https://github.com/npct/pct-shiny/commit/d9d875cfce9cc3d8bdbdbd8da99e416ba6944d3c) and [here](https://github.com/npct/pct-shiny/commit/c352b12f0388d8e96b3f6899496a3852e9bd846d)).

**Comment by Robinlovelace** [comment]
Thank Ali, I think it's better to keep the UI as stable as possible. All this has consequences for the [Manual](https://github.com/npct/pct-shiny/blob/master/static/manual.Rmd) (your suggestion would mean more work so I'm also grateful for this revert as it means less work on that) and makes me think we could do with a 'User interface' section. CC @RachelAldred.
