### ISSUE TITLE
make the intrazone flow circles less intrusive

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#262]
I assume others agree on this?
I suggest increase transparency and make them smaller when you are zoomed out - it is hard to see the lines when you are zoomed out.When you are zoomed in close they are fine.

**Comment by Robinlovelace** [comment]
I agree - found them pretty intrusive in demos, especially when zoomed out a long way they cover the basemap.

**Comment by JDWoodcock** [comment]
one option (though has disadvantage of providing new clutter) is a turn on/off radio button

**Comment by Robinlovelace** [comment]
I suggest simply reducing the opacity in the first instance to avoid adding to the UI.

**Comment by usr110** [comment]
@JDWoodcock What about a checkbox like this?
![centroid-checkbox](https://cloud.githubusercontent.com/assets/10958628/15752204/ef7a0d20-28e4-11e6-8f1e-612096f33169.png)

I know @nikolai-b is not so keen to add new controls, but this will solve the issue. Have created a new branch [here](https://github.com/npct/pct-shiny/tree/centroids-as-checkbox)

**Comment by usr110** [comment]
Also created a [pull request](https://github.com/npct/pct-shiny/pull/269)

**Comment by usr110** [comment]
#269

**Comment by JDWoodcock** [comment]
i think it is an improvement- would need to be wordy though e..g within zone flows
