### ISSUE TITLE
Non-issue: Nice PCT blog by Mark Treasure

### ISSUE THREAD

**Issue by jf1** [npct/pct-shiny#263]
Apologies if it's not apt to post this here, but in the absence of a PCT discussion forum on Cyclescape or elsewhere I'm not sure how else to alert people to this. https://aseasyasridingabike.wordpress.com/2016/05/26/propensity-to-cycle-and-the-importance-of-main-roads/

While I'm discussing non-issues, if anyone's available to present on PCT in Manchester on Tuesday June 28 from 6.30pm then please let me know here or get in touch by email. www.eventbrite.co.uk/e/open-data-manchester-transport-special-tickets-24758036955

**Comment by Robinlovelace** [comment]
Thanks - info logged (the article is great btw) but closing as it's not an issue.
