### ISSUE TITLE
PCT blog is down

### ISSUE THREAD

**Issue by RachelAldred** [npct/pct-shiny#267]
Hi there, the blog seems to have vanished - @nikolai-b @Robinlovelace @JDWoodcock http://pct.bike/wp/. My other q is whether it'd be possible to have http://pct.bike/blog/ instead, as it would be easier for people to find before we get decent search engine indexing.

thanks :)

**Comment by RachelAldred** [comment]
The blog links have been removed from the PCT page as it was not possible to save the current blog. Aim is to get a replacement blog - with copied over content - up before the launch, on Wordpress.com.

**Comment by nikolai-b** [comment]
@JDWoodcock 
To move this issue forward we need to
* redirect pct.bike to www.pct.bike
* set blog.pct.bike to point to the new Wordpress install

I don't have access to the domain registration but I'm happy to answer questions if you have issues doing the above.

**Comment by usr110** [comment]
The [blog](http://blog.pct.bike) seems to be working fine, so closing the issue now.
