### ISSUE TITLE
front page of pct

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#268]
looks nice!  but

*On the popups, the % for ebike is wrongly set the same as genderequality
*On the key, it is not clear where e.g. 3.0% exactly goes.  can it become "0– 2.9%", "3 - 5.9%" etc? 
*The key is inconsistent, it should have "cycle to work" everywhere, not just the go Dutch

**Comment by Robinlovelace** [comment]
Thanks Anna. All but the middle points are resolved [here](http://pct.bike/map-test.html) and I don't think it's essential to add notation for the unusual case were pcycle = 3.0000000000. The two ways I've seen this done are ugly or confusing:

0 < x <= 3
3 < x <= 6

or more elegantly and endorsed by ISO

(0, 3]
(3, 6] 

But unfortunately most people don't know about[ iso standards for mathematical notation](https://en.wikipedia.org/wiki/ISO_31-11)...

**Comment by Robinlovelace** [comment]
whereby [a,b[ = {x ∈ ℝ ∣ a ≤ x < b}
