### ISSUE TITLE
Shiny reloads data after any user input

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#27]
Currently the shiny, it seems, is requesting updated data every time the user interacts with the map (e.g. panning/zooming). This causes the map to temporarily go grey. It also places a load on the server, in terms of CPU, bandwidth and maybe RAM.

The solution may be to set up shiny so it *only* requests new data when new data is needed, i.e. when one of the dropdown menus on the right is used. This could help with #16.

**Comment by audev** [comment]
On the same line, I think shiny updates the map base image when lines are re-rendered, even without panning/zooming. If that is function [updatescene], it accounts for ~60-70% of cpu time.

**Comment by Robinlovelace** [comment]
@audev interesting. Do you mean 60-70% of cpu on the client or the server side? It's an issue in any case but less of an issue if it's server side because the basemap is served externally.

**Comment by audev** [comment]
No, on the client side (no idea on the server). In reality it's just a count of groups of functions on the browser, so no more than a 'relatively' bad proxy. 
Top 2 functions: [updateScene], 60% counts (~10% time), and onreadystatechange: 15% counts (~80% time).

**Comment by usr110** [comment]
@Robinlovelace Could you deploy the app on the server, and then test it out how is it performing?

**Comment by usr110** [comment]
It'd be nice if everyone tests out the recent changes, and then see if it is working.

**Comment by Robinlovelace** [comment]
@usr110 looks OK to me - just deployed it and restarted shiny-server on geo8.

**Comment by usr110** [comment]
@Robinlovelace That's great, thanks!
