### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#270]
choose scenario, choose heat or co2 on flows, change to route network- it crashes

**Comment by Robinlovelace** [comment]
Have you pushed to production @nikolai-b ?

**Comment by usr110** [comment]
I don't think it is completely fixed. What I find it: when you switch back to `route-network` from `straight lines`, no network is displayed - it's blank. 
![blank-route-network](https://cloud.githubusercontent.com/assets/10958628/15776051/539b0a50-297d-11e6-9b83-623ea80924b1.png)

**Comment by nikolai-b** [comment]
https://github.com/npct/pct-shiny/issues/270#issuecomment-223538464 you can tell by which branch its on

**Comment by usr110** [comment]
@nikolai-b Great fix! So quick too. Good job.

**Comment by nikolai-b** [comment]
Thanks for spotting I'd not fixed it first time.  I've pushed to http://npct0.vs.mythic-beasts.com/
