### ISSUE TITLE
increase deaths and health economic value

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#271]
if there is an increase in deaths and thus a negative monetary value then please change font for that line in the label to red. see example
[example.docx](https://github.com/npct/pct-shiny/files/297324/example.docx)

**Comment by AnnaGoodman1** [comment]
needs to be done for the within-zone flows too

**Comment by Robinlovelace** [comment]
Thanks Anna. @usr110 could you take a look?

**Comment by usr110** [comment]
@AnnaGoodman1 thanks for pointing it out. I missed that one. Now it's fixed. You will soon see the changes once it's pushed onto the server.

**Comment by usr110** [comment]
@AnnaGoodman1 Please try the [test server](npct0.vs.mythic-beasts.com/nottinghamshire); the update is visible there.
