### ISSUE TITLE
Quiet roues pop-up

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#275]
The quiet routes pop-up currently shows the same information as the fast routes pop-up (e.g. baseline and scenario numbers of cyclists), but I think it is meant to show only distance, percent increase in distance relative to fast route, and hilliness.

**Comment by Robinlovelace** [comment]
Agreed - that was the plan, thanks for pointing this out.

**Comment by AnnaGoodman1** [comment]
You may have reintroduced the column, but the pop-up is still showing the same – so I'm not sure that this issue is closed.

**Comment by usr110** [comment]
@AnnaGoodman1 It is resolved; it's just that it hasn't been pushed onto either of the servers. Sorry about it. I am dealing with the permission issue. May be @nikolai-b or @Robinlovelace can push the changes onto the test server?

**Comment by usr110** [comment]
Test server is now updated. See the changes here

http://npct0.vs.mythic-beasts.com/oxfordshire/

@AnnaGoodman1
