### ISSUE TITLE
user warning

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#28]
As people are now accessing the tool there must be a danger someone starts thinking they can use the results. So I think we need a health warning that this is a prototype under development and not all the data is intended to be correct. Do not use!

**Comment by usr110** [comment]
Does this help? - https://github.com/npct/pct-shiny/commit/834b0fd1eeb45fc67465b6bdf3726cd03442a1ff

![helpful-text](https://cloud.githubusercontent.com/assets/10958628/7299127/0382511e-e9cc-11e4-91a6-56df7615579a.png)

**Comment by Robinlovelace** [comment]
Yes - I've tweaked the message though.
