### ISSUE TITLE
Update front page

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#285]
If you click on say Norfolk or Lincolnshire you can't see popup as blocked by scenario dropbown
if you right click and select 'view this element' only you can see it very nicely- but most people wont see that. Maybe that option could be made easier?

**Comment by JDWoodcock** [comment]
for discussion - how about just having the map http://www.pct.bike/map.html as front page (plus little box offering more text if you expand it) and smaller logos maybe in Belgium?

we could then have hover overs for the regional data and clicking to go to the region itself?

**Comment by Robinlovelace** [comment]
Me or @usr110 to explore

**Comment by Robinlovelace** [comment]
Add the video @nikolai-b

**Comment by JDWoodcock** [comment]
i am talking to a web designer about the front page on Monday. Nikolai have you had any success with getting advice?

**Comment by Robinlovelace** [comment]
And include (a potentially modified version of) this text from @RachelAldred : 

Welcome to the Propensity to Cycle Tool (PCT)

Created by the Propensity to Cycle Tool team.

Last updated: 2016-07-27.

Welcome to the Propensity to Cycle Tool for England (PCT-England), which provides an evidence base to inform cycling investment. To find out more about the tool, its use and the four scenarios, please watch the video below. More detailed information can be found on PCT blog, the Manual, an academic paper or the about page [include links].

To run the PCT, click on a region in the map to the left. This will open up the PCT for that region. The PCT will then show you cycling levels in that region at area, ‘desire line’ and route network levels, from 2011 Census for commuting and for various scenarios that illustrate where cycling has the greatest potential to grow. This is based on a model that estimates cycling potential based upon trip distances and hilliness.

Currently the PCT only shows commuting trips but additional layers are planned.
