### ISSUE TITLE
Quiet data in cambridge is not right

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#288]
The route distance is quite long, hence the difference with fast route too becomes fairly large.

![cambridge-quiet-route](https://cloud.githubusercontent.com/assets/10958628/16150562/d4771c50-348f-11e6-8a21-7ed6cce175fe.png)

See here: http://npct0.vs.mythic-beasts.com/cambridgeshire/

**Comment by usr110** [comment]
As expected, like before, this problem exists in [Cornwall and Isles of Scilly](http://npct0.vs.mythic-beasts.com/cornwall-and-isles-of-scilly) as well.

**Comment by Robinlovelace** [comment]
Interesting problem. Here's the spatial distribution of crazy reported distances:

![selection_160](https://cloud.githubusercontent.com/assets/1825120/16247413/7e416852-3801-11e6-9695-50669b6272d6.png)

**Comment by Robinlovelace** [comment]
Fixed these at national level and uploading new dataset here: https://github.com/npct/pct-bigdata/releases

**Comment by usr110** [comment]
Perhaps the unit issue has again popped out for Cambridgeshire. 

![cambridge-distance-km](https://cloud.githubusercontent.com/assets/10958628/17410488/cf440868-5a6b-11e6-938c-04ac7c5e690c.png)

There are loads of NAs too

![cambridge-nas](https://cloud.githubusercontent.com/assets/10958628/17410512/eafc51b4-5a6b-11e6-98fb-eeeba62f962f.png)

**Comment by Robinlovelace** [comment]
I'll update pct-bigdata and then rebuild Cambridge.
