### ISSUE TITLE
Legend

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#29]
The map needs a legend and brief description of use. @usr110 were you working on this? Please add the popup if so! Thanks.

**Comment by usr110** [comment]
@Robinlovelace I was working on a general tutorial - see here: https://github.com/npct/pct-shiny/blob/master/tutorial.md
Is that what you were thinking of? It might need readjustment as the UI has been changed quite sometime.

**Comment by usr110** [comment]
@Robinlovelace 
Please have a look the new tab I've introduced. The text is not final, but I believe the screenshots cover all aspects of the underlying app.

![help-tab](https://cloud.githubusercontent.com/assets/10958628/7396694/1b86fe30-ee9b-11e4-99a6-6ea6253b5ba4.png)

**Comment by Robinlovelace** [comment]
Fantastic work @usr110, I like the tab-based approach. Massive :+1: for your hard work on this

**Comment by usr110** [comment]
@Robinlovelace Thanks!
