### ISSUE TITLE
For Ali: minor bug in the new centroids feature (not urgent)

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#296]
It is really nice the way that the do not appear except at high levels of zoom, so that they don't clutter up the map when one is zoomed out. However, there seems to be a small bug, in that when one switches between scenarios one always starts off seeing the centroids – i.e. the zoom level does not kick in when one first sees the scenarios. For example, open Lincolnshire, click on straight lines, and then change the scenario from census to go Dutch. At that point one sees the centroids, even though they disappear when one zooms in one level (and reappear only when one is very zoomed in).

I think that it is not urgent to solve this issue, I just wanted to note it here.

Also, the rule for the centroids seems to be related to geographical resolution, and this works nicely in most of England, but this means that in large cities like London one does get a lot of centroids on the screen at a fairly low level of zoom in. An alternative might be to have a rule that was something to do with centroid density (e.g. no more than ?20 centroids of the screen at once), but I appreciate that might not be feasible.  If not feasible/a lot of work then I suggest this second point is ignored or marked "for the future"

**Comment by usr110** [comment]
@AnnaGoodman1 Thanks for testing the new feature out. Really useful. I now have fixed this issue:

> It is really nice the way that the do not appear except at high levels of zoom, so that they don't clutter up the map when one is zoomed out. However, there seems to be a small bug, in that when one switches between scenarios one always starts off seeing the centroids – i.e. the zoom level does not kick in when one first sees the scenarios. For example, open Lincolnshire, click on straight lines, and then change the scenario from census to go Dutch. At that point one sees the centroids, even though they disappear when one zooms in one level (and reappear only when one is very zoomed in).

See the change on the [test server](http://npct0.vs.mythic-beasts.com/). Would appreciate to have your feedback.Thanks!

As for the other issue, I am marking this for future. Hope that's fine.

**Comment by usr110** [comment]
For a generalized solution, it's better not to calculate centroids density or region-specific zoom level, to determine a suitable radius of centroids.
If we normalize the size of centroids then I believe we will resolve the issue.
For instance right without normalization London's region looks like this:

![london-current-centroids](https://cloud.githubusercontent.com/assets/10958628/18673523/fa37155e-7f43-11e6-9fc6-3dfbd076c446.png)

It has quite a few overlapping centroids (once zoomed further in, this gets resolved). This can be resolved by normalizing the radius (works for all other small or regions too). See the image below:

![london-normalized-centroids](https://cloud.githubusercontent.com/assets/10958628/18673630/6767ae86-7f44-11e6-9a07-9670de3d2040.png)
