### ISSUE TITLE
regions

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#297]
please can we have Cov back in Warwickshire please

**Comment by Robinlovelace** [comment]
Closing as this is already an issue: https://github.com/npct/pct-shiny/issues/228 - prioritising fixing errors in data atm - for example no one notices but there were 100s of fast route distances in metres that no one noticed - data before and after the fix:

```
> summary(rf_nat$length)
    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
    0.37     5.49     9.75    48.00    16.01 39390.00 
> rf_nat <- readRDS(file.path(pct_bigdata, "rf.Rds"))
> summary(rf_nat$length)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  0.374   5.481   9.734  11.250  15.980  42.960 
```
