### ISSUE TITLE
Explore removing routes / lines / network after aggregating

### ISSUE THREAD

**Issue by nikolai-b** [npct/pct-shiny#303]
For LSOAs the route / line data for less that x cyclists is useful to build an accurate route network.

After the route network has been generated we could remove the lines / routes with less than n cyclists (where n > x) and also remove sections of the network with less than m cyclists.  This could be important to keep the data size manageable.

n and m would have to be determined.

**Comment by Robinlovelace** [comment]
Options have been explored, especially by @mem48 - no action point so closing.
