### ISSUE TITLE
lines that are missing from visualisation

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#304]
Some lines are apparently not being visualised even though they meet our criteria of <20km euclidean and >10 commuters,  For example, there are 237 lines that I think ought to be visualised in Cambridge according to our criteria, but which are not shown on the map, are not part of the data download and are not counted in the number of 1110 lines given in the model output tab. An example is the 343 commuters travelling 5.7 km between E02003251 (Peterborough 015) and E02006878 (Peterborough 023) [these 343 commuters include those travelling in either direction]. To see these 237 "missing" lines, choose the lines in which the attached spreadsheet for which “visualised_Anna” is equal to 1 and “visualised_Robin” is equal to 0. Note that all the lines in the attached have been aggregated to be bidirectional, and always have the MSOA with the smaller numerical value listed first.
[160624_MissingCambLines.xlsx](https://github.com/npct/pct-shiny/files/333471/160624_MissingCambLines.xlsx)

**Comment by nikolai-b** [comment]
@Robinlovelace if you want to follow up on this I started by removing the one-way lines using this: https://github.com/npct/pct/commit/395b1ba14
I'm not sure this is the same as `stplanr::onewayid` or the code you emailed but it avoids the loop and feels cleaner unless I'm missing something.

**Comment by Robinlovelace** [comment]
Thanks Nikolai - will give it a try, will be nice if it works without the loop.

**Comment by Robinlovelace** [comment]
This has been fixed in the code - just need to do a national build now I think.
Please check the results for Isle of Wight and Cambridge (which will be updated soon) - resulting increases for Isle of Wight are impressive! (see below)

![updated-rnet](https://cloud.githubusercontent.com/assets/1825120/17363865/dc886106-5974-11e6-81d5-629133630abe.png)

**Comment by AnnaGoodman1** [comment]
this is fixed for the latest Cambridge build
