### ISSUE TITLE
statcounter

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#306]
http://statcounter.com/  can we find a way to install this?

**Comment by usr110** [comment]
James, may I ask: why do you want to have it installed? We already have Google analytics running on our website, which identifies users' behaviour. @nikolai-b might want to shed more light to it.

**Comment by JDWoodcock** [comment]
Okay great- so where can we see the results from this?

**Comment by nikolai-b** [comment]
I set this up but something has changed. @Robinlovelace have you still got the GA access I gave you?  Has something changed as I can't login anymore.

The GA code is still there so not sure what has changed...
https://github.com/npct/pct-shiny/blob/master/www/assets/google-analytics.js
