### ISSUE TITLE
tiny change in ebike data - new national datasets to be supplied by Anna before the next national build

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#307]
I'm not quite sure why, but the numbers for the Ebike scenario in the PCT interface do not perfectly match those in the latest versions of the datasets generated by me. I suspect that the most likely reason is that since the national model was last built, there has been a very tiny change in how the Ebike data was calculated.  The difference is trivial, but when the national build is next done (possibly before the launch, given the potential issue with the missing lines and also given the known problems with some fast lines being in metres not kilometres?) I will provide new csv input datasets for the areas /lines. This will mean that the numbers shown in the PCT interface are generated using a method identical with that described in our flow paper.

**Comment by Robinlovelace** [comment]
Suggest this is fixed at the same time as #304

**Comment by AnnaGoodman1** [comment]
this seems to be fixed, thanks
