### ISSUE TITLE
Wrong units for some distances in data download

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#308]
Specifically, the lines data

**Comment by nikolai-b** [comment]
The distance is wrong in rf and rq :cry: 

```R
summary(rf["length"])

Data attributes:
     length        
 Min.   :    0.37  
 1st Qu.:    5.49  
 Median :    9.75  
 Mean   :   48.00  
 3rd Qu.:   16.01  
 Max.   :39387.00  

head(rf["length"])
head(rf_nat["length"])
  length
1  4.897
2  3.899
3  2.925
4  4.113
5  1.868
6  2.238
```

What units are they?  It looks like some are km and some are m.

I tried 
```R
rf$length <- ifelse(rf$length>=1000, rf$length / 1000 , rf$length)

**Comment by nikolai-b** [comment]
Ah, this has been fixed sorry.  I guess we just need to re-generate the download data.

**Comment by Robinlovelace** [comment]
Yes they are wrong in pct-data but not in pct-bigdata.
That's one of the reasons I want to do a national build this afternoon doh!

P.s. in realtime, glad you cottoned on hehe :+1:

**Comment by nikolai-b** [comment]
I believe this has been fixed
