### ISSUE TITLE
Automatic reload for a new town

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#31]
/pct-shiny/bolton/ is working locally and the data has been added.

But it's crashing on geo8 - try reproducing this.

@nikolai-b a reason to update the code to download the data I think.

Using git pull could be an alternative to downloading the whole zip - more efficient when we're uploading new cities one by one...

**Comment by nikolai-b** [comment]
Tried to use submodules but they [don't work](http://stackoverflow.com/questions/9448682/git-submodule-on-remote-bare) on a bare git repo (i.e. the server).  [Fixed](https://github.com/npct/pct-shiny/commit/9ae8a474a7c9a9f4f822c2819ce7a6115f5a7ec3) using `git pull`.

**Comment by Robinlovelace** [comment]
OK - so if I need to deploy it for [Sheffield](https://github.com/npct/pct-data/commit/03e890bef1d281f0ca5893434380961c125a121e) (or any new town I happen to add) how do I do so - ssh in and git pull? I guess so - works for me!

**Comment by nikolai-b** [comment]
no, do nothing.  When you refresh the page this triggers a background `git pull` https://github.com/npct/pct-shiny/blob/master/master/master.R#L19 automatically
