### ISSUE TITLE
wrong/inconsistent units in 'avslope' variables

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#310]
In the data download file on the test server I believe that the avslope lines variable has (incorrectly) been multiplied by 100 twice , whereas avslope_q lines variable has (correctly) only been multiplied by 100 once, and the avslope zones has (incorrectly) not been multiplied by 100 at all.  

Note that this seems a bit different from the situation on the master server, where it looks to me as if the avslope lines variable has (correctly) been multiplied by 100 once, whereas avslope_q lines variable has (incorrectly) not been multiplied by 100 at all, and the avslope zones has (incorrectly) also not been multiplied by 100 at all. 

The good news is that both on the test and the master server, the numbers on the fast/quiet routes on the "map" screen seem to be correct, it is only in the data download that there is a problem.  But we will want to check that any fix on the data download does not mess up the units on the map

**Comment by Robinlovelace** [comment]
Fixed [here](https://github.com/npct/pct-load/commit/ef5dec21619f8682dbe7036b6122c7e2169012d9).

Please test here - note this may lead to incorrect display in the map:

http://npct0.vs.mythic-beasts.com/cambridgeshire/
