### ISSUE TITLE
codebook update (minor)

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#312]
Apologies, there was a small mistake in the version of the zones/lines codebook I supplied earlier in the week (I called variables "ebikes_*" in the codebook, whereas their actual variable names are "ebike_*".  Could the attached two codebooks replace the ones currently loaded up on the data download pages? Thanks!

[Codebook.zip](https://github.com/npct/pct-shiny/files/365952/Codebook.zip)

**Comment by nikolai-b** [comment]
The zones codebook you attached still has `ebikes` which I _believe_ is an oversight as they should be `ebike` in zones and lines.  I've pushed that instead, hope its ok.
