### ISSUE TITLE
Testing freezing on poor connections

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#316]
There is anecdotal evidence that the PCT freezes when the user is connected via a poor connection.
On the assumption that this is the case I propose mentioning it on the front page, to avoid confusion: https://github.com/npct/pct-shiny/commit/e69005524fed7da8caed87f964ee704a194a9ca1

@nikolai-b are you up for testing this with the software you mentioned?

**Comment by nikolai-b** [comment]
Using chome connection throttling (in Network tab GPRS connection) and 
`tc qdisc change dev wlan0 root netem loss 1% 25%` which simulates a 1% packet loss I was able to load the site.  I'm not that happy with e690055 as it *should* work fine on mobile devices and if not we should fix, a warning doesn't really help much IMHO.

**Comment by Robinlovelace** [comment]
But the question is can we replicate the freezing behaviour? E.g. loading and reloading the Route Network in a large region like http://www.pct.bike/west-yorkshire/

**Comment by Robinlovelace** [comment]
Can replicate crashing on Chrome with 'GPRS connection':
![gprs-crash](https://cloud.githubusercontent.com/assets/1825120/17130610/53989668-5311-11e6-8602-cc578959a431.PNG)

**Comment by Robinlovelace** [comment]
So I think the statement that "you need a good internet connection for the PCT to run, i.e. not via a mobile device" is not unreasonable. Please try to replicate @nikolai-b.

**Comment by nikolai-b** [comment]
I cannot reproduce, can you add the exact steps,

Here is a screencast of it working 

[out.ogv.zip](https://github.com/npct/pct-shiny/files/384864/out.ogv.zip)

**Comment by Robinlovelace** [comment]
Are you sure that throttling affected that particular Chrome tab?
I'm not sure it did - rnet loaded too fast for that by my estimation.
Robin

**Comment by Robinlovelace** [comment]
Try to reproduce with the same analytics in the right hand panel as I did and let me know.

**Comment by Robinlovelace** [comment]
OK tried just now, cannot reproduce.
This suggests it may be something else.
Maybe simultaneous users issue - or maybe the updates have fixed it...
Cheers for testing reproducibility.

**Comment by Robinlovelace** [comment]
@npct/admin and all any further issues please report them in this thread.

**Comment by Robinlovelace** [comment]
Closing for now - it passed the crowd-sourced test with these results (attached). Many thanks @nikolai-b for testing.
![robins-propensity-tc-didnt crash](https://cloud.githubusercontent.com/assets/1825120/20796251/41567bde-b7cd-11e6-8db3-eb0e0afe968e.jpg)

**Comment by Robinlovelace** [comment]
[Testing pct.pdf](https://github.com/npct/pct-shiny/files/624736/Testing.pct.pdf)

Also attached: server logs thanks to Nikolai.
