### ISSUE TITLE
internet explorer & edge

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#317]
I can't get IE to show the network layer. It works on Ali's laptop but not that well. I have yet to try Edge as I uninstalled it from my laptop. Could someone have a look?
If we dont think it works on those we could come up with up with a recommended browser list?

**Comment by mvl22** [comment]
Many, many local authorities use IE, I suspect even down to IE8 or IE9, even though IE11 now is the only supported version (unless using Vista, which is unlikely).

https://support.microsoft.com/en-us/lifecycle#gp/Microsoft-Internet-Explorer

**Comment by nikolai-b** [comment]
Agreed, thank you Martin!

@Robinlovelace there are a few js errors from the user manual https://github.com/npct/pct-shiny/commit/f6fad4c4d30c334f175faab28610b92f8ea20b05#commitcomment-18392114, I will track down others...

**Comment by nikolai-b** [comment]
@Robinlovelace I'm finding all the extra files that knitr generates and then links to a real pain as they are not served by shiny, is there an option to include them as it is causing JS errors.

**Comment by Robinlovelace** [comment]
Update: the first task is to find out how much time it will consume to fix different versions. And to say which versions of IE won't work.

**Comment by nikolai-b** [comment]
@Robinlovelace https://github.com/npct/pct-shiny/issues/317#issuecomment-235186479 any update?

**Comment by Robinlovelace** [comment]
Not from me!

**Comment by JDWoodcock** [comment]
We confirm working on IE9 and Edge & aim to get working on IE8. We dont care about IE 7 or earlier.

**Comment by nikolai-b** [comment]
Great, thanks @JDWoodcock!

I've asked about browser support on the shiny examples https://github.com/rstudio/shiny-examples/issues/40 as I'm also unable to get shiny's example apps to run in IE8 :disappointed:

**Comment by Robinlovelace** [comment]
@nikolai-b any update on this (for meeting tomorrow)?

Just a list like:

Browser | Share | Works
============
Chrome 51.0:	| 29.15%| works 
Microsoft IE11.0 |	18.08% | works
Chrome 45.0:	| 5.62% | works
Firefox 47	| 5.33%| works
Microsoft IE 8.0 |	4.79% | fails

will be fine.

**Comment by Robinlovelace** [comment]
Plus an indication of how much effort it would be to get it to work would be instructive - my instinct being that shiny apps overall do not play well with IE8 but work OK with IE9.

**Comment by nikolai-b** [comment]
IE8 is unsupported by Microsoft and by Rstudio:
https://github.com/rstudio/shiny-examples/issues/40#issuecomment-236208506

**Comment by JDWoodcock** [comment]
Okay thanks for checking on this. Let's put up a warning somewhere saying that it doesnt work on IE 8 as unfortunately a lot of people are still using it @RachelAldred

**Comment by JDWoodcock** [comment]
@nikolai-b @Robinlovelace @usr110 @RachelAldred @AnnaGoodman1 
just checking Ali's lovely new map and unfortunately it doesnt work on IE11

Also got this feedback from @pct.bike
"The site loads fine without an issue using internet explorer (Version 11.0.9600.18617 Update 11.0.40)  but once you click on a map (e.g. http://www.pct.bike/m/?r=essex) the page takes over 2 minutes to load and any further clicks form the map page like changing the map base take around 2 minutes to process. The site works without an issue in Chrome and Firefox on the same PC."

I havent replicated the issue but it certaintly less smooth on IE 11. 
I suggest we i) develop a process for checking on Chrome and IE, ii) we put up warning as discussed before to say Firefox is our recommended browswer

**Comment by mvl22** [comment]
Testing on Edge is now available for free via a remotely-hosted VM on Browserstack:

https://blogs.windows.com/msedgedev/2017/03/30/free-edge-testing-browserstack/

If you find the problem and get things working on Edge, I think it's likely IE11 with then work.

**Comment by usr110** [comment]
That's brilliant. Thanks Martin. Have just begun testing in various IE versions.

**Comment by nikolai-b** [comment]
I've tested 

| OS | Browser | Works | Site |
| :-: | :-: | :-: | :-: |
| Window Vista | Microsoft IE 9 | worked | [browserling](https://www.browserling.com/internet-explorer-testing)
| Window 7 | Microsoft IE 9 | failed | [browserstack](https://www.browserstack.com/test-on-microsoft-edge-browser#live-cloud)
| Window 7 | Microsoft IE 10 | worked * | [browserstack](https://www.browserstack.com/test-on-microsoft-edge-browser#live-cloud)
| Window 10 | Microsoft Edge 10 | worked | [browserstack](https://www.browserstack.com/test-on-microsoft-edge-browser#live-cloud)
| Window 10 | Microsoft Edge 14 | worked | [browserstack](https://www.browserstack.com/test-on-microsoft-edge-browser#live-cloud)

* Had minor issue with the URL, [this line](https://github.com/npct/pct-shiny/blob/55745dd41f8895bcecd72a33b82e935b27cc9efe/regions_www/www/assets/extra.js#L44)

**Comment by nikolai-b** [comment]
If we get specific issues I think we should note them but as far as I'm aware this is no longer a problem.
