### ISSUE TITLE
Rnet is slow 

### ISSUE THREAD

**Issue by nikolai-b** [npct/pct-shiny#318]
Similar to #16.

Writing down some observations.

From my local computer using Cambridge (running this twice)

====

with 30% (772 lines) network shown:
rnet takes 2465ms and ...? to display (from changing the slider to the route network being returned but not drawn)
of which 1060ms and 1200ms is from [addPolylines](https://github.com/npct/pct-shiny/blob/59a0e3/server-base.R#L336)

====

with 50%  (1287 lines) network shown:
rnet takes 3359ms and 3418ms to display (from slider change to rnet returned from server)
of which 1935ms and 1900ms is from the [addPolylines](https://github.com/npct/pct-shiny/blob/59a0e3/server-base.R#L336)

**Comment by nikolai-b** [comment]
Tried updating leaflet and shiny packages but no improvement.

**Comment by Robinlovelace** [comment]
Interesting stuff.
It's slow even on UoL superfast (800 Mps) internet, suggesting to me it's our server's side:

![speed-internet](https://cloud.githubusercontent.com/assets/1825120/17170351/892dc6d6-53e3-11e6-8bc6-5030092be7e6.PNG)

**Comment by Robinlovelace** [comment]
Could remove segments that are below a threshold length and simplify more.

**Comment by nikolai-b** [comment]
https://github.com/npct/pct-load/blob/7701c0815ba4a10471d5394cbc64d7c84788b612/build_region.R#L127 rnet is simplified here.  We can also remove segments with less than a threshold of cyclists.

**Comment by Robinlovelace** [comment]
Yes - we can change the % of vertices that remain. Good idea re threshold for n cyclists also, but remember that duplicates work done by the % lines slider. Another peripheral idea: create a simplified version of rf before generating rnet. This would speed-up `overline()`, the slowest part of `build_region.R`.

**Comment by Robinlovelace** [comment]
Closing for now as I can't see any action. Please re-open @nikolai-b or anyone if this becomes actionable.
