### ISSUE TITLE
Minor update to quiet route pop up

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#319]
Two changes to suggest
one) show percent change in hilliness, as we do distance
two) in front of the percent change values for distance and hilliness, show a + sign or a – sign. At the moment it is ambiguous whether e.g. "30" means "30% longer" or "30% of the original". The former is what is correct, and I think the plus and minus signs make this clearer

**Comment by Robinlovelace** [comment]
First part is fixed I believe. - NAs are preventing % - I'll provide without NAs and @usr110 will implement b).

**Comment by Robinlovelace** [comment]
Another fast fix!
