### ISSUE TITLE
shinybs tooltips are a bit flakey

### ISSUE THREAD

**Issue by nikolai-b** [npct/pct-shiny#32]
they seem to work intermittently

**Comment by usr110** [comment]
This fix https://github.com/npct/pct-shiny/commit/ee8c7e796c245e7c5547fd5ce825d93796342aad change the cursor from 'move' to 'inherit' might have solved the problem. Give it a try now.

**Comment by nikolai-b** [comment]
That didn't fix it for me (chrome and firefox on debian and ubuntu).  I've move the tooltips to use `tipify` in https://github.com/npct/pct-shiny/commit/a7a010aa4e7a8bc1f86e0e7bf32185938160d5d1 and that seems to do it (except the alignment of the [scenario tooltip](https://github.com/npct/pct-shiny/blob/master/master/ui.R#L40) was wrong with `tipify` so I've left it as `bsTooltip`)
