### ISSUE TITLE
Lines are not writing to geojson with the new national data

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#320]
See https://github.com/npct/pct-load/commit/7701c0815ba4a10471d5394cbc64d7c84788b612#diff-791c1cd294481b6e3534f73155099be4R239

**Comment by Robinlovelace** [comment]
Maybe due to the NAs.

**Comment by nikolai-b** [comment]
This did not occur when I rebuilt Cambridgeshire.
The permanent parts of the [commit](https://github.com/npct/pct-load/commit/1853fbba) are:
 
* We were not removing od pairs where o == d https://github.com/npct/pct-load/commit/1853fbbac04e3d14c9cec19ccfd87625a21992a6#diff-d940ca220e49d9c4b14e5cc04a12a39eR152
* This does not try to merge the old routes with the missing routes (it just gets all routes anew)
