### ISSUE TITLE
Route network line widths are too uniform with the new data

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#321]
Before: 

![before-rnet](https://cloud.githubusercontent.com/assets/1825120/17365552/95d1340e-597e-11e6-8c56-248c1349192d.PNG)

After:

![after-rnet](https://cloud.githubusercontent.com/assets/1825120/17365555/9c050d64-597e-11e6-8adc-acdc6998815b.PNG)

**Comment by usr110** [comment]
@Robinlovelace There are lots of NAs in the `sorted_l[[line_data()]]`, hence creating problems for the weight attribute. 

> summary(sorted_l[[line_data()]])
>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
>   328.5   542.7   842.4  1044.0  1369.0  4575.0      44 

Out of  `1737`, `44` are NAs.

Have removed them here: 
https://github.com/npct/pct-shiny/commit/a7ee13cccba76e1b3ce1df49ba28671dcb3e0ef8
Might have fixed the problem.

Re NAs in data, probably you want to look into it.

**Comment by Robinlovelace** [comment]
Fixed in https://github.com/npct/pct-shiny/commit/a7ee13cccba76e1b3ce1df49ba28671dcb3e0ef8 - and should be fixed upstream in pct-bigdata also.

**Comment by Robinlovelace** [comment]
Thanks @usr110 for diagnosing and fixing this btw.
