### ISSUE TITLE
Add zones and all data layers to switching tab functionality

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#324]

**Comment by Robinlovelace** [comment]
Any update @usr110? Happy for you to close if it's been fixed/won't fix.

**Comment by usr110** [comment]
Already fixed it.

**Comment by Robinlovelace** [comment]
Great work!

**Comment by usr110** [comment]
Just noticed that with `downloadHandler` the problem was, inadvertently, reintroduced (see: https://github.com/npct/pct-shiny/commit/daa29cf147fc47124f39b57ecc38f2b9c84a98b7)

**Comment by nikolai-b** [comment]
The help for `downloadHandler` says
>  Both filename and contents can be calculated dynamically at the time the user initiates the download

but if that needs to be wrapped in an observe block that doesn't feel like it is true.

It is great fix but that feels like a bug in shiny, what do you think @usr110 ? Or am I reading the problem wrong.
