### ISSUE TITLE
JS errors

### ISSUE THREAD

**Issue by nikolai-b** [npct/pct-shiny#325]
Some of the Rmd files the js is embedded in them.  On others it is not (e.g. https://github.com/npct/pct-shiny/issues/317#issuecomment-235186479) .

When a js error is encountered in a browser this can cause issues so ideally this would be fixed when we update these Rmd (and then html) files.

**Comment by AnnaGoodman1** [comment]
I'm not sure if this is the same issue, but I have multiple times this morning had the website crash and disconnect due to java errors, meaning i had to start again.  this happened once when downloading lines, once when downloading zones,  and once when looking on the map page

**Comment by nikolai-b** [comment]
If that happens could you see what the issue was in the console (on most browsers that is Ctrl+Shift+I ) as I'd really like to know why.

**Comment by Robinlovelace** [comment]
I think it was a different issue related to data downloads, that Ali fixed - please confirm @usr110. To the best of my knowledge this is not a blocker issue - prioritising data build at the moment.

**Comment by Robinlovelace** [comment]
I think these will be resolved in the latest version - please confirm @usr110.
Unless they are part of the user manual, in which case I'll take a look in due course.

**Comment by usr110** [comment]
Robin, I don't know about the JS issues regarding the `Rmd` documents (if there are some, then they must be in `manual.Rmd`) but as far as I know the issue Anna raised has been resolved.

**Comment by Robinlovelace** [comment]
OK I'll wait for @nikolai-b to comment as he identified them before acting on or closing this issue.

**Comment by nikolai-b** [comment]
Yep, looks fixed.
