### ISSUE TITLE
Front page text

### ISSUE THREAD

**Issue by RachelAldred** [npct/pct-shiny#326]
Sorry all, I put it in the wrong place, here it is again. My first go at proposed changes to the front page text so we can fit in the video... I think we could actually cut it right down - at the moment we provide a little information but the video is better at getting that across.

Welcome to the Propensity to Cycle Tool (PCT)

Created by the Propensity to Cycle Tool team.

Last updated: 2016-07-27.

Welcome to the Propensity to Cycle Tool for England (PCT-England), which provides an evidence base to inform cycling investment. To find out more about the tool, its use and the four scenarios, please watch the video below. More detailed information can be found on PCT blog, the Manual, an academic paper or the about page [include links].

To run the PCT, click on a region in the map to the left. This will open up the PCT for that region. The PCT will then show you cycling levels in that region at area, ‘desire line’ and route network levels, from 2011 Census for commuting and for various scenarios that illustrate where cycling has the greatest potential to grow. This is based on a model that estimates cycling potential based upon trip distances and hilliness.

Currently the PCT only shows commuting trips but additional layers are planned.

**Comment by Robinlovelace** [comment]
Closing as this is duplicated here: https://github.com/npct/pct-shiny/issues/285
