### ISSUE TITLE
route network scenario numbers look wrong

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#327]
As shown in the example screenshot attached, the baseline number of cyclists has increased slightly between the current national build on PCT.bike, which seems correct given that we have added in some missing lines (most of which contained a small number of people). By contrast the scenario number of cyclists has gone from 346 to 4575. This is far too large an increase (Cambridge is already not far from go Dutch), and the same applies to many other lines in Cambridge. The same very large increases in the scenario number of cyclists is seen in Kent. I think something must have gone wrong in the route network aggregation?

[160806_RouteNetwork.docx](https://github.com/npct/pct-shiny/files/404884/160806_RouteNetwork.docx)

**Comment by JDWoodcock** [comment]
Hi,
the outstanding errors identified so far by Anna are:
 1) the route network values looked wrong when I checked on Friday, so we need to check those
2)  - There were some things that worked in the build for Cambridge but failed for Kent related to the data download - we will want to check on this, Hopefully was just a glitch that has now been fixed
3) one of the numbers was wrong in  the model output tab, and it also still has some holes in – but this is less urgent.

**Comment by JDWoodcock** [comment]
Particularly as I don’t understand all the tech issues please edit the following
Proposed timeline and steps
·        NB is kindly redoing the cycle streets calling of data this weekend & to push test server http://npct0.vs.mythic-beasts.com/. He hopes that some of the problems arose in the previous merging stage. This is currently looking promising
·        Monday morning (or earlier if it is ready earlier) AG and RA check the Cambridgeshire results on the test server (AG to send RA Cambridgeshire line csv)
·        Monday afternoon – if it is right then RL builds for a few other regions including Kent . If there are still problems then we have a conference call to discuss on Monday afternoon
·        Tuesday morning- check other regions. If there are problems with these other regions then we have a conference call to discuss on Tuesday afternoon
·        Tuesday afternoon- RL start national build if no problems with the several regions
·        Wed- check national build. And if all okay RA presses go button on press release for the 25th (note this means press offices send out on 23rd August)

**Comment by nikolai-b** [comment]
I have re-built Cambridgeshire.

Looking at the line Anna highlighted this issue seems fixed:

![screenshot from 2016-08-07 10-40-56](https://cloud.githubusercontent.com/assets/6289830/17461645/a4f71010-5c8b-11e6-84a9-f626c6c0804f.png)

**Comment by AnnaGoodman1** [comment]
Agreed seems fixed for that issue - thanks - but now I have seen a problem of some segments having zero baseline and scenario cyclists in the new build, where as they did not have zero before.  see attached
[Pct.docx](https://github.com/npct/pct-shiny/files/406215/Pct.docx)

I'm not hundred percent clear how the route network is built, so not sure why there should ever be a segment that has zero cyclists displayed?  plus the fact that this is different from the currentPCT buildmeans it would be good if we could look at this
