### ISSUE TITLE
need to update the input file for the zones data

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#328]
the input CSV file for area values, pct_area.csv, has not been updated in the latest national build.  ( by contrast the updated lines file has been used).  The correct file is attached. It has an identical file structure, just a few of the ebikes values are different.  Hopefully replacing the old file with this file should be straightforward
[pct_area_update.zip](https://github.com/npct/pct-shiny/files/404886/pct_area_update.zip)

**Comment by AnnaGoodman1** [comment]
corrected, thanks

**Comment by AnnaGoodman1** [comment]
This now seems again to be wrong, in Robin's latest build

**Comment by Robinlovelace** [comment]
This was fixed - just didn't clear the workspace before the regional build - my mistake cc @nikolai-b .
