### ISSUE TITLE
Issue with new town

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#33]
@nikolai-b still having issues adding new towns. Sheffield, for example, seems to be down: http://geo8.webarch.net/pct-shiny/sheffield/ Works locally and I'm confident I've waited long enough for the new data to download...

**Comment by Robinlovelace** [comment]
P.s. may be because I've changed the data for Sheffield. Still, a resilient system would be able to handle that.

**Comment by Robinlovelace** [comment]
@nikolai-b added Bristol, not tested it yet, could be a useful test case

**Comment by nikolai-b** [comment]
Tentatively closing due to https://github.com/npct/pct-shiny/commit/74c735678c4889e48b63b7e5292bc937322d2512

**Comment by Robinlovelace** [comment]
:+1:
