### ISSUE TITLE
filtering lines for fastest route distance <30km + on whether they merge with scenario data

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#330]
On 19th July Robin and I agreed to filter the between-zone lines included in the new national build to be less than 20 km Euclidean distance * and also* less than 30 km fastest route distance.  this does not seem to have been done in Kent, e.g. the line E02003314 E02005118 is included even though in January Robin told me it had the fast route distance of 40.5 km.  

Can we check this field has been applied correctly? The other alternative is that cycle streets algorithm has changed such that this line is now coming up is less than 30 km, in which case I need the new route distance data in order to generate the scenario numbers (which are currently blank)

**Comment by nikolai-b** [comment]
I had noticed that some of the scenario numbers were missing. I can do this but I'm not sure where it should be done.  I'd like to do it as early in the process as possible but this would mean excluding them from all subsequent calculations (i.e. creating the route network which would be ok but also I'm not sure if this would effect general information about the zone).  I'll try removing early on in the process but will have to wait till @Robinlovelace is back to fully check implications.

**Comment by AnnaGoodman1** [comment]
as early as possible in the process sounds good. These lines have already been filtered out when it comes to generating information about the zone, which has been done separately by me in  a different set of syntax.  I think it is fine to exclude them from all subsequent calculations as early as possible, just as we exclude lines with Euclidean distance of 21 km at an early stage.

**Comment by AnnaGoodman1** [comment]
one other thing that we do still need to check is that the resulting lines after this filtering all find a match when merging with the dataset I provided. This could just possibly not happen if CycleStreets gave slightly different distance estimates at different times which pushed it across the 30km threshold, e.g. giving an estimate of 30.01 km back in January and 29.9 km now - such a line would not be present in the lines that I have provided. this does not seem to be an issue in Cambridge, but maybe an issue in some regions.

If this happened it would involve a bit of back-and-forth to fix, which would not be hard butcould be time-consuming– specifically,I would need to change the line in question to having a distance of 29.9 km in my dataset and then recalculate the lines and zones input file, which I would then give to you and you would redo the regional build.  given that we are under time pressure, and given that this will only affect a tiny number of lines ( if any), I think it might be better simply to exclude lines that did not find a matchin the scenario CSV files - i.e. implicitly use the original cycle streets value of 30.0 1KM

as such, my suggestion is that we also filter lines that have missing scenario data at the point that we merge in the scenario attributes, after first checking that they do all have a fast distance of very close to 30 km ( i.e. to establish that is the source of the discrepancy, not something else)

**Comment by Robinlovelace** [comment]
Fixed upstream by this: https://github.com/npct/pct-load/commit/eea4762cdb0bf81425309239261c9a59d411d14f

New data on its way.

**Comment by nikolai-b** [comment]
I am not that happy with you fix.  The reason is that it will remove flows but not routes which seems inconsistent.

What I had done is:
https://github.com/npct/pct-load/blob/d252788/R/lines_oneway_shapes.R#L206
which removed fast route distances over 30km.  I agree with using the lack of scenario data (instead of the 30km threshold - as that may change) but I think you need to remove the routes also.  Also, you have not added a check that the route distance has become much larger than 30km, in which case I think we should still remove the line as @AnnaGoodman1 suggested.

**Comment by nikolai-b** [comment]
Sorry, I see that https://github.com/npct/pct-load/blob/eea4762c/build_region.R#L102 means that we ARE removing the routes.  I think we should be careful in case Cyclestreets route length does increase (i.e. streets become one way) but it is much lower priority so probably safe to close for now...
