### ISSUE TITLE
(for Ali?): a couple of changes to text

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#332]
* the information pop-up that appears when you click on the codebook for the lines and zones data, there is a typo in the word "variable" - it is written "vairable".  You could search for "vairable" to find this
* In the grey bar in the top corner, we should change " national propensity to cycle tool (prototype)" to "Propensity to Cycle Tool"

**Comment by usr110** [comment]
Fixed both of them:
1) Fixed tool-tip typos: https://github.com/npct/pct-shiny/commit/aa6679d66a800ac6da82f1963f954f42945770af
2) Removed  'prototype': https://github.com/npct/pct-shiny/commit/ec5d5d827ea95e54e67c340b86b847019495b39d
