### ISSUE TITLE
Convert distances from metres to kilometres in pct-shiny

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#334]
@nikolai-b says:
> I prefer them in meters as that is returned by Cyclestreets as an int  https://www.cyclestreets.net/api/v1/journey/ and converting to km means it becomes a float.  If we convert then I think it should be done in the shiny app not in the data

If we can all agree, then this conversion (of meters into kilometers) can be easily done in the interface. Need your inputs here @npct/admin.

This will, of course, mean all the underlying data is in `meters `not in `kilometers`. Also the codebooks need to reflect it.

**Comment by Robinlovelace** [comment]
I think we should keep the data in pct-data as close to that displayed in pct-shiny as possible. So we convert from metres to km in pct-load. The data in pct-bigdata can be in m though. Sound good? I see this more as an issue for discussion rather than action as I think this is what we do already.

**Comment by usr110** [comment]
That's a fair point, Robin.

**Comment by usr110** [comment]
@nikolai-b Would be nice to carry this discussion here. What do you think? We definitely need a closure on it; the sooner the better.

**Comment by nikolai-b** [comment]
In R

```R
> 1.1111111111111111 * 9.9 == 11
true
```
(although it should be 10.99999999999999989)

When we are aggregating things or using CSV representations this could easily cause inaccuracies.  Integers do not have this problem.  I believe we should store the distances as the come from Cyclestreets, changing them to km is a display issue that we can change in shiny.

**Comment by AnnaGoodman1** [comment]
see issue #337 - need also to change the units for avslope in zones file and cirquitry

**Comment by Robinlovelace** [comment]
Fixed and agreed in meeting: distance is in m in `rf$length` etc but in km in `l$dist`, `l$dist_fast` etc. in pct-data. Conversion happens in pct-load.
