### ISSUE TITLE
Quiet routes overlap with fast routes

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#335]
Using Cambridgeshire data:
Test-server
![test-server-cbg-routes](https://cloud.githubusercontent.com/assets/10958628/17480106/36b189d0-5d6e-11e6-8e91-9ae0f74210d2.png)

Live-server
![live-server-cbg-routes](https://cloud.githubusercontent.com/assets/10958628/17480123/413c679e-5d6e-11e6-86e0-f9e2c14f3a93.png)

**Comment by Robinlovelace** [comment]
That for raising this @usr110 - one I'd though about but never flagged as an issue. Are you up for looking into a fix? I suggest creating a separate 'quite routes' layer is a good plan. In addition I have the following proposal: make the faster routes thicker overall and plot them under (not over as is currently the case) the fast routes. That will emphasise them appropriately. What do others think? Note: this issue is far less severe in other regions. Because Cambridge has good cycle paths, the fastest route is often also the quietest.

**Comment by AnnaGoodman1** [comment]
Robin, I think this is an error that you have introduced your most recent build.  The  fast and quiet routes maybe similar, but they  should not be identical in Cambridge, as Ali's example shows - there ought to be points of non-overlap. I have checked, and the same problem is in e.g. Peterborough - the fast and quiet routes are exactly the same.  On cycle streets itself the fast and quiet routes are different, even in Cambridge.  Please can you look into whether you have accidentally simply created the fast routes twice

**Comment by usr110** [comment]
As Anna said, it's more of a recent data issue, Robin. It seems not all quiet routes are same as fast routes, but a lot of them are (unlike the previously generated data on the live server). 
Re displaying quiet or fast route, I'd rather go for providing provisions to the users to select either of them.

**Comment by usr110** [comment]
I have now introduced a layer control in https://github.com/npct/pct-shiny/commit/4edc5f071acf3da83b4d26cd9fae11c8357d0e06, so that users may deselect `fast routes` when they'd like to see just `quiet routes`. 

![quite-route-layer-selector](https://cloud.githubusercontent.com/assets/10958628/17487389/781bba3a-5d8c-11e6-93fe-6c1fb67cbe14.png)

Until the testing is completed, I believe, it's a useful control. We may remove it afterwards.

**Comment by usr110** [comment]
Note that I am displaying this control only when `Fast & Quiet Routes` is selected

**Comment by Robinlovelace** [comment]
Thanks Anna - looking into it and re-generating the quiet routes.

**Comment by Robinlovelace** [comment]
Now fixed for Cambridge as shown below and as can be seen here:
http://npct0.vs.mythic-beasts.com/cambridgeshire/

![selection_183](https://cloud.githubusercontent.com/assets/1825120/17490908/0ca7ec5e-5d9d-11e6-8b82-4154abe9fbf1.png)

The routes were regenerated using the script committed here: https://github.com/npct/pct-load/commit/09fcaaf09216b9ecec340de887678e89bc12c340

Closing for now - the new data is regenerating - please re-open if this happens again.

**Comment by usr110** [comment]
@Robinlovelace Great!
