### ISSUE TITLE
regression in variable ordering and content in the l.csv download

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#338]
there is a regression in the content and ordering of l.csv.  The ordering no longer matches the codebook, and there are some variables included that should not be there.  I think this was still working at the weekend, and certainly we had it working until very recently, so hopefully quick to fix by reinstating the previous code here

**Comment by Robinlovelace** [comment]
Fixed in build script here (assumes consistently named codebook data): https://github.com/npct/pct-load/commit/bdcfd90306bb78c1d86fb56f8870cf091ede713d
