### ISSUE TITLE
Error in formatting of £ sign in codebook

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#339]
As can be seen here - partially fixed for lines - I think this may also need to be done for zones. Is there a fancy regex that can automate this @nikolai-b ?

![screenshot from 2016-08-09 07-50-33](https://cloud.githubusercontent.com/assets/1825120/17507187/31f0b306-5e06-11e6-9073-d51e46c88d93.png)

**Comment by AnnaGoodman1** [comment]
your fix has actually broken it as far as I'm concerned - I think it may be a difference between .xls and .ods.  In the latest codebook (see#340) I now just use the word "pounds"

**Comment by AnnaGoodman1** [comment]
Robin, please can you change the £signed to the word "pounds"?  The symbol you have introduced may work for you, but it does not work in Excel

**Comment by AnnaGoodman1** [comment]
Okay, so you are still working on this Robin and will upload corrected codebooks?

**Comment by Robinlovelace** [comment]
I'm not sure what you mean. The correct codebooks were added in the commit that closed this issue - please take a look here: https://github.com/npct/pct-shiny/commit/906a202738d7a920eb453369a90349c9d55f6a2e

I think this fixes the issue, hence closing it.
