### ISSUE TITLE
Unusual order of modes in codebook for lines

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#340]
Currently we have:

```
all
light_rail
train
bus
taxi
motorbike
car_driver
car_passenger
bicycle
foot
```

I think that should be:

```
all
bicycle
foot
car_driver
car_passenger
light_rail
train
bus
taxi
motorbike
```
The latter better reflects the importance of each mode for the PCT.

**Comment by AnnaGoodman1** [comment]
this file has the order updated, and some other variables reordered (but none deleted)

[New folder.zip](https://github.com/npct/pct-shiny/files/408581/New.folder.zip)
