### ISSUE TITLE
Inconsistent variable names for Ebikes scenario in codebook

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#341]
Somtimes it was `ebike...` other `ebikes...`:

E.g.:
ebike_sid	Increase no. car drivers in Ebikes vs. Census 2011
ebikes_slco2	Change in CO2/year (kg) in Ebikes versus 'no cycling'

Fixed for the lines - not sure if this persists in the zones data.

**Comment by AnnaGoodman1** [comment]
fixed, see #340 codebooks
