### ISSUE TITLE
modification of text to line data download pages

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#348]
see attached for requested modification to the text of the data download page for the lines.  The extra three codebooks will be added by Robin 
[160809_Download text.docx](https://github.com/npct/pct-shiny/files/410372/160809_Download.text.docx)

**Comment by usr110** [comment]
Not closing right now, as Robin needs to add codebooks there. Anna, if you get the chance, please see on the test-server (in a couple of minutes) if are you happy with the changes.

**Comment by Robinlovelace** [comment]
Great work @usr110. I've added codebook_rnet now: https://github.com/npct/pct-shiny/commit/009f16c8ff737c66c000af733071bf0ef0e7afa5

Note: this is not yet linked to build_regions.R - will add that now.

Robin

**Comment by AnnaGoodman1** [comment]
Hi Ali, thanks for looking at this. Two/three things
1) seems to be a bug, the first paragraph is now showing the "zones" paragraph in both places, as opposed to the "lines" paragraph on the lines page
2) to improve readability, could we have a line gap between "* To get attribute data, use 'ID' field to merge with straight-line CSV file" and "No lines selected: Lines must be displayed on map"
3) is easy, but only if easy, I think readability would be further improved if the list were somewhat indented, i.e. straight lines through to "*to get attribute data..." had a few spaces before them. But don't bother if this is hard
