### ISSUE TITLE
New Route Network layer not working for London

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#349]
I think it may be due to the sheer size of it. All of it won't display locally with `mapview(rnet)` but I can see chunks of it, e.g. via `mapview::mapview(rnet[1:(nrow(rnet)/4),])`. Plan: find ways to shrink it. Other layers seem to work.

**Comment by AnnaGoodman1** [comment]
see #350, fast routes not working for 15% lines.  could this be the issue? possibly solved in national fast routes dataset?

**Comment by Robinlovelace** [comment]
Yes I suspect the correct national routes dataset should solve the '15%' issue, but not necessarily this one.
