### ISSUE TITLE
15% fast routes not working in london

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#350]
for e.g. E02000619 E02000620.  they have'NA' for slope and distance, and are visualised as straight lines.  lets see if fixed in national fast routes line dataset

**Comment by AnnaGoodman1** [comment]
could this be why rnet not working?

**Comment by Robinlovelace** [comment]
Yes that may help explain it (looks like some of the routing failed), although slope and distance variables aren't used to generate rnet so may not help fixing #349. Sounds like a new build is in order - I ran this on a new computer so propose to try a build on a computer that's definitely got the right set-up.
