### ISSUE TITLE
data in e.g. fast route geosjon does not match dist_fast

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#351]
The value of "length" in fast route in geojson Kent does not seem to match dist_fast.  Sometimes the difference is relatively small, less than a kilometre, but in a few cases it is an order of magnitude out eg E02005014 E02005015

 Fortunately, I think that the dist_fast values look more plausible, so hopefully the PCT as a whole is not compromised. But this is worrying. If the problem is with these variables in geojson rather than in PCT then this greatly strengthens my belief that they should be deleted!  

For the cases where the values are similar but not the same, I wondered if a different process had been used in aggregating the lines to be bidirectional...

**Comment by Robinlovelace** [comment]
Please could you check if this discrepancy also applies for Cambridgeshire? Thanks for reporting it.

**Comment by AnnaGoodman1** [comment]
Apologies, either you have fixed this else it was a mistake by me, since the data of Kent now looks fine.  Sorry if my mistake....
