### ISSUE TITLE
Issues in avon test build of alternative method

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#352]
1) missing lines: current PCT has 2650, I think there should be 4557, currently only 1630
2) distance variables are wrong, looks like they may be sometimes 1000 times too small and sometimes 1 million times too small
3) rnet is not showing baseline numbers, nor is it any different from PCT.bike
4) fast and quiet routes do very often overlap, more so than on PCT.bike – makes it look as if they are identical in one of the constituent data files

**Comment by Robinlovelace** [comment]
Thanks Anna.
