### ISSUE TITLE
unroutable centroids

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#353]
Failed lines: this sounds to me like a similar issue to the one that we spent some time on in late February/early March, where we manually reassigned centroid locations.  At the time you wrote some syntax to fix this, I think now here:
https://github.com/npct/pct/blob/cba7ac976535b73b9d170206f8e3fced54a051b7/analysis/update-cents.R
https://github.com/npct/pct/blob/cba7ac976535b73b9d170206f8e3fced54a051b7/analysis/update-cents-scenarios.R

the update-cents.R file imports an excel file 160301_MovePoints_v2.xlsx that I created, which was second of two update files. I have put both update files together, and attach them.
[New folder.zip](https://github.com/npct/pct-shiny/files/412460/New.folder.zip)

One thing to check is whether any of these same points could be a problem again  - but that clearly isn't the whole issue,  there are also new problematic centroids.

moreover,looking at the regions built so far, in Derbyshire there is only one problematic centroid : Amber Valley 008.  It is odd, I can't see why this is problematic, the centroid is quite near a road.  In Dorset there are seven or eight centroids all of which are problematic, again for no obvious reason. this contrasts with the problems in February, when the issues were clearly related to being e.g. in an airfield or lake.  ( looking at region, it is quite easy to spot the relevant centroid, or just scans over the region with fast route selected, and looks for the place where there are lots of straight lines)

 so perhaps the error this time is random, rather than to do with being in a non-cyclist environment.  I have tried on cycle streets itself, and line seem to work starting and ending from roughly where the centroids are.  since so far the reasons for the errors this time are not obvious,  one option would just be to try randomly moving the problematic points by 50 m, and seeing if they work then?

**Comment by mvl22** [comment]
Can I suggest re-running that dataset again in case there was a server problem at the time. We did have some error reports yesterday on the general server that you are using. There has been heavy load recently from a mix of sources and we also suspect a possible regression in the engine aligned with the routing import made live yesterday lunchtime; we've rolled back to the previous version pending some further investigation. This seems to have stopped the error reports but the load pattern is also different this morning.

**Comment by nikolai-b** [comment]
@Robinlovelace noticed the errors and wanted to check with you that he wasn't (in part) causing the issues with the routing engine.  I noticed that you have fixed the all unrouteable lines we previously asked about https://github.com/ropensci/stplanr/issues/91, thanks.  This means that we can move the centroids back to their actual position instead of being artificially moved by us so they are nearer the route network.

**Comment by mvl22** [comment]
He phoned yesterday lunchtime but the routing engine went live shortly after that (not before), and load is generally high at the moment anyway.

**Comment by Robinlovelace** [comment]
I'm re-routing them and it seems most can be re-routed - i.e. it was a temporary problem, maybe related to the server going down. Expect an updated version of rf_nat here soon: https://github.com/npct/pct-bigdata/releases

**Comment by Robinlovelace** [comment]
Fixed here - adding rq_nat now.
