### ISSUE TITLE
3 msoa's not included in dorset build, not sure why

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#354]
E02004287   Weymouth and Portland 007
E02004288   Weymouth and Portland 008
E02004289   Weymouth and Portland 009

this seems to leave whole areas of the region missed out, particularly island of Portland

**Comment by Robinlovelace** [comment]
Interesting... Not priority but one to investigate.

**Comment by Robinlovelace** [comment]
Closing as it's a duplicate of https://github.com/npct/pct-shiny/issues/468

**Comment by AnnaGoodman1** [comment]
@Robinlovelace , based on work in #539 , I wonder if the issue is that these missing three MSOAs are not covered by the crude outline for Dorset that you see on the front page - perhaps there is a rule that MSOAs are only selected if they lie within the crude regional outline shape?  If so then I guess the solution would be to fix the regional outline shape

**Comment by Robinlovelace** [comment]
That could well be it, thanks for spotting this.

**Comment by Robinlovelace** [comment]
Job done I think.

Before:

![image](https://cloud.githubusercontent.com/assets/1825120/23684554/57f2fa6e-0397-11e7-836c-66b541116558.png)


After:

![image](https://cloud.githubusercontent.com/assets/1825120/23684516/2f4d6c7a-0397-11e7-8a6c-59d1cb33d952.png)
