### ISSUE TITLE
two lines missing in Devon, not a big problem in itself but if possible would be nice to understand why

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#355]
E02004228   E02004230, 
E02004228   E02004232 

I think both have a fast distance under 20 km, not sure why excluded in case it is a larger bug. not a priority

**Comment by Robinlovelace** [comment]
Please try to keep the issues clear and actionable - e.g. 'Add two missing lines in Dorset'. If you could provide a .csv files with the values you have that will make it easier to fix. Thanks.

**Comment by nikolai-b** [comment]
Seems clear and actionable to me.  These lines are missing, why?  
Adding them isn't a big deal but finding out why they were missed is.

```R
l_anna <- readr::read_csv("path/to/160708_AreaLinesPCT/pct_lines.csv")
cents <- readRDS("../pct-data/devon/c.Rds")
m1 <- l_anna$msoa1 %in% cents$geo_code
m2 <- l_anna$msoa2 %in% cents$geo_code
l_anna_devon <- l_anna[o & d, ]
l_anna_devon <- l_anna_devon[l_anna_devon$msoa1 != l_anna_devon$msoa2,]
l_anna_devon$id <- paste(l_anna_devon$msoa1, l_anna_devon$msoa2)
l_shiny_devon <- readRDS("../pct-data/devon/l.Rds")
missing <- l_anna_devon[!l_anna_devon$id %in% l_shiny_devon$id,]$id
```
This gives me 687 lines, not sure if that is expected or not but the two @AnnaGoodman1 put up are in `missing`.

**Comment by AnnaGoodman1** [comment]
these are lines that I think meet our criteria for inclusion, and they are included in the pct_lines file I provided. So my guess is that they are missing from the batch of lines that Robin routed through cycle streets - not sure if they were missing even before they were put through cycle streets, or whether they became missing downstream.  I will keep checking all regions, and if it turned out to be only these two lines that are missing then we can ignore them, but if there are more lines missing it would be good to check where in the process they got missed out

**Comment by Robinlovelace** [comment]
Agreed - we should fix nationally. Thanks for making this actionable @nikolai-b, I'd just add that we would go back to the subsetting phase here - guess that's where they were missed, e.g. here: https://github.com/npct/pct-load/blob/master/R/lines_oneway_shapes.R#L23

**Comment by AnnaGoodman1** [comment]
lets leave this for now, and when we redo national build we make sure these few missing lines are included.  checking other regions, I have found one or two other missing lines, but nothing on any large-scale
