### ISSUE TITLE
Display increase in percentage for scenarios for route-network

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#358]
Also add in a caveat that further information can be seen in the model output tab

**Comment by Robinlovelace** [comment]
I suggest this is more a 'for the future' and discussion issue so closing for now. Would you mind suggesting it here https://github.com/npct/pct-shiny/issues/273 to keep the bug tracker for things that are definitely agreed and actionable.

**Comment by Robinlovelace** [comment]
Have agreed on this? One for discussion I think.

**Comment by JDWoodcock** [comment]
Please dont close issues without checking. Anna & I would like to see this down before launch. The reality is as we dont include all commuters in the route network the ratio is more accurate than the absolute nos.

**Comment by Robinlovelace** [comment]
OK fair point. Please discuss issues and get a check on effort, who can do it etc before opening next time... One to discuss tomorrow but agree an indication of % increase could be useful and probably not too hard to calculate in rnet.Rds and to display in the associated pop-ups.

**Comment by Robinlovelace** [comment]
Fast work @usr110 !

**Comment by usr110** [comment]
Updated text for the route-network:

> Between-zone cyclists* (baseline):   
> Between-zone cyclists* (scenario):   
> Ratio (scenario/baseline):   
> \* Selected cyclists: see Model Output tab

**Comment by Robinlovelace** [comment]
Hi Ali and all I think this is great work but think we need to modify the popup text to make it easier to understand (hence re-opening for now, even though the central issue has been resolved). Here's a concrete example from the latest London data: 
![screenshot from 2016-08-11 16-31-13](https://cloud.githubusercontent.com/assets/1825120/17594454/41f4f014-5fe1-11e6-8eeb-762e78f80849.png)

The problem as I see it is that the meaning of "Ratio (scenario / baseline):   	2.45" is not instantly clear, especially if you don't have formal technical training or an A Level in Mathematics.

Suggestion:

"Percent increase: 145%"

The code could look something like 

```
round(100 * rnet$senario / rnet$bicycle - 1)
```
In this case that would look a bit like this for output:
```
> (100 * (12000 / 5000 - 1))
[1] 140
```
Sound good?

Also suggested change to the text:

**Of** trips in the model (see model output tab).

**Comment by Robinlovelace** [comment]
I think 'cyclists' is not the right word. Could also use 'commuter', but not generalisable, so suggest trips may be safest and simplest. Thoughts?

**Comment by JDWoodcock** [comment]
Stick with ratios- most people dont understand %s.

**Comment by Robinlovelace** [comment]
I disagree - I think more people understand % than "ratio", especially as the raw numbers are also provided, minimising the probability of mis-interpretation. One to discuss I think.

**Comment by mvl22** [comment]
> I think 'cyclists' is not the right word.

"Bicycle user" or "Cycle user" is what we use nowadays in campaigning in Cambridge. Don't know if that's what you meant.
