### ISSUE TITLE
wrong mflow in avon, west mid, perhaps WYCA

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#359]
mflow has been set at 50 not 10 ffor West Midlands and Avon, I can't test West Yorkshire as the server is disconnecting, but plausibly here too.  I think Ali and Alvaro must have been working off a version of the script with mflow==50, i.e. not the version that Robin is using.

(ALSO rnet in avon looks funny, noticeably less complete than PCT.bike, and also looks less complete than most of the new regions)

can we rebuild these regions, and can we first work out what the apparent version control issue is?

**Comment by nikolai-b** [comment]
I can re-build west mid.

**Comment by Robinlovelace** [comment]
Thanks for the update - great to have it working on multiple computers.
