### ISSUE TITLE
New About page

### ISSUE THREAD

**Issue by nikolai-b** [npct/pct-shiny#363]
- [x] The h4 headers look to be links but have no href, any reason they are in a anchor tag?  E.g. `<a name="team">The PCT Team</a>`
- [x] I wouldn't link the titles, e.g. Principal Investigator.  I'd just link the names
- [x] I wouldn't have the ` ( ` in the links.
- [x]  The header at the top should link back to the home page, e.g. 
```
<a href="/">
  <img src="./img/logos/pct-logo.png" alt="Propensity to Cycle Tool">
</a>
```
- [x] We should symlink so the license link isn't to kent folder

**Comment by JDWoodcock** [comment]
How about hyperlinking logo so it goes back to front page?

**Comment by nikolai-b** [comment]
Yep, that is what I meant in
> The header at the top should link back to the home page, e.g.

**Comment by AnnaGoodman1** [comment]
I agree with Nikolai that just our names, not roles, should be hyperlinked . I would also prefer removing hyperlinks to our unis, just as  am not sure that is necessary, to me it looks too busy, and makes it a bit less obvious where to click

**Comment by AnnaGoodman1** [comment]
text edits:

* (Aldred et al 2016.   --- needs to close the parenthesis
* government’s Cycling Delivery Plan  ---- government’s draft Cycling Delivery Plan
*  thank CycleStreets for providing routes.  -----  thank CycleStreets for providing data on routes.
* Aldred reference at bottom ---------- add text "DOI: 10.1080/01441647.2016.1200156
" and have this hyperlinked http://www.tandfonline.com/doi/full/10.1080/01441647.2016.1200156.  Also Elliott B needs to be added as second author


and link nikolai, "The h4 headers look to be links but have no href," - I found this confusing, would be better with no jump-to if there is no middle option

**Comment by usr110** [comment]
Thanks Nikolai, James and Anna for the comments. I have incorporated all of them apart from two points. First Anna's point:

>I would also prefer removing hyperlinks to our unis, just as am not sure that is necessary, to me it looks too busy, and makes it a bit less obvious where to click

@JDWoodcock, what do you think?

and then Nikolai's

>We should symlink so the license link isn't to kent folder

Tried relative path [here](https://github.com/npct/pct-shiny/commit/2fc3e9d0c76da2572b3ceeae26b3781a76dcac34), but that didn't work on the server. Worked locally though. Any ideas how to do that?

**Comment by jf1** [comment]
> Tried relative path here, but that didn't work on the server.

Do you merely need to upload a copy of the license to /www/license.html ?
(or drop `www/` from the link and upload it to the root folder)

Suggestion for the text, from:
This is the online home of the open source transport planning system, the Propensity to Cycle Tool (PCT).
To:
This is the online home of the Propensity to Cycle Tool (PCT), an open source transport planning system.

**Comment by nikolai-b** [comment]
If you have a simlink of the license in `regions_www` then I _think_ it can be linked to as `href=/licence.html`.

**Comment by Robinlovelace** [comment]
This is looking great, I have a few more minor additions/changes @usr110,:

1) We use the same order for people that we have here: http://npct0.vs.mythic-beasts.com/about.html

2) I change my profile picture to something more professional! (I'll do that one - will let you know if I have issues)

3) Also there should be a reference to this I think, as there is in the original:

https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/364791/141015_Cycling_Delivery_Plan.pdf

4) I think it would be good to link to the source code so it's clear where all the code is to encourage the sharing mentioned.

Sound good?
Cheers,

Robin

**Comment by usr110** [comment]
Robin, have included all your points in https://github.com/npct/pct-shiny/commit/5c72a9cdfdcdaed308b4c962fc58225605730c63 and https://github.com/npct/pct-shiny/commit/aa2a99cf9a1437d5eb1b3d9806907bbd10213652. Closing the issue now. 
If anyone feels like there are other issues, re-open it.

**Comment by Robinlovelace** [comment]
Many thanks Ali, this is really great work. Please can you push all this so it shows on the test server? Will be good to have that on http://npct0.vs.mythic-beasts.com/  to see how it all fits together. Also let me know you availability Friday.

**Comment by usr110** [comment]
Robin, you can see the updated index and about files on the test server. Re Friday, have send you an email.

**Comment by Robinlovelace** [comment]
Ali, thanks for the updates.
