### ISSUE TITLE
"502 Bad Gateway" error

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#364]
I have been doing checking, and have intermittently not been able to download the L.CSV or the Z.CSV files in Hereford and Worcestershire,, or in Hampshire, or in Norfolk across the course of the morning . I get an error message "502 bad Gateway".  in both places, I had the problem initially and then a bit later it worked – i.e. the problem is intermittent.  possibly something else is happening on the server to interfere? (I'm doing this checking at 9 -11 AM Sunday morning)

**Comment by AnnaGoodman1** [comment]
(possibly linked to #366 ?)

**Comment by usr110** [comment]
Anna, have you recently tried this issue? I believe that it was temporal. I can't seem to reproduce it (have tried in Norfolk and Hampshire)

**Comment by AnnaGoodman1** [comment]
Agreed, hopefully now fixed
