### ISSUE TITLE
rnet very odd in one small section of  Wiltshire

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#365]
in itself this is not a big issue, but I wonder if it represents a larger bug? On this section of road, the number of cyclists At baseline goes from 80 to 1 to 81 without it being obvious how many cyclists could be joining or leaving.  I think Robin said there had been an issue with cycle streets having three lines on each place, rather than just one – not sure if it could be related.  on PCT.bike this section builds without problems, with 80 cyclists along the whole Line
![untitled](https://cloud.githubusercontent.com/assets/11818225/17648659/d892e858-621d-11e6-91a2-1a3fb5347ff0.png)

**Comment by Robinlovelace** [comment]
I'm also seeing issues like this over bridges in London. As you say not a major issue as users will be able to read between the lines but I think we should figure out what's causing it. I suggest rebuilding with `keep = 0.12` to see what changes - hopefully that will fix it.

**Comment by AnnaGoodman1** [comment]
yes, fixed in wiltshire
