### ISSUE TITLE
Maps not responding in Microsoft Edge due to "long-running script"

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#366]
I get this message about the timing out due to a long-running script. Most obvious in Manchester and London, but I have had it even in Cambridge.  This is when using Microsoft Edge 25.  In Firefox it works.
![untitled](https://cloud.githubusercontent.com/assets/11818225/17656032/c76ac0b2-62b5-11e6-8a31-9b623010aa1e.png)

**Comment by AnnaGoodman1** [comment]
have run this again, and it remains extremely slow Microsoft edge. Will try on the new server

**Comment by nikolai-b** [comment]
@AnnaGoodman1 sorry I ran out of time to check this with you.  I am getting a copy of Microsoft Edge locally to test.

**Comment by nikolai-b** [comment]
Hi @AnnaGoodman1 I've tried to reproduce but I can't.  It works on Edge in a Virtual Machine, here is a screencast:
[london.zip](https://github.com/npct/pct-shiny/files/433683/london.zip)

Could you confirm it is still happening?  Maybe it could be an extension or plugin?

**Comment by AnnaGoodman1** [comment]
odd, yes still happening to me.  
![untitled](https://cloud.githubusercontent.com/assets/11818225/17922021/23774fb4-69dd-11e6-99a5-c14600f0b7ff.png)

also (not sure if relevant) a shot of my settings, not sure how to check extensions/plugins.  
![untitled2](https://cloud.githubusercontent.com/assets/11818225/17922027/2ba8c3c0-69dd-11e6-94d2-212650d0efe1.png)

perhaps next step is have someone else try this who has windows 10 and see if they have the problem? or skype sharing screens and you look at my laptop?

**Comment by nikolai-b** [comment]
What is your Edge version?  Mine is 20.10240.  Maybe we can try Skype tomorrow.

**Comment by usr110** [comment]
@AnnaGoodman1 is this still an issue?

**Comment by mvl22** [comment]
IE9 is completely broken. I'll start a new issue on that.

**Comment by Robinlovelace** [comment]
Any update on this @nikolai-b?

**Comment by Robinlovelace** [comment]
Closing for now as now updates and no response - treating as a 'won't fix'.
