### ISSUE TITLE
rnet patchy in London, and one notices short local lines being excluded

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#367]
rnet is worse on the test server than in the current PCT, including missing out key segments such as the bridges over the Thames. also Using Mflow=50  also means that coverage of the route network is down to 33%, and some areas only connect to one other area when you zoom in.  we could perhaps discuss whether there are any ways to solve this problem of rnet, and improve the trade-off between rnet working but mflow high enough for good local coverage, e.g.
  - Changing inclusion settings? Is it the long lines that particularly a problem, and if so should we try making the maximum distance 12 km or 15km? (plus possibly lower mflow for very shortest lines, e.g. mflow=20 if dist<2, So they show up on a map?).  could also consider reducing the distance in greater Manchester, if this would improve rnet
  - try again with different rnet settings?
  - ?? reconsider splitting London into four zones (not what we want....)
  - ?? other options

![untitled](https://cloud.githubusercontent.com/assets/11818225/17656218/a3641cf2-62b7-11e6-8318-96e1441d626c.png)
.

**Comment by Robinlovelace** [comment]
Fixed here - tried 5 times with `mflow = 50` but issue only went away with it increased to 70 - results look good to me: http://npct0.vs.mythic-beasts.com/london/

Before:

![screenshot from 2016-08-15 15-43-24](https://cloud.githubusercontent.com/assets/1825120/17667952/0e5068c6-62ff-11e6-96f7-775fc837536f.png)

After: 

![screenshot from 2016-08-15 15-42-54](https://cloud.githubusercontent.com/assets/1825120/17667953/0e60bc76-62ff-11e6-9fc6-112c2392be8f.png)


Commit: https://github.com/npct/pct-data/commit/07fa099fcdd97cf2d48a828ef87af6061ae9fadb
