### ISSUE TITLE
Model output error

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#369]
I got this fail on the automated build: `Error: could not find function "add_table_style"`

I guess that's due to changes by @usr110 - please confirm.

I've stopped creating the model output - please can you revert this commit https://github.com/npct/pct-load/commit/0a04768f10d6f8a5bdd59e9b62f8ccd5e9747cbd and rebuild the model output for the affected regions (those built in the next few hours)?

**Comment by usr110** [comment]
The code works just fine. You need to update the repo. See here: https://github.com/npct/pct-load/commit/0a04768f10d6f8a5bdd59e9b62f8ccd5e9747cbd

**Comment by usr110** [comment]
I will generate all model-output files once everything looks fine in Cambridgeshire.

**Comment by Robinlovelace** [comment]
Sounds like a good plan.
