### ISSUE TITLE
greying out

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#37]
No not my hair but when I leave it open for a minute or two it sort of greys out and you can see it but not so well. Could be my pc setting.

Also to remind people there is user testing tomorrow so please be careful not to break anything :)

**Comment by Robinlovelace** [comment]
Yes - that's normal behaviour for shiny. Some explanation: http://shiny.rstudio.com/articles/scaling-and-tuning.html Solution: refresh!
