### ISSUE TITLE
bug/inconsistency: filter by distance first or aggregate to bidirectional?

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#370]
when generating the scenario numbers, I first filtered by route distance, and only at the end aggregated flows to be bidirectional - i.e. each set of scenario numbers was generated using the directional distance and hilliness.  By contrast, I think perhaps you are first aggregating them for distance and filtering afterwards?  in a few cases, this means that you are including flows in both directions, whereas I'm including flows in one direction but not the other if the distance crosses the 30 km threshold.  

home_msoa	work_msoa	all	bicycle	dist_fast
E02002188	E02006875	133	  2	         30.904
E02006875	E02002188	 2	  0	          28.583

let's discuss ways to make this consistent as a process for the next national build - which order makes more sense, and if we are aggregating to be bidirectional before generating scenario numbers then can we simply process off the number of lines?

Also, as a fix for this bug in the short term, would it be possible to use my values of "all", "bicycle" et cetera rather than your values in l.csv, since minor all internally consistent

**Comment by Robinlovelace** [comment]
Solution: remove offending lines.

**Comment by AnnaGoodman1** [comment]
ID pairs oflines to delete are in the attached –  after dist<20 and mflow<10 have been applied in lines_oneway_shapes_updated_id_all then it turns out that there are only 32 problematic lines left.  as such it will be good if we can remove these lines, but if we can't then leaving the men would not be a disaster
[New folder.zip](https://github.com/npct/pct-shiny/files/419964/New.folder.zip)

**Comment by Robinlovelace** [comment]
Fixed here: https://github.com/npct/pct-bigdata/commit/0d388ed502f651a10b03e0e1aada30a7c405eab3

**Comment by AnnaGoodman1** [comment]
Thanks, but lines not yet deleted in the regions affected I think? I.e. not yet re-run the final bit of script to make the changes to l.Rds appear in the data download?  Have re-opened to remind us to do that in due course...

**Comment by Robinlovelace** [comment]
OK no problem - fixed upstream in any case. Reminder to all @npct/admin - please update pct-bigdata before doing any more builds! Note probably the more important change than removing the 32 lines with distances above and below 30 km was the removal of 8000+ lines which had NA values: https://github.com/npct/pct/commit/b57c14d953ead7938aa28810435b4ad2814feb32 - I think we also dealt with that downstream though.

**Comment by AnnaGoodman1** [comment]
or http://colorbrewer2.org/#type=diverging&scheme=RdYlBu&n=11
