### ISSUE TITLE
Route Network failing intermettently 

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#373]
This issue is about the general problem of the Route Network failing.

There are many individual instances, as documented in these cases:

- https://github.com/npct/pct-shiny/issues/368
- https://github.com/npct/pct-shiny/issues/372
- https://github.com/npct/pct-shiny/issues/362

This issue is the general issue: what's causing it, how to solve it.

Latest example that I'll try to reproduce is this from Liverpool. To reproduce try to build liverpool-city-region with `rft_keep = 0.08` and the `mflow` parameters both set to 30. Will be good to see if that is reproducible, as there's clearly something wrong here:

![liverpool-rnet](https://cloud.githubusercontent.com/assets/1825120/17696716/22f917d8-63a8-11e6-876b-461f2252c03b.PNG)

**Comment by Robinlovelace** [comment]
Latest finding: as you increase `keep =` from 0.08 through to `0.12` (and I imagine beyond) the probability of this gradually seems to reduce. I think it may fail more on large areas because if one node fails, the whole thing goes wrong. So as @nikolai-b says we should make `overline()` better in **stplanr**. For what it's worth liverpool is now fixed on the test server so closing for now.

**Comment by Robinlovelace** [comment]
Heads up on a plan to solve this (mentioned to @AnnaGoodman1 ):

I think setting the default keep parameter a low (e.g. 0.6 which works in most cases), then running a test on the first rnet, then if it fails iterate through keep = 0.15, 0.20, 0.30, 0.40, 0.5 and 1 until it works, would be a robust workflow for the next national build.

**Comment by Robinlovelace** [comment]
Another line of investigation, in addition to improving `stplanr::overline()` is to experiment with additional tags used here - there seem to be more of them than we have tried. Heads up @nikolai-b - this *is* an excellent package, despite being written in JavaScript! https://github.com/mbloch/mapshaper/wiki/Command-Reference

**Comment by nikolai-b** [comment]
mapshaper is mature but https://github.com/ateucher/rmapshaper is less mature.  Yes, I've looked at the options, sadly they are more focused on Polygons than lines but you are more an expert on what some of these simplification algorithms.  I would strongly suggest that `overline` is looked at first as you have the skills to do this and it this has known issues, instead of _experimenting_ (trying options somewhat randomly) with mapshaper.

**Comment by Robinlovelace** [comment]
Agreed re mapshaper vs rmapshaper - was thinking the same thing. I'm not ruling out calling a recent version of mapshaper with `system()`.
