### ISSUE TITLE
Route network mostly empty for Liverpool on production

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#375]
This will be resolved in when we push the latest data, but thought it worth flagging that we didn't notice this by the looks of it:

![liverpool-rnet](https://cloud.githubusercontent.com/assets/1825120/17701884/8642e268-63c3-11e6-9ea0-65718bec219a.PNG)

**Comment by AnnaGoodman1** [comment]
agreed, there have been several route networks on PCT.bike but have been very problematic
