### ISSUE TITLE
Add codebooks for fast route, quiet route and route network

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#376]
these have been written, but not yet added to the data download "lines" page

**Comment by Robinlovelace** [comment]
Here are the relevant files:

- For the fast and quiet routes: https://github.com/npct/pct-shiny/blob/master/static/codebook_routes.csv

- For the Route Network layer: https://github.com/npct/pct-shiny/blob/master/static/codebook_rnet.csv

@usr110 are you up for including this in pct-shiny?

**Comment by usr110** [comment]
Fixed in https://github.com/npct/pct-shiny/commit/68cddc87a03597267576865c3a81e7532dcd4e84 and https://github.com/npct/pct-shiny/commit/0a873b08e21a92bdf80ad6716c887721f19b7dc9

**Comment by Robinlovelace** [comment]
Great work Ali, thanks.
