### ISSUE TITLE
For Ali: minor change to navigation bar

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#377]
could we change "National Propensity to Cycle Tool" to just "Propensity to Cycle Tool", once one is in a region?  I think the latter will be more generalisable, e.g. if we build for Wales

**Comment by usr110** [comment]
That's a good point, Anna. Just to be sure, are we replacing `National Propensity to Cycle Tool` with  `Propensity to Cycle Tool` all over the application (which I think should be done), or only in the navigation bar?

**Comment by Robinlovelace** [comment]
I think the change should be in all parts of the application but should remain on the landing page. Sound reasonable?

**Comment by usr110** [comment]
There is no 'national' on the landing page, Robin.

**Comment by usr110** [comment]
Fixed in: https://github.com/npct/pct-shiny/commit/5a4b67a20beaa2f30b559d508091932c2a693662
