### ISSUE TITLE
Images in Manual

### ISSUE THREAD

**Issue by nikolai-b** [npct/pct-shiny#378]
I don't understand Markdown but this https://github.com/npct/pct-shiny/commit/4fae7853b1bc01a508f8b0360908052674518555 brakes all the images as we don't have access to 
`/home/robin/npct/pct-shiny/www/assets/FAQs/Fig3.png` on the server.

**Comment by Robinlovelace** [comment]
Fair point - that should never have crept in (worked 1st time I tested it on the server) - I'm on the case. It will be a simple matter of using relative paths I imagine - will try not to bodge it, promise!

**Comment by usr110** [comment]
With all the amazing fixes by Nikolai unfortunately the images path issue still persists, so re-opening the issue.

**Comment by Robinlovelace** [comment]
Now fixed on the test server thanks to this: https://github.com/npct/pct-shiny/commit/0570adddb7272ce8f6c67608cee3d26e35bd840e

**Comment by usr110** [comment]
:thumbsup:

**Comment by Robinlovelace** [comment]
Good stuff it's finally working - we also need to update the images at some point. You up for having a quick go at that if you find some free time Ali? Thanks.
