### ISSUE TITLE
Repeated values in production colourscheme

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#383]
Currently it has repeated 1s in regions with low levels of cycling, e.g.:

![screenshot from 2016-08-22 20-11-42](https://cloud.githubusercontent.com/assets/1825120/17868027/d89bcfc6-68a4-11e6-90b4-be996ca1754c.png)

Would be solved by the new colourscheme described in https://github.com/npct/pct-shiny/issues/374

**Comment by AnnaGoodman1** [comment]
now fixed with new colour scheme

**Comment by Robinlovelace** [comment]
Ace!
