### ISSUE TITLE
minor point for Ali (I think): change 0% to <0.5% in pop-ups if possible

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#384]
We round % cycling (and driving) to nearest percent. This is usually fine, but would it be possible to have "<0.5%" replace "0%" when the value is less than 0.5% but not actually zero?  (or even better, but probably harder, a rule that if less than 1% we show to 1 decimal place rather than whole number).  Not a major issue, though

**Comment by Robinlovelace** [comment]
I'm not sure this is a good idea. One to discuss I think.

**Comment by usr110** [comment]
It's a good point, Anna. I can implement it. Just one thing though: could you point me where the value is shown as 0? I will use it as a test case then.

**Comment by usr110** [comment]
No worries, Anna. Found plenty of examples in `north-east`. Now I am on it.

**Comment by usr110** [comment]
I've introduced 1 decimal point for values greater than 0 but less than 0.5.
