### ISSUE TITLE
Replace popups with hover for the front map

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#385]
Instead of two-steps (click a region, and then click on the popup to open app) introduce a simpler mechanism to select a region.

- Replace popups with hover to display a region's cycling percentage of commuters (for the selected scenario)
- Click on a region to open the application

**Comment by usr110** [comment]
Have created a new map in Javascript which solves the issue:

http://npct0.vs.mythic-beasts.com/testmap.html

Things to be done:

- Update it with once decided colour scheme
- Integrate it in the front-page

**Comment by Robinlovelace** [comment]
Looks good. Not sure that this issue needs to be solved, but it's nice to see the percentages change in real time as you hover over it. How did you create it out of interest? Could be useful for future reference and will be good if the same functionality is available in the regional app, e.g. when this PR is completed: https://github.com/npct/pct-shiny/pull/249 . One question - is it possible to make the zone borders the same as in the original for continuity between the frontpage map and the regional map? At present this map has quite a different border style and feel.

**Comment by usr110** [comment]
> Looks good. 

thanks

> Not sure that this issue needs to be solved before the national launch or if it's a blocker, but it's nice to see the percentages change in real time as you hover over it. 

Needs to be done before the launch. James has asked me to work on it. Anna too, probably, was involved in the decision. Not sure.

> How did you create it out of interest? Could be useful for future reference and will be good if the same functionality is available in the regional app, e.g. when this PR is completed: #249 . 

It's all in JavaScript. The code is in the HTML file. See it here:

https://github.com/npct/pct-shiny/blob/master/regions_www/testmap.html

Unfortunately leaflet in R does not support such functionality. Have exported the underlying regions as geojson, which is then used in the leaflet library (similar to R).

>One question - is it possible to make the zone borders the same as in the original for continuity between the frontpage map and the regional map? At present this map has quite a different border style and feel.

Have updated the border of regions to a solid line. Once a region is highlighted (and gets darker), the default white border makes more sense to me.

**Comment by usr110** [comment]
Two points from Anna:

  - any way to show the ".0" , e.g. "24.0%" not "24%"?
  - the box you see when you are not hovering over anything is a different size, particularly a different height, from the box you see when you are hovering over something, which makes the other scenario box jump around in terms of its position on the screen. Possibly we could make the box you see when you are not hovering over anything the same size as the box you see when you are offering?

**Comment by usr110** [comment]
Anna's your two points are resolved here:

https://github.com/npct/pct-shiny/commit/135550dd41c1c19fa6da4632cac9ee6c3d449cfd

Robin, have made the border solid in the same commit.

**Comment by Robinlovelace** [comment]
Great stuff, looking good. Could I ask to everyone that we discuss such changes before putting them as definites to fix - this was the 1st I heard of it, but think it's great it's in there. Look forward to getting consensus on the color schemes. Note the discussion around bins here https://github.com/npct/pct-shiny/issues/374  may have implications for your work @usr110 - easy to get the old style map update but you may need to do some tweaking to https://github.com/npct/pct-shiny/blob/master/regions_www/testmap.html to get the bins, colour scheme etc identical as in the app.

**Comment by Robinlovelace** [comment]
Another thing of integration @usr110: please could you make the borders slightly thinner and grey so they look more like those in the regional app. Minor detail but think visual consistency will improve the appeal of it, as illustrated here: 

![screenshot from 2016-08-23 15-30-07](https://cloud.githubusercontent.com/assets/1825120/17895902/81ff9d08-6946-11e6-84d5-018bf53d893f.png)


Thanks.

**Comment by usr110** [comment]
Open all attribution links in a new tab

https://github.com/npct/pct-shiny/commit/8000e16492a21d9ab0c61da2620ecdc8c0354554

**Comment by usr110** [comment]
Robin, thanks for the suggestion about the visual aspect. Re other points, I have those in my mind. See this comment: https://github.com/npct/pct-shiny/issues/385#issuecomment-241695304

**Comment by usr110** [comment]
@npct/admin for testing (and comments), the new landing page is ready. Access it here:

http://npct0.vs.mythic-beasts.com/new_index.html

**Comment by Robinlovelace** [comment]
The map looks good self standing and embedded in the new index. Great work Ali!

**Comment by AnnaGoodman1** [comment]
agreed that it looks good. One issue is that the functionality is less good with Microsoft edge (the default Windows browser that comes with Windows 10).  specifically, you get the dark hover lines when you are over a region, but they don't go away when you move to a new region, so all regions quickly become highlighted.  I think this is not enough of an issue to stop us using this front page, but if we could fix it  at some point that would be nice. 
![untitled](https://cloud.githubusercontent.com/assets/11818225/17919648/58e93bc0-69cf-11e6-89d4-a17d68066527.png)

**Comment by usr110** [comment]
@AnnaGoodman1 Thanks for the feedback. I was just able to reproduce this issue (had asked someone in office to use the front-page using Edge browser). Unfortunately I don't know how to resolve it. May be @nikolai-b might have some ideas?

**Comment by AnnaGoodman1** [comment]
Thanks.  If no ideas then we can certainly live with it as it is.  Microsoft Edge seems an irritating browser in various ways!

**Comment by AnnaGoodman1** [comment]
ps I think this is now basically ready to become new front page map, and potentially get pushed to server tomorrow with Robin's other fixes?  (just need to make the labels/bins consistent with those inside the regions, see my latest comment on colour scheme issue)

**Comment by usr110** [comment]
Finished it in https://github.com/npct/pct-shiny/issues/374#issuecomment-242440663
Thanks Anna for the response. Since we not looking at the Edge browser problem (for now), I am closing the issue.
