### ISSUE TITLE
Change colour of quiet routes

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#386]
Currently `quite routes` are displayed in `turquoise` colour which doesn't sit well with either `dutch` or `ebike` scenarios. I would suggest to change the colour to something else. Perhaps green?
![quiet-route-colour](https://cloud.githubusercontent.com/assets/10958628/17931751/dfe7f5f0-6a04-11e6-9d5c-09551527cbdc.png)

**Comment by usr110** [comment]
How does `aquamaine` look like?

![quite-route-aquarmine](https://cloud.githubusercontent.com/assets/10958628/17932482/1b1bfb00-6a08-11e6-8737-ea60db7b9947.png)

For suggestions, please use this figure
![colorschart3 1](https://cloud.githubusercontent.com/assets/10958628/17932501/35d28b94-6a08-11e6-9470-52f60baf590c.jpg)

(taken from: http://research.stowers-institute.org/efg/R/Color/Chart/)

**Comment by Robinlovelace** [comment]
I think 51 would be worth trying. Well spotted and yes this will fit better. Also, has anyone tried looking at the red lines in a low cycling scenario? Could be an opportunity to re-assess that also. And the route network...

**Comment by usr110** [comment]
Robin, dark colours don't look nice as quiet and fast routes overlap. 

Have updated colour of the quite routes to `aquamarine` in https://github.com/npct/pct-shiny/commit/a25bcef879b403673dd35cfec24b20555b625f3b

**Comment by usr110** [comment]
Re other lines, good point. I have looked at straight lines in different scenarios; they don't look that bad.

**Comment by Robinlovelace** [comment]
They're still a bit hard to see in the Go Dutch and Ebikes scenario on the test server. 

![screenshot from 2016-08-25 08-29-08](https://cloud.githubusercontent.com/assets/1825120/17960458/0bb90aea-6a9e-11e6-825b-56432b06214f.png)

![screenshot from 2016-08-25 08-28-44](https://cloud.githubusercontent.com/assets/1825120/17960460/10a0336c-6a9e-11e6-8637-becffef29215.png)

I suggest more of a change, e.g. to chartreuse. Can change it for testing once people have had a chance to test aquamarine.

**Comment by mem48** [comment]
Using contrasting colours might help https://en.wikipedia.org/wiki/Complementary_colors  this site http://paletton.com/ will show you the most contrasting (opposite) colour for any given colour. If we a colouring  the map on a Red-Yellow-Blue scale then lines should be green / purple / orange to achieve the best contrast.

**Comment by mvl22** [comment]
We use green for quiet routes as they tend to be greener.

**Comment by usr110** [comment]
That's a good point, Robin. Let's see what others feel about it.
@mem48 As the zones colour keeps changing, we can't use just one contrasting colour. It has to work in all cases. We are now using these colour schemes: http://colorbrewer2.org/#type=diverging&scheme=RdYlBu&n=11

@mvl22 Green is a good suggestion. For a test I have used it in the two extreme scenarios and it looks nice in both of them.

**Census**
![quite-route-green-census](https://cloud.githubusercontent.com/assets/10958628/17966839/b0ce091e-6abb-11e6-8808-542e8fb90072.png)

**Ebikes**
![quite-route-green-ebikes](https://cloud.githubusercontent.com/assets/10958628/17966863/d570fe0c-6abb-11e6-9b49-84ced836765f.png)

**Comment by Robinlovelace** [comment]
I like this latest setting. Please push this 'extreme' (which to me looks pretty good) colourscheme to the test server so we can all have a play.

**Comment by usr110** [comment]
Committed https://github.com/npct/pct-shiny/commit/36c075886872f7d808b2683818fe84e7c6aa4837

**Comment by Robinlovelace** [comment]
![screenshot from 2016-08-25 12-55-31](https://cloud.githubusercontent.com/assets/1825120/17968175/3c02e692-6ac3-11e6-9fb5-c5209c7d8ab6.png)
![screenshot from 2016-08-25 12-55-05](https://cloud.githubusercontent.com/assets/1825120/17968176/3c137160-6ac3-11e6-9a2f-650ebbf5e62d.png)

This looks like a definite improvement to me, and now we don't use green in the colourscheme, I think the suggestion from @mvl22 for green to mean quiet makes perfect sense. Thanks for the quickfire updates.

**Comment by usr110** [comment]
Closing now as it's fixed in https://github.com/npct/pct-shiny/commit/36c075886872f7d808b2683818fe84e7c6aa4837
Re-open if need be.
