### ISSUE TITLE
Licence link doesn't work within application

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#388]
Shows "Not Found"

**Comment by Robinlovelace** [comment]
Well spotted. With this and other fixes, can we push the latest version to production? Will open a PR for comments.

**Comment by usr110** [comment]
Robin, I would wait for the colour (as well as the bins) issue to be resolved (https://github.com/npct/pct-shiny/issues/374). Are you looking into it? Once fixed, the new front-map needs to be updated as well.

**Comment by Robinlovelace** [comment]
OK great - will hold my horses then. We can discuss this here now: https://github.com/npct/pct-shiny/pull/389

**Comment by Robinlovelace** [comment]
I'm not looking into it as the front page map will need to be updated simultaneously and that's more your domain. So please push the new bins - great that you picked up on that. I totally agree we should get that fixed before pushing to production.
