### ISSUE TITLE
Make the height expand/contract to the size of the user's screen

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#39]
Is this a bug in rstudio/leaflet?

If so, can we put in a bug report and look at a fix?

If not, can we implement it?

**Comment by usr110** [comment]
@Robinlovelace I believe it's to do with the fixed height of the map - see here https://github.com/npct/pct-shiny/blob/master/master/ui.R#L33

May be you or @nikolai-b could set it to a relative height. For some reason "100%" doesn't work.

**Comment by Robinlovelace** [comment]
Yes, this is due to the fixed height of the map. I was just wondering if this can be fixed or if it's a bug - what are your views @usr110 ? I'm not sure how to set it as a relative height - I tried in the past and it failed, hence the possibility that it may be a bug. Thanks.

**Comment by nikolai-b** [comment]
p.s. the R shiny browser doesn't handle this on my PC but it works in FF and Chrome.

**Comment by usr110** [comment]
@nikolai-b Brilliant work once again!
For me it seems to be working both in the Shiny Browser as well as in FF. Looks magnificent now. Great!

The only thing which got messed up is DataTables - they aren't working any more.  Of course it's not relevant to this commit, but relates to the version of leaflet. Shiny advises us to move from Shiny:Rendertable to DT::Rendertable.

**Comment by Robinlovelace** [comment]
These are big steps forward. Thanks for the fix and comments.
