### ISSUE TITLE
Lines and Routes being mixed in East London

### ISSUE THREAD

**Issue by mem48** [npct/pct-shiny#394]
I've just noticed that in East London, some fastest routes are displayed as straight lines, is this correct?

It also happens for some (but different) quiet routes

![routesnlines](https://cloud.githubusercontent.com/assets/15819577/18206244/acbce5f8-711d-11e6-9d46-c55d68edb558.png)

**Comment by Robinlovelace** [comment]
Thanks for reporting this - will look into it, perhaps with your help.

**Comment by usr110** [comment]
Closed by @mem48 in https://github.com/npct/pct-data/commit/3008b2460a99f0c57422a3087641bdbd7128ed31

**Comment by RachelAldred** [comment]
I've noticed that some quiet lines in London are being displayed as straight line  -see below
![image](https://cloud.githubusercontent.com/assets/11818218/18429206/3014d600-78ca-11e6-97e9-d693306a0e54.png)

**Comment by RachelAldred** [comment]
Also some fast routes seem to be appearing as straight lines in East London.

![image](https://cloud.githubusercontent.com/assets/11818218/18429304/87abfe98-78ca-11e6-8841-c73a17c4bfe6.png)

**Comment by usr110** [comment]
@RachelAldred The issue has been resolved; it's just the live server wasn't updated - have just now updated it. Hopefully you won't see this issue any more.

**Comment by usr110** [comment]
Closing it now. Please reopen if you find this issue again.
Note: if it's a minor issue, push changes to both `test` and `live` server.
