### ISSUE TITLE
cycle streets estimates of journey duration are direction-specific

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#395]
Estimates of route distance and total change in elevation from cycle streets are more or less invariant regardless of the direction in bidirectional flows (i.e. A to B is pretty much the same as B to A).  however estimated duration can vary a lot, e.g. due to hilliness – see screenshot for an example where it is 15 minutes one way and 24 minutes the other way.  as such using duration calculated from just one direction may be quite misleading as to the average.  previously I would have suggested that this was a reason to exclude the duration variables, but since Rachel finds them useful (and others may too) perhaps we should try to fix this.  one solution would be to run lines in both directions through cycle streets as part of Malcolm rerouting all lines, and then we can give an average duration.  (even better would be for stplanr to extract the round-trip duration from cycle streets, but I'm guessing this is not feasible?)  thoughts? 

![untitled](https://cloud.githubusercontent.com/assets/11818225/18225787/e41d0b3c-71f3-11e6-9ea0-b7f994443603.png)

**Comment by Robinlovelace** [comment]
Good point. Those hilly lines were one of the motivations for 2 way routing in the first place. However, having thought about it more, routes in either direction would be inaccurate. There are various ways of tackling this issue, including

 - subset lines above a certain level of hilliness and re-route them in both directions
- subset lines above a certain threshold amount of vertical displacement and re-route in both directions
- re-route all lines in both directions, to account for the cases where 1 way streets cause a difference

Of those three options my mild preference would be for the 2nd, as it is probably the most computationally efficient in terms of fixing the worst offending lines. Any other potential fixes spring to mind? Would be interesting to do an analysis of the vertical displacement and hilliness vs discrepancy between direction in relation to the % of the population affected.

**Comment by AnnaGoodman1** [comment]
I think what is most efficient depends on how much human effort it takes to route the lines through cycle streets – if we get batch routing, or if Malcolm develops a good method for doing this routing in the background of other tasks, then I think the third option would be best in terms of generating a simpler database created through a less fiddly process (albeit one requiring more lines to be routed), yielding a simpler merging strategy at the end, and also being accurate for all the lines.  so I suggest Malcolm could perhaps see how he goes in routing the lines one way, and if the amount of human effort is not too great and the time taken is not too slow then he could simply route all the lines the other way, But if it is too effortful/slow and we did do a subset then I agree that it is plausibly total vertical displacement rather than average hilliness that is most relevant.  in either case, perhaps in the first instance Malcolm should focus on routing the lines in one direction and we see how fast progress is?

**Comment by mvl22** [comment]
The new server and the batch routing are all set up, so feel free to fire away requests.

The batch routing interface will do calculations in both directions if you wish.

**Comment by Robinlovelace** [comment]
Many thanks @mvl22 for setting all that up, and the impressively featured CycleStreets.net batch routing interface. @mem48 please let us know of any progress you make with this to avoid any duplication of effort - tempted to give it a spin even while I'm supposed to be on holiday!

**Comment by RachelAldred** [comment]
I would suggest if possible that in the data downloads we could include duration for the route each way - that would be ideal as would be specific information about each journey, and people could then average it themselves. The first time variable could be for the route from the first mentioned MSOA in the downloads to the second mentioned MSOA, and the second time variable could be for the reverse. Would this be possible and not too much extra work do you think?

**Comment by mem48** [comment]
Rerouting the whole dataset in the opposite direction is very time consuming for a minor increase in detail. Ine the example @AnnaGoodman1 gave the speed varies from 10 mph to 6.25 mph. it might be easier to calculate time from the distance with an uphill calculation and a downhill calculation. Or simply apply an average speed of 8 mph to the distance. As cycling speed varies significantly I'm unclear how reliable cycle streets estimates are.

**Comment by mvl22** [comment]
We use a cycling version of Naismith's Algorithm for the hills, and this will mean that journeys will sometimes be different because of this (and one-way streets). Work in the coming month or two is putting in a substantially refined turn delays algorithm, which will also be heavily directional - we'll have a blog post on that soon and will flag this up.

https://www.cyclestreets.net/journey/help/routing/#hills

I'm aware Malcolm is awaiting a reply from me re batch routing - I'll try and follow that up soon. (Sorry, it's been a busy month or two).

> Would this be possible and not too much extra work do you think?

The batch routing UI does have the option to run routing in both directions, though obviously it doubles the run time.

**Comment by Robinlovelace** [comment]
My suggestion: re-run in both directions and take the average for lines above a threshold level of vertical displacement (e.g. 50 m per km or 5% on average).

**Comment by AnnaGoodman1** [comment]
that would probably be an improvement, though 5% seems high - that is only the top 1.5% of lines nationally.  I would suggest 1) modify the text in the codebook to flag this problem (I did consider doing that myself a couple of weeks ago but could find where the codebook's were); 2) put this issue on hold for now, possibly until the next national build, or at least until February

**Comment by AnnaGoodman1** [comment]
suggest we close this? Solving it properly would involve routing all lines in both directions, I suggest we close it for now and we open it up if it becomes an issue later on. For now I am not sure anyone is using the time estimates in a way that is a critical problem. (It is also highlighted as being one-way direction and the codebook)

**Comment by Robinlovelace** [comment]
Sounds good.
