### ISSUE TITLE
Area-based visualisations - by health/CO2?

### ISSUE THREAD

**Issue by RachelAldred** [npct/pct-shiny#398]
I wondered whether we wanted to consider being able to order the area-based map by health and CO2 benefits , as an alternative to ordering by cycling levels (as we do for lines)?

**Comment by Robinlovelace** [comment]
Think this is a good idea but closing for now as it does not seem to have an action/assignee associated with it. Happy for it to be re-opened though, when it has both of those things (perhaps one to discuss during the team meeting).
