### ISSUE TITLE
Add link to cyclestreets.net and a link to where to dl the data

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#40]
should be self-explanatory

**Comment by usr110** [comment]
@Robinlovelace I haven't put the link to download the data but have provided a panel which describes where the route data comes from - see here: https://github.com/npct/pct-shiny/commit/081d9f875906507da78d2c94888553a42d07c636. If you can pinpoint to the data, I will include it in the panel.

**Comment by Robinlovelace** [comment]
:+1:
