### ISSUE TITLE
Possibility of including average trip lengths in data downloads by area?

### ISSUE THREAD

**Issue by RachelAldred** [npct/pct-shiny#401]
Something that occurred to me when writing a case study - it might in future be useful to have information in the area downloads on the average (mean) trip length in that area.

**Comment by Robinlovelace** [comment]
I think that's a really good suggestions - should be reported in the model output tab too.

**Comment by AnnaGoodman1** [comment]
This is now done in the July 2017 national build – after discussion with Rachel, we decided that "percent of trips below 10 km" was the best single metric to use, also corresponds to what TfL sometimes uses a cutpoint

**Comment by Robinlovelace** [comment]
This is awesome - very useful.
