### ISSUE TITLE
minor adjustments to wording of PCT option menu (for Ali)

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#403]
At some point – not at all urgent – might you be up to look into tweaking some of the wording on the PCT options menu?  looking at this again in the light of Rachel's manual, I realise that some of the text is unclear or out of date

1)  I realise that on the option menu in PCT the header "N. Lines (most cycled)" is not always correct.  Only in the census 2011 scenario does will always see the lines ranked by number of cyclists. If you have chosen to order the lines by carbon reductions, then the "(most cycled)" part is wrong. 
If the label could be different for different scenarios them one could have:
Census 2011 
"N. Lines (most cycled)" > "Top N Lines (most cycled)"
Scenarios
"N. Lines (most cycled)" > "Top N Lines"

Can this be done easily? Or you have a different suggestion? E.g. perhaps we could have "N. Lines (most cycled)" > "Top N Lines" and then a tooltip?

2) I realise that in the 'order lines/flows by' menu, "Level of cycling" is ambiguous. Could this be clarified to either "Number of cyclists" or "Level of cycling (%)"  (I'm not sure which it is)

3) could a tooltip that pops up when you hover over 'Scenario' be change from "Scenario (see FAQ tab)" to "Scenario (see Manual)"

4)  could the tool tooltip that pops up over the number slide option change from "Flows to show" to "Number of lines to show"

**Comment by usr110** [comment]
@AnnaGoodman1 Sorry I should've told you that I created an issue for it - and have also resolved all the points (see https://github.com/npct/pct-shiny/issues/402). You can see the changes on the test server.
So closing this issue now.
