### ISSUE TITLE
Turn 'freeze lines' off by default

### ISSUE THREAD

**Issue by RachelAldred** [npct/pct-shiny#406]
I think we should turn 'freeze lines' off by default - having just had an argument where I have tried to explain 'your map is misleading' (they obviously left 'freeze lines' on and then scrolled to another area). To be fair, I think they have a point that having 'freeze lines' on by default may make people think there is no cycling potential in a particular area. Could we turn it off by default? What do you think? I would be keen we do this as I worry it will be an issue again.

**Comment by usr110** [comment]
This is easily fixable, but I'd recommend let's first discuss it.
1) I believe we introduced this option to reduce the server-load (especially for `route-network`)
2) Some users might get confused with updated lines, as they move around the map, and might not be able to select region-wide top flows. 
3) This option would require users to turn on `freeze` when they've identified a sub-region (how do we communicate this to users? need text or video to explain)

**Comment by RachelAldred** [comment]
Agreed. Personally I think (1) is the main barrier. I do think a new user would automatically tend to think that as they move the lines, the map would move, rather than expecting the originally selected lines to stay by default. But I can see if server capacity/speed is an issue, it might not be desirable.

**Comment by Robinlovelace** [comment]
My preference would be to leave it on by default. I think the advantages of stability of lines, ability to zoom right into specific lines (and the route network) outweigh the disadvantage of some people not realising how to use it. However, I totally agree that it's not at all obvious. Suggestion: make how to use 'Freeze lines' more clear and make it more prominent. One way to do that is to have it on from the beginning and have it subset zones as well as routes. Another would be to beef up and highlight the description of it in the Manual and elsewhere. Really useful feedback and good to discuss in any case.

**Comment by jf1** [comment]
This was discussed in #210 where @nikolai-b and I both expressed a preference for 'freeze lines' to be off as the initial default.

For @usr110's (2) do you think that would be more or fewer users than those confused by the existing situation, and for (3) would a user need to freeze if they're not moving the map, and would a guide be desirable for either (frozen by default / un-frozen by default) situation.

A suggestion made in #210 was that if it were possible to show 100% of an area's route network then this could be frozen and there would never be any under-reporting/displaying even if a user moved and/or zoomed the map. For info I workaround this by exporting the data into QGIS but this defeats the purpose of PCT's web UI and also means I'm often working with old data.

**Comment by RachelAldred** [comment]
I definitely wouldn't want it extended to areas - I think that would be more confusing and not that useful. I am not convinced that people are all that keen to use it (I think it's something people might actively want to select if going to look in more detail at somewhere, rather than having on all the time) and I worry that the potential misunderstanding is going to be off-putting. I'm not convinced that having more on it in the manual would help either. Would be interested to hear what others think though.

**Comment by nikolai-b** [comment]
I think it is confusing having the lines frozen.
When I open a map and move then I expect features on the map to move and follow the map extent.
This is the case in google maps, bing maps, the superzip example, cyclestreets and all other online maps that I have used.
@Robinlovelace is strongly opposed https://github.com/npct/pct-shiny/issues/210#issuecomment-214957555
The only issue I see is with 1), as the route network is much more time consuming.  I don't have a good solution I'm afraid.

**Comment by usr110** [comment]
It seems the majority is in favour of keeping `freeze lines` as `on` by default; that's fine
Re `route-network`, unlike all other lines, I'd propose if we switch to make `freeze lines` `off` when user selects it? (Some users might want to make it `on`, on their own) After all, `route-network` is always showing region-wide aggregated flows; not specific to a sub-region, so that should work fine. What do you think?

**Comment by usr110** [comment]
@npct/admin I've made the following changes:
1. Freeze lines is `off` by default. 
2. It becomes `on` and also unchangeable for `route_network`, as it is always independent of the sub-region. Hence it's drawn for the whole region (`bounding box` is not calculated for the `route_network`).

You may see the changes on the [test-server](http://npct0.vs.mythic-beasts.com/). Please share your comments. I believe this solution should satisfy everyone's requirements.

**Comment by usr110** [comment]
Closing the issue now - fixed in https://github.com/npct/pct-shiny/commit/bc9046b7b756f6308b1d674c4e55a4db216b870f. For those who haven't noticed/seen the changes, you can use the [test-server](http://npct0.vs.mythic-beasts.com/)

**Comment by Robinlovelace** [comment]
Good implementation - works well and great that it preserves the Route Network. One problem, that I've mentioned previously, is that it now makes it impossible for users who don't know about Freeze Lines (the majority I expect) to zoom into a specific route, e.g. to see which road a particular desire line goes along. I've put in a new issue, #421, to tackle this.
