### ISSUE TITLE
Put Manual Sections A and B onto the 'Manual' page.

### ISSUE THREAD

**Issue by RachelAldred** [npct/pct-shiny#407]
Hi, can we re-jig the Manual page please? We now have Manual A and Manual B finalised, so pending their being put into html it would be great to have them up as pdfs on the manual page - as links to the 'Manual Part A' and 'Manual Part B' below. I would suggest rewriting it as follows (I have removed the comment about users editing it given the current pdf format). I also suggest removing some of the FAQs as not needed (and the 'how to use it' section is now out of date).

[User Manual A_final.pdf](https://github.com/npct/pct-shiny/files/500598/User.Manual.A_final.pdf)
[User Manual B_final.pdf](https://github.com/npct/pct-shiny/files/500597/User.Manual.B_final.pdf)

Welcome to the Manual for the Propensity to Cycle Tool (PCT).

This is work in progress and is being developed as part of a suite of training materials during 2016. To request more information or provide feedback, please email us at pct@pct.bike or report issues on our GitHub issue tracker. 

Manual Part A 
Manual Part B

Additional FAQs

1. Does hilliness matter for cycling? Do the Dutch just cycle more because the Netherlands is flatter?

2. How does propensity to cycle differ between England and the Netherlands?

3. Why focus on the direct routes?

4. What are the estimates of future cycling rate based on?

**Comment by usr110** [comment]
The `pdf` links don't seem to work from within the application.

**Comment by usr110** [comment]
@RachelAldred You can see the changes on the [test-server](http://npct0.vs.mythic-beasts.com/)

**Comment by Robinlovelace** [comment]
Looks great to me. Fast work Ali and good stuff re pdf manual. One question @RachelAldred - you mentioned saving the images in a separate folder which is really useful - could you share this (e.g. as a .zip file attached here).

**Comment by jf1** [comment]
As these pdf manuals may get saved by users, might their filenames be better as:
PCT-bike-user-manual-A.pdf & PCT-bike-user-manual-B.pdf
Instead of: User.Manual.A_final.pdf & User.Manual.B_final.pdf

**Comment by RachelAldred** [comment]
Hi @Robinlovelace - it's in my Work in Progress/User Manual file in dropbox, and I have also attached. I hope it uploads ok - it's quite large - if not please get from Dropbox.
[Uploading Images_B.zip…]()

**Comment by RachelAldred** [comment]
And thanks @usr110 - looks good!

**Comment by usr110** [comment]
thanks @jf1 for the comment - have changed the filenames.
Based on the comment made by @nikolai-b (see https://github.com/npct/pct-shiny/commit/0eb84ec8d82f51d925da99f83246d01bef331788#commitcomment-19238332), I have saved the pdfs of the manual in the `static` folder and provided repo-specific links. You can see the changes on the test server.
