### ISSUE TITLE
No map at all on IE9

### ISSUE THREAD

**Issue by mvl22** [npct/pct-shiny#416]
IE9/Win7 gives no map at all:

![ie9](https://cloud.githubusercontent.com/assets/361423/19049673/508a3652-89a3-11e6-89f9-47ed01bd0e1b.png)

http://pct.bike/cambridgeshire/

We learnt over many years that IE is very particular indeed about JS syntax (e.g. disallowing trailing commas at the end of an array), and that using http://jslint.com/ is almost essential. I realise this might not be easy given that Shiny seems to generate JS for you, but I would strongly consider using JSLint if you can.

Also, get yourself an account on https://www.browserstack.com/ so you can do simple visibility checks quickly, which would pick up the problem screenshotted above. This won't solve the problem of interactivity checks but it will at least pick up major bloopers.

IE may indeed be a nuisance from a developer's perspective, but it is prevalent within Local Authorities. You should definitely assume that a significant part of the PCT audience will be using it.

**Comment by mvl22** [comment]
Running the `F12` debugger, the problem above arises at:

```<script>if (window.location.href.includes("pct.bike")){```

I've come across this before - includes() is ECMAScript 2015 so isn't supported:
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/includes

Try one of these instead:
http://stackoverflow.com/questions/1789945/how-to-check-if-one-string-contains-another-substring-in-javascript
http://stackoverflow.com/questions/3480771/how-do-i-check-if-string-contains-substring

or add the polyfill specified in MDN.

**Comment by usr110** [comment]
Great fix, Nikolai
