### ISSUE TITLE
Front page map takes you to wiltshire

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#418]
Whichever zone I click on it takes me to http://www.pct.bike/wiltshire/

Reproducible example: go to http://www.pct.bike and click on a zone

**Comment by usr110** [comment]
Good fine, Robin
With the reduced number of variables in the geojson file, there's no variable called `url`. Now it needs to be replaced with `Region` at:

https://github.com/npct/pct-shiny/blob/master/www/front_page/map.js#L144

**Comment by usr110** [comment]
It seems there's another `regions.geojson` file in `regions_www` folder where there's a `url` variable with all values as `wiltshire`

https://raw.githubusercontent.com/npct/pct-shiny/master/regions_www/regions.geojson

**Comment by Robinlovelace** [comment]
Good work Ali. This links to something @nikolai-b said: we should keep regions.geojson in one place and one place only. Happy for that to be here. Will need to update pct-load slightly if so. You up for that Nikolai?
