### ISSUE TITLE
Users who don't know about Freeze Lines cannot zoom into a single desire line or route (e.g. to see what road it's on)

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#421]
Related to #406 - this will reduce the negative impacts of implementing this feature for people who want to view the roads that desire lines travel on at high geographical resolution. Quick fix, no impact on other parts of the tool, happy to give it a shot.

**Comment by nikolai-b** [comment]
I'm not in favour of more popups as I think that is confusing.
I'd be in favour of making the lines jump less when we zoom as I believe that is the issue.

**Comment by Robinlovelace** [comment]
The issue is that when a first time user of the PCT wants to see which road a cycle path is on, a common use case, they cannot because as they zoom in the path disappears. A popup is one solution - there may be others so I'll generalise the issue name.

**Comment by Robinlovelace** [comment]
Fixed here: https://github.com/npct/pct-shiny/commit/ecec53ecf13a5a82aa4246001e7d9562a1a561eb
