### ISSUE TITLE
Base Map Missing on Website

### ISSUE THREAD

**Issue by mem48** [npct/pct-shiny#424]
Some of the base maps are missing on regions. The Roadmap black and white and hilliness do not show anything except a grey background. Is anybody else seeing this? It seems to affect all regions.
![no background](https://cloud.githubusercontent.com/assets/15819577/19593103/cc59792e-9776-11e6-89bb-1e9193412f1d.png)

**Comment by Robinlovelace** [comment]
That's because this fix has not yet been pushed to production I think: https://github.com/npct/pct-shiny/issues/423

**Comment by Robinlovelace** [comment]
And will be fixed when we merge this PR: https://github.com/npct/pct-shiny/pull/425 - happy for Nikolai or Ali to do that. Please check bugs on on www.pct.bike are not fixed already on the test server, e.g. http://npct0.vs.mythic-beasts.com/cambridgeshire/ before reporting. New hidden trip type floating menu looks great by the way @usr110.

**Comment by Robinlovelace** [comment]
This PR rather: https://github.com/npct/pct-shiny/pull/426
