### ISSUE TITLE
Downlodable data should be updated for all-trips GM

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#427]

**Comment by Robinlovelace** [comment]
Any update on this @usr110 or @audev ? Cheers.

**Comment by audev** [comment]
Was not on my radar, thanks for reminding @Robinlovelace 
If this was about downloading lines/zones/rf... , the functionality has been there & working for quite a while.

**Comment by Robinlovelace** [comment]
Closing for now then. @JDWoodcock please re-open if needs be.
