### ISSUE TITLE
route information

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#43]
-          It’s not clear where a route goes from and to – would it be possible when one clicks on a route (to see distance, increase in cycling etc.) to highlight the whole route so you can see where it goes from and to.

**Comment by Robinlovelace** [comment]
Re-opening this - does not seem to highlight the selected line. Am I missing something. Please provide a screenshot to illustrate should be happening. One to talk about perhaps.

**Comment by Robinlovelace** [comment]
:+1: Apologies @nikolai-b you've done an awesome job on this - please deploy!

**Comment by usr110** [comment]
@nikolai-b It is indeed a great work. Good job!
