### ISSUE TITLE
Confidentiality & Protection of Personal Data (LSOA)

### ISSUE THREAD

**Issue by nikolai-b** [npct/pct-shiny#431]
We don't have a `l.Rds` because it would be braking census safeguarding.  I could not find a clear document on this or on what is required of us.
If we simply stripe out flows of less that n people is this enough (where n ~ 20)?
Would someone mind linking me to the guidelines on data?
Are we allowed to share it amongst ourselves?

**Comment by mem48** [comment]
[ukda137-enduserlicence.pdf](https://github.com/npct/pct-shiny/files/594474/ukda137-enduserlicence.pdf)
 Licence Attached

**Comment by AnnaGoodman1** [comment]
yes, thanks @mem48 .  also the attached is what is on WICID, where we actually download the data.  It says  we need to protect cells with less than three individuals. So would not be enough to flows where n>20 commutesr, as this would still potentially include flows in which the number of *cyclists* was 1 or 2.  it also says  it is fine to share the data with other people who've accepted the UKDA end user license – so it is fine to share the data amongst ourselves @nikolai-b .

one option is that we could:
     1) post online an open, freely-downloadable version of the lines in which the variables are total number of commuters; distance plus hilliness; and the go Dutch and ebikes no. cyclists (as these all depend only on the total number of commuters, not on the existing number of cyclists, so can't be reverse engineered).  we would only include lines with 3+ commuters.
and
    2) give the full version of the data, including the number of cyclists, walkers, drivers (which will often be one or two people), to people who had "registered with the UK data service and accepted the terms and conditions stipulatedin the end user license". I am guessing that this process would involve them emailing us in the first instance to request the data, and then we get them to register with UK DA. we would have to think about how we would verify that they had done this, the data management team at Cambridge may be able to help.

**Comment by Robinlovelace** [comment]
Closing this as it seems there's no action point - very useful discussion and happy for it to be re-opened if there's more to be said. You happy with that @nikolai-b? Good point that it only allows us to go down to all >= 3, which fits with our plans for the lsoa routing: `mdist < 20 & all > 3`  - heads up @mem48.
