### ISSUE TITLE
Issues on new national build (Isle of Wight test)

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#432]
Data downloads :   since the last national build there seems to have been a rule implemented to only show numbers the three significant figures. I think this needs to change to “three significant figures or nearest whole number, whichever is the more precise”. Otherwise at the moment we are rounding the number of individuals in each zone (e.g. a zone containing 3297 individuals comes out as containing 3300 individuals) meaning that our data does not perfectly match what is in the original census files, the number of commuters for each mode in the data download does not match the total number of commuters, and the numbers in the data download do not match what is on the interface and the model output tab.  Alternatively, I think the datasets I provided already have an appropriate level of precision in them, so you could just apply additional rounding to the new variables that have been added in downstream of my input datasets, i.e. clc, distance, cirquity, hilliness, time. Perhaps the latter might be simpler?

Model output tab: something has gone wrong figure 3

**Comment by nikolai-b** [comment]
Are you happy with this @AnnaGoodman1 ?  It now only changes decimals to 3 sig. figs.

**Comment by AnnaGoodman1** [comment]
thanks, perfect
