### ISSUE TITLE
For Nikolai: changing labels on the 'all trips' prototype

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#433]
thanks for saying you will have a look at this, Nikolai.  Attached are the bits of text that I think need to change for the " all trips" map layer in greater Manchester (on the test server).  the model output tab has been disabled, and before we give this to DFT we may disable the data download tabs too (but let's leave them for now, so that we can check the data)

Hope this makes sense, if not please ask – if possible by email, since I don't check Github that often

[Labels.zip](https://github.com/npct/pct-shiny/files/573764/Labels.zip)

**Comment by Robinlovelace** [comment]
Great for the prototype but in the main app I think this introduces a related bug - that "all_trips" does not exist. Trace (when clicking on fastest and quietest routes):

```
Warning: Error in get_scenario_name: argument "all_trips" is missing, with no default
Stack trace (innermost first):
    73: get_scenario_name [../../pct-shiny-funs.R#7]
    72: paste
    71: popup_fn [../../pct-shiny-funs.R#358]
    70: evalAll
    69: evalFormula
    68: invokeMethod
    67: eval
    66: eval
    65: %>%
    64: addPolylines
    63: plot_lines [../../server-base.R#417]
    62: function_list[[k]] [../../server-base.R#239]
    61: withVisible
    60: freduce
    59: _fseq
    58: eval
    57: eval
    56: withVisible
    55: %>%
    54: observerFunc [../../server-base.R#235]
     1: shiny::runApp
ERROR: [on_request_read] connection reset by peer
```

Seemed to work before these changes so think its due to them although not sure - please try to reproduce and test before pushing.

**Comment by Robinlovelace** [comment]
Just confirmed on fastest and quietest routes here - please try to reproduce: http://npct0.vs.mythic-beasts.com/avon/

**Comment by AnnaGoodman1** [comment]
Thanks for this, in general this looks great but two changes in my initial set were missed out.  @nikolai-b was this by accident, or is modifying the right hand menu bar not possible without introducing bugs? Thanks, Anna

Right-hand menu bar, scenario drop down menu
       Census 2011 cycling    >>>  Current travel patterns
Right-hand menu bar, 'order lines/flows by' drop-down menu	
         Number of cyclists	       >>>    Number of cycle trips

**Comment by nikolai-b** [comment]
Accident, sorry I went through all the changes for popups only.

**Comment by AnnaGoodman1** [comment]
Thanks @nikolai-b .  Did you fix it and has there been a reversion on current interface, or is this just still on the to do list?  If could be done by deliverable date next weds that would be perfect...

**Comment by AnnaGoodman1** [comment]
@nikolai-b , appreciate you are working hard on national build too (thanks!), but if you might be able to fix these final 2 labelling points on the menu by next Tues that would be appreciated, as we are handing this Manchester layer over to DfT then...
