### ISSUE TITLE
Need to merge correct hilliness data into R files

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#434]
I realise we have forgotten to address getting the correct elevation and incline data into the geographical files - it is not enough for me to have corrected it in the files I'm using, it also needs to be correct in the .Rds files since that is where we get the hilliness values from the display on the interface. At the moment there seem to be some problems, e.g. in line ID "E02003581, E02003583” the fastest route length is given correctly as 1935m but the elevation is very wrong (given as 20m, correct value 79m), and I am not sure how the average incline was calculated (it is given as 0.0393, which is not far off the right value of 0.0408, but not quite right and also not consistent with the elevation value given).  In any case, we ought to have the same numbers on the interface/download files as I have used in my scenario building, so that people applying our formulae can regenerate our results.

Could someone – Malcolm? - Merge into the .Rds ‘fast lines’ the attached CSV file, which provides replacement values for change_elev and av_incline, and then replace the existing files with the corrected files?  And do you want me to make an equivalent file for correcting the quiet routes?  

[Hilliness.zip](https://github.com/npct/pct-shiny/files/580113/Hilliness.zip)

**Comment by AnnaGoodman1** [comment]
yes (though I can't easily open them to check).  How have you corrected hilliness for the routes - did you do this yourself independently using the same method I had, i.e.
diff_elev= modulus(altitude1- altitude2)
correct_elev=round((change_elev-diff_elev)/2)

**Comment by Robinlovelace** [comment]
@mem48 please create a build for isle of Wight si we can check.
