### ISSUE TITLE
DataDir doesn't change for more than once

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#44]
I am not sure you guys are receiving this error or not. Once you start the application (say from the master folder), it shows you Manchester's map. Once you navigate to some other LA (say Sheffield), and its map gets loaded, after that you can't change LA any more. I receive this error:

Warning in run(timeoutMs) :
  Unhandled error in observer: missing value where TRUE/FALSE needed
observe({
    LA <- findLA()
    dataDir <- file.path("..", "pct-data", LA)
    if (session$dataDir != dataDir && !is.null(LA) && file.exists(dataDir)) {
        session$dataDir <- dataDir
        loadData(session)
        updateSelectInput(session, "scenario", selected = "base")
    }
    session$dataDir
})

Does it appear on your end too?

**Comment by Robinlovelace** [comment]
Think this was fixed by @nikolai-b . Please close issues you fix.

**Comment by nikolai-b** [comment]
fixed in 76db22f, sorry I was  a day too slow :smile:
