### ISSUE TITLE
pct.bike is down 

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#441]
@Robinlovelace @nikolai-b

**Comment by Robinlovelace** [comment]
Confirmed. http://npct0.vs.mythic-beasts.com/ is up though. No ideas why - please prioritise @nikolai-b. Could it be due to recent changes to the gm_layers crashing shiny-server?

**Comment by nikolai-b** [comment]
I was down but then it came back up.  I will contact the hosting company
