### ISSUE TITLE
National build 19/11/2016: issues

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#442]
The issues I have found are:
•	the centroid values have not been updated on the map interface
•	The quiet route hilliness data is not correct – e.g. avslope_q value is incorrect in the straight lines download, and change_elev and av_incline are incorrect in the routes download.  These values have incorrectly been set to be the same as for the fastest routes.  The correct values are in the file ‘161113_CorrectHilliness_rf_rq.csv’ that I uploaded last weekend in issue #439.
•	there has been reversion in the data downloads, we have lost Nikolai’s implementation here (https://github.com/npct/pct-shiny/issues/432) of only applying 3 sig fig to decimals.
•	Error message when you click on geojson route network file (“ERROR: trying to get slot "data" from an object of a basic class ("NULL") with no slot”)
•	The variables ‘serror’, ‘ferror’ should be removed from the fast/quiet routes download, they are  for internal checking.  Rq_inc and rqinc are duplicative of each other and also of distq_f  so ideally they would also be removed.  And there are now also lots of scenario parameters in there that would need to be defined in the codebook or in some cases perhaps ideally removed (it doesn't make much sense to have average slope in there twice, once as a percentage and once not… or distance twice, once in meters and once inkm). NB @Robinlovelace , I thought the process was that only variables in the codebook appeared in the data downloads? Could we bring that system back, it did seem good. 
•	There is a typo in the data download name ‘routes_quite.geojson’ (less important, but good to fix)

Also can I check 
•	Are nat_rf and and nat_rq are now both based on the full eligible set of 226,103 lines (see file 161111_NatLinesSet.csv, comment #439)? 
•	Have those 2584 quiet lines that did not get correctly routed the first time having now been re-routed and merged in (again see 439 and associated ‘161113_MissingQuietLines.xlsx’ CSV)? Otherwise will get problems especially in London of showing straight lines where should be routes.  (None of these routes are in the Isle of Wight, so I have enough to check directly whether this has been done)

Lastly I see that the old files pct_area.csv and pct_lines.zip are still at https://github.com/npct/pct-bigdata, can these be deleted please? And where are the new files saved?

**Comment by nikolai-b** [comment]
> The centroid values have not been updated on the map interface

I assume this is for @mem48 but if it is something I should try to fix I will need a bit more detail.

> The quiet route hilliness data is not correct 

I know @mem48 merged in your hilliness data but I guess there was a mistake, I'll believe I have all I need to fix this.

> There has been reversion in the data downloads

Yes, I believe this was reverted by mistake.  I've reapplied them.

> 	Error message when you click on geojson route network file

Again, I believe this was fixed and has been _unfixed_ by mistake.  I will fix it again.

> The variables ‘serror’, ‘ferror’ should be removed from the fast/quiet routes download,

@Robinlovelace has done this in https://github.com/npct/pct-load/pull/66

> There is a typo in the data download name ‘routes_quite.geojson’

Fixed, thanks.

> Are nat_rf and and nat_rq are now both based on the full eligible set of 226,103 lines 

I believe so.  I would have to defer to @mem48 but my understanding is that they are.

> Have those 2584 quiet lines that did not get correctly routed the first time having now been re-routed and merged in?

Again, I believe they have been.

**Comment by nikolai-b** [comment]
To make it easy to track progress I'm turning this into a checkbox:

- [ ] The centroid values have not been updated on the map interface
- [ ] The quiet route hilliness data is not correct
- [x] There has been reversion in the data downloads
- [ ] Error message when you click on geojson route network file
- [x] The variables ‘serror’, ‘ferror’ should be removed from the fast/quiet routes download,
- [x] There is a typo in the data download name ‘routes_quite.geojson’

**Comment by Robinlovelace** [comment]
Great - how did the test build go? Can try to do a build from my desktop - let me know if you're still working on it this eve.

**Comment by Robinlovelace** [comment]
Update - did the test build and the new data are sat on the test server for the IoW so I believe the errant variables have been removed, so ticking that box.

@mem48 and @nikolai-b I believe you have everything ready fix the remaining 3 issues asap (aim: by Weds).

**Comment by mem48** [comment]
I'll be able to redo the quiet routes with the appropriate hilliness on Thursday

`Are nat_rf and and nat_rq are now both based on the full eligible set of 226,103 lines (see file 161111_NatLinesSet.csv, comment #439)?`

@AnnaGoodman1  No, there are more lines that that. @nikolai-b and I got quite confused about which lines we should subset too as different datasets have different numbers of lines. Can we have a definitive list of MSOA pairs that need doing so I can check everything against that list?

`the centroid values have not been updated on the map interface`

Don't know how to fix this. Suggestions? @Robinlovelace 

There are also 33 duplicated lines in the data I published which I will clean up.

**Comment by Robinlovelace** [comment]
My old `lines_oneway` file provided a comprehensive list.

You and @nikolai-b re-generated that so I think you should know what's in there.

Note: it contains lines with all < 10:

```
> flow_nat <- readRDS(file.path(pct_bigdata, "msoa", "l_nat.Rds"))
> summary(flow_nat$all)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   1.00    2.00    6.00   26.81   19.00 4998.00 
```

For that reason you now require a computer with > 16 GB RAM to load it!

Note also, `l_nat` now contains duplicate column names:

```
 names(flow_nat)
 [1] "msoa1.x"                  "msoa2.x"                  "all.x"                   
 [4] "light_rail.x"             "train.x"                  "bus.x"                   
 [7] "taxi.x"                   "motorbike.x"              "car_driver.x"            
[10] "car_passenger.x"          "bicycle.x"                "foot.x"                  
[13] "other.x"                  "is_two_way"               "dist"                    
[16] "id"                       "msoa1"                    "msoa2"                   
[19] "all"                      "light_rail"               "train"                   
[22] "bus"                      "taxi"                     "motorbike"               
[25] "car_driver"               "car_passenger"            "bicycle"                 
[28] "foot"                     "other"   
```

Please can you push new versions of `l_nat` and `rf` and `rq` that only contain all > 10?

No need to delete the previous ~ 1.5 GB files as they could be useful for future work.

I'm working on fixing this:

- [ ] The centroid values have not been updated on the map interface

Robin

**Comment by Robinlovelace** [comment]
Job done I think. @AnnaGoodman1 please check the centroid results in http://npct0.vs.mythic-beasts.com/isle-of-wight/

Many thanks.

**Comment by nikolai-b** [comment]
Job done is somewhat confusing as there are many issues.  For clarity I am closing this and opening up separate issues.

**Comment by nikolai-b** [comment]
https://github.com/npct/pct-shiny/issues/442#issuecomment-261917219

So the selection criteria of which lines to include is somewhat confusing as the old `lines_oneway` did not included all the lines that @AnnaGoodman1 generated.  Was it comprehensive in the sense that we should have ignored lines that were in Anna's data and kept lines in the old `lines_oneway`?  When we asked you in person you said we should just used the lines Ann gave hence the much larger files.

I believe the selection criteria is:

1. have a straight-line (Euclidean) distance of less than 20km 
1. A fast-route distance less than 30km
1. contain more than 10 commuters (by any mode, counting commuters in both directions)

@AnnaGoodman1 which of these has been applied to your data set (i.e the lines part of 161103_PCTarealines_csv)?
