### ISSUE TITLE
The quiet route hilliness data is not correct

### ISSUE THREAD

**Issue by nikolai-b** [npct/pct-shiny#443]
The quiet route hilliness data is not correct – e.g. avslope_q value is incorrect in the straight lines download, and change_elev and av_incline are incorrect in the routes download. These values have incorrectly been set to be the same as for the fastest routes. The correct values are in the file ‘161113_CorrectHilliness_rf_rq.csv’ that I uploaded last weekend in issue #439.

@mem48 has offered to work on this:
https://github.com/npct/pct-shiny/issues/442#issuecomment-261909541

**Comment by nikolai-b** [comment]
I believe this is now done.  I've built for IoW...

**Comment by Robinlovelace** [comment]
@nikolai-b remember to put the updated data as a release on pct-bigdata and let me know when it's there. Cheers.
