### ISSUE TITLE
The centroid values have not been updated on the map interface

### ISSUE THREAD

**Issue by nikolai-b** [npct/pct-shiny#444]
@Robinlovelace fixed this in https://github.com/npct/pct-load/commit/5a424f8d5cf7d2d4675de12f23b2ec233eb3e3cb
but waiting on @AnnaGoodman1 to check / sign it off.

https://github.com/npct/pct-shiny/issues/442#issuecomment-261927041

**Comment by Robinlovelace** [comment]
That's what I meant by job done! Will re-open if there are any issues with the updated centroid values.
