### ISSUE TITLE
National Lines selection

### ISSUE THREAD

**Issue by nikolai-b** [npct/pct-shiny#445]
https://github.com/npct/pct-shiny/issues/442#issuecomment-261917219 from @Robinlovelace 

So the selection criteria of which lines to include is somewhat confusing as the old `lines_oneway` did not included all the lines that @AnnaGoodman1 generated.  Was it comprehensive in the sense that we should have ignored lines that were in Anna's data and kept lines in the old `lines_oneway`?  When @mem48 and I asked @Robinlovelace in person we were told we should just used the lines Ann gave hence the much larger files.

I believe the selection criteria is:

1. have a straight-line (Euclidean) distance of less than 20km 
1. A fast-route distance less than 30km
1. contain more than 10 commuters (by any mode, counting commuters in both directions)

@AnnaGoodman1 which of these has been applied to your data set (i.e the lines part of 161103_PCTarealines_csv)?

**Comment by nikolai-b** [comment]
P.S. with the duplication of columns I believe the problem was we failed to run https://github.com/npct/pct-load/blob/master/R/merge_annas_into_lines.R#L10, sorry about that!

**Comment by nikolai-b** [comment]
I believe https://github.com/npct/pct-load/commit/cfe84f27c60cd0b351a53b7abbcab4183a6e212a#diff-cc2f49538eebc13d804d242645ebcb3dR17 fixes this, @Robinlovelace ?

**Comment by Robinlovelace** [comment]
Cannot argue with that, although I think just the `rf$length <= 30000` part of it is sufficient. Will await confirmation from @AnnaGoodman1. Thanks!

**Comment by AnnaGoodman1** [comment]
All those 3 selection criteria have been applied to the dataset 161111_NatLinesSet.csv I provided in #439:
    1) have a straight-line (Euclidean) distance of less than 20km
    2) A fast-route distance less than 30km
    3) contain more than 10 commuters (by any mode, counting commuters in both directions)
(plus 4), only include between-zone lines not within-zone or outside England/Wales or no fixed place).

so you don't need to reapply the criteria, although for future reproducibility of this stage (i.e. not needing to go via me) then it might instead make sense to use the equivalent-looking code "l_nat$all > 10 & l_nat$dist <= 20 & rf$length <= 30000" (and check it gives the same answer)

One reason why the set of lines I provided might be larger than last time is that it includes all of Wales.

**Comment by AnnaGoodman1** [comment]
oh, also, just because I think it tripped us up once before, the minimum of 10 commuters is calculated after aggregating the lines to be bidirectional - so the code "l_nat$all > 10 & l_nat$dist <= 20 & rf$length <= 30000" is correct assuming l_nat is an aggregated-to-bidirectional-flows file

**Comment by nikolai-b** [comment]
Great, thanks.  Done in https://github.com/npct/pct-bigdata/releases/tag/1.6-beta
