### ISSUE TITLE
257 quiet-routes lines to be re-routed and merged in

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#447]
the attached 257  lines have failed to route as quiet routes through cyclestreets so have missing values on length/av_incline etc.  They should be re-routed, and then merged back into the relevant national files.  in the meantime, we should not build Manchester, Northamptonshire, or Greater London as these regions contain some of these missing lines.

[rq_missing_incline_162211.zip](https://github.com/npct/pct-shiny/files/606096/rq_missing_incline_162211.zip)

**Comment by mem48** [comment]
I'm rerouting these now

**Comment by mem48** [comment]
Done, but may require some cleaning up

[rq_mssing_257.zip](https://github.com/npct/pct-shiny/files/606583/rq_mssing_257.zip)
