### ISSUE TITLE
lines as slider or enter value

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#449]
this came up from a few people in Manchester. They find it hard to choose a specific value so would prefer another way to specify the number of lines to show.

**Comment by Robinlovelace** [comment]
That was the initial way of doing it - possible to change and has advantages. Suggest we test it on the test server and see what people think. Can see pros and cons.

**Comment by nikolai-b** [comment]
For what its worth I think the advantage of allowing people to pick a specific number is outweighed by another toggle / input field in the UI.

**Comment by JDWoodcock** [comment]
but this would instead of the slider?

**Comment by Robinlovelace** [comment]
Yes I understood the proposal as a replacement for the slider. Advantage: more specific. Disadvantage: less interactive. I think it's worth testing - would be a line of code to test.

**Comment by Robinlovelace** [comment]
Closing for now - I think we should re-open this if/when it becomes actionable. Really useful discussion.
