### ISSUE TITLE
Only allow this box to appear if 'all' data is there

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#453]
Just spotted this in Avon - should not be there, misleading and clutters the map.

Fixing this will get latest version closer to ready for pushing to production:

![screenshot from 2016-11-22 23-01-40](https://cloud.githubusercontent.com/assets/1825120/20545566/cbefeae0-b107-11e6-898e-01cc3c423449.png)

CC @JDWoodcock @AnnaGoodman1 and @RachelAldred

**Comment by AnnaGoodman1** [comment]
Agreed, but actually there is a wider issue which is that even in Manchester we do not want to push to the live server version that has 'all trips' – that should remain only a prototype.  I am not sure what the right way is to make this happen, perhaps the version with the prototype should be branched to a different URL e.g. 'greater-manchester2' or something?

**Comment by Robinlovelace** [comment]
I think thats a good plan Anna + straightforward to do.

**Comment by Robinlovelace** [comment]
You up for taking a look at this @usr110?
