### ISSUE TITLE
significant figures in downloads

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#454]
@nikolai-b implemented here ( #432 ) a rule of 'only applying 3 sig fig to decimals'.  But I now realise this is not quite working as I had hoped, since there are some variables that are provided by me as decimals but are also quite large.  E.g. ebike_slc is provided by me to 2dp, e.g. '1236.53' but is now being rounded to '1240'.  This is not really right, better would be either leaving it 1236.53 or else rounding to nearest whole number '1237'.  

Could we switch from rounding to 3sf to 4sf (quick and dirty option, but none of the zones have values >10000 for these variables)?

**Comment by Robinlovelace** [comment]
A simple solution is to round variables with values > 1000 to the nearest whole number and all all others to 2 d.p. Sound good? A list of variables for each rule would be useful here.

**Comment by AnnaGoodman1** [comment]
I think the problem with 2dp is that some variables need more than this, e.g. number of deaths at the level of lines.  it could be a rule that some variables get rounded to the nearest whole number, and other things to 3 s.f.  but we would need to specify which variables were which rather than calculating it from the data, since it would be a bit odd to e.g. give dutch_slc to nearest whole number but dutch_sic to 3 s.f. just because the former happened to have a value exceeding 1000.  

If we get into specifying different rules for different variables, then I think the simplest thing is to leave all my scenario numbers untouched (since I already provide them in an appropriately rounded form) and just apply the 3 s.f. rule to the variables that come from somewhere else ( distance, hilliness, clc, dist_q_f).  I could provide that list.  But on reflection, I think probably it is good enough as it is, so am closing this issue for now.
