### ISSUE TITLE
new set of MSOA shape files

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#455]
At the moment the zones cover areas of the seas which looks odd (see e.g. Avon), I think instead using the 'clipped' version might solve this: https://census.edina.ac.uk/easy_download_data.html?data=England_msoa_2011

**Comment by Robinlovelace** [comment]
Thanks Anna - on it.

**Comment by mem48** [comment]
Yes the OA system covers the 'extent of the realm' so it goes to the low water mark, the clipped versions go to what we normally consider to be the land.

**Comment by Robinlovelace** [comment]
My bad - plan to update the msoa data with new geometry and then run a for loop to update them for all the regions.

**Comment by jf1** [comment]
Might one of the 'generalised clipped' versions reduce the server- and browser- loads?

https://census.edina.ac.uk/easy_download_data.html?data=England_msoa_2011 has: English Middle Layer Super Output Areas, 2011, Clipped and Super-Generalised

The ONS also releases 'ultra generalised' boundary data, however I think super-generalised is the simplest version available for MSOAs: http://geoportal.statistics.gov.uk/datasets?q=msoa

**Comment by Robinlovelace** [comment]
We're going to simplify them with `rmapshaper::ms_simplify()` anyway. Thanks for the comment though!

**Comment by jf1** [comment]
The simplification has already been done, and checked, so I can't understand why you'd want to process a non-generalised version yourself, just to create a new and non-standard set of boundaries. Hey ho!

**Comment by Robinlovelace** [comment]
Good points will made - very useful to have a standard boundary definition. @AnnaGoodman1 I will go with these thanks to Jonathan Fingland - glad I left time for community feedback before implementation!

![screenshot from 2016-11-25 12-33-15](https://cloud.githubusercontent.com/assets/1825120/20625508/ac4e474e-b30b-11e6-9206-8eaa6e8fb331.png)

**Comment by Robinlovelace** [comment]
Many thanks for your input on the @jf1 and please keep it up with any other suggestions/constructive criticism.
