### ISSUE TITLE
Missing lines in London

### ISSUE THREAD

**Issue by mem48** [npct/pct-shiny#457]
Builds of London using @nikolai-b  updated data fail due to  there being  10455 lines in rf and 10451 lines in rq with the following errors in build_region

```
> if(nrow(rf) != nrow(rq)) next()
Error: no loop for break/next, jumping to top level
> # Remove unwanted columns from routes
> rf <- remove_cols(rf, "(waypoint|co2_saving|calories|busyness|plan|start|finish|nv)")
> rq <- remove_cols(rq, "(waypoint|co2_saving|calories|busyness|plan|start|finish|nv)")
> # create rq_increase variable
> rq$rq_incr <- rq$length / rf$length
Error in `[[<-.data.frame`(`*tmp*`, name, value = c(1.10235934664247,  : 
  replacement has 10455 rows, data has 10451
In addition: Warning message:
In rq$length/rf$length :
  longer object length is not a multiple of shorter object length
```

**Comment by mem48** [comment]
Problem also in Greater Manchester 13824 rq vs 13826 rf

**Comment by Robinlovelace** [comment]
@nikolai-b let's sort this tomorrow

**Comment by AnnaGoodman1** [comment]
Also one missing line in West Midlands: the fastest-route line E02002132 E02002135 (values NA in the lines download).  Although not sure why this is missing, since I have it correctly routed by Malcolm in one of the October routed files...

**Comment by nikolai-b** [comment]
Very sorry, fixed (for more detail see https://github.com/npct/pct-load/commit/6f93cee2a7).
New routes in https://github.com/npct/pct-bigdata/releases/tag/1.7-beta
