### ISSUE TITLE
suffolk: error when you click CSV in the zones tab

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#458]
"ERROR: undefined columns selected"

**Comment by Robinlovelace** [comment]
Note @AnnaGoodman1 that commit didn't actually fix it (closed mistakenly) but the issue seems fixed now. Please check and re-open if needs be.

**Comment by AnnaGoodman1** [comment]
not fixed for me

**Comment by Robinlovelace** [comment]
Thanks - @nikolai-b can you have a look please?

**Comment by usr110** [comment]
I've investigated the issue. It boils down to the `NAs` values in the `avslope` column for `suffolk`. See the summary below:

> > summary(readRDS("../pct-data/suffolk/z.Rds")@data$avslope)
    Min.  1st Qu.   Median     Mean  3rd Qu.     Max.     NA's 
0.003000 0.009443 0.013590 0.012590 0.015800 0.021880       13

The `is_decimal` function can't deal with `NA` values; this is where the error comes from. 

https://github.com/npct/pct-shiny/blob/master/pct-shiny-funs.R#L44-L46

**Comment by Robinlovelace** [comment]
Great work Ali, thanks for getting up-to-speed with this so quickly since getting back.
