### ISSUE TITLE
No flow lines are displayed when 'Zone Attribute' is set to 'none'

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#46]
For some reasons, the cycling flows don't appear when 'zone attribute' is set to 'none'. Please see the attached screenshot for it.

**Comment by usr110** [comment]
![flow-lines-no-zone](https://cloud.githubusercontent.com/assets/10958628/7699908/fb95011c-fe12-11e4-9dec-d5c046f4a56f.png)

**Comment by Robinlovelace** [comment]
@usr110 confirmed this is a bug - quite a recent one I think. Any ideas @nikolai-b . Thanks for reporting.
