### ISSUE TITLE
rnet not complete for northamptonshire

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#464]
![screenshot from 2016-11-25 13-21-01](https://cloud.githubusercontent.com/assets/1825120/20626507/10e7182e-b312-11e6-9ef7-59195be64d34.png)

**Comment by Robinlovelace** [comment]
Just pushed latest version and looking much better so closing for now.

![screenshot from 2016-11-30 15-30-44](https://cloud.githubusercontent.com/assets/1825120/20758533/05544fbe-b712-11e6-81bd-afb3c24c5def.png)

**Comment by AnnaGoodman1** [comment]
OK to close for now, but I may re-open this once we are further along, current rnet (left side of image) is still much less good than current pct.bike (right hand side below)...

![image](https://cloud.githubusercontent.com/assets/11818225/20784967/81f45612-b795-11e6-9dff-0e04656426fb.png)

**Comment by Robinlovelace** [comment]
Well spotted but the latest commit means rnet should now be as good as previously with `rft_keep = .4` as before.
