### ISSUE TITLE
rney not working in leicestershire

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#469]

**Comment by Robinlovelace** [comment]
Latest version looks good to me, if a little bity. Please take a look @AnnaGoodman1 and re-open if needs be.

![screenshot from 2016-11-30 15-28-56](https://cloud.githubusercontent.com/assets/1825120/20758464/c92d540e-b711-11e6-8d29-8706ef4394c5.png)

**Comment by AnnaGoodman1** [comment]
sorry, I think not ok, much worse than current pct.bike in terms of being patchy and fragmented - seems a shame to go backwards...

![image](https://cloud.githubusercontent.com/assets/11818225/20784814/9feb5f2c-b794-11e6-9e2b-b5129d93f89a.png)

**Comment by Robinlovelace** [comment]
True that - will push a new version.
