### ISSUE TITLE
Simultaneous deploys can brake the deploy scripts

### ISSUE THREAD

**Issue by nikolai-b** [npct/pct-shiny#475]
https://circleci.com/gh/npct/pct-shiny/534
Namely `fatal: Unable to create '/home/git/pct-data/index.lock': File exists.`
I'm not sure why that was as the server has enough space, I'm guessing it was when another deploy was happening.  Something to keep an eye on.

**Comment by Robinlovelace** [comment]
Ah OK - we should not hammer pct-shiny with simultaneous commits then. Happy to close - lesson learned, mystery solved!

**Comment by nikolai-b** [comment]
Not sure I agree with closing.  I think we should make the deploy script pause if another deploy is happening.  It should be able to handle simultaneous deploys.

**Comment by Robinlovelace** [comment]
OK - do you know how to do that?

**Comment by Robinlovelace** [comment]
Closing for now - can re-open when this becomes actionable.

**Comment by Robinlovelace** [comment]
You happy to be assigned to this @nikolai-b ?

**Comment by nikolai-b** [comment]
Yep, happy.  At the moment if you deploy and it brakes making a "empty commit" e.g.
`git commit --allow-empty -m "Redeploy (empty commit)"` will fix it.  @usr110 and @Robinlovelace please take note as trying to fix it on the server may well ended up braking the flow.
