### ISSUE TITLE
warwickshire centroid data not updated

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#476]
it has been updated in avon and north yorkshire, but in warwickshire the old data is still showing on server.  can you not just fix this but see if you can work out why this went wrong, and whether all regions need to be checked for this error?  thanks

**Comment by Robinlovelace** [comment]
Yes I know how this happened - @mem48 and I built on a different computer which must have not had the centroids updated. I think that's the only region that was built on that computer.

**Comment by Robinlovelace** [comment]
Fixed now as shown here: 

![image](https://cloud.githubusercontent.com/assets/1825120/20751832/fda73efa-b6f5-11e6-87e4-695d4567d903.png)

Also heads up @AnnaGoodman1 - not sure what's going on with west-yorkshire as it seems I updated it only 5 days ago - please raise a separate issue on that if confirmed: https://github.com/npct/pct-data/tree/master/west-yorkshire
