### ISSUE TITLE
Scale bar gone on test server

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#481]
Can we re-add this please? A really useful feature.

**Comment by Robinlovelace** [comment]
Cheers, great fix

**Comment by Robinlovelace** [comment]
Although not sure how this re-added the scale bar - please explain (just for interest) @nikolai-b.

**Comment by nikolai-b** [comment]
`$.fn.dataTable` was being called before datatables were initialised which was causing a JS error which stopped other things in that JS file from working, i.e. the scale bar and the switching region.
