### ISSUE TITLE
rebuild regions: 

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#482]
- [x] north-east (rnet not ok)

- [x] north-yorkshire (rnet not awful but still worse than on pct.bike)

- [x] nottinghamshire (uses 70 commuters as mflow cutoff, should be 10)

- [x] west midlands (rnet worse than last build... also uses 20 commuters, last time was 50, not sure if that would help)

**Comment by Robinlovelace** [comment]
Updated rnet in west-midlands: 

![image](https://cloud.githubusercontent.com/assets/1825120/20829716/20616dfa-b875-11e6-9fae-3748c839aa40.png)

**Comment by AnnaGoodman1** [comment]
north yorkshire is not terrible but is still worse than last build - last build is on left, new one on right.  Suggest leave it til last but maybe have another go then

![image](https://cloud.githubusercontent.com/assets/11818225/20831759/8bde86a4-b87e-11e6-9c79-f08225bbb072.png)

**Comment by AnnaGoodman1** [comment]
West Midlands is looking fantastic
