### ISSUE TITLE
Add a routing accuracy measure?

### ISSUE THREAD

**Issue by mem48** [npct/pct-shiny#483]
I've been thinking about routes to places with large MSOA/LSOA etc. This will always be a problem to some extent but I was wondering if we could put a measure on how confident we were of the routing of a particular route.

A first guess could be the ratio of the length of the route to side size of the zones, to try and flag routes that are shorter than the size of the zone. We could also look at the shape of the zone, with square zones being better than long thin zones.

**Comment by Robinlovelace** [comment]
Closing for now - we can re-open this in Phase III I guess.
