### ISSUE TITLE
Don't display trip_menu on production

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#485]

**Comment by usr110** [comment]
I erroneously thought the `on_production` flag (https://github.com/npct/pct-shiny/blob/master/server-base.R#L31) determines if we are on the production branch, but it is on even on the test server. Needs some other mechanism to determine the branch. Perhaps @nikolai-b is the right person to do it.

**Comment by nikolai-b** [comment]
Sorry, that was (very) badly named.  Nice work @usr110

**Comment by nikolai-b** [comment]
P.s. @usr110 I altered this slightly as it appeared initially on my browser and then vanished which was a bit confusing so I've move it to a conditional panel 
https://github.com/npct/pct-shiny/commit/a41983
what do you think?

**Comment by usr110** [comment]
Seems quite fine to me @nikolai-b, thanks. Just please make sure that the line:

https://github.com/npct/pct-shiny/blob/master/server-base.R#L42

,in Linux, returns the branch name. As you use Linux, you're best suited to test it out.

**Comment by usr110** [comment]
As I had feared that the trip dropdown menu is not appearing for `greater-manchester` on the test server.

http://npct0.vs.mythic-beasts.com/greater-manchester/

@nikolai-b can you please have a look at it?

**Comment by usr110** [comment]
@nikolai-b I believe I've resolved the issue in https://github.com/npct/pct-shiny/commit/76cd62e40e103e29f64d946f6f96bb10aa5ea710. In any case, please test it. Once tested, I will close the issue.

**Comment by Robinlovelace** [comment]
Tested - there on test server, not on production. Great work.
