### ISSUE TITLE
Lines and zones DT don't get updated when moved to a new region

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#487]
Sorry @nikolai-b but it seems, with your new fix https://github.com/npct/pct-shiny/commit/859df1679f5029c8f24c065ad696445e10f24ce0, another problem arose. Now the tables become empty when moved to a new region.

**Comment by Robinlovelace** [comment]
@usr110 can you please look at this today? Hoping to update production by 15:00!

Thanks for spotting this.

**Comment by usr110** [comment]
@Robinlovelace sorry but I can't. Only @nikolai-b knows how to deal with such issues.
In any cases, if you really have to update production anyway, I would say go for it. It's not a major issue.

**Comment by Robinlovelace** [comment]
OK thanks - agree, based on further discussion with @AnnaGoodman1 the plan is to update production by 15:00 today. Exciting stuff.
