### ISSUE TITLE
New lines don't display when you shift data via zoom in / zoom out

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#49]
Pretty sure this is a bug - please confirm for other cities.

When I add zones on master all is fine.

Yet zoom out and zoom into Leeds and they disappear:

![selection_205](https://cloud.githubusercontent.com/assets/1825120/7736890/f2cdff20-ff3e-11e4-9931-66a26ab09406.png)

Any ideas @nikolai-b ?

**Comment by nikolai-b** [comment]
You have freeze lines selected @Robinlovelace

**Comment by Robinlovelace** [comment]
True - I still see that as problematic: line bounding box should surely jump to the bb of the new zones? If not users should at least be notified of the solution. "New data scope - unfreeze lines to see line data" in a popup would solve it. Which do you prefer @nikolai-b - jumping scope or notification?

**Comment by nikolai-b** [comment]
How about this?
https://github.com/npct/pct-shiny/blob/master/master/master.R#L109-110
