### ISSUE TITLE
All urls on front page map point to the north east

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#491]
And on production

**Comment by usr110** [comment]
Good find. Here's the culprit: https://github.com/npct/pct-shiny/commit/9a765384094071756adcb576d47d5220daf4a030

**Comment by Robinlovelace** [comment]
I've just fixed it...

**Comment by Robinlovelace** [comment]
Here: https://github.com/npct/pct-load/commit/d0d40cb4b25d91ab759efa32b6db7246988a97ff

**Comment by usr110** [comment]
Fast fix there. Robin. Great.

**Comment by Robinlovelace** [comment]
Cheers - good to keep our eyes on the ball - apologies also for introducing the bug - caught red handed there @nikolai-b I confess hehe

**Comment by nikolai-b** [comment]
Fast work :cake: these things happen!
