### ISSUE TITLE
Download links don't work when moved to a new region

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#494]
Relevant https://github.com/npct/pct-shiny/commit/86677148d761de2470b97422302c2e3ac3bf5897#commitcomment-20106183

**Comment by nikolai-b** [comment]
It still isn't working in the test server for me, how about you @usr110 ?

**Comment by usr110** [comment]
Thanks for testing. It sure isn't. I tested locally and it was working.

**Comment by usr110** [comment]
Different issue @nikolai-b but now it seems even the DT table for `lines` is not being updated when moved to a new region (again this is working fine locally, but not on the test server) - it becomes empty.

**Comment by usr110** [comment]
Good point. Seems like global updation of variable is indeed required there.

**Comment by nikolai-b** [comment]
Right I think that's done it. I'll close but if I'm made a mistake please re-open.

The issue was that when we changed the history the then the download links stopped pointing to the right URL.  I used the same type of code we use with the DT call back to update the links

**Comment by usr110** [comment]
Great work, Nikolai! Tested and it seems to work. Found another bug, btw. Creating an issue for it.
