### ISSUE TITLE
DT tables become empty when moved to a new region

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#495]
A bit difficult issue to reproduce, unless these steps are followed:

1. Go to any region
3. Select either `straight lines` or `routes`
2. Don't change tabs to see either lines or zones DT table
3. Move to a new region
4. Now go to the lines tab, and see the table. It will be empty.

**Comment by Robinlovelace** [comment]
Thanks for reporting, well spotted. Are you up for looking into a possible fix?

**Comment by usr110** [comment]
Tried but failed. Perhaps it's relevant to the callback function (in specific to `history.state`). 

https://github.com/npct/pct-shiny/blob/master/server-base.R#L59

Any ideas @nikolai-b ?

**Comment by Robinlovelace** [comment]
Thanks for trying - it's not an urgent one but is the last UI bug that I know of so would be good to get it sorted.

**Comment by usr110** [comment]
@nikolai-b sorry but it seems the issue hasn't been fixed. Did you test it on the `test-server`?
Follow the steps in https://github.com/npct/pct-shiny/issues/495#issue-194942270 and see for yourself.

**Comment by nikolai-b** [comment]
Yes I did. Sadly this it worked locally but not when on the server as they are different.  Thanks for re-opening.

**Comment by usr110** [comment]
Brilliant job, Nikolai. Seems like quite a lot of work. It's working like a charm.
Does that mean when the `DT` package is updated, all these changes have to be redone? I am guessing at least the folder name needs to be updated. Is that right?

**Comment by nikolai-b** [comment]
Yep, bit rubbish it will all have to change if we update DT on the server (which may well be a different value in prod :cry: ).  I can't work out how to force shiny to render in an inactive tab.  The only thing I can find is an un-answered SO q
http://stackoverflow.com/questions/36918750

To really I want to be able to init the DT tables when the app loads.  I tried lots of things (having the zone and line DT on the map tab and in their own tabs, putting a blank DT in below the map then hiding it, using `DT::reloadData` etc.) but basically DT::datatable [creates a widget](https://github.com/rstudio/DT/blob/764039c9c6b3530d263c2826f660bfe33b30781e/R/datatables.R#L239) and the [dependencies](https://github.com/rstudio/DT/blob/764039c9c6b3530d263c2826f660bfe33b30781e/R/datatables.R#L554) are called only when the widget comes into view.  So yes, I real pain.  Not really sure it was worth the effort updating the browser url when we move regions...

**Comment by Robinlovelace** [comment]
Yes - it's a subtle yet impressive feature that is non arbitrary to implement. Thanks also from me!

**Comment by usr110** [comment]
Thanks @nikolai-b for the explanation. Was really useful.
