### ISSUE TITLE
Error in Extra Potential Cycle Scenario

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#5]
Under the Zone Attribute, when a user selects, "Extra Potential Cycle (ECP)", an error appears:

ERROR: color intensity NA, not in 0:255

**Comment by Robinlovelace** [comment]
Fixed by this https://github.com/npct/pct/commit/57ddbe1857144fb956e6aef487d56621f6e6ff44 and this https://github.com/npct/pct-data/commit/a3c6186fda61e3688150286f1878f41175fca8b4
