### ISSUE TITLE
put case studies on pct.bike

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#505]
@RachelAldred @usr110 @Robinlovelace

as requested by DfT.

**Comment by usr110** [comment]
Let us first decide where do we need to host the case studies? In my view, the ideal place would be the landing page. Users may select them from the top navigation bar.

**Comment by Robinlovelace** [comment]
Great - please attach them to a comment in this thread and we can upload them.

**Comment by usr110** [comment]
Didn't realize that @RachelAldred had already posted them on the pct-blog at:
https://blog.pct.bike/category/case-studies/

We may attach a link to it on the landing page as well. 
First a decision needs to be made where and how the case studies should be integrated (as I've already mentioned in https://github.com/npct/pct-shiny/issues/505#issuecomment-270375166.)

**Comment by Robinlovelace** [comment]
Just linking to them in the about page and perhaps the front page too is a good place to start - was going to make some changes to the about page (e.g. adding a link to the published version of the PCT paper) so a good time to work on this.

**Comment by RachelAldred** [comment]
Please can the links go on the manual page - below the sections of the manual? I don't think they should be on the about page (that's about the team) - they go more with the manual which is showing people how they can use the tool. Also Manual Part C can go up there too. 

I've attached the relevant documents (also in Dropbox). It would be great if this could happen before 26th Jan so I can point to all this during my training session.

Let's leave Cornwall off for now as I need to tweak it.

[W_Sussex_PCT(1).pdf](https://github.com/npct/pct-shiny/files/711244/W_Sussex_PCT.1.pdf)
[Preston.pdf](https://github.com/npct/pct-shiny/files/711246/Preston.pdf)
[Rotherhithe Case Study_final.pdf](https://github.com/npct/pct-shiny/files/711245/Rotherhithe.Case.Study_final.pdf)
[Tunbridge PCT Draft Report_final.pdf](https://github.com/npct/pct-shiny/files/711243/Tunbridge.PCT.Draft.Report_final.pdf)
[User Manual C_final.pdf](https://github.com/npct/pct-shiny/files/711242/User.Manual.C_final.pdf)

**Comment by usr110** [comment]
@RachelAldred Thanks for providing all the documents. I have updated the manual. You may have a look at it on the [test-server](http://npct0.vs.mythic-beasts.com/).

**Comment by RachelAldred** [comment]
Great thanks looks great - could this please be sent live? Sorry only just picked this up.

**Comment by usr110** [comment]
Rachel, thanks to Nikolai, I have just updated the manual on the live server; it now has the manual part C and all the case studies.

**Comment by RachelAldred** [comment]
Fab, thanks!

**Comment by RachelAldred** [comment]
Could we also add Cornwall now, attached (I revised it on their request).
Also just a typo - 'use manual' should be 'user manual' (or just manual).
[Cornwall PCT Draft Report_updated.pdf](https://github.com/npct/pct-shiny/files/743277/Cornwall.PCT.Draft.Report_updated.pdf)

**Comment by usr110** [comment]
Thanks @RachelAldred for identifying the typo. Have fixed it. Also have added the Cornwall case study - updated the manual both on the live and the test servers.

Relevant commits: https://github.com/npct/pct-shiny/commit/2d880a2d1470ee7c65f950d4512cabab39771a55 and https://github.com/npct/pct-shiny/commit/2fbfb701dc769ca3427efc27d10e0ff1cc4806b5
