### ISSUE TITLE
Data files as geojson are not downloadable

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#511]
Receive this error:  `could not find function "geojson_write"`

The `geojsonio` is not installed, or not loaded when the application starts.

**Comment by RachelAldred** [comment]
I hope this is fixed -seems to be on my machine - as we will be using this in tomorrow's training?

**Comment by usr110** [comment]
@RachelAldred This issue only exists on the test server. I assume we will be using the live-server in tomorrow's meeting, so we don't have to worry about it.

**Comment by RachelAldred** [comment]
Oh thanks! Panic over. Yes indeed we will use the live server.
