### ISSUE TITLE
Error messages on PCT interface - 'application unexpectedly exited'

### ISSUE THREAD

**Issue by RachelAldred** [npct/pct-shiny#515]
These seem to appear when loading up the map and then quite speedily putting on a lines layer e.g. route network. Have seen it on Firefox and on IE this morning. Does seem to work after reloading but have reproduced the error a few times now.

![image](https://cloud.githubusercontent.com/assets/11818218/22328720/a5b9fa42-e3b5-11e6-8eff-224028b1b778.png)

**Comment by RachelAldred** [comment]
pct.lancashire > Route Network

**Comment by RachelAldred** [comment]
If people could check and see whether it happens to you that would be great, maybe I am clicking through too fast.

**Comment by RachelAldred** [comment]
So, it's happened every time so far I've clicked on RN while Lancashire is loading up (using Firefox, Chrome, IE). If I wait (till the map & zones have appeared) it seems ok on all those browsers. So I won't worry too much, but will be prepared that it might happen with 20 people using it at once.

**Comment by nikolai-b** [comment]
If we can't reproduce this on the test branch then I think we can close this issue as I've fixed a few things like this on the test server.

**Comment by RachelAldred** [comment]
Fine.
