### ISSUE TITLE
LSOA raster visualisation - parallel lines issue in Ripon, North Yorkshire

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#516]
@mem48 : See below for Ripon, North Yorkshire, which is the place I randomly chose to start looking at the LSOA raster. It looks as if a number of the lines are duplicated with an offset of ?20m inside report (e.g. the roundabout and route going out south). Having checked some other areas, it looks as if this is very unusual (which is a relief!) -  but perhaps at some point you could look into why this happened here, iin case it holds any lessons for avoiding this in the future.  but no rush with this, it does look as if it is just an occasional glitch and the layer as a whole is looking beautiful

![ripon_northyorkshire](https://cloud.githubusercontent.com/assets/11818225/22367937/0b34aa0e-e47c-11e6-9382-1ff7601d82bd.jpg)

**Comment by nikolai-b** [comment]
I believe this is fixed

**Comment by Robinlovelace** [comment]
What makes you think this is fixed? Please put in a counter-example of the area Anna showed for reproducibility and good comms before it's closed again.

**Comment by AnnaGoodman1** [comment]
now fixed: 
![image](https://cloud.githubusercontent.com/assets/11818225/23988070/8b5835de-0a24-11e7-84ef-9b4f30287322.png)
