### ISSUE TITLE
Upload georectified tileset

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#518]
Currently the LSOA tiles are not geo-rectified: 

![image](https://cloud.githubusercontent.com/assets/1825120/22476584/d021b602-e7da-11e6-9c43-10dc6b4dcf4c.png)

This dataset, georectified by @mem48 and myself fixes it:

https://github.com/npct/pct-lsoa/releases/tag/0.2

**Comment by nikolai-b** [comment]
I think this has been done, please re-open if I'm mistaken
