### ISSUE TITLE
Create new Downloads tab

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#519]
This will merge the Lines and Zones data tabs into a new tab, slightly simplifying this UI.

The preliminary plan is to not show the data tables and prioritise the download links.

Would be useful if the tables could be revealed by clicking on a link, E.g:

```
Show sample of MSOA data (lines)
Show sample of MSOA data (zones)
```

**Comment by AnnaGoodman1** [comment]
This has now been done in the July 2017 build

**Comment by Robinlovelace** [comment]
Indeed + add regional raster downloads that @mem48 and I are working on.

**Comment by AnnaGoodman1** [comment]
Now done in pct-tidy

**Comment by Robinlovelace** [comment]
Great work on tidying all these issues, and doing much of the work Anna!
