### ISSUE TITLE
branding 

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#52]
We need some acknowledgements and branding on the interface- probably another tab.
It should acknowledge the DfT project, the NPCT academic team, & then specific work

**Comment by Robinlovelace** [comment]
Agreed. Here are some logos we could use: 

![dftlog2](https://cloud.githubusercontent.com/assets/1825120/9021838/2b01bca6-3851-11e5-82bc-3d8cf22d32b1.png)

![dft_logo](https://cloud.githubusercontent.com/assets/1825120/9021841/2eb6e8bc-3851-11e5-9419-489d5d04e846.png)
