### ISSUE TITLE
LSOA base map

### ISSUE THREAD

**Issue by nikolai-b** [npct/pct-shiny#522]
From: https://github.com/npct/pct-lsoa-vis/issues/2

the census and government target tiles are up live, are we happy with the colour scheme and how it looks @mem48 @Robinlovelace @AnnaGoodman1 @JDWoodcock ?

**Comment by JDWoodcock** [comment]
thanks, when you say live is this for all regions and all scenarios?

**Comment by nikolai-b** [comment]
All regions but only the census and government target tiles are up yet.

**Comment by mem48** [comment]
Repeating my email to Nikolai:

1) Can we hide the zone boundaries, as they clash wit the LSOA data
2) We need a legend to explain the colours

Also, 

Are we going to LSOA desire lines? I think the old code should handle the additional data as straight lines are very simple.

**Comment by mem48** [comment]
Also see https://github.com/npct/pct-lsoa-vis/issues/2 for discussion on colour schemes and alternative visualisations

**Comment by JDWoodcock** [comment]
Thanks – so for a final decision it would be useful to have the conversation so far summarised in doc. I find these github discussions hard to join mid way through.
James

**Comment by nikolai-b** [comment]
@AnnaGoodman1 has confirmed we are happy with the colour scheme
