### ISSUE TITLE
R version not working on Ali or my windows computer

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#53]
rror in gzfile(file, "rb") : cannot open the connection
Warning in run(timeoutMs) :
  cannot open compressed file 'pct-data/manchester/l.Rds', probable reason 'No such file or directory'

**Comment by Robinlovelace** [comment]
Suggest chat w. Nikolai on Slack may be the best approach to deal with this. Could be an operating system issue. Ali, have you tried debugging it? Sounds like a fairly simple directory issue. I know R understands "\" in Windows - please look into what's causing the issue. FYI you can test whether the file exists like this: 

```
R4geo> file.exists( 'pct-data/manchester/l.Rds')
[1] TRUE
```

Please try that and let us know.

**Comment by Robinlovelace** [comment]
I think my latest commit in pct-shiny should fix this - please re-open if not.

**Comment by usr110** [comment]
@Robinlovelace Sorry but your fix didn't work. I have added my fix - https://github.com/npct/pct-shiny/commit/b5b22f7539bf31bc3f1f19918cb1dc8371e0b585. Let me know if this works on your end too - or do I have to set it specifically for Windows?
Also, for some reason, I didn't find the model-output.html file. So now, I have commented it out - see here: https://github.com/npct/pct-shiny/commit/fbeed09e64f84da46b4f58da8cddddd9b9f5eca7
You may see it here:
https://github.com/npct/pct-data/tree/master/manchester

**Comment by Robinlovelace** [comment]
Just added the new model output data! Cheers for your fix

**Comment by Robinlovelace** [comment]
+ checkout the new data online - looks cool to me!

**Comment by usr110** [comment]
Thanks Robin for the fix. It does indeed look cool.
