### ISSUE TITLE
Front page base map is missing on live and test server

### ISSUE THREAD

**Issue by mem48** [npct/pct-shiny#530]
![missing basemap](https://cloud.githubusercontent.com/assets/15819577/23124944/70e7961a-f767-11e6-8305-e2914448e4b9.png)

**Comment by Robinlovelace** [comment]
Suggestion: if it's not fixed by tomorrow morning, switch the basemap, e.g: https://github.com/npct/pct-shiny/pull/531/files

This happened I think because Nikolai exhausted the number of uses of his Mapbox api key.

Probably best if its the same basemap but I'm happy with the one I'm suggesting.

**Comment by usr110** [comment]
Quick fix @Robinlovelace 👍

**Comment by nikolai-b** [comment]
Yep great work.  Btw I don't think I ever added mapbox the the front page, I looked at my account but couldn't see it.  Was it @usr110 in https://github.com/npct/pct-shiny/commit/dba8e1bdb1bb7b36618ac1bde16c4ce5301afe72#diff-459f9d5f1be598a986715888f2a6cf2cR61 ?  This is a good reminder to check we aren't using services that are limited.

**Comment by usr110** [comment]
Yes Nikolai it was I who added that line

**Comment by Robinlovelace** [comment]
Thanks for the archaeology Nikolai and apologies (again!) for incorrectly blaming you when things break haha.
