### ISSUE TITLE
Go Dutch Tile for LSOA Route Network doesn't work

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#532]
Correct me if I'm wrong, but I thought the `Go Dutch` tile had been made. 
At the moment it is displayed by default but when you zoom in, it disappears. See the screenshot:

![go-dutch-lsoa-tile](https://cloud.githubusercontent.com/assets/10958628/23130852/ee571108-f77f-11e6-9c29-b38fc4ba15e0.png)

**Comment by Robinlovelace** [comment]
You're not wrong. @mem48 knows about it and is on the case I believe. Useful have a ticket thought. Thanks for reporting.

**Comment by usr110** [comment]
Great and thanks for the update @Robinlovelace

**Comment by usr110** [comment]
Further on that: it seems like the files are missing - giving `404 - Not Found` error

Example: `1365.png` is there for all scenarios but `Dutch`. `Census` image in:

http://npttile.vs.mythic-beasts.com/olc/11/1025/1365.png

but `Dutch` image is not there:

http://npttile.vs.mythic-beasts.com/dutch/11/1025/1365.png

**Comment by nikolai-b** [comment]
The higher zoom tiles were being built.  Done now

**Comment by usr110** [comment]
👍
