### ISSUE TITLE
link to PCT brochure and evidence brief

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#534]
brochure is at 
http://www.cedar.iph.cam.ac.uk/wp-content/uploads/2017/02/PCT_Brochure_UPDATED_25.01.17_WEB.pdf 

brief is at
http://www.cedar.iph.cam.ac.uk/resources/evidence/eb-14-englands-cycling-potential/ 

can we have a link below the video
@usr110

**Comment by usr110** [comment]
Please also mention the text accompanying it. What about this: 

> [Evidence Brief special – England’s Cycling Potential](http://www.cedar.iph.cam.ac.uk/resources/evidence/eb-14-englands-cycling-potential/). The PCT brochure is available [here](http://www.cedar.iph.cam.ac.uk/wp-content/uploads/2017/02/PCT_Brochure_UPDATED_25.01.17_WEB.pdf).


I'd put it after this text:
`Welcome to the Propensity to Cycle Tool (PCT) for England, which provides an evidence base to inform cycling investment.`

**Comment by JDWoodcock** [comment]
How about something to highlight these are new and to make clear these are two separate things
New evidence Brief special – England’s Cycling Potential. 
New PCT brochure is available here.

**Comment by usr110** [comment]
ok sure. So you want it just below the first paragraph as I mentioned in my earlier post then? (the term `PCT` is defined in the first paragraph)

**Comment by JDWoodcock** [comment]
if there is someway to make it look more like a newsfeed - not part of the general text?

**Comment by usr110** [comment]
In that case, an example would help.

**Comment by JDWoodcock** [comment]
I suggest to ask Oliver and/ or David vaughan- they both know more about what will look good than I do.

**Comment by usr110** [comment]
ok fine

**Comment by Robinlovelace** [comment]
Just seen this and wanted to add: the CEDAR evidence brief looks great.

**Comment by usr110** [comment]
Closing as it's a copy of: https://github.com/npct/pct-shiny/issues/561
