### ISSUE TITLE
Make freeze lines select lines that intersect with the bounding box

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#536]
Not just those that the bounding box contains.

**Comment by usr110** [comment]
👍

**Comment by Robinlovelace** [comment]
Why do this? Before you could not zoom into a line by default.

Before:

![image](https://cloud.githubusercontent.com/assets/1825120/23549747/8f309efe-0005-11e7-8fa8-dc3fbdb540c2.png)


After:

![image](https://cloud.githubusercontent.com/assets/1825120/23549708/697b3ff2-0005-11e7-9620-a276d840c1cc.png)

@JDWoodcock should we push this single improvement to prod? I suggest so - please test to confirm!

**Comment by JDWoodcock** [comment]
I am happy with this :) @RachelAldred @AnnaGoodman1 please confirm before we push

**Comment by usr110** [comment]
Need to verify this, but I believe, with the current implementation, the only downside is: the lines are redrawn when user pans the map (and see the same lines); this should not be happening.

**Comment by Robinlovelace** [comment]
Good point Ali - creating a new issue.

**Comment by Robinlovelace** [comment]
The updated version, without the issue reported by @usr110, is now on the test server. Please @JDWoodcock, @RachelAldred and @AnnaGoodman1 confirm this can go on PCT.bike so that users can zoom in on specific paths again without knowing about Freeze Lines (most do not). If you get back within the hour we can do that by the end of the day so please prioritise!

**Comment by AnnaGoodman1** [comment]
I think this is a definite improvement, and I now am firmly in favour of this rather than having freeze lines ticked by default.  Unless anyone else still thinks this is may not be the best solution, I suggest we don't need further user feedback on this and @RachelAldred can just ask about LSOA. Well done @Robinlovelace the doing this so quickly, and thanks also for spotting that issue @usr110

**Comment by Robinlovelace** [comment]
Thanks Anna and all - will get this on production asap. Agree definite improvement, and shows the value of discussing things in detail and being adaptive. Great example of an agile workflow in action!

**Comment by JDWoodcock** [comment]
Agreed
