### ISSUE TITLE
For fast and quite routes the downloaded data is the fast route

### ISSUE THREAD

**Issue by nikolai-b** [npct/pct-shiny#538]
If the user selects the fast routes then the data is of the fast routes, if the user selects the fast and quite routes the downloaded data is also the fast routes.  I believe we agreed to make it the quite routes or else they are never shown.

This would also fix a bug with fast and quite routes being `identical` to fast routes in 93fc173621910dd72443afdfb47d4c172f02b2cf

**Comment by Robinlovelace** [comment]
Looks good, thanks for finding and fixing this subtle issue.
