### ISSUE TITLE
API key needed for OpenCycleMap

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#540]
![image](https://cloud.githubusercontent.com/assets/1825120/23605029/04241688-0253-11e7-8b58-ae4fd7e28a90.png)

Thoughts? Suggest it may be worth paying. If @nikolai-b or someone could ask how much that would cost that could be a starter. Otherwise we change basemap.

**Comment by mvl22** [comment]
> API needed in OpenCycleMap

Can you clarify?

**Comment by Robinlovelace** [comment]
Thanks Martin.

**Comment by Robinlovelace** [comment]
Another option: https://leaflet-extras.github.io/leaflet-providers/preview/#filter=HikeBike.HikeBike

**Comment by usr110** [comment]
Great fine, @Robinlovelace 
I believe it's a good option and free too. Just looking at their description for `free`

> We try to maintain leaflet-providers in such a way that you'll be able to use the layers we include without paying money. This doesn't mean no limits apply, you should always check before using these layers for anything serious.

Source: https://github.com/leaflet-extras/leaflet-providers

So I am guessing we need to take their permission. Is that right?

**Comment by Robinlovelace** [comment]
Yes I think it would be good to contact them. You up for that Ali? I think they'd like to be used in our site. Then we can switch the layer and close this issue - my suggested solution to this issue.

**Comment by usr110** [comment]
>  You up for that Ali?

Sorry but no. Quite occupied. Can you do it instead?

**Comment by mvl22** [comment]
Why not just get an OpenCycleMap key? It's free for 150k tiles, which is plenty.
