### ISSUE TITLE
region-switching function - regional boundaries

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#542]
These regional boundaries have been simplified, and don't match the actual regional boundaries we are using, which looks a bit messy. Would it be possible to create regional boundaries directly from the MSOAs, and use those to define the regions so that they align better? Or at a minimum, could the boundary around each region become thinner/be removed, so the nonalignment is not so obvious? (e.g. be a blue shape but not darker blue border). Just a thought

![image](https://cloud.githubusercontent.com/assets/11818225/23611762/7e5e84b6-0270-11e7-9d15-960b7ed63324.png)

**Comment by Robinlovelace** [comment]
Yes this is possible. Not a high priority, but definitely worth doing. @nikolai-b if I send you the high res boundary data are you up for giving this a shot?

**Comment by nikolai-b** [comment]
sure, Rds or equivalent with the shapes only would be great, or I can generate them for the regions my self but it would probably take me a bit longer.

**Comment by Robinlovelace** [comment]
This should do the trick:
[regions-highres.zip](https://github.com/npct/pct-shiny/files/826226/regions-highres.zip)

Looking into the issue of missing msoas now...

**Comment by Robinlovelace** [comment]
That one omitted the 3 MSOAs that got away. Try this one: 

[regions-highres2.zip](https://github.com/npct/pct-shiny/files/826320/regions-highres2.zip)
