### ISSUE TITLE
Testing: Replace popups with mouseover labels for regions

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#544]
Replace the popups with mouse-over hover labels for the regions.

@nikolai-b I've updated `leaflet` to the version `1.1.0.9000`. Didn't have permission as a `git` user, so used `root`.

**Comment by usr110** [comment]
Please test it out and share your comments

**Comment by Robinlovelace** [comment]
Tested - an improvement I think. Excellent work Ali!

![image](https://cloud.githubusercontent.com/assets/1825120/23655859/ebca4300-032e-11e7-840f-c34d14cd1774.png)
