### ISSUE TITLE
Boundaries and popups do not disappear when not hovering over an outside region

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#545]
See https://github.com/npct/pct-shiny/pull/539#issuecomment-284777050 for a lucid description of this issue.

**Comment by nikolai-b** [comment]
My fix isn't ideal as when you mouse out of a region then mouse back in it doesn't always re-appear.  I'm guessing its a leaflet issue but :man_shrugging:

**Comment by Robinlovelace** [comment]
This isn't fully fixed so re-opening.

It's intermittent now - not a high priority but worth being aware of in case anyone has any flashes of insight into how to fix it. My own preference would be to have consistency - the blue boundary never disappearing - rather than intermittentent behaviour.

Perhaps it is a leaflet issue, worth putting in an issue at https://github.com/Leaflet/Leaflet ?

**Comment by Robinlovelace** [comment]
My current preference: go back to having non-disappearing boundaries - just set a transparent fill should be a 5 minute job I'd imagine...

**Comment by Robinlovelace** [comment]
Fixed by Ali - now behaves consistently. Very smooth and nice colours, so closing.

![image](https://cloud.githubusercontent.com/assets/1825120/23946234/87f82f06-0971-11e7-8ee6-58a3b51a7e3c.png)
