### ISSUE TITLE
Updated manual documentation to include LSOA layer info

### ISSUE THREAD

**Issue by RachelAldred** [npct/pct-shiny#548]
Please see below, comments/edits welcome. Also in my Dropbox.

User Manual C (this is the methodology section). I have added:

xv.	The LSOA-level route network layer
The LSOA-level route network layer is generated at LSOA level. This new dataset has a much higher geographical resolution, as LSOAs are on average less than a quarter the size of MSOAs: there are 32,844 across England.  The number of OD pairs increased six-fold, from 700,000 to over four million.  This far exceeded the visualisation capabilities of the web-based tool. The technological solution to visualizing the LSOA level route network data involved rasterising the routes and pre-rendering the data as a raster tile set. This reduced the complexity of the in-browser visualisation without affecting functionality, as the raster tiles lack the interactivity of the vector lines.  
The LSOA-level route network layer provides a more detailed geographical resolution, and for some routes (e.g. busy main roads in London) a substantial uplift in modelled cycling flows, because some trips that would have been excluded are now included. Indeed, the LSOA-level route network overcomes a number of limitations of the existing PCT flow data, in particular the exclusion of cross-regional flows. While the MSOA-level route network excludes commuters who cross regions, who travel on routes with relatively few commuters, and can only visualise up to 50% of the network, the LSOA-level route network includes all who commute within England, all LSOA-level OD pairs, and visualises the whole network. 

User Manual B (this is the 'how-to' one)
I've changed the 'Route Network' section to be titled 'Route Network - MSOA'. And added:

Route Network – LSOA
The PCT now offers a LSOA level route network. This provides more granular detail, because we route cyclists from LSOA rather than MSOA centroids. LSOAs are around a quarter the size of MSOAs. While still approximate – particularly for workplaces, because the centroids are weighted to resident population – the LSOA layer allows greater accuracy in routing cycling to and from origins and destinations.
The LSOA level route network involves an improvement that we hope to extend to the MSOA flow data: it includes flows that cross regional boundaries, leading to an increase in accuracy towards the edge of a region, rather than removing flows from (for instance) Lancashire into Yorkshire.
The LSOA layer’s additional accuracy necessitates a substantial amount of additional data, and so it is rendered differently from the MSOA layers. Those are vector data, while the LSOA layer is a raster. It is not clickable in the same way that the LSOA layer is, and there is a legend illustrating different categories of flow, from under 10 to over 2,000.
 
Figure 18: South Lancashire 'Go Dutch' LSOA level route network
![image](https://cloud.githubusercontent.com/assets/11818218/23753873/efc864d2-04d2-11e7-87c1-df849a43634f.png)

And under the 'Data Downloads' section of Manual B, I'd add another heading with 'LSOA-level downloads' and ...
For the LSOA layer, data downloads on the PCT site will be available by early April. They will consist of:
1. Area-level data, similar to that provided for the MSOA layer.
2. Fast and quiet route data, similar to that provided for the MSOA layer.
3. Raster data for the Route Network layer, which can be opened in GIS programmes or used as a standalone image.
4. On the UK Data Archive site (as safeguarded data due to small cell sizes), lines data similar to that provided for the MSOA layer.

I propose just saying that for now as we are going to improve the organisation of other downloads, so when that happens I'll have to change the manual again anyhow. I do think we'll start getting enquiries about the downloads so as I say would really appreciate any pointers on effectively opening the TIF files in QGIS so I'm prepared for when they are up there!

Finally, I'm not sure what we change on the Model Output page - maybe just under 'Key Information'  add a final line saying 'Unlike the MSOA flow data, the LSOA route network contains all flows with England mapped to the route network. For more detail please see User Manual C.'

**Comment by AnnaGoodman1** [comment]
Hi, I have made some edits to the model output page, perhaps @Robinlovelace  or someone can check it does not look a disaster and merge if so ( I hope I've made it in the right place and ddone the pull request correctly – what I have changed it here https://github.com/npct/pct-load/compare/master...AnnaGoodman1-patch-1?quick_pull=1) 

The LSOA layer text otherwise looks good to me but I have some suggested changes, which I think it might be easier to do in track changes in word – so I am going to email that around now

**Comment by usr110** [comment]
Thanks @RachelAldred for the updates. I might have a look at them early next week. I assume you've also updated `PDF` files for manual B and C. Is that right?
@AnnaGoodman1 thanks for the changes; just skimmed through them. Your changes are at the right place. I will merge it.

**Comment by RachelAldred** [comment]
Hi all, no I haven't updated the PDF files - was waiting for suggested changes. Anyone else? Or I can merge Anna's suggestions into the Word and PDF files in my Dropbox.

**Comment by RachelAldred** [comment]
Here it is with Anna's updates - I've also put this loose in my Dropbox ('User Manual' folder) if people prefer to edit there.

User Manual C (this is the methodology section):
xv. The LSOA-level route network layer
The LSOA-level route network layer is generated at LSOA level. This new dataset has a much higher geographical resolution, as LSOAs are on average less than a quarter the size of MSOAs: there are 32,844 across England. The number of OD pairs with a distance <20km increased six-fold, from 700,000 to over four million. This far exceeded the visualisation capabilities of the web-based tool. The technological solution to visualizing the LSOA level route network data involved rasterising the routes and pre-rendering the data as a raster tile set. This reduced the complexity of the in-browser visualisation with some compromise in functionality, as the raster tiles lack the interactivity of the vector lines.
The LSOA-level route network layer provides a more detailed geographical resolution and can model the route for many short trips that were ‘within zone’ in the MSOA layer.  This combination means that for some routes (e.g. busy main roads in London) the LSOA layer estimates a substantial uplift in modelled cycling flows. The LSOA-level route network also overcomes a number of other limitations of the existing PCT flow data, in particular the exclusion of cross-regional flows. While the MSOA-level route network excludes commuters who cross regions, who travel on routes with relatively few commuters, and can only visualise up to 50% of the network, the LSOA-level route network includes all who commute within England, all LSOA-level OD pairs, and visualises the whole network.
User Manual B (this is the 'how-to' one)
I've changed the 'Route Network' section to be titled 'Route Network - MSOA'. And added:
Route Network – LSOA
The PCT now offers a LSOA level route network. This provides more granular detail, because we route cyclists from LSOA rather than MSOA centroids. LSOAs are around a quarter the size of MSOAs. While still approximate – particularly for workplaces, because the centroids are weighted to resident population – the LSOA layer allows greater accuracy in routing cycling to and from origins and destinations.
The LSOA level route network involves an improvement that we hope to extend to the MSOA flow data: it includes flows that cross regional boundaries, leading to an increase in accuracy towards the edge of a region, rather than removing flows from (for instance) Lancashire into Yorkshire.
The LSOA layer’s additional accuracy necessitates a substantial amount of additional data, and so it is rendered differently from the MSOA layers. The MSOA layers are vector data, while the LSOA layer is a raster. It is not clickable in the online interface in the same way that the LSOA layer is, and there is a legend illustrating different categories of flow, from under 10 to over 2,000.

**Comment by JDWoodcock** [comment]
thanks

**Comment by RachelAldred** [comment]
@usr110 @AnnaGoodman1 @JDWoodcock @Robinlovelace   Here are the two updated PDF versions of Manuals B and C to upload
[User Manual C_final.pdf](https://github.com/npct/pct-shiny/files/850396/User.Manual.C_final.pdf)
[User Manual B_final.pdf](https://github.com/npct/pct-shiny/files/850397/User.Manual.B_final.pdf)

**Comment by RachelAldred** [comment]
As discussed I have also now drafted a blog post (just containing the new manual material and saying how excited we are) and will publish that once the LSOA layer is up - assuming this will be Monday? And will tweet :) Can someone drop me an email when it is up there please to ensure I don't miss it? Thanks. @AnnaGoodman1 @usr110 @JDWoodcock @Robinlovelace @nikolai-b @audev @mem48

**Comment by usr110** [comment]
Thanks @RachelAldred for the udpated manuals. I have just updated them on the [test-server](http://npct0.vs.mythic-beasts.com/manual.html). Let me know if you find any issues.

**Comment by Robinlovelace** [comment]
Fantastic work Ali and many thanks for getting these ready @RachelAldred. Plan: push to production by 16:00 today.
