### ISSUE TITLE
PCT about page - update journal article citation x2

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#549]
the full , published citation now exist for b oth of these - note the year of publication changes to 2017 on both, and the journal volumn/issue/page no's exist:

Aldred, R., Elliott, B., Woodcock, J., Goodman, A., 2017. Cycling Provision Separated From Motor Traffic: a systematic review exploring whether stated preferences vary by gender and age. Transport Reviews.  37:1, 29-55, DOI: 10.1080/01441647.2016.1200156 [hyperlink still http://www.tandfonline.com/doi/full/10.1080/01441647.2016.1200156]

Lovelace, R., Goodman, A., Aldred, R., Berkoff, N., Abbas, A., Woodcock, J., 2017. The Propensity to Cycle Tool: An open source online system for sustainable transport planning. Journal of Transport and Land Use. 10:1, 505–528, DOI:  10.5198/jtlu.2016.862  [hyperlink still https://www.jtlu.org/index.php/jtlu/article/view/862]

**Comment by Robinlovelace** [comment]
Hi All,

There's been a lot of debate about this - it's 2016 not 2017. Please use that version, from JTLU and every other place:

![image](https://cloud.githubusercontent.com/assets/1825120/23895043/4a2c1be0-089c-11e7-99c6-b78dc63e5f22.png)


I had to get my University's own system to update it to the correct year (2016, date of online publication) manually.

**Comment by AnnaGoodman1** [comment]
sorry, my fault.  JTLU does now list it as 2017, and to find the paper on the website  you have to search under '2017 > vol 10 > issue 1' so I think there is an argument for the switching - but happy to go back to 2016 if Robin prefers.

![image](https://cloud.githubusercontent.com/assets/11818225/23903465/8c40bb74-08bc-11e7-9041-c433dba89fb5.png)

**Comment by usr110** [comment]
At [JTLU's site](https://www.jtlu.org/index.php/jtlu/rt/captureCite/862/0/AbntCitationPlugin) there is a mixture of `2016` and `2017` depending on the citation format. Using the default `ABNT` format, at my end, it still shows `2017`.
I don't mind either `2016` or `2017`; it just needs to be consistent on the Journal's website.

**Comment by usr110** [comment]
With `MLA` format this is what the tool provides:

> Lovelace, Robin, Anna Goodman, Rachel Aldred, Nikolai Berkoff, Ali Abbas, & James Woodcock. "The Propensity to Cycle Tool: An open source online system for sustainable transport planning." Journal of Transport and Land Use [Online], 10.1 (2017): n. pag. Web. 14 Mar. 2017

**Comment by Robinlovelace** [comment]
Ah OK - seems the consensus is for it to be 2017. Assuming that's the year the CWIS is also launched it could be quite useful. In summary: thanks for changing it!
