### ISSUE TITLE
Lines panel reports error when no lines are present

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#55]
It should say "please load lines from the Interactive Map panel to see lines".

It should not cause an error, even if there are not lines. 
![selection_244](https://cloud.githubusercontent.com/assets/1825120/8061446/c2dd1dd0-0ec2-11e5-89fa-843f664ec357.png)

**Comment by usr110** [comment]
It doesn't - generally, thrown an error. Can you please tell me the steps you used to see this error? When no lines are selected, this is displayed:

"No lines selected: Lines must be displayed on map"

**Comment by usr110** [comment]
@Robinlovelace For some reason, this error only comes on the server. Once you run it locally, it doesn't appear. I don't know the reason. Do you have any ideas?

**Comment by Robinlovelace** [comment]
I'm afraid not, maybe we could try updating our R version? @nikolai-b the server is probably due an update. We could even consider shifting to OSGeo Live 9.0 which will be released very soon: http://wiki.osgeo.org/wiki/Live_GIS_Disc_Press_Release_59 . This is not a major issue in any case...
