### ISSUE TITLE
warning banner on test server

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#553]
please can we have a warning banner on the test server
Proposed text
"This is the PCT test site. Please do not circulate links to this site. Findings from this site should not be assumed to be reliable without specific agreement from the PCT team. Please use www.pct.bike instead."

**Comment by Robinlovelace** [comment]
Good shout.

**Comment by mvl22** [comment]
I would add a robots.txt file as well to ensure it stays out of google.

**Comment by Robinlovelace** [comment]
+1 thanks Martin. @nikolai-b you up for that?

**Comment by JDWoodcock** [comment]
thanks
