### ISSUE TITLE
Current region also gets highlighted when flows are displayed

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#555]
Thanks again @Robinlovelace for testing. Just when I thought everything was working fine, found an error

![highlight-error](https://cloud.githubusercontent.com/assets/10958628/23946387/1b1f71ea-0972-11e7-9edc-94c4e902be54.png)

**Comment by Robinlovelace** [comment]
Ahh - woops. I clearly didn't test in enough detail. Was just testing the region switching function - had no idea it would have side effects. Any idea how complex a mission this will be to fix?

**Comment by usr110** [comment]
It's to do with layer order - had dealt with before, but with highlight it becomes slightly complex. Working on it. Let's see how long it takes.

**Comment by Robinlovelace** [comment]
Many thanks Ali, sorry it's had this side-effect.

**Comment by Robinlovelace** [comment]
Will be worth-it in the end, looking really slick.
