### ISSUE TITLE
West Yorkshire is 'West Sussex' in new regions

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#557]
![image](https://cloud.githubusercontent.com/assets/1825120/23952101/3acae090-0988-11e7-839f-400c1e9f0d7d.png)

**Comment by Robinlovelace** [comment]
Looks like there's been an error introduced - perhaps in the translation from `regions-highres.Rds` to a geojson? It seems correct in the geojson version:

![image](https://cloud.githubusercontent.com/assets/1825120/23952319/08d6b248-0989-11e7-82dc-852bd1af459c.png)

Any ideas @usr110?

**Comment by usr110** [comment]
@Robinlovelace both `layerId` and `label` params needed to be updated. Have fixed it

**Comment by usr110** [comment]
Fixed in: https://github.com/npct/pct-shiny/commit/b274b8389e793dcbf77f3bf7c5ee10d33dad8209
Re-open if you needed
