### ISSUE TITLE
Update model output page + change where Lovelace Ref points to on about page

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#559]
@usr110 / @Robinlovelace 
I updated the model output page (now covers LSOA layer briefly in first section, and updates the Lovelace reference to be 2017 / point to JTLU not arXiv), but it is not showing on the test server - did I update the wrong place? Sorry if so, and I can update the right place if you show me where it is... or if it is the right place, could you integrate it to the test server? Many thanks!

https://github.com/npct/pct-load/blob/master/model_output.Rmd

**Comment by usr110** [comment]
@AnnaGoodman1 You made the edits in the right place. However the `model-output` page needs to be generated for each of the regions (using `pct-load`). Only then you'd be able to see it on the test-server. 
For a test I can generate it for a region say `Cambridgeshire`. What do you think?

**Comment by usr110** [comment]
@AnnaGoodman1 Just generated the `model-output` file for 'Cambridgeshire`. Please see it here:

http://npct0.vs.mythic-beasts.com/m/?r=cambridgeshire

Noticed that the bottom there are some garbled character `â€`. Will fix it.
Once you think that it is all fine, I can generate it for all the regions and display it on the test-server.

**Comment by usr110** [comment]
Have fixed:

> Noticed that the bottom there are some garbled characters â€. Will fix it.

in: https://github.com/npct/pct-load/commit/37c7754a626b0b1f7a8f956e50a193accaf0d0bd

**Comment by Robinlovelace** [comment]
I've checked this for Cambridge Ali. Looks good. Please build build for all regions pending sign-off from @AnnaGoodman1. Great this uses the doi link as suggested by @mvl22. Makes me think of other things we could change in the model output tab but lets get these fixes in as a matter of priority. Many thanks Anna for creating this issue and Ali for fixing it.

**Comment by AnnaGoodman1** [comment]
ok, this seems good to build for all regions - i made just one change, removing the link from MSOA, since it leads to a page that you needt o be signed in to access (see below) + defining LSOA

![image](https://cloud.githubusercontent.com/assets/11818225/24040396/fc6196a8-0b00-11e7-8bc0-f7ef79a9e1fd.png)

**Comment by usr110** [comment]
Good point, Anna. How about replacing the publicly inaccessible link with this one: https://data.gov.uk/dataset/middle-layer-super-output-area-msoa-boundaries?

**Comment by AnnaGoodman1** [comment]
Yes sure, thanks

**Comment by Robinlovelace** [comment]
Has that link been replace now @AnnaGoodman1? If so I guess the action needed to close this is to rebuild the model output page for all regions. Right? Will be good to get it done before we push changes to production today but not essential in my view.

**Comment by Robinlovelace** [comment]
Just checked west-yorkshire and looks good. Great fix.
