### ISSUE TITLE
infrastructure planning tool

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#56]
Please change heading from "Infrastructure planning tool" to "Cycle Planning Tool"

Can we have a new little box at the top- saying "Commuting Layer"

**Comment by Robinlovelace** [comment]
I've had a 1st attempt at fixing this but the result is ugly and clunky. Good for users to know can add more data 'layers' in the future. Any ideas for a better solution @nikolai-b @usr110?
