### ISSUE TITLE
what's new box on front page

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#561]
![image](https://cloud.githubusercontent.com/assets/11818225/24039367/cfce2024-0afc-11e7-8e8b-38481d24c421.png)

mock up

**Comment by usr110** [comment]
@AnnaGoodman1 and @RachelAldred Can you please remind me what did we decide how to link LSOA information as new information? Should there be a link to page 11 of manual `b`?
Like this: https://rawgit.com/npct/pct-shiny/master/static/pct-bike-user-manual-b.pdf#page=11

**Comment by usr110** [comment]
I've just added the `what's new` section on the landing page. Would appreciate if some of you @npct/admin would have a look at it and share your comments. It would be nice if this goes on the live-server.

**Comment by Robinlovelace** [comment]
Looks good to me so closing - great work @usr110 

![image](https://cloud.githubusercontent.com/assets/1825120/24110005/369e9858-0d8a-11e7-909b-124f240ec127.png)

**Comment by JDWoodcock** [comment]
hi all looks nice but I thought plan was if you click on the lsoa layer hyperlink it goes to Rachel's blog rather than downloading the manual @RachelAldred @usr110

**Comment by RachelAldred** [comment]
yes @usr110  please can the link go to http://blog.pct.bike/2017/03/21/lower-level-super-output-area-route-network-now-up/ not to the manual?
thanks :)
