### ISSUE TITLE
Provide download of LSOA route network region-by-region

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#564]
Please can you provide as data release
 @Robinlovelace @mem48

**Comment by Robinlovelace** [comment]
Sure - in one way or another this will happen. Cheers for flagging as an issue.

**Comment by JDWoodcock** [comment]
thanks - we are a bit unclear exactly what files exist and how easy it to make them available. Is there a whole of England raster file that has the numerical values still included?

**Comment by Robinlovelace** [comment]
@mem48 and I will plan to discuss this early April and come back with a proper answer then of how to do this best.

**Comment by Robinlovelace** [comment]
@JDWoodcock note change in title. Heads up @mem48 I'm planning to do this around mid April.

**Comment by AnnaGoodman1** [comment]
now done by Robin and Malcolm, will go live shortly
