### ISSUE TITLE
Update text for the local authority map

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#569]
From @AnnaGoodman1 
>* 'HEAT' should be 'Health'  in options radio button/ title in the display - more intuitive
> * Number of deaths should be to 2 dp for 'total deaths' not just 'deaths per 10,000', I think
> * There should probably not be a minus sign before 'deaths' if it is 'deaths avoided' - either the minus sign or the 'avoided'.  Ideally CO2 could be consistent.  Perhaps it could have 'Health Impact - Deaths Avoided' as the title and then '-0.52 deaths/year in total' on the row? and similarly for carbon 'Carbon Impact - CO2 Reduction' as the title and '-32 tonnes...' as the row?

**Comment by usr110** [comment]
Fixed in https://github.com/npct/pct-shiny/commit/b1c4fee352fa5e4f11aeda531d25520a8537131b and  https://github.com/npct/pct-shiny/commit/6e501ba0a9a7ab6ee5c5adbba791183e20e3fc91

**Comment by Robinlovelace** [comment]
Great work on the LA map btw Ali.

**Comment by AnnaGoodman1** [comment]
yes, perfect, one other tiny thing: can the CO2 reduction be to nearest whole number for the 'per 10000' commuters, currently 2dp for 'per 10000' but nearest whole number in total.  Thanks Ali! Anna

**Comment by usr110** [comment]
thanks Robin

Anna, have sorted it out in https://github.com/npct/pct-shiny/commit/372acfab19458614d8bbb7246151fc205b58b10c. Thanks.
