### ISSUE TITLE
Make model-output.html tab shift to the local authority of interest

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#57]
At the moment it's fixed.

Also making it not crash if there is not html may be a good, but not essential, addition.

**Comment by usr110** [comment]
Both issues are now fixed - https://github.com/npct/pct-shiny/commit/491f08ef8c9458de53375a1ad8f1acffed38f40b

**Comment by Robinlovelace** [comment]
:+1: Thanks Ali. Seems to work for all the cities (even when zooming from one to another!) but not for Norwich, even though the data is there: https://github.com/npct/pct-data/blob/master/norwich/model-output.html . Any ideas why not?

**Comment by nikolai-b** [comment]
![screenshot from 2015-06-16 22 44 01](https://cloud.githubusercontent.com/assets/6289830/8195260/4e4c526c-1479-11e5-80c0-6fd7d30cc6f4.png)
@Robinlovelace works fine for me (and on the server)

**Comment by Robinlovelace** [comment]
Thanks Nikolai for testing - your changes seem to have fixed it.

Not 100% sure what was going on there. Looking awesome in any case.

**Comment by usr110** [comment]
Robin, I just ran the app with yesterday's commit - before Nikolai's changes, and for me too Norwich is showing the model-output html file. I don't know what was happening at your end. 

![norwich-model-output](https://cloud.githubusercontent.com/assets/10958628/8205018/b9058a2c-14e4-11e5-8158-2356977d151b.png)

**Comment by Robinlovelace** [comment]
Thanks for the info people - strange. I think it was because I hadn't added model-output.html when I first ran it and Shiny cached that result. Thanks for the testing!
