### ISSUE TITLE
Add x3 new case studies to PCT website

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#570]
1) Can 3 case studies be added:
Ealing case study
Greater Manchester case study
Hounslow case study

2) can these 3 case studies and the current 5 be re-ordered to be alphabetical (i.e. cornwall first)
[Ealing.pdf](https://github.com/npct/pct-shiny/files/884664/Ealing.pdf)
[Greater Manchester.pdf](https://github.com/npct/pct-shiny/files/884663/Greater.Manchester.pdf)
[Hounslow.pdf](https://github.com/npct/pct-shiny/files/884662/Hounslow.pdf)

@RachelAldred, I think you had tweaked Manual C too, correcting the small issues Robin saw.

**Comment by usr110** [comment]
Thanks @AnnaGoodman1. I have added these three case studies (have also re-ordered them).
@RachelAldred If you could provide me an updated `Manual-C` I will add it and then close the issue.

**Comment by usr110** [comment]
Creating a new issue for the updated manual. Closing this one (closed in https://github.com/npct/pct-shiny/commit/2dd120ea4440d8c55ca2b6b9ec281dd2d6120ea6 and https://github.com/npct/pct-shiny/commit/bfdcc7e285ca7b5adef43de03a1c4030c5c3cb16)
