### ISSUE TITLE
co2 legend health legend

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#575]
not sure if -79+ is helpful band. What is top of band.

for health and co2 legends would be nice to have title as units less clear than for % cycling

**Comment by usr110** [comment]
> not sure if -79+ is helpful band. What is top of band.

The top value is `-79`
Re bands, this is what I am using:
`[-680, -600, -530, -450, -380, -300, -230, -150,  -80,  0]`

> for health and co2 legends would be nice to have title as units less clear than for % cycling

What labels do you prefer?
for health: `Deaths avoided`?
for co2: `CO2 Reduction`?

**Comment by JDWoodcock** [comment]
0 would be clearer than -79+
What labels do you prefer?
for health: Premature deaths avoided per 10,000 commuters?
for co2: CO2 Reduction TCO2e

**Comment by usr110** [comment]
sorry the highest value is `-4.38`

**Comment by JDWoodcock** [comment]
fine use -4 then.

**Comment by usr110** [comment]
so the first bin is `0 to -4' then?

> for health: Premature deaths avoided per 10,000 commuters?
for co2: CO2 Reduction TCO2e

It's quite a long label for health. Also if we are going to mention `10,000 commuters`, shouldn't it be used for `CO2` as well?

**Comment by JDWoodcock** [comment]
so the first bin is `0 to -4' then - _ I thought -4.38 was top so 0 to -4 not needed?

    for health: Premature deaths avoided per 10,000 commuters?
    for co2: CO2 Reduction TCO2e

It's quite a long label for health. Also if we are going to mention 10,000 commuters, shouldn't it be used for CO2 as well?
- Agree be consistent and need to see what looks like 
how about?
    for health: Deaths postponed/ 10,000 commuters
    for co2: TCO2e reduced/ 10,000 commuters

**Comment by usr110** [comment]
Changed into:
`Deaths avoided per 10,000 commuters`
`TCO2e reduction per 10,000 commuters`

**Comment by usr110** [comment]
Re bins for `CO2` I am still not clear what you would like.
Can you write the bins as:
`-680, -600, -530, -450, -380, -300, -230, -150, -80, 0`?

If we use -4 as the last entry, it would be something like:
`-680 -605 -530 -455 -380 -305 -230 -155  -79   -4`

this means the first label would be `-4 to -78`

**Comment by JDWoodcock** [comment]
If we use -4 as the last entry, it would be something like:
-680 -605 -530 -455 -380 -305 -230 -155 -79 -4

this looks good to me
James

**Comment by usr110** [comment]
So you want just one LA with `-4.38` in the first bin of `-4`?
The second bin would start from `-5`. Is this right?

**Comment by JDWoodcock** [comment]
I think we are speaking at cross purposes (ie I am confused) 

doesnt this work -680 -605 -530 -455 -380 -305 -230 -155 -79 -4?

**Comment by usr110** [comment]
if we have bins like: `-680 -605 -530 -455 -380 -305 -230 -155 -79 -4`
the first label as I mentioned [here](https://github.com/npct/pct-shiny/issues/575#issuecomment-290736894) would be
`-4 to -78`

the second would be: `-79 to -154` (and so on..)

**Comment by JDWoodcock** [comment]
that seems fine to me

**Comment by usr110** [comment]
great

**Comment by usr110** [comment]
Fixed in https://github.com/npct/pct-shiny/commit/077f5c2601a266c6e4714e1025fed4baa5e10626 and https://github.com/npct/pct-shiny/commit/a9276566aea5179f509b2303e4de1dd9d3e4866f
