### ISSUE TITLE
Develop a method for monitoring PCT usage / strengthening server as needed

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#576]
As part of the four-month extension from DFT, we have agreed to a set of small deliverables of which the first is: _There is now a need to ensure the tool remains maintained and fit for purpose for the coming months as user demand is likely to increase significantly [e.g. with the launch of the Cycling and Walking Investment Strategy in the coming weeks]. In practice this means that the current Server capacity need to be assessed and strengthened if required to ensure increase site traffic can be handled. The performance of the tool will need to be supervised and measures taken to ensure satisfactory service levels are maintained. The initial assessment is required by end of April with ongoing checks required until the end of the contract._ 

I think it would be good to have two things happening in an ongoing way from now on (I appreciate that we may already be doing either or both of these things to a considerable extent – great if so):
[ ] a procedure for keeping an eye on the PCT usage and performance in general, perhaps with a monthly update circulated around the team.  hopefully @nikolai-b , or someone, could then assess each month whether the current server arrangements remain adequate
[ ] some mechanism for identifying acute problems, e.g. if the server crashes completely.

@nikolai-b, @Robinlovelace , @usr110 - input welcome on what we should be monitoring and how.  If helpful then, if you three can agree on what information we should be collecting and can show me where to get it, then I would be happy to pull it together and circulate the monthly update.  Or of course very happy for one of you 3 to lead on this if you have the time and inclination.

**Comment by nikolai-b** [comment]
Thanks @AnnaGoodman1 
The servers are monitored by our hosts MythicBeasts and if the site homepage doesn't load (or something else strange happens) then they will be alerted and will check what has happened.

If you log into their website we get server monitoring graphs giving a whole host of information for both servers npt1 and npt2.  I think the things to keep an eye on are:
CPU load, memory usage, disk usage (if we change things in pct-data) and network bandwidth.
At the moment
CPU is fine the load is around 50% but most of the processes are idle, memory is fine seems about 50% in use, disk usage is also fine at 43% and network is fine.  I can try to give you a monthly report if that helps.

We track events and users in https://analytics.google.com and you should be able to log in an view things.  This means if we start getting lots more users then we can see how the system performs but at the moment it is hard to tell if 100s of users will make a massive dent in our CPU and memory or be hardly noticed.

**Comment by AnnaGoodman1** [comment]
OK great,thanks @nikolai-b , very helpful.  I think that,  at least for the next four months when we have been specifically tasked by DFT to keep an eye on this, it would be great if we could check the CPU load/memory/disk usage/bandwidth every month or so. It doesn't really need report, but an equivalent of the sentence "CPU is fine the load is around 50% but most of the processes are idle, memory is fine seems about 50% in use, disk usage is also fine at 43% and network is fine." every month would be great.  If it seems like everything is always fine then we could make the check just every eg 3-4 months. 

Also any graphs from google analytics would be very good for sharing with DfT/our info - I tried looking in that the DA managed to find how to access PCT usage graphs. Perhaps at some point (not urgent) someone can show me how to do this/take a screenshot and circulate the relevant graphs.
