### ISSUE TITLE
Region is over lines in new inter-regional flows

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#578]
Please see [here](http://npct0.vs.mythic-beasts.com/m/?r=warwickshire):

![image](https://cloud.githubusercontent.com/assets/1825120/24728546/4abd86d0-1a52-11e7-9e9c-7a9334b7524e.png)

The problem is that when you are hoping to simply get info about the inter-regional flow, it switches region instead.

An easy fix for @nikolai-b I suspect ;)

**Comment by Robinlovelace** [comment]
Tested, works, great fix! From the West Mids on the test server:

![image](https://cloud.githubusercontent.com/assets/1825120/24952974/82153d66-1f71-11e7-8100-24248a9ad908.png)

**Comment by usr110** [comment]
Such a neat solution. Great, Nikolai 👍
