### ISSUE TITLE
local authority map

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#579]
sorry to raise further issues but
1) can we have a button or something to go to pct.bike (I know it should be obvious but ...) Perhaps some kind of home button? @Robinlovelace @RachelAldred @AnnaGoodman1 any views?
2) can we have link to LA report somewhere

@usr110

**Comment by usr110** [comment]
> _can we have a button or something to go to pct.bike (I know it should be obvious but ...) Perhaps some kind of home button? @Robinlovelace @RachelAldred @AnnaGoodman1 any views?_

Have added a clickable icon at the bottom right in: https://github.com/npct/pct-shiny/commit/a9a5727142405224aa8e9ace27b0a206cc453b62. 
![pct-icon-la-map](https://cloud.githubusercontent.com/assets/10958628/24796499/1440a2ca-1b85-11e7-8971-1f23d7b50a1d.png)

> _can we have link to LA report somewhere_

I would rather link the map in the report's page. Let's see what others think about it.

**Comment by usr110** [comment]
I have just now added a button which takes users to CEDAR to read the evidence briefing (see at the bottom left). If you are happy with both the tasks, I can close the issue.
Please share your comments: @JDWoodcock @RachelAldred @AnnaGoodman1

**Comment by JDWoodcock** [comment]
thanks

**Comment by JDWoodcock** [comment]
please remove from live server for now

**Comment by usr110** [comment]
Removed

**Comment by usr110** [comment]
Closed in https://github.com/npct/pct-shiny/commit/a9a5727142405224aa8e9ace27b0a206cc453b62 and https://github.com/npct/pct-shiny/commit/c459d7e7485b3d98d1bb6ca092456d65b836ebf0

Reopen if need be
