### ISSUE TITLE
Revert PCT cross-border flows from live server

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#585]
The new cross border Flows have gone live on the main PCT server – can we revert until Rachel has a chance to check/update the user manual accordingly

**Comment by usr110** [comment]
Fixed in https://github.com/npct/pct-shiny/commit/cba201dffc0d8719bdf93114fa5d8833b09dbd69

**Comment by Robinlovelace** [comment]
@usr110 fast response - note that production and master have now diverged.
