### ISSUE TITLE
Update about page

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#588]
Thanks to input from @AnnaGoodman1 and others - latest version attached.
[about.zip](https://github.com/npct/pct-shiny/files/913266/about.zip)

**Comment by nikolai-b** [comment]
@Robinlovelace I saw this an updated it, next time can we produce a diff with just the changes?

@AnnaGoodman1 please check I've not introduced an errors.

**Comment by Robinlovelace** [comment]
That was the plan but @AnnaGoodman1 @JDWoodcock and @RachelAldred requested a docx. Also, you've jumped the gun a little as I was waiting until this afternoon for feedback from others, hence tagging me. But cheers for doing it in any case.

**Comment by nikolai-b** [comment]
Sorry I should have checked, I was updating something else and thought I'd do this as well.

Also to bring up the docx format again, can we please make sure we do things as "things that have changed" and not a docx?

**Comment by Robinlovelace** [comment]
Yes - one to ask the others about - much better to use version control and PRs for sure.
