### ISSUE TITLE
Incorrect wording descibing the PCT project on the LA map

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#589]
It should say the Propensity to Cycle Tool project:

![image](https://cloud.githubusercontent.com/assets/1825120/24910887/169be3c4-1ec1-11e7-9ab4-5a5ccdc467fa.png)

**Comment by usr110** [comment]
Good find, Robin.

**Comment by usr110** [comment]
Have pushed the change onto the live-server as well.

**Comment by Robinlovelace** [comment]
:+1: : )

**Comment by Robinlovelace** [comment]
But this his not fixed on production I don't think @usr110.

**Comment by usr110** [comment]
> But this his not fixed on production I don't think @usr110.

It is. Try again.

**Comment by Robinlovelace** [comment]
Just tried again on a new window:

![image](https://cloud.githubusercontent.com/assets/1825120/24913696/da4c17fa-1ec9-11e7-8f91-3674b76bf344.png)

**Comment by usr110** [comment]
Thanks Robin - I had mistakenly used `Propensity of Cycling Tool`. Have now fixed it.
