### ISSUE TITLE
Remembering zone attribute selection when zooming in or out

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#59]
When one zooms in or out, the map forgets ones selection of 'attribute to display' (basic version) or  'zone attribute' (advanced options version).  Instead it defaults back to 'scenario level of cycling'.  For example, select advanced options > zone attribute 'none'; then increase the scale ; and the 'scenario level of cycling' colours return.  The same thing happens for 'scenario increase in cycling'

(by contrast, options for the flow attributes do seem to be remembered when one zooms in or out, if advanced options has been ticked and so flow attributes is one of the options)

**Comment by Robinlovelace** [comment]
Confirmed. Thanks for highlighting this bug Anna.

**Comment by Robinlovelace** [comment]
This also relates to a wider issue: do we even need to distinguish between slc and sic? I suspect it may be better placed in the 'advanced' tab and to use slc as default.

**Comment by Robinlovelace** [comment]
Please confirm bug @nikolai-b or @usr110

**Comment by nikolai-b** [comment]
Closing as advanced tab has been removed

**Comment by usr110** [comment]
The problem, unfortunately, still persists. If you select any scenario other than "census 2011 cycling", and then select "Science Increase in Cycling (SIC)". After this when you change your map center (by navigation) or zoom, the attribute to display changes to "Scenario Level of Cycling (SLC)".

**Comment by usr110** [comment]
May have fixed it by: https://github.com/npct/pct-shiny/commit/c79dac3f8a4a04f03f372dffb04249c68c990e25. Please try it first. If everything seems ok, we can then close the issue.

**Comment by nikolai-b** [comment]
Thanks ali, lgtm

**Comment by usr110** [comment]
@nikolai-b great, thanks
