### ISSUE TITLE
Put interregional lines on production

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#590]
- [x] Test downloaded lines
- [ ] Signed contract
- [ ] Document in manuals + model output
- [ ] Add in 'new features' linking to a blog if possible
- [ ] Push live
- [ ] [for the future] Rebuild the route network - #584

**Comment by Robinlovelace** [comment]
Update on this - the new inter-regional flows should be on the test server now.

**Comment by AnnaGoodman1** [comment]
Will appear in new version (thanks Robin)
