### ISSUE TITLE
local authority map downloads

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#591]
please can we have the %s visible in the interface available in the spreadsheet/ csv file

**Comment by nikolai-b** [comment]
Sorry I'm not sure what you referring to.  Would you mind adding a screen shot as I don't know what
> %s visible 

means.  Also I don't which csv file, would you mind adding an example csv file with the additional column?

**Comment by usr110** [comment]
Nikolai, James is referring to the newly calculated variables in the map. See these lines:
https://github.com/npct/pct-shiny/blob/master/regions_www/la-map.html#L419-L431

James. I have just created new variables (`39` new variables). See them here:
https://github.com/npct/pct-shiny/blob/master/regions_www/laresults.csv

There are three sets of new variables created:

1) Suffix `_pert` contains percentage (`values / all * 100`)
2) Suffix `__deaths_per_10k` contains death savings per 10k commuters
3) Suffix `_co2_savings_per_10k` contains co2 savings per 10k commuters

@JDWoodcock if you are happy with the names I will include them in the codebook. (@AnnaGoodman1 you too might be interested in it.)

**Comment by JDWoodcock** [comment]
thanks this looks good but suggest perc or percent is better than pert.

**Comment by usr110** [comment]
Thanks James. Replaced `_pert` with `_percent`

**Comment by usr110** [comment]
Fixed in https://github.com/npct/pct-shiny/commit/7a7923de970ae4f25264ffbbbebb2f356bbdf96f and https://github.com/npct/pct-shiny/commit/bc4bb95fe91800d0823998bc3be1027ceaa14fd8
