### ISSUE TITLE
Linking back to main tool from LA map

### ISSUE THREAD

**Issue by OCSFrancis** [npct/pct-shiny#592]
It would be good to have the following on http://www.pct.bike/la-map.html

- A link back to the main tool http://www.pct.bike/ (At the top? Could read "Visit the full Propensity to Cycle Tool"

- A link from the right hand key under the different scenarios: "Find out more about these scenarios" Link to http://www.cedar.iph.cam.ac.uk/resources/evidence/eb-14-englands-cycling-potential/#4scenarios ?

**Comment by usr110** [comment]
Thanks @OCSFrancis for raising the issue.

> A link back to the main tool http://www.pct.bike/ (At the top? Could read "Visit the full Propensity to Cycle Tool"

I don't know if you noticed that there's already an icon on bottom right which takes users to pct.bike.
Did you mean to add another link on top of it?

> A link from the right hand key under the different scenarios: "Find out more about these scenarios" Link to http://www.cedar.iph.cam.ac.uk/resources/evidence/eb-14-englands-cycling-potential/#4scenarios ?

What about a tooltip which shows such info? Or perhaps an expandable pane which has more information.

**Comment by OCSFrancis** [comment]
I didn't spot that square at all. And we shouldn't assume that people who come to this map already know about the PCT, so I think it's worth spelling out. It doesn't have to be at the top - it could be along the bottom where the current icon is.

A tooltip/ expandable pane would be even better - good idea.

**Comment by usr110** [comment]
> ..so I think it's worth spelling out

It already says `Propensity to Cycle Tool (PCT)` there. Can you expand on it?

> A tooltip/ expandable pane would be even better - good idea.

Great, thanks. Had that in my mind. Will work on it.

**Comment by OCSFrancis** [comment]
I'm not seeing that at all. I don't know how to add images on GitHub, so I'll email you as screen grab

**Comment by nikolai-b** [comment]
At @usr110 I believe this is fixed, please re-open if I'm mistaken

**Comment by usr110** [comment]
@nikolai-b haven't completed it yet. Needs to deal with tooltips/pane for additional info for both scenarios and variables. If you get the chance, would you have a look at it? I will provide the required text.

**Comment by usr110** [comment]
In addition to the logo with text at the bottom right position, I've added an information pane (right below the variables) @OCSFrancis. Have a look at on our [test-server](http://npct0.vs.mythic-beasts.com/la-map.html). What do you think? @nikolai-b your inputs would be valueable too.

**Comment by Robinlovelace** [comment]
This is much better Ali, many thanks. Good to go onto production I'd say!

**Comment by OCSFrancis** [comment]
I agree - looks good to go live.

**Comment by usr110** [comment]
Great!
Closing the issue then.
