### ISSUE TITLE
MAnchester feedback

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#6]
Area numbers are wrong (2 orders of magnitude) in interface

**Comment by RachelAldred** [comment]
yup

**Comment by JDWoodcock** [comment]
In scenario for Go Dutch numbers going over 100% for cycling potential

**Comment by JDWoodcock** [comment]
In scenario for Go Dutch numbers going over 100% for cycling potential

**Comment by Robinlovelace** [comment]
Fixed with updated [load.R script](https://github.com/npct/pct/blob/master/loading-data/load.R), illustrated in this commit: https://github.com/npct/pct-shiny/commit/28acb44ec6dd27d1c1a24285a876e64cb5fe06a2
