### ISSUE TITLE
pct wales

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#601]
http://npct0.vs.mythic-beasts.com/shiny_interface/?r=wales
on firefox and chrome I am just getting disconnected from the server reload straight away and repeatedly.
@usr110 @AnnaGoodman1 @Robinlovelace

**Comment by nikolai-b** [comment]
I believe this was due to us merging #596 too early

**Comment by Robinlovelace** [comment]
I don't think so @nikolai-b - I think Ali worked on this after the merge.

**Comment by usr110** [comment]
Sorry but no; nothing to do with `npct/pct-shiny` here. `shiny_interface` is using `pctbike/pct-shiny` repo - more specifically [`server` branch](https://github.com/pctbike/pct-shiny/tree/server).
It was a data issue, which I had fixed. Now the changes @nikolai-b is making has again made the app to not work, so I am not closing the issue.

**Comment by Robinlovelace** [comment]
Apparently that website will no longer be affected by changes to the repos thanks to @usr110 - any updates on that? I've also tried to use that site but it ain't working. On a different note, great work @nikolai-b it seems the test server is working again!

**Comment by Robinlovelace** [comment]
Ah OK sounds good Ali cheer for the update. I suggest we can close this and use the test server.

**Comment by nikolai-b** [comment]
@usr110 what is the https://github.com/pctbike/pct-shiny repo for?

I am not able to support things that I am not told about so sadly changes will be made to the server that are likely to break apps that are rely on things outside their own repo (other than `pct-shiny`).

**Comment by AnnaGoodman1** [comment]
sorry @nikolai-b , pctbike was a temporary test organisation I set up over the summer when I was very new to Github (e.g. did not net know how to do pull requests (I am still a bit hit and miss!)) and didn't want to start breaking things on npct, so found it easier to practice on a test organisation where I always just pushed to master.  And Ali then kindly created a temporary app/link pointing to that so we would have something to show DFT for the nominal deadline and of July. pctbike & all repos is now completely obsolete, I plan to delete it by the end of the week.
