### ISSUE TITLE
PCT-Wales banner

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#605]
In this pull https://github.com/npct/pct-shiny/pull/600 , in file regions_www/m/ui.R line 65:

wwe need a flag to identify whether the region is Wales (TRUE) or not (FALSE).  I hope one can do this by e.g. doing a grep on the URL? but I could not work out how to do that, so for the moment I just put some place-holder code where it is set to always be True that the region is Wales

**Comment by nikolai-b** [comment]
Done
