### ISSUE TITLE
Possible to change to all-trips after changing region

### ISSUE THREAD

**Issue by nikolai-b** [npct/pct-shiny#608]
Minor bug but it is possible to change to all trips after selecting a new region (where it doesn't exist)

![output](https://user-images.githubusercontent.com/6289830/30086204-f72a7fb0-9291-11e7-8ea4-e25bcaf1bd4e.gif)

**Comment by Robinlovelace** [comment]
Minor quirk linked to previous issue. This only happens for a second or so (while the new region loads) right?

**Comment by AnnaGoodman1** [comment]
okay right, sorry,I had not noticed this ( I think maybe my computer is too slow to ever have let me do that!) . I think your new code is fixing this?  many thanks

**Comment by nikolai-b** [comment]
@Robinlovelace nope, this causes the server to crash.

**Comment by Robinlovelace** [comment]
@nikolai-b Thanks for the clarification!

**Comment by Robinlovelace** [comment]
P.s. can see the crash now right at the end of the gif - but yes would have been better to be explicit.
