### ISSUE TITLE
Possible to change purpose before region loads

### ISSUE THREAD

**Issue by nikolai-b** [npct/pct-shiny#609]
Probably the same fix as #608 but logging for completeness.

It is possible to change the purpose as a the map loads:

![school](https://user-images.githubusercontent.com/6289830/30086360-a470ebb4-9292-11e7-9cc5-60e0a0620230.gif)

**Comment by Robinlovelace** [comment]
Just to clarify, what's the problem from the user's perspective of this behaviour?

**Comment by nikolai-b** [comment]
@Robinlovelace sorry I didn't add but at the end of that gif you can see the screen goes grey and the server crashes, that is the problem.

**Comment by Robinlovelace** [comment]
@nikolai-b cheers for the clarification and see that was a major issue now.
