### ISSUE TITLE
website now basically live so need the following 

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#61]
hi all,
the website should now be considered live as link has been made public so we need to do a few things
1) we need a note on the front saying this is a prototype and we accept no liability. This should then be repeated in more detail on the Help Page or Information page. This is really important. It should say Prototype Cycling Planning tool.
2) We need to be clearer on the copyright. Currently I see this on the 'model ouput' tab ;'The model driving the NPCT is licensed under the open source MIT License and can be modified by others provided attribution to the original.' At the minimum this needs a link to the MIT licence. But I think this better goes on the help page or on a new more information page. I also find it a bit confusing as I understand we are using  licence that does limit for profit use. 
3) DfT logo should be added but not until we have put up prototype no liability.
4) We should have a more Information page. This should contain
 a) information saying this is a dft funded project
b) link to CEDAR website on project & other sites as they come on line
c) summary of team members
5) there are a couple of minor things need editing on the Help page - notes in bold, I put these in I know so my apologies but dont have time to fix them. Please can someone fix or at least remove them.
6) it should then be sent to Shane to check he is happy 

thanks,

**Comment by JDWoodcock** [comment]
sorry also meant to add 
7) we should have an email address set up that we can access as a group & we should put this on the Information page

**Comment by Robinlovelace** [comment]
@nikolai-b are you on this?

**Comment by nikolai-b** [comment]
I've some time on Sunday.
@JDWoodcock I don't understand:
>  I also find it a bit confusing as I understand we are using licence that does limit for profit use.
Are you unhappy with using the MIT licence?

> there are a couple of minor things need editing on the Help page - notes in bold, I put these in I know so my apologies but dont have time to fix them.

With the Government Cycling Delivery plan I will use [the paper](https://github.com/Robinlovelace/pct/blob/1e6180b74a2929da455404be7a97df43d772a4dd/flow-model/flow-model.Rmd#government-target) as an outline and ideally it will link to it when published.

**Comment by nikolai-b** [comment]
So this is basically done.  I've not set up an email as I don't have access to anything sounding professional ( npct@gmail.com doesn't look good ).  I suggest that someone gets an institutional one.  The summery of team members is just a list of names.  If you can add it directly [here](https://github.com/npct/pct-shiny/blob/master/master/help.html#L7) or send it to me.  Do you want me to push it to the website so you can check it @JDWoodcock (it does have the DfT logo now).

**Comment by Robinlovelace** [comment]
Sounds good. Will wait to see what James says but I'd imagine putting the logo on the front page would also be good if you could find a way to make it work. I tried a while back and couldn't!

**Comment by usr110** [comment]
@nikolai-b Great work! It seems all of the points have been looked after. Let me know if you require any assistance.
@Robinlovelace I agree with you on this. I was looking at an app which has a logo on its bottom left. I believe we too should have the same. See here

http://www.mappinggm.org.uk/gmodin/

What say?
As far as my information goes, I believe, leaflet's library doesn't allow logos to be added. Do you guys happen to know a solution for it?

**Comment by usr110** [comment]
How does this look:

https://github.com/npct/pct-shiny/commit/8f69fbae68efe8c6a44e7ce088e928ecb20b4b6b

The quality of images is not that great, but I believe, this is the right place to put the logos. What do you guys think?

**Comment by JDWoodcock** [comment]
hi all,
thanks- 
1) on my laptop the dft logo on the front and the smaller one on the more info page look off centred and stretched. The more informatoin page is also oddly laid out with log overlapping the team information
2) The 'more information' and the older 'help page' should be 2 separate pages. The help page can go back to previous (the minor corrections having been made). The more information page can be minimal for now- I would add in the line " The NPCT will be launched for England in June 2016". I would also like to see all our names hyperlinked to our work home pages e.g. for me here http://www.cedar.iph.cam.ac.uk/people/leads/james-woodcock/ The CEDAR weblink would be better here http://www.cedar.iph.cam.ac.uk/research/modelling/npct-tool/
thanks,

**Comment by JDWoodcock** [comment]
hi 
has anyone bought any npct domain addresses? If not I will buy npct.org.uk (https://iwantmyname.com/?domain=NPCT.org)

**Comment by Robinlovelace** [comment]
sounds great. Thanks @JDWoodcock

**Comment by Robinlovelace** [comment]
![selection_313](https://cloud.githubusercontent.com/assets/1825120/9543181/a4317a44-4d6e-11e5-84ed-984d7ebd50be.png)

It's getting there but the tab has a weird name beginning with <div> and the image is not there - in some ways I prefer the text link to DfT anyway. Any ideas @usr110 or @nikolai-b ? Think I pushed the latest version.

**Comment by usr110** [comment]
@Robinlovelace I've fixed the title of the Window (tab) and also reintroduced width and height of the logo. Please readjust the position of it - https://github.com/npct/pct-shiny/commit/bcd6da4d22885db5f8ded2a96f7607464702437f
As for the logos not appearing on the server, please make sure that the image files exist within the asset folder.

**Comment by Robinlovelace** [comment]
Hi @usr110 it's still looking very sketchy (squashed) on the live server: 
![selection_314](https://cloud.githubusercontent.com/assets/1825120/9554051/1461700c-4dbb-11e5-97be-5791a263ba4d.png)

Not sure why - the .gif file (which seems to have been deleted by ed8afe1 ) looked good to me locally. @nikolai-b are you pushing these changes to the server? Could you give user@geo8 rights in the /srv/ folder so I can push these changes out?

Getting there in any case!

**Comment by nikolai-b** [comment]
That should be fixed but I'm unsure why it was broken. It it happens again
could you wait till I've had a chance to look so I can dig fir the
underlying issue (so long as it is critical). You should not have rights in
/srv  by the way, that should only be for user shiny. I plan to put "funded
by the dft " below the map later today.

**Comment by Robinlovelace** [comment]
I think this is basically done so ready to close. These ones are semi done but easy to complete:

1) **Summary of team members** - please update here: https://github.com/npct/pct-shiny/edit/master/master/help.html


2) **there are a couple of minor things need editing on the Help page - notes in bold** - are these done? 
 
6) **it should then be sent to Shane to check he is happy** @JDWoodcock please do this and close. He's happy with the paper so should be no probz.
