### ISSUE TITLE
Is national data needed?

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#611]
I am talking about this line:

https://github.com/npct/pct-shiny/blob/master/regions_www/m/server.R#L32

If you want to run the app, you need to clone the `pct-outputs-national` repo - is it really needed at this point in time? Also I don't see the variable `data_national_root` being used at all. See here: https://github.com/npct/pct-shiny/search?utf8=%E2%9C%93&q=data_national_root&type=

**Comment by AnnaGoodman1** [comment]
thanks Ali, I agree it is  not needed and I think Nikolai has got rid of it in this pul request https://github.com/npct/pct-shiny/pull/606/files#diff-e742b53b5986fdf6e52477865d38ea79

**Comment by usr110** [comment]
Great thanks, @AnnaGoodman1
