### ISSUE TITLE
planning to delete pct-outputs-regional and pctbike organisation– any objections?

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#612]
I am planning to delete
repository: npct/ pct-outputs-regional [now split to pct-outputs-regional-R / pct-outputs-regional-notR]
and
organisation: github/pctbike

I think neither are needed any more  by us, and so no point paying for the LFS storage. @usr110 , @nikolai-b , @Robinlovelace I assume this is okay with you all – unless I hear any objections I will do this by the end of the week.

**Comment by Robinlovelace** [comment]
All good, thanks for the heads-up.

**Comment by Robinlovelace** [comment]
Oh OK will re-open and let you close when it's done probably better.
