### ISSUE TITLE
Getting in a loop if changes made too fast

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#613]
if you open one of the bigger regions, e.g. Wales or London,  and then immediately change both  middle layer to lower layer geography  plus change the scenario to e.g. go Dutch then it gets into a loop where it flicks between the census 2011 scenario and the new scenario. (See video in zip folder). This only happens, I think, in the big regions because in the smaller regions the app deals with the geography switch fast, before you have time to make the  scenario switch.  it happens both on internet edge and firefox. It only happens if you first switch geography (which is slow, as files need to reload), and then switch scenario (which is fast) – not the other way round

Ideally the app would handle making both changes simultaneously, or if not then at least force a revert to the current scenario – being a loop between the two seems the worst of all worlds... Would there be some way to force the app not to accept any input on the ui menu until the geography-switching was complete?

[video.zip](https://github.com/npct/pct-shiny/files/1283835/video.zip)

**Comment by AnnaGoodman1** [comment]
you get the same issue if you switch middle to lower layer and then change from having no line showing to having e.g. fast and quiet lines showing – again the lines get into a loop of flashing on and off

**Comment by Robinlovelace** [comment]
![peek 2017-09-08 09-00](https://user-images.githubusercontent.com/1825120/30201915-569d3db4-9474-11e7-9e33-a6c8818b2e41.gif)

**Comment by Robinlovelace** [comment]
Initially I thought this bug was minor but I've tested it and it seems easy to put it in a loop so I think this is a priority to fix. Reproducible example above. Many thanks for testing Anna - agree one to

**Comment by AnnaGoodman1** [comment]
instead of getting in the loop, it now briefly shows the newly selected scenario but then reverts to the original scenario and stays there - i.e. forces people to select the new scenario a second time.  I think this is good enough to be going on with, so suggest we close this issue for now (but if we ever find a way to handle these changes even more gracefully that will be great)
