### ISSUE TITLE
Add network analysis

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#62]
High demand for this. We now have the data and methods to do this.

@nikolai-b are you up for this?

Script to make the data:
https://github.com/Robinlovelace/pct/blob/master/analysis/rnet.R

The data:
https://github.com/npct/pct-data/blob/master/leeds/rnet.RData

Example of how this looks:
![selection_298](https://cloud.githubusercontent.com/assets/1825120/9298808/d46cf442-44ac-11e5-9eb9-e7114c6f5e34.png)

**Comment by Robinlovelace** [comment]
@nikolai-b we can now work on this: the complete network with all slc scenarios is now available for Blackpool, thanks to this: https://github.com/npct/pct/commit/fab9ea9e9ff1d28d4d59c65c6ba85b76a02c240a

Blackpool data: https://github.com/npct/pct-data/blob/master/Blackpool/rnet.Rds

**Comment by usr110** [comment]
@Robinlovelace I've added a  basic infrastructure of network analysis, which does following things:
1. Shows network analysis only when the user selects it
2. Shows network analysis on the focussed region only - (when freeze is unchecked)
3. Introduced a pop by to display baseline_OLC as an example. 

Things to do:
1. Introduce a new slider - as we discussed earlier
2. More useful popup info - your comments will be required there.

Need your feedback on this. You can see the updates here - https://github.com/npct/pct-shiny/commit/cef4d3c91bd3791ef4e782df6613b00cbdfebcfe and https://github.com/npct/pct-shiny/commit/e98fa839158680ad5e7d02520518a84da579ce95.

**Comment by Robinlovelace** [comment]
Hi @usr110, this is great progress. Many thanks for the changes, which we have built on, and the clear communication. @nikolai-b and I worked on this today and have built on your work, with this and subsequent commits, pushed to production: https://github.com/npct/pct-shiny/commit/ef6ea9e13742d0d34d38965318a8d3ad72c0fa0c 

Please take a look: I think it's looking great!

I agree we could make the popups better but the scenario dependent data is in there and that's most important one probably. I think we fixed the slider issue - we need to update the help pages to explain that the n lines is actually % in the network analysis.

@JDWoodcock I'm closing this issue now as the network has definitely been added thanks to a team effort from everyone. Please re-open specific issues. I'm about to add an issue allocated to @nikolai-b despite his new job commitments ;-)
