### ISSUE TITLE
non-urgent issue - geographies not updating

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#620]
as @Robinlovelace points out, there is now a bug  with switching geographies:
1. Go to Manchester on the test server and select LSOA layer (purpose = commuting)
2. Switch the purpose to 'all trips'

On the screen, the zones correctly update to now be showing MSOAs.  However the geography is still shown as LSOA (see below), and LSOA is also given as an option on the drop-down menu when one firsts switches to all trips.  

I think I have found the problem, which is that the list of geographies needs to update if the purpose changes, and I fixed it here: https://github.com/npct/pct-shiny/pull/619 . @Robinlovelace / @Robinlovelace / @nikolai-b , could you test and merge if you are happy with this?

![untitled](https://user-images.githubusercontent.com/11818225/30322174-7d1be5c8-97b0-11e7-9fee-0d4fbb1757ad.png)

**Comment by Robinlovelace** [comment]
Thanks for finding and fixing this Anna.
