### ISSUE TITLE
Testing banner is on in production

### ISSUE THREAD

**Issue by nikolai-b** [npct/pct-shiny#623]
On www.pct.bike the testing banner is always on

**Comment by Robinlovelace** [comment]
I'm not sure it is always on - there was a thread on this and @RachelAldred, @AnnaGoodman1 and @JDWoodcock seemed to think it was fine. Could you provide a screenshot of when it is on (maybe browser-specific). See here for an example on Chrome (also tested on Firefox) just now:

![image](https://user-images.githubusercontent.com/1825120/30363299-84d8720c-9857-11e7-8025-523bd8f0dbef.png)

I'm sure merging this will do no harm but just want to know what's going on - understand the logic but not what will change as a result of merging this to master.

**Comment by AnnaGoodman1** [comment]
I have not ever seen the test banner on the main PCT site, but like Robin it seems a good idea to me to do this merge if it fixes an occasional bug

**Comment by nikolai-b** [comment]
The issue is the site could be accessed via `www.pct.bike` or `pct.bike`

`www.pct.bike` would not show a test banner but `pct.bike` does

![screenshot from 2017-09-13 18-42-51](https://user-images.githubusercontent.com/6289830/30392065-8ee65802-98b3-11e7-80d2-75222e5294c5.png)

**Comment by Robinlovelace** [comment]
Ah yes - just saw that. Thanks for the explanation and the fix.

**Comment by RachelAldred** [comment]
Is it fixed? I'm seeing it for pct.bike still.

**Comment by Robinlovelace** [comment]
Yes but I'm waiting until midday to push to production and waiting on @nikolai-b.

**Comment by RachelAldred** [comment]
OK sorry!
