### ISSUE TITLE
where are the centroids?

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#626]
when I run the app locally then I see the centroids, but they are not there on either the test server or the live server, at the equivalent zoom level (see below).  Not sure why this could be – assuming the code is identical, my only thought is could the c.Rds files in pct-outputs-regional-R somehow not have been copied across to the server?
![untitled](https://user-images.githubusercontent.com/11818225/30367596-8f6904f2-9866-11e7-96af-6267ce5bad2a.png)

@Robinlovelace / @nikolai-b , not sure if either of you could check this?

**Comment by Robinlovelace** [comment]
Well spotted - I confirm they are not there.

**Comment by Robinlovelace** [comment]
Update: they are not there on my local instance either.

**Comment by Robinlovelace** [comment]
Do you have the latest version of the repo? I'm on the master branch.

**Comment by AnnaGoodman1** [comment]
thanks Robin: yes I'm on the master branch in pct-shiny, having updated it, and I do still see them in my local run.  When you have time, you could perhaps check if the c.Rds are present in your local copy of pct-outputs-regional-R (they should be : see e.g. https://github.com/npct/pct-outputs-regional-R/blob/master/commute/msoa/avon/c.Rds).  If they are, but it's still not working locally few, then that seems strange indeed...

**Comment by AnnaGoodman1** [comment]
Okay sorry, I was wrong, I was still seeing the centroids locally after updating pct-shiny... But now don't. so maybe one of them more recent changes, I will see if I can work out what is going on

**Comment by AnnaGoodman1** [comment]
sorry, I think what I said before about being able to see the centroids locally was just a mistake – I could only see them because I was printing 'input$map_zoom' as a test (but one that fixed the problem!).  So actually I think this problem may have been therefore while, probably introduced by me.  This maybe fixes it, splitting up the zones and centroids 'observe' commands: https://github.com/npct/pct-shiny/pull/627 . As I check it it seems to work, but would be grateful if @nikolai-b / @Robinlovelace could also look and confirm they are happy that this won't break something else I haven't thought of

(NB the reason one can't just observe 'input$map_zoom' in the original combined zone/centroid function is this issue https://github.com/npct/pct-shiny/issues/597 of zones refreshing every time you change the zoom level)

**Comment by AnnaGoodman1** [comment]
final clarification (!)  of what I think the issue is: It is possible to see the centroids on the test/live server at the moment, but only if you zoom in to the required resolution *and then also change something else*, e.g. geography, purpose, region or scenario.  Just zooming in – or zooming out – by itself is (incorrectly) not enough to make the centroids update to showing/hiding, because input$map_zoom is isolated and not observed by the current combined zone-and-centroid function.  My pull request fixes this, but perhaps there is a simpler solution.

**Comment by Robinlovelace** [comment]
Thanks for the clarification - sounds spot-on. Good for @nikolai-b to see this also - pls merge if you're happy with this Nikolai.

**Comment by AnnaGoodman1** [comment]
pull reqest acceped, so closing this
