### ISSUE TITLE
CSV area level downloads?

### ISSUE THREAD

**Issue by RachelAldred** [npct/pct-shiny#632]
Hi, I can't see any CSV level regional or national downloads...(also a minor query, on our HEAT popups the legends says tonnes of CO2 but I think should be kg, which is what the codebook says?)

![image](https://user-images.githubusercontent.com/11818218/30476682-a45e153a-9a02-11e7-81e7-08e7501e2197.png)

**Comment by RachelAldred** [comment]
sorry, I meant CSV zone downloads.

**Comment by RachelAldred** [comment]
Ah, I realise this is in progress, so I think my only question is about tonnes/kg CO2. Apologies - I assumed I was ok to update the manual this week, but should have checked on pending updates. Will finish the manual off next week when I can do the new screenshots.

**Comment by AnnaGoodman1** [comment]
Hi @RachelAldred , I think it is correct as it is – you're right that we use tonnes in the interface and kg in the downloads, but the numbers are the same (i.e. download numbers are x1000 the interface numbers).  I think it was a trade-off between wanting to give the raw results in the downloads but limit the number of decimal places/make numbers easy to read in the pop-ups.  Will close this, but please reopen if I've missed something
