### ISSUE TITLE
Scale bar issues in Chrome

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#635]
There are issues with the scale bar on at lease some versions of Chrome.

Less serious, on `Version 61.0.3163.100 (Official Build) (64-bit)`  is that the scale bar is not vertical:

![image](https://user-images.githubusercontent.com/1825120/31236770-f795bb14-a9ec-11e7-9dc8-433fb761cee1.png)

@mem48 and @AnnaGoodman1 have identified another issue that's more serious.

**Comment by AnnaGoodman1** [comment]
yes, we had the same basic issue but a greater corription of the scale bar to point where unuseable.  I get what Robin has on my laptop, but @mem48 can perhaps screenshot what he had on desktop

**Comment by Robinlovelace** [comment]
It was a total red bar.

**Comment by Robinlovelace** [comment]
Problem (Google Chrome is up to date
Version 61.0.3163.100 (Official Build) (64-bit)):

![image](https://user-images.githubusercontent.com/1825120/31574592-bd88f0d2-b0ca-11e7-9e9a-7cd7c6bbf4e2.png)

**Comment by Robinlovelace** [comment]
Next step towards a solution: test on a recent version of RStudio/leaflet to see if that fixes it. I wonder if it's related to this as some of the colours appear as you change the size of the browser window: https://github.com/rstudio/leaflet/issues/248

**Comment by Robinlovelace** [comment]
Update: this also affects the front page map - not good:

![image](https://user-images.githubusercontent.com/1825120/31574665-d5d5c0ba-b0cb-11e7-9ac5-5f29428fea9f.png)

**Comment by nikolai-b** [comment]
I've tried in the latest Chrome
(64.0.3282.140 was released 2018-02-6)

![screenshot from 2018-02-28 19-47-08](https://user-images.githubusercontent.com/6289830/36809582-33ae3eb4-1cc0-11e8-92bc-041449b19934.png)

and in the version @Robinlovelace posted

![screenshot from 2018-02-28 19-59-20](https://user-images.githubusercontent.com/6289830/36810205-f3718a02-1cc1-11e8-8c52-1e4ed9440d82.png)

but it works fine for me.  The scale bar is aligned (on the region page) and the map scale is multi coloured on the front page.

Without being able to reproduce this locally I don't think I can help much, sorry.

My guess is that its a graphics driver issue if disabling hardware acceleration fixes it: https://github.com/Leaflet/Leaflet/issues/5841#issuecomment-338138289

If it is still in the newest version of Chrome have you raised a bug with them?

You will need to create a minimal reproducible example as no one will want to go thought all the html to find out what is causing the issue.

This is a striped down version of the scale bar: [map.html](https://github.com/npct/pct-shiny/files/1768684/map.html.txt) does it work on your Chrome version?

If it doesn't then that is a great place to start!  If it works then we will need to add more elements into the mix to find out which one is the culprit.

**Comment by mvl22** [comment]
Probably this is due to font size setting in the browser being slightly higher. Try pressing Control-plus and you will see the problem.

**Comment by AnnaGoodman1** [comment]
yes, weirdly it seems to flip between working and not working as one increases the zoom – for me it is find at 100%, not fine at 110% or 125%, fine at 150%, not fine at 175% etc [this is version Version 64.0.3282.186 (Official Build) (64-bit)].  I can't replicate the bar-completely-red issue, though I do remember it 

![100](https://user-images.githubusercontent.com/11818225/36832780-d6a4f1d0-1d24-11e8-8849-fce2645f2bf5.png)
![125](https://user-images.githubusercontent.com/11818225/36832783-d8691776-1d24-11e8-9af3-2781843c250c.png)
![150](https://user-images.githubusercontent.com/11818225/36832807-ef47a48a-1d24-11e8-8838-0eac70cbcecf.png)

**Comment by usr110** [comment]
Cool fix @nikolai-b :+1:
