### ISSUE TITLE
Title (for URL bar / search results) does not state area

### ISSUE THREAD

**Issue by mvl22** [npct/pct-shiny#636]
http://pct.bike/m/?r=isle-of-wight

has

`<title>Propensity to Cycle Tool</title>`

but it would be more useful, for back/forward navigation, for this to be

`<title>Propensity to Cycle Tool - Isle of Wight</title>`

**Comment by Robinlovelace** [comment]
I don't think this is that important but would be nice. Bigger impact but harder feature would be to save the current state of the pct in a URL in a makeshift API but I don't think that' worth doing.

@nikolai-b is the current issue easy to do (less than a couple of hours)? If not I suggest we close and add the for future tag.

**Comment by mvl22** [comment]
Key benefit of this is that it will then show up in Google search results, assuming there exists a spiderable link to the region.

**Comment by Robinlovelace** [comment]
Thanks for the explanation - hadn't thought of that. Now I better understand why you were badgering about it!
