### ISSUE TITLE
Do tiles for Wales

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#647]
@nikolai-b: I have created a release of the England plus Wales raster .tif files here: https://github.com/npct/pct-inputs/releases/edit/untagged-c6cfec2972276d2c500b 

There are 15 files, for the five scenarios * 3 different resolutions for different levels of zoom (e.g. ‘-50’ is a cell size of 50m2. The ‘-10’ version is also available regional/national download files for users).  If I understood correctly from Malcolm these are what you will need to create the tiles that are served for the LSOA raster layer, but let me know if you need anything else or I can provide them in a more helpful format. 

I think the code you will use for this has now been archived here: https://github.com/npct-archive/pct-lsoa-vis - but actually (sorry) it should probably be unarchived and moved back to npct, since it is still in use? Or if only the files in pct-lsoa-vis/generate/ are needed and not those in pct-lsoa-vis/zones/ then perhaps it could be added as an additional step in npct/pct-scripts, e.g. as files prefixed with 10a_, 10b_, 10c_ ?

Obviously good if you can keep a copy of the current England-only tiles somewhere, in case anything goes wrong and we need to avert.  Otherwise it will be fine to switch to having the England+Wales tiles being what the server is deploying as and when those are available.  I have done some checking of what I created, so hope it is all okay, but can do some more checking when the tiles are up on the test server

**Comment by nikolai-b** [comment]
I'm not sure where the cross over between the zoom levels and cell sizes was that @mem48 used.

The 10m<sup>2</sup> files should be able to generate the whole lot but they didn't look so good when zoomed out so @mem48 re-did the zoomed out levels (hence the 50m<sup>2</sup> & 100m<sup>2</sup>).  The tiles are done at [zoom levels](https://wiki.openstreetmap.org/wiki/Zoom_levels) 15 - 5.  I'll generate the lot from the 10m<sup>2</sup>  and then we can re-asses.

**Comment by AnnaGoodman1** [comment]
in my notes from working with Malcolm I wrote "10 is for zoom 11-19, 50 is zoom 9-10, 100 is zoom 1-8" [from what you say, it may instead be that the limits are 5-15, not 1-19].

My impression of the workflow– but quite possibly wrong – was that Malcolm had provided you with these different zoom levels , and you then tiled each of them separately. But of course if you can do everything yourself from the 10m2 ones then that is also fine

**Comment by AnnaGoodman1** [comment]
@nikolai-b , okay I see that you have actually already done the Welsh tiles, and they look brilliant.  Just so I can make a note about the correct workflow for next time, did you make use of the 10m/50m/100m files I provided from last time? Or in future would you just want the 10m ones and you do everything from their?

**Comment by AnnaGoodman1** [comment]
@nikolai-b , I realise I don't think I ever heard from you on this – did you use the 50m/100m files I provided? Or in future would you just want the 10m ones and you do everything from there? I will update my "how to do this" notes accordingly...
