### ISSUE TITLE
Page layout gets disturbed by model output

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#65]
I don't know if you noticed this or not, but once the tool starts, its layout remains stable as long as you don't click on the "model output" tab. The moment you click on it, the whole layout gets disturbed. Please see the image below:
![disturbed-layout-model-output](https://cloud.githubusercontent.com/assets/10958628/9602033/4f868566-509d-11e5-92d0-0301f3bf0c29.png)

Any ideas what's going on here?

**Comment by Robinlovelace** [comment]
Thanks - will look into it. @nikolai-b has pointed out similar problems and may help me with fix.

**Comment by nikolai-b** [comment]
Fixed in https://github.com/npct/pct-data/commit/80db63c and https://github.com/npct/pct/commit/664e4ac
