### ISSUE TITLE
PCT blog seems to be down

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#662]
Is this a known issue, @RachelAldred ?

@npct/admin

**Comment by usr110** [comment]
Ah ok, thanks @RachelAldred 

If I am not mistaken, this might be useful here: https://en.support.wordpress.com/domains/

Seems like default setting comes with one free domain credit. 

Have you added multiple domains to your blog? May be that's what creating this issue? Any ideas @nikolai-b ?

**Comment by mvl22** [comment]
An article about the PCT, which directly references the blog, is about to be published by Camcycle. I've been asked to flag that here.

**Comment by mvl22** [comment]
The blog points to the subdomain blogpctbike .wordpress .com.

I'm sure if you just message them they'll help you get this sorted ASAP.
https://en.support.wordpress.com/live-chat/

**Comment by RachelAldred** [comment]
Thanks. So it's not the blog that's down, it's the pointing to it. From memory I set up the blog and @nikolai-b set up the pointing to it on the PCT site, although I may be wrong on this. There are working links, but not on the site - so from the webpage https://blog.pct.bike/2018/03/16/launch-of-the-pct-for-wales/ no longer works, but https://blogpctbike.wordpress.com/2018/03/16/launch-of-the-pct-for-wales/ works fine, so @mvl22 - might you be able to include the working link in your blog? As we may not fix it in time. Anyway I will ask wordpress.

**Comment by RachelAldred** [comment]
Oh I would need a paid plan to access the support. I'll look into what might have gone wrong with the domain mapping later in the week.

**Comment by nikolai-b** [comment]
@RachelAldred from memory we needed to be on the paid version of WordPress to have domain mapping so maybe or subscription just expired. 

If there is something wrong with the domain that was registered with https://www.enom.com/ @JDWoodcock should have access (I did have access but I think I've either recorded the details incorrectly or something there has also expired)

**Comment by mvl22** [comment]
How's this going? As I said, an article linking to this is about to come back from the printer.

Sounds like you simply need to renew the paid Wordpress plan.

**Comment by RachelAldred** [comment]
Hi Martin, yes I think it would involve paying for another sub and then setting up the mapping again. Not sure what other team members think, but I am a bit loathe to pay myself for an upgrade while we are still waiting for funding to come through to maintain and develop the PCT. As I mentioned, the blog is still online and can be linked to so it's not like info is missing, it's just the mapping that is currently down. Hopefully the funding issue will be resolved soon and we can get this (and a few other minor pending issues like IMD tiles) fixed.

**Comment by nikolai-b** [comment]
I'm closing as the http://blog.pct.bike/ is now back up!  There is an issue but I'll open a new one
