### ISSUE TITLE
blog.pct.bike missing SSL certificate

### ISSUE THREAD

**Issue by nikolai-b** [npct/pct-shiny#664]
Re: #662 these is a slight new issue that http://blog.pct.bike/ it is missing an SSL certificate.  I _hope_ it will be resolved within [72 hours automatically](https://en.support.wordpress.com/https-ssl/#why-is-my-site-missing-an-ssl-certificate) but I'll leave this open till it is fixed.

**Comment by jf1** [comment]
Looks fine now so think you can close this, @nikolai-b

**Comment by nikolai-b** [comment]
@jf1 thank you.
