### ISSUE TITLE
rename govtarget scenario?

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#665]
As part of the new DFT contract, will be creating a new “near market” scenario, which is essentially a version of government target, i.e. doubling cycling. So now there will be two types of government target scenario, one in which all types of cyclist increase equally (the current one), and one in which some sort of, cyclists e.g. young males, are more likely take up cycling (the new nearmarket one).

One problem is that the scenario abbreviation ‘govtarget’ will no longer be ideal since actually there will be two government target scenarios.  After some discussion with @Robinlovelace , I think the ideal new names would be to rename the current govtarget scenario ‘govequity’ and name the new scenario ‘govnearmkt’. 

@nikolai-b and @usr110 , are you happy with the idea of (in due course) one of us searching and replacing all instances of ‘govtarget’ with ‘govequity’ in the pct-shiny data files and codebase? Plus potentially manually renaming e.g. tiled files on the server, as necessary? I appreciate doing this might cause the site to fail in the short term, but I would hope it would be fairly quick to clean up any resulting bugs? But would be interested to hear how terrible/not terrible an idea you think this is. 

The alternative option is to keep the government target equity scenario called ‘govtarget’ are just name the new one ‘govnearmkt’.  This is a bit less clear/user friendly in terms of the names, but would mean fewer changes needed to the codebase - and would also be fine by me if you hate the idea of renaming one of our existing scenarios.

**Comment by Robinlovelace** [comment]
Happy with either solution. Thinking about it, keeping
 `govtarget`
unchanched and making the new one
`govnearmkt` 
may be the simplest solution.

Look to hearing from Nikolai and Ali on this.

**Comment by nikolai-b** [comment]
I would prefer to keep `govtarget` internally as I fear it might be reasonable chunk of work that doesn't impact site users, other than if others want to re-generate the data.

The one place I'm aware we expose this to site users if they download data i.e. in the Region Data tab.  Maybe we should work out a way to rename it there?  In fact given that requires a codebook maybe we could make that more user friendly also (human readable titles would be a start :smile:).  I assume we can just make the script where we save the output also rename scenarios https://github.com/npct/pct-scripts/blob/020ab4c9ecee21f1cde77b67f61bf53c5f4dc5e3/07b.1_commute_build_region.R#L107 ?

@AnnaGoodman1 would that be acceptable or would you also like to change it internally?

**Comment by AnnaGoodman1** [comment]
@nikolai-b I am not sure changing it just in the codebook/data download woodwork, because those same data downloads are also what the server.R app runs on. But thinking about this more, I agree that maybe just keeping govtarget and adding govnearmkt is the best plan.  thanks both! Anna

**Comment by usr110** [comment]
Sorry for the late reply. Seems quite fine. 

A thought: shouldn't this new scenario (**govnearmkt**) be represented in the local-authorities' map as well?

**Comment by AnnaGoodman1** [comment]
yes thanks @usr110 , it should and will be - I have started creating a pct-shiny branch that adds in this new scenario, I will get you to check/correct to LA map fpr this new scenario when we're getting closer to the launch
