### ISSUE TITLE
schools layer on PCT landing page

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#669]
Before the schools layer can be launched, ideally we should update the landing page of the PCT to show the map of England + Wales but with the possibility to switch between the commute and the schools layer.  One minor complication is that for Wales there is no schools data, so we would instead I guess just show 'not available' or '-' something for there?

Currently the commute and school layers are now saved in parallel in ‘pct-shiny\regions_www\www\front_page’, one in a folder called commute and one in a folder called school. I think one next needs to modify ‘pct-shiny\regions_www\www\front_page\map’ to be able to dynamically switch between them. Feel free to modify how these files are saved, e.g. giving them different names rather than different purpose folders. If you do this then I will modify the source code in pct-scripts/06_merge_national_datasets.R accordingly.

who wants to have a go at this? @usr110 or @nikolai-b ? Not urgent, but good if could be done within a month or so.

**Comment by AnnaGoodman1** [comment]
no love for this issue from @usr110 / @nikolai-b  / @Robinlovelace :-( ?

**Comment by usr110** [comment]
Looking at it @AnnaGoodman1

**Comment by nikolai-b** [comment]
Thanks @usr110 I missed this entirety somehow.

**Comment by Robinlovelace** [comment]
Any updates on this? Let me know @usr110 when you want me to test and look to merge this: https://github.com/npct/pct-shiny/compare/front_page_school_layer

Good work.

**Comment by usr110** [comment]
See this: https://github.com/npct/pct-shiny/pull/692

@Robinlovelace

**Comment by usr110** [comment]
> 
> 
> Thanks @usr110 I missed this entirety somehow.

No worries @nikolai-b. Need your inputs in the pull-request: https://github.com/npct/pct-shiny/pull/692

**Comment by Robinlovelace** [comment]
Thanks for the update. Suggestion: @nikolai-b takes a look when he gets a chance and you ping me an update when ready to test/merge.

**Comment by Robinlovelace** [comment]
Great work all, looks good on the test server. Impressive JavaScript skills @usr110 and @nikolai-b !
