### ISSUE TITLE
welcome page and more...

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#67]
1.       Mention that it’s a prototype tool where NPCT is mentioned – more prominently at the top
2.       Introduce a welcome screen with the following info:
a.       what is the npct (use “Lorem ipsum dolor sit etc" for now.
b.     List of logos
c. link to individual pages & ability to chose city 
    Sort of like MET’s website - http://www.metoffice.gov.uk/
4.       Change name of ‘help’ to ‘how to use it’
5.       Change ‘More Information’ into ‘About’
6. Change basic background map to one with city and town names

**Comment by usr110** [comment]
Have completed the following points:
1. Prototype tool is mentioned - https://github.com/npct/pct-shiny/commit/55a12be4a52d24587be45a5fd7b41021fa5fe058
3. Changed name of ‘help’ to ‘how to use it’ - https://github.com/npct/pct-shiny/commit/8fd1906d292b87bf84d1f498a20c4b9fa3f4e7d2
4. Changed ‘More Information’ into ‘About’ - https://github.com/npct/pct-shiny/commit/c16c2a3f929e26772163a60f90a660397faa8a7a
5. Change basic background map to one with city and town names - introduced a new map layer called acetate. Details can be seen here: https://github.com/npct/pct-shiny/commit/22b2e8d9eed52ab47b2eef44b1306461bdf22f9a

**Comment by usr110** [comment]
@nikolai-b I believe you mentioned that you'd have a go at the welcome screen. Are you on it?

**Comment by Robinlovelace** [comment]
Great work Ali - just taken a look on the website and it's looking good. To confirm, the latest version is pushed right? Thanks.

**Comment by usr110** [comment]
@Robinlovelace Thanks. No, I haven't pushed the latest code. Do you want me to?

**Comment by usr110** [comment]
Pushed!

**Comment by Robinlovelace** [comment]
:+1:

**Comment by JDWoodcock** [comment]
looking nice :)

**Comment by nikolai-b** [comment]
I'm looking at making a clickable svg of unitary authorities.

**Comment by nikolai-b** [comment]
We have a clickable map on the front page, needs styling but 
http://geo8.webarch.net/
thoughts?

**Comment by Robinlovelace** [comment]
It works and that's the main thing. I think using a screenshot of the basemap we use as default (we may change this) would be good. It would be good if the name is displayed as you hover over each area also. Really promising, it's going to look mint.

**Comment by usr110** [comment]
@nikolai-b It looks great. Great work!
Personally I think if the selected regions were bigger, that'd be great. Or alternately, if there was a table which contained the clickable maps of the regions we are interested in (and then you don't have to show the unrepresented areas). 
@Robinlovelace I believe you do see the name when you hover over the regions. There's a slight delay, but it sure does appear.

**Comment by nikolai-b** [comment]
Hi,
I want this to be general so I don't want to only have the regions we currently support as we are planning on opening this nationwide soon.  Also a table would fill up a lot of space and isn't really like the Met Office site.  I'm not sure how I can make the regions selected bigger but I could try.  Might be worth timeboxing it to an hour as I don't think that is highest priority, correct me if I'm wrong though @usr110 .
@Robinlovelace I don't know what you mean about the basemap, do you mean have a screenshot of the map somewhere on the page?  I think that is what James said, I will add more styling but other than the map most other things will be static.

**Comment by Robinlovelace** [comment]
Yes I was also talking about styling.
We could have an alternative url that just starts with the pct zoomed out to England - what do you reckon?

**Comment by nikolai-b** [comment]
I've not done the selectable list as it will only have 4 items at the moment.   I've spent another hour or two on the front page making it look nicer but I think the best thing will be to reassess when we have more unitary authorities included.

**Comment by JDWoodcock** [comment]
hi,
I suggest we make it closer to master page. So the welcome page keeps the top banner stuff with Interactive Map, Lines etc... We lose the side details - they only come up when you select an area. You see the zoomed out map but lose the areas outside of UK.

I agree with Robin- I am  concerned that having one map of England to link to another different map of England is not the right solution - if you look at met office you can click on a UK map but then at least to the user it looks like you are zooming in rather than being shown a completely different map. So as I think Robin is suggesting you start zoomed out and then you click on area to zoom in. 

I think we should have a drop down list of areas, or you start typing in a box and matching options pop up.That would be the generalisable solution. Initially not many places to choose from but soon there will be more.

I think the text needs to be bigger and probably in some kind of box.

**Comment by nikolai-b** [comment]
I don't think this currently makes sense.  It seems like you want the welcome page to be like the shiny map but with clickable links to regions.  This isn't possible, you have have clickable links or we can just set up the welcome page to be a shiny map but not a mixture of them both.  Does this make sense?

I can make the current map look a bit more like a shiny map (i.e. try to have a set image as a base map) but it can't have the Interactive Map, Lines etc.  I can add the dropdown select to this version. 
OR
I can just make the home page be a shiny app zoomed out to england but it won't be clickable (in which case the additional text doesn't make sense).

**Comment by JDWoodcock** [comment]
yes that makes sense. What I think we want is something that looks similar. The user doesn't care if they are really the same. We dont need (we dont want) lines etc on the intro map. The intro map is just a way of selecting areas. 
As you said earlier I dont think we can be sure exactly how the zoomable map will work when we have all areas- this will come out of user testing and exactly how the areas are specified. But for now with only a few areas outside of London created the clickable approach works.

**Comment by nikolai-b** [comment]
Just to clarify, the map on the front page will not be zoomable, it will be a static image that when clicked will redirect the the url with the city and have the actual shiny map.  

Could you expand on these:
> We dont need (we dont want) lines etc on the intro map. 

and

> So the welcome page keeps the top banner stuff with Interactive Map, Lines etc... 

as I want to make sure we are on the same page. The top navigation will not have Lines, Zones etc. as they would link nowhere.  It could have Additional Help but the way that is done currently is through shiny so I'd have to build it manually and it could be a bit faffy.

**Comment by Robinlovelace** [comment]
Just to chip in here, NB and I discussed this at the conference and I tend to agree that it's not worth ploughing lots of time into. Most users will navigate straight to the URL. The static map will be sufficient and agree @JDWoodcock it's just a way to select a zone. Think what you've done so far is moving in the right direction Nikolai.

**Comment by JDWoodcock** [comment]
let's discuss Monday. 
we should work on the basis lots of people will be sent link and know next to nothing about NPCT. They need a welcome page to introduce them to the project. The link to the next map can be done simply. The main point is to orient people who have been told about NPCT.

**Comment by JDWoodcock** [comment]
thanks Ali for updating text. I think next stages are
1) make default text bigger
2) add institutional logos
3) use the same banner as for the rest of the site
4) we probably need to discuss the map

**Comment by Robinlovelace** [comment]
Make version for new regions: https://github.com/npct/pct-bigdata/blob/master/national/regions.geojson

**Comment by JDWoodcock** [comment]
hi the new regions look nice but I dont think they should be shown until they are populated. We want to send users to the Welcome page but they will try clicking - find regions not done and get bored.
A more minor point I am not sure the 2 stage process is ideal- one click would be neater.

**Comment by Robinlovelace** [comment]
@JDWoodcock yes fair point - I've updated the front map with https://github.com/npct/pct-shiny/commit/5be65fdfa80aa94fc9a3081bea883333f9ed1974 

Please take a look at let me know your thoughts - looking good to me. @usr110 please could you take a look at the popup creation and make them nicer if you get a chance - see here: https://github.com/npct/pct-shiny/blob/master/mapgen.R#L56

**Comment by JDWoodcock** [comment]
thanks @Robinlovelace , looks better.
Could say 5% cycling instead of cycling =5%

**Comment by Robinlovelace** [comment]
Yes, thanks @JDWoodcock. Took longer than expected to fix but I learned some things in the process! @usr110 can you try to fix the popups please? Otherwise I can but I want to stay focussed on the data and the model.

**Comment by usr110** [comment]
@Robinlovelace Done by https://github.com/npct/pct-shiny/commit/69098df1e0a598b1f79f7a9a1908472b09036f15 and https://github.com/npct/pct-shiny/commit/f07796882b8eeba820bf8c43e1491dbfac0af49a. It'd be nice if one person ends the whole job, or if not possible, at least point out where the changes need to be done. It took me a while to figure it out.

**Comment by Robinlovelace** [comment]
Thanks for the fix @usr110! I'm sorry I didn't fix it - asked if you wanted to do it because I thought you'd be interested in how the map was created and wondered if you'd prefer to add some html. Apologies if it took away time from more important stuff (network analysis stuff) and feel free to say no next time. Also let me know if you'd like a hand with any of your stuff.

**Comment by usr110** [comment]
@Robinlovelace Duly Noted. Thanks.

**Comment by JDWoodcock** [comment]
the front page is looking good but @usr110 would you be able to highlight when an area is done (perhaps in a darker shade or with some other marking)?

**Comment by Robinlovelace** [comment]
@JDWoodcock to be fair this is probably easier for me to do as I wrote the build script for this - will update https://github.com/npct/pct/commit/39fbaec11eccd8bb009eaf6f7ea8a28d274f039a when I get a chance. Not top of priority list though and will be redundant when all regions are built. Any outstanding issues? Suggest closing this monster thread if not.
