### ISSUE TITLE
when/how to launch new national build + near market scenario

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#670]
The new national build + near market scenario are basically ready to launch except for the rasters. The two options I can see are:

1) wait until Malcolm has been able to do the rasters for the 6 scenarios - so that maybe means a launch date of ??april or after

2) launch it soon, but with the rasters not updated until later - we could add a note that the rasters were not yet updated. i.e. a sort of soft launch.

Any views between these? I don't vary much mind. (also @JDWoodcock and @RachelAldred ). 

Also the launch would in practice take a bit of time since some very large datasets need to be uploaded from my computer to Github – so there would be a week or so when it was a mixture of old data and new data on the site.  which I think would be fine, but we should make sure to avoid any PCT training days – when are those Rachel?

**Comment by RachelAldred** [comment]
6th March and 4th April are the first two combined basic/intermediate.

**Comment by JDWoodcock** [comment]
i think it would be nice to have at least a blog post on the near market scenario. If we had time we could do more e.g. update local authority level analysis / pamphlet but I dont see this a priority.
Rachel- how does it affect training materials?

**Comment by AnnaGoodman1** [comment]
re training materials, I have made essential updates here on dropbox 'PCT\2_WorkInProgress\Anna\NearMarket', e.g. making sure we always say there are five scenarios not four, plus giving substantially more information in the methodology manual C.  @RachelAldred , you could perhaps look and see if you are happy with this or if you want to add in something further

**Comment by JDWoodcock** [comment]
thanks

**Comment by RachelAldred** [comment]
Those are looking good Anna, thanks. I could draft a blog post ideally after having been able to look at the results so I can give e.g. a couple of examples of differences in results between the two Government Target scenarios.

**Comment by AnnaGoodman1** [comment]
@Robinlovelace , do you have views on this? You can also ask Malcolm when home

**Comment by Robinlovelace** [comment]
An important consideration in technology is stability. I therefore think that waiting until the rasters is done, and announce a proper launch with all the features, is probably the best idea. I think putting the new scenario on the test servers without rasters is a good idea though.

**Comment by AnnaGoodman1** [comment]
Thanks Robin. Fine by me as long as rasters won't be too too long. The problem with raster on test server is it uses the new datasets - so one can do that locally via this branch, but I think not default

**Comment by Robinlovelace** [comment]
Point taken re. timescales. Will wait to hear from @mem48 on that when they're back (looking forward to it : )

**Comment by Robinlovelace** [comment]
Closing as superceded by #703 - ASAP is the consensus I believe! That issue mentions Friday next week, although I suspect we may need to push it back to end of the month. Sounds reasonable @AnnaGoodman1 ?
