### ISSUE TITLE
school raster tiles mask basemap above zoom level 15

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#677]
See #675 and below for demon:

![peek 2019-02-25 07-54](https://user-images.githubusercontent.com/1825120/53322321-f23ecb80-38d2-11e9-8a9a-7e359d7ad12a.gif)

**Comment by mem48** [comment]
I know why this is happening, but it might take a while to fix. The problem is in how I stitched the very large 10m raster togther.

**Comment by Robinlovelace** [comment]
Any ideas how long it might take to fix @mem48? Worth liaising with @nikolai-b on this because they're also thinking of a fix (want to avoid duplicate effort on this).

**Comment by nikolai-b** [comment]
This is dup of https://github.com/mem48/pct-raster-tests/issues/4
I've given a suggested fix https://github.com/mem48/pct-raster-tests/pull/3

**Comment by Robinlovelace** [comment]
Great @nikolai-b and @mem48 can either of you test that on a sample of the tiles to see if it works?

**Comment by Robinlovelace** [comment]
@nikolai-b Please can you test these tiles work: https://github.com/npct/pct-lsoa-vis/releases/download/0.0.1/output2.4.zip

Building using the latest version of GDAL for all tiles, but please test for these zoom levels first.

**Comment by nikolai-b** [comment]
@Robinlovelace looks ok:
![screenshot from 2019-02-27 20-31-29](https://user-images.githubusercontent.com/6289830/53520997-ea4b7b00-3ace-11e9-9386-b194e5be8d23.png)
it is only upto zoom 9 so hard to tell if all the colours match but it doesn't overwrite the other base layer

**Comment by Robinlovelace** [comment]
Good to see, that's all I wanted to check. Thanks for testing. More soon.

**Comment by Robinlovelace** [comment]
@nikolai-b as a minimum viable product I've generated the tileset up to zoom level 12. Please can you test deploying these: https://github.com/npct/pct-lsoa-vis/releases/tag/0.0.2

Then we can just add the 13, 14 and 15 zoom level folders in the appropriate places. Note one difference is that the resolution is fixed. I'd say that is not a priority issue, as the layer is designed to be used while zoomed in, but no harm in updated the zoomed out layers to be more in sync with the commute LSOA data.

**Comment by nikolai-b** [comment]
I've updated our tile server and told leaflet the school tiles stop 12. 
https://github.com/npct/pct-shiny/commit/4632f53650f9a386122b8ffb9ba9655aa78acb2b

**Comment by Robinlovelace** [comment]
Great work @nikolai-b can see where we need safe routes to school in Chapeltown now:

![image](https://user-images.githubusercontent.com/1825120/53679129-60630400-3cc0-11e9-9b35-71af1cb42216.png)


Hopefully the layers 13-15 have finished building now. I'll add them to the same place and tag you if so...

**Comment by Robinlovelace** [comment]
Heads-up: the new tiles for the Go Dutch have finished. See here: https://github.com/npct/pct-lsoa-vis/releases/tag/0.0.3

Will add the rest when they are finished.

**Comment by Robinlovelace** [comment]
Please give these a spin @nikolai-b. Hope they work!

**Comment by Robinlovelace** [comment]
Please give these a spin @nikolai-b. Hope they work!

**Comment by Robinlovelace** [comment]
Update: they have finished.

**Comment by nikolai-b** [comment]
Great work @Robinlovelace !  I guess your uploading them now and I'll update the tile server.

**Comment by Robinlovelace** [comment]
I've uploaded them to GH. Pls put them on the tileserver yes :+1: Great work you too, thanks for the quick (dare I say agile) work on this!

**Comment by nikolai-b** [comment]
@Robinlovelace there is a disk space issue on our tile server, I've raised a support ticket but I'm guessing it'll be tomorrow before I can finish this.

**Comment by Robinlovelace** [comment]
Now working:

![image](https://user-images.githubusercontent.com/1825120/53869002-2f9c0b00-3fef-11e9-882b-9208996b3d20.png)
