### ISSUE TITLE
Cycling ratio between baseline and scenario is infinity

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#679]
Just started testing and found an interesting result. Since we are displaying ratio of scenario and baseline, and when there are no baseline cyclist, it shows `Inf` (infinity). See below for `bedfordshire`

![image](https://user-images.githubusercontent.com/10958628/53579972-87132480-3b72-11e9-8648-728d53edf327.png)

We should instead use `undefined` or some other helpful message there.

**Comment by Robinlovelace** [comment]
I think in some places Infinity is a realistic expectation ;) Seriously though, this one of those things that can be seen as a bug or a feature, depending on how you look at it. Does not seem like a major issue to me and I think there are more important ones to address right now. Great to have it open though for now and if you think of a fix, e.g. `NA`, I think that would be great.

**Comment by AnnaGoodman1** [comment]
I think Inf is clearer than NA, I agree this could be ignored for now...

**Comment by Robinlovelace** [comment]
Closing for now. If anyone thinks of a better message, please let us know.
