### ISSUE TITLE
Remove (-%)

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#681]
James suggests that after an uncertain number, e.g. '1 or 2', switch from current '(-%)' to having nothing at all, i.e. no percentage information.  This involves changing line 606, 610, 635, 776, 780, 811 of pct_shiny_funs, i.e.

      <td>", school_smallcell(data$bicycle), " (", ifelse(school_smallcell(data$bicycle, return_tf = T), "-", round_percent(data$bicycle / data$all)) , "%) </td>

such that the "(" and "%)" go inside the ifelse. @Robinlovelace , could you do this? had a quick go and couldn't make it work

**Comment by Robinlovelace** [comment]
Not at the moment...

**Comment by usr110** [comment]
Looking at it now!

**Comment by usr110** [comment]
Not really fixed. See below:

![image](https://user-images.githubusercontent.com/10958628/54087847-5344b580-434f-11e9-9a83-3bd602e7e2cf.png)

**Comment by AnnaGoodman1** [comment]
see now fixed, thanks!
