### ISSUE TITLE
some downloads for schools not availalble

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#686]
we do not currently have raster regional downloads.

We do not currently have raster or vector national downloads

if we wanted these, 
1) the files would need to be uploaded to the appropriate place on git, i.e. pct-outputs-national\school\lsoa. @Robinlovelace  / @mem48 , are you planning to do this? If so, ideally it should be saved there as part of the creating code in pct-scripts, to keep the workflow nice
2) the files would need to be linked to from pct-shiny\non_www\tabs\school\download_national.  I could possibly have a go at the latter, or someone else can

**Comment by Robinlovelace** [comment]
rnet national download: https://github.com/npct/pct-lsoa-vis/releases/download/0.0.1/schools_rnet.gpkg

**Comment by Robinlovelace** [comment]
Raster downloads: too big to be worth uploading IMO. Could generate regional rasters though.

**Comment by Robinlovelace** [comment]
I've uploaded the vector rnets, so I think 1. is done, unless we want to upload the fastest and quietest routes also?

I think it's a good idea to link to the files that are uploaded.

**Comment by Robinlovelace** [comment]
@mem48 can you take a look at this one:

> we do not currently have raster regional downloads.

My thinking on the national downloads is that the vector download is done. See here: https://github.com/npct/pct-shiny/commit/6e10d6c87fdd9fc36dc453b5a2644f55d33c4981

Happy for more national downloads to be added.

@AnnaGoodman1 am I thinking it's just the regional rasters that need to be done now?

**Comment by AnnaGoodman1** [comment]
well, we had a national download for raster for commuting, rachel seemed to like it, so suggest why not that too?

**Comment by AnnaGoodman1** [comment]
also the national one needs to be uploaded to the right place (pct-outputs-national\school\lsoa) - I could do that once we are clear anonymisation has been done correctly

**Comment by Robinlovelace** [comment]
> well, we had a national download for raster for commuting, rachel seemed to like it, so suggest why not that too?

I have no objection to that. One for @mem48 as he generated the huge 20+GB files that I tiled for the LSOA route network layer. Not sure if they have the capacity to produce those at present.

**Comment by Robinlovelace** [comment]
> I could do that once we are clear anonymisation has been done correctly

Great, please do. The file is here: https://github.com/npct/pct-lsoa-vis/releases/download/0.0.1/schools_rnet.gpkg

**Comment by AnnaGoodman1** [comment]
Sorry, @Robinlovelace , could you provide this as 1) an .Rds and 2) a .geojson file? I will then upload to relevant place

**Comment by AnnaGoodman1** [comment]
ok, I think this is now done
