### ISSUE TITLE
anonymising rnets

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#688]
In the region stats data, we state 'The pop-ups do not present exact numbers for segments containing 1 to 2 cyclists.', and in the old rnet data downloads we set to NA situations as follows (lines 87-91 of 07b.2 file in pct-scripts):

  rnet <- rnet
  rnet@data$bicycle[rnet@data$bicycle>0 & rnet@data$bicycle<=2] <- NA
  for(i in scenarios){
    rnet@data[[i]][is.na(rnet@data$bicycle) & rnet@data[[i]]<=2] <- NA
  }

 @Robinlovelace / @mem48  , I think you need to
1) [optional: save your current complete, new rnets in pct-outputs-regional-R\school_private locally.... but NB can't be on github]
2) incorporate the above anonymisation on those for the new rnets.  
3) save those new anonymized rnets to pct-outputs-regional-R\school

**Comment by Robinlovelace** [comment]
Thanks @AnnaGoodman1 will look tomorrow, when back from travels. I guess this also means we should remove the national rnet here: https://github.com/mem48/pct-raster-tests/releases

**Comment by AnnaGoodman1** [comment]
Right, yes, should be anonymised first before on git

**Comment by Robinlovelace** [comment]
Updated rnet: https://github.com/npct/pct-lsoa-vis/releases/download/0.0.1/schools_rnet.gpkg

**Comment by mem48** [comment]
If the values are set to NA doesn't that just mean that NA values are equal to 1 or 2. Not really very anonomised. I looked at the stats and there are no NAs for the govtarget or godutch (but there are some 0 values?) Especially if the govtarget is 3 and the bicycle is NA that is a very strong clue to the true value.

**Comment by Robinlovelace** [comment]
Updated and tested locally. Seems like it's addressed this issue, as illustrated below.

![image](https://user-images.githubusercontent.com/1825120/53982320-85b2a080-410c-11e9-9523-9db031687256.png)

**Comment by Robinlovelace** [comment]
Clarification: here are some results from a test region, with rnets just pushed:

```
> test_rnet = "../pct-outputs-regional-R/school/lsoa/avon/rnet.Rds"
> test_rnet = readRDS("../pct-outputs-regional-R/school/lsoa/avon/rnet.Rds")
> summary(test_rnet$bicycle)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  0.000   0.000   5.000   8.226  10.000 258.000    2490 
> summary(test_rnet$bicycle == 1)
   Mode   FALSE    NA's 
logical    7088    2490 
> summary(test_rnet$bicycle == 2)
   Mode   FALSE    NA's 
logical    7088    2490 
> summary(test_rnet$bicycle == 3)
   Mode   FALSE    TRUE    NA's 
logical    6228     860    2490 
```

**Comment by AnnaGoodman1** [comment]
Where have you applied my code @Robinlovelace ? I'm worried about Malcolm statement that there are no NAs in the scenarios, there should be from my code. 

@mem48 , I agree it is not very anonymized but the rules are that 'cell sizes of 1 or 2' need to be protected. If the government target value is three, you don't actually have any clue as to whether in practice there were one or two cyclists on the route before

**Comment by Robinlovelace** [comment]
Hi @AnnaGoodman1 see below reproducible tests that the rnets do contain no values of 1 or 2:

``` r
region_to_test = "london" # pick any region
u = paste0("https://github.com/npct/pct-outputs-regional-R/raw/master/school/lsoa/", region_to_test, "/rnet.Rds")
download.file(u, "rnet.Rds")
test_rnet = readRDS("rnet.Rds")
summary(test_rnet$bicycle)
#> Loading required package: sp
#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
#>   0.000   0.000   3.000   3.671   5.000 301.000   17776
summary(test_rnet$bicycle == 1)
#>    Mode   FALSE    NA's 
#> logical   31823   17776
summary(test_rnet$bicycle == 2)
#>    Mode   FALSE    NA's 
#> logical   31823   17776
summary(test_rnet$bicycle == 3)
#>    Mode   FALSE    TRUE    NA's 
#> logical   27647    4176   17776

# test national rnet
region_to_test = "london" # pick any region
u = paste0("https://github.com/npct/pct-lsoa-vis/releases/download/0.0.1/schools_rnet.gpkg")
download.file(u, "rnet.gpkg")
test_rnet = sf::st_read("rnet.gpkg")
#> Reading layer `schools_rnet' from data source `/tmp/RtmpOxa3pT/reprexc4b7666ac54/rnet.gpkg' using driver `GPKG'
#> Simple feature collection with 412433 features and 4 fields
#> geometry type:  LINESTRING
#> dimension:      XY
#> bbox:           xmin: -6.31188 ymin: 49.91577 xmax: 1.75576 ymax: 55.78544
#> epsg (SRID):    4326
#> proj4string:    +proj=longlat +datum=WGS84 +no_defs
summary(test_rnet$bicycle)
#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
#>    0.00    0.00    0.00    5.42    6.00  966.00  111916
summary(test_rnet$bicycle == 1)
#>    Mode   FALSE    NA's 
#> logical  300517  111916
summary(test_rnet$bicycle == 2)
#>    Mode   FALSE    NA's 
#> logical  300517  111916
summary(test_rnet$bicycle == 3)
#>    Mode   FALSE    TRUE    NA's 
#> logical  274336   26181  111916
```

<sup>Created on 2019-03-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

So I think this issue is sorted. Please close if so.

**Comment by Robinlovelace** [comment]
> Where have you applied my code

I think this is the line you're looking for - applied 'upstream' to the national route network in a slightly different way but seems to do the job: https://github.com/npct/pct-scripts/blob/master/07b.3-regional-rnets.R#L21

**Comment by Robinlovelace** [comment]
I've double checked and think it's sorted so closing for now. But if you find any further issues with this @AnnaGoodman1 or anyone, please re-open and we can resolve the issue. Think it was resolved yesterday. Apologies if not.

**Comment by Robinlovelace** [comment]
Re-opening - I missed the for-loop:

```r
rnet <- rnet
rnet@data$bicycle[rnet@data$bicycle>0 & rnet@data$bicycle<=2] <- NA
for(i in scenarios){
rnet@data[[i]][is.na(rnet@data$bicycle) & rnet@data[[i]]<=2] <- NA
}
```

**Comment by Robinlovelace** [comment]
OK, now it can be closed. After discussion with @AnnaGoodman1 I've changed the values in other scenarios also. Please check:

- The code. Just checked this and it's reproducible and is building all rnets as we speak: https://github.com/npct/pct-scripts/commit/0135be56287bb1ad4a985c13613b5ff6d5af2d4f
- The updated .Rds files, with new `rnet_full.Rds` file for the downloads (just for Avon for now): https://github.com/npct/pct-outputs-regional-R/tree/master/school/lsoa/avon
- The updated .geojson files (also just for Avon): https://github.com/npct/pct-outputs-regional-notR/tree/master/school/lsoa/avon

I can push the data for all regions when I get the 👍 

Many thanks @AnnaGoodman1

**Comment by Robinlovelace** [comment]
Heads-up: the regional rnet builds are finished and look good, so pushing them all now!

Please update the download links/descriptions if you get a chance @AnnaGoodman1.

**Comment by AnnaGoodman1** [comment]
great, have changed both code and files so the geojson ones are correctly called rnet_full - otherwise looks perfect
