### ISSUE TITLE
using build_param place to determine no. children per segment

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#689]
@Robinlovelace , rather than hard coding the number of children per segment we should use the same system that we do elsewhere in setting parameters, namely taking it from pct-scripts\school\lsoa\build_params_pct_region.csv.  I have made a new column there called 'mingodutch_rnet' : it would be good if your code could link to this and use it. At the moment I have set it to be what I think is currently correct, namely 10 children everywhere but 50 in London

**Comment by Robinlovelace** [comment]
I've dealt with this in a different way: making only route networks above a certain size filtered by:

```r
      rmini_spatial = rmini_spatial[rmini_spatial$dutch_slc >= 50, ] 
```

I think this resolves the issue: it's automated and built-in, although using a different and slightly more generalised logic that the regions name, so closing for now.

Happy for this to be re-opened and addressed in a different ways, e.g. via edits to these lines: https://github.com/npct/pct-scripts/blob/77e1656aae1832f35b30523011eba4217409e849/07b.3-regional-rnets.R#L53-L55

**Comment by AnnaGoodman1** [comment]
I don't think this is a pressing issue, but I don't think what you have done is ideal @Robinlovelace – the key advantage of using our existing build_params file is that the one only has to change the value '50' in one place, for it to be used both to build the route network and also parameterise the region_stats file. I'm not absolutely against leaving it as it is, on the basis that in practice we probably are not going to do a national build again, but it does mean that if you have a change this code you need to remember to change it  in build_params too, which is less elegant and more error prone...
