### ISSUE TITLE
update region stats files and data download files

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#690]
see https://github.com/npct/pct-scripts/pull/80 . I have provisionally pushed the new versions to pct-shiny, but might need further updating if @Robinlovelace  makes additional changes to my pull request

**Comment by AnnaGoodman1** [comment]
see also this pr, https://github.com/npct/pct-shiny/pull/691 , again @Robinlovelace I am not sure if the description matches what you have done

**Comment by Robinlovelace** [comment]
> actually I think I may have misunderstood, from your email you don't include the full vector network even in the download, just sections with at least 10 children?

That's true, but it's actually rnet segments in which there is noteworthy cycling potential, specifically segments along which there a cycling potential of 10+ people under the Go Dutch scenario:

https://github.com/npct/pct-scripts/blob/77e1656aae1832f35b30523011eba4217409e849/07b.3-regional-rnets.R#L18

**Comment by Robinlovelace** [comment]
Just checked the results for London. It says:

> Finally, the Route Network (LSOA, clickable) and the Route Network (LSOA, image) are built from all origin-destination fast routes within the region. In the online version of the 'clickable' route network, we only present route segments that contain at least 50 cyclists in the Go Dutch scenario. All route segments are included in the versions that can be downloaded. The pop-ups and downloads do not present exact numbers for segments containing 1 to 2 cyclists.

This is correct (image below) so closing for now. Please re-open if I missed anything. Many thanks for updating the Region stats @AnnaGoodman1!

![image](https://user-images.githubusercontent.com/1825120/53984051-73d2fc80-4110-11e9-8585-08007468205b.png)

**Comment by Robinlovelace** [comment]
Update: just tested it for another region (`hereford-and-worcester`) and the results are right:

> Finally, the Route Network (LSOA, clickable) and the Route Network (LSOA, image) are built from all origin-destination fast routes within the region. In the online version of the 'clickable' route network, we only present route segments that contain at least 10 cyclists in the Go Dutch scenario. All route segments are included in the versions that can be downloaded. The pop-ups and downloads do not present exact numbers for segments containing 1 to 2 cyclists.
