### ISSUE TITLE
None of the tabs are scrollable on test-server

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#695]
Hi,
Just noticed that none of the tabs are vertically scrollable - not an issue on the live server, which means you can't read any page properly (try for instance `Region stats`). If I am not mistaken, we had this issue before, and the reason was that the markdown documents' `script` tags were messing with it. Most probably the school region's tab might be creating this issue. Isn't that right @nikolai-b ?

**Comment by Robinlovelace** [comment]
Well spotted Ali, just verified and this is indeed a major regression! Any way I can help, let me know, although this a bit beyond my ken.

**Comment by nikolai-b** [comment]
@usr110 I was me :sob: , I wanted a nice way to make the map full screen so I played around with the CSS so the map filled all vertical space not taken by the header but the header size can change and  apparently that is almost impossible without flex boxes (to cut a long story short even then leaflet was spilling outside the container).  Anyway: I hacked the CSS a bit to hide the [vertical overflow](https://github.com/npct/pct-shiny/pull/685/files#diff-f4f2bb17902c3061ef9c48f66ad81d23R4) and now I've added readded explicit overflow :sweat_smile:.
Not sure if that make sense but thanks for spotting!

**Comment by usr110** [comment]
> 
> 
> Well spotted Ali, just verified and this is indeed a major regression! Any way I can help, let me know, although this a bit beyond my ken.

Thanks @Robinlovelace for the offering. I was wrong in assuming that `markdown` documents were to blame. I am glad that it's sorted.

> @usr110 I was me sob , I wanted a nice way to make the map full screen so I played around with the CSS so the map filled all vertical space not taken by the header but the header size can change and apparently that is almost impossible without flex boxes (to cut a long story short even then leaflet was spilling outside the container). Anyway: I hacked the CSS a bit to hide the [vertical overflow](https://github.com/npct/pct-shiny/pull/685/files#diff-f4f2bb17902c3061ef9c48f66ad81d23R4) and now I've added readded explicit overflow sweat_smile.
> Not sure if that make sense but thanks for spotting!

Yes, it does @nikolai-b and thanks a ton for the quick fixing. So glad we didn't have to recreate all `stats` html file, as I had expected.

Minor issue though: it seems the bottom bit is not properly shown - it's somewhat cut. See below from the `about` page:

![Screenshot_2019-03-10 Propensity to Cycle Tool - Wales](https://user-images.githubusercontent.com/10958628/54092437-04654300-4384-11e9-9d18-efaad41a9158.png)

Tested in `firefox` and `opera`.
