### ISSUE TITLE
Bottom not visible from Region stats tab and other tabs

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#696]
This is what I see:

![image](https://user-images.githubusercontent.com/1825120/54104760-d7874f00-43c8-11e9-8a56-30edc4fd909b.png)

**Comment by usr110** [comment]
Thanks @Robinlovelace ; this is what I've raised here: https://github.com/npct/pct-shiny/issues/695#issuecomment-471360815

Closing this one as I think it's a duplicate. Do open if you think otherwise.

(this behaviour appears to be in all tabs - the bottom bit is missing)

**Comment by Robinlovelace** [comment]
Re-opening as it's a separate issue. The scrolling issue has been fixed and closed. This one (which is likely related) has not been fixed yet, to my knowledge, so re-opening. Any ideas? I'm not even sure the reference text is in there...

**Comment by usr110** [comment]
Ok fine, as you like.

It's relevant to the #695 issue, as I believe this pertains to the CSS changes made by @nikolai-b 
You can find the `reference` section in all of the `region_stats` files here: https://github.com/npct/pct-shiny/tree/master/regions_www/tabs/region_stats/commute

Re my comment, I was referring to this bit

> Minor issue though: it seems the bottom bit is not properly shown - it's somewhat cut. See below from the about page:

**Comment by Robinlovelace** [comment]
Thanks for this link. Just checked and I confirm the text is there: https://github.com/npct/pct-shiny/blob/cfec7d2c553a9f716609b0d25ee37bfe5623f373/regions_www/tabs/region_stats/commute/lsoa/wales/region_stats.html#L213

So yes this is the same problem that's causing the bottom not to be shown. Good practice to open it as a separate issue though, so we can track when it's fixed, without opening the previous, slightly different issue #695.

**Comment by usr110** [comment]
> Good practice to open it as a separate issue though, so we can track when it's fixed, without opening the previous, slightly different issue #695.

Fair point :+1:
