### ISSUE TITLE
Navigation bar disappears when you click sidebar links within the app

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#697]
Just doing more testing. Found an interesting behaviour. Once you're inside the application, it seems that the navigation bar disappears when you click any of the links in the sidebar. Say for instance when you click `Zones data` in `Region data` tab, the navigation bar disappears, so you are sort of stuck there.

![Screenshot_2019-03-12 Propensity to Cycle Tool - Avon](https://user-images.githubusercontent.com/10958628/54198119-9b81e600-44bd-11e9-9a19-91dfafdac30a.png)

I am afraid this is a universal issue. You can find the same strange behaviour in all tabs with sidebar links. Try any of these: `Region data`, `National data`, `Manual` and `About`. Any ideas @nikolai-b ?

**Comment by usr110** [comment]
Might have to do with https://github.com/npct/pct-shiny/commit/5e4ffa0cfd0ad87e38a214a31987be69a138ab2d

specifically these lines: https://github.com/npct/pct-shiny/blob/48bfd2aa403bab1bfa65c902dbd40bad72e16ac1/regions_www/www/stylesheet.css#L1-L5

**Comment by nikolai-b** [comment]
:octocat: looks to be a bit broken as it has missed
https://github.com/npct/pct-shiny/commit/3ebb98922c2af752b785731bec10377444a859c9
which fixes this
