### ISSUE TITLE
Dropping off the bottom of the screen

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#7]
When I select the 'lines' option, and get those extra options, I lose the ability to change the 'zone attributes' type to be 'extra cycling potential'.  

A solution would be to remove the 'additional features' option and 'type of zone' options, and to add a 'none' option to the 'zone attributes' (i.e. equivalent to seeing no MSOA outcomes).

**Comment by nikolai-b** [comment]
Thanks, could you tell me your screen resolution?

**Comment by Robinlovelace** [comment]
Hi Nikolai - I asked the same question. The issue will be resolved by removing the 'zone' and 'additional feature' drop-downs. We should probably communicate over speaker-phone to get you up-to-date. Consensus-based decision making has been in action!

**Comment by nikolai-b** [comment]
Thanks, with the changes just made then this should no longer be an issue.

**Comment by Robinlovelace** [comment]
@nikolai-b :+1:
