### ISSUE TITLE
Map on landing page has square outlines on firefox

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#702]
See below. Can anyone else reproduce this behaviour? I noticed it after recent updates to production

![image](https://user-images.githubusercontent.com/1825120/54977159-5e752380-4f94-11e9-8822-3db1553c1f9c.png)

Looking at the latest updates in https://github.com/npct/pct-shiny/commit/820663cd8eb47240f84ded83e768482767d5b6f2 I cannot see anything obvious though. Ideas @nikolai-b and @usr110 ?

**Comment by Robinlovelace** [comment]
I've checked on a few other machines today and think it was a quirk with my laptop and its high res screen so closing for now.

**Comment by usr110** [comment]
This is appearing again - both on my office and home computers. Saw that on @JDWoodcock's computer as well, and also it's visible in the issue created by @AnnaGoodman1 (https://github.com/npct/pct-shiny/issues/712#issue-434364927)

Any ideas @nikolai-b?

**Comment by JDWoodcock** [comment]
yes I see this all the time now

**Comment by Robinlovelace** [comment]
Thanks for re-opening - see it wasn't just my computer. I think it's just firefox. Worth checking the leaflet issue tracker I think.

**Comment by usr110** [comment]
> Worth checking the leaflet issue tracker I think.

I did - very briefly, but didn't find any issue.

Just to add: there is no issue in Opera and Brave browsers, btw.

I don't know what's going on, for instance [`la-map`](http://npct0.vs.mythic-beasts.com/la-map.html) seems to work fine though.

**Comment by Robinlovelace** [comment]
Something to do with the CSS on the landing page?

**Comment by JDWoodcock** [comment]
I would add that as problems go this is not a bad one. When I first saw it I thought it was probably deliberate.

**Comment by nikolai-b** [comment]
I believe this is caused due to an update in how FF renders leaflet maps rather than our code changing.  Any, https://github.com/npct/pct-shiny/pull/720 fixes it for me!
