### ISSUE TITLE
Make school layer rnet consistent with commute layer

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#704]
@Robinlovelace great to see all this progress on nat build...

My understanding of what you did for the rnet school layer is "the Route Network (LSOA, clickable) and the Route Network (LSOA, image) are built from all origin-destination fast routes within the region."

But am I right that for the commuting layer you are planning to do something different, namely build the route network from all flows starting or ending in the region? It doesn't seem ideal to do it differently for the two layers... though not the end of the world I guess...

**Comment by Robinlovelace** [comment]
@AnnaGoodman1 yes, as discussed, I'm proposing to provide all routes intersecting with each region in the `rnet_full` files for the commute layer. This is better from the perspective of encouraging joined-up, strategic networks.

I suggest that re re-name this issue 're-do regional rnets for schools', to make them consistent - not a priority issue but worth doing IMO. Sound reasonable? Thanks for raising this, and good point from a documentation + communication perspective.

**Comment by AnnaGoodman1** [comment]
yes fine. and to double check, you will do a hard clip of each region at boundaries to avoid the double counting issues?

**Comment by Robinlovelace** [comment]
There are 2 methodologies to prevent double counting:

1. Do a 'hard clip' (aka an intersection, with `st_intersection`) for each region.
1. Combine all the 'internal route networks' and then add the route network resulting from all routes that intersect with the region boundaries.

The first is simpler so yes, going with that. Thanks for double checking and updating the issue. Not a priority ATM but definitely worth doing.

**Comment by AnnaGoodman1** [comment]
@Robinlovelace , Remembering about this issue, in the context of adding a new schools go Cambridge scenario. How about
1) I confirm with DfT they are happy with the scenario
2) I create the go Cambridge scenario, and all associated files except rnet and raster
3) you create new rnets + rasters for all school scenarios, this time using a method comparable to the commute layer. I think it does ideally need to be all scenarios recreated, otherwise different scenarios within the same layer will be using slightly different methods...

**Comment by Robinlovelace** [comment]
Sounds good @AnnaGoodman1, looking forward to Go Cambridge!

**Comment by AnnaGoodman1** [comment]
not 100% consistent still, but good enough and this can close
