### ISSUE TITLE
Manchester all trips layer

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#705]
it shouldnt be showing but it is on pct.bike

**Comment by Robinlovelace** [comment]
@usr110 are you up for taking a look? As I recall it was your great work getting it up. Thanks for spotting that James!

**Comment by usr110** [comment]
Good catch indeed, @JDWoodcock 

Have now created a PR for it: https://github.com/npct/pct-shiny/pull/706

@Robinlovelace would you mind testing it?

**Comment by JDWoodcock** [comment]
it was good catch by @RachelAldred during training (I think training is really useful for bug spotting!) Im just the messanger

**Comment by nikolai-b** [comment]
This is deployed and all trips is no longer available.  Thanks!

**Comment by Robinlovelace** [comment]
Great work @nikolai-b
