### ISSUE TITLE
Reduce memory usage

### ISSUE THREAD

**Issue by nikolai-b** [npct/pct-shiny#707]
Each time a new Rds file is loaded it takes memory, if 10 people look at the same region we open 10 copies of that Rds file.

https://shiny.rstudio.com/articles/scoping.html

It is possible to share this memory but loaded all the Rds files isn't possible (takes ~ 14 Gb and our server only has 8 Gb)

**Comment by Robinlovelace** [comment]
This has been fixed so closing. One danger I can see with this is that if 'bad' data gets loaded, it will persist in the global environment for a long time. I think this is currently happening for http://npct0.vs.mythic-beasts.com/m/?r=cheshire. Thoughts @nikolai-b ? Amazing memory-reducing work in any case, and should not have any negative consequences once all the data is 'good'.
