### ISSUE TITLE
Satellite overlay is tinged with colour

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#71]
The only one that ever gets used is changing the basemap and that's not 'advanced'.

No one ever uses the additional line/zone options: they're confusing.

Suggest we just have a box saying 'Satellite basemap'.

That would simplify things lots - thoughts @nikolai-b @usr110 @JDWoodcock?

**Comment by usr110** [comment]
@Robinlovelace I see that you've changed the options for the base map. The satellite map base doesn't seem very useful. See the image below:


![satellite-map-base](https://cloud.githubusercontent.com/assets/10958628/9875609/3e3e1caa-5ba7-11e5-8883-e851d5ce6594.png)

What do you think?

**Comment by Robinlovelace** [comment]
Hi Alli, the satellite layer is useful, at high zoom levels. It can help identify where there is space of a cyclepath or, in some cases, if there is a cycle path there at all (see image below). Another option would be to have 3 layers: b+w OSM, OpenCycleMap (for identifying paths) and this satellite layer.

One possibility that someone suggested yesterday was only enabling aerial photography below a certain zoom level but that could cause more harm than good!

See below for a concrete example when it's useful: Trinity Way clearly has the width would enable a cycle path along this stretch. That's useful I'm sure you'll agree.

![selection_328](https://cloud.githubusercontent.com/assets/1825120/9879605/0380453e-5bc0-11e5-8d71-6bbe5e814f51.png)

**Comment by Robinlovelace** [comment]
Added thought based on those maps: could we have 'transparency' in the advanced control tab? Or an 'Additional settings' panel that is closed by default? Thanks for your input Ali.

**Comment by usr110** [comment]
Ah ok. That makes sense. Thanks
About the satellite base, the easiest way, in my view, is to incorporate it in our map by changing the colour base, which ideally doesn't have any green in it.
Re additional setting panel, can you please expand on that? I believe once we develop a colour scheme which works for the satellite view, we won't need it. What do you think?

**Comment by Robinlovelace** [comment]
Hi Ali, I think that any colour overlay will interfere with the satellite layer and that it would be advantageous to have "Fill transparency" and maybe also "Line transparency" as additional settings. What do you think? How long would this take to do? I can have a bash if you like but think you're more proficient in this area.

Additional settings panel things I'd like to see:

 - Fill transparency (definitely)
 - Basemap (seems like the right place for it)
 - Line transparency (maybe)

After we've created the panel we can take a look and think about anything that would go well in there. I also think it will look really cool - is it possible to have it closed by default with ShinyJS stuff?

Thanks for these insightful comments.

**Comment by usr110** [comment]
Have introduced a new control called "Fill Transparency" which affects the opacity of zones. Details can be seen at: https://github.com/npct/pct-shiny/commit/35d0fc4e95104625ef35fa820de0294a8d4bce0e

Have also attached a screenshot of it. Please have a look at it.

![fill-transparency](https://cloud.githubusercontent.com/assets/10958628/9958056/a85e500c-5dfd-11e5-82eb-cbd58bf4e903.png)

This control, as you'd expect, shows itself in the same input panel when Cycling Flows is set other than 'none'. Let me know what you think about it?
I might introduce, as you suggested, to have this in an additional panel. Let's see what others think about it.

**Comment by Robinlovelace** [comment]
Hi Ali, great work with the flows slider.

2 issues:

1. It only seems to display when lines are displayed. this adds unnecessary complexity - if it's an addition control it should always or never be there - I couldn't even find it initially! Please change this asap.

2. I think it makes the basic side-panel too long for small screens. I think the additional settings should all be in an additional panel (see below). Sound do-able? 

![selection_331](https://cloud.githubusercontent.com/assets/1825120/9958680/55b431f8-5e04-11e5-8cf7-93b560854775.png)

Overall I think the addition of transparency sliding is a great.

Robin

**Comment by usr110** [comment]
Robin, valid points. Here are my responses:

1) I mentioned that the zone transparency appears only when the Cycling Flows is set other than 'none'. May be you missed that point. I agree that it's cumbersome. Have removed it from the input panel

2) Re screen size, I must say, your screen does make it difficult to introduce a panel. In any case, I now have introduced a separate control at the bottom right of the screen. Give it a try (see for details: https://github.com/npct/pct-shiny/commit/3be8de98bd45c65fbcb802c060c5bcc5af60f3cb). Let me know how it feels like.

**Comment by nikolai-b** [comment]
I've removed advanced controls and update the transparency automatically in 4b5d86a

**Comment by Robinlovelace** [comment]
Hi Nikolai, there is still a distracting colour overlay after your latest commit - re-opening for now...

**Comment by nikolai-b** [comment]
See #72

**Comment by Robinlovelace** [comment]
Closed by https://github.com/npct/pct-shiny/commit/a5f1160b744c422524cfbefe5359c853b33effbf

**Comment by Robinlovelace** [comment]
Closed by https://github.com/npct/pct-shiny/commit/a5f1160b744c422524cfbefe5359c853b33effbf
