### ISSUE TITLE
Satellite map colour overlay

### ISSUE THREAD

**Issue by nikolai-b** [npct/pct-shiny#72]
https://github.com/npct/pct-shiny/issues/71#event-416725402

> Hi Nikolai, there is still a distracting colour overlay on the satellite basemap after your latest commit. Think we agreed there should be no colour overlay on the satellite map so re-opening for now...

**Comment by nikolai-b** [comment]
I'm not sure.  The layer is very transparent so the satellite map is very visible.  What do other people think @usr110 and @JDWoodcock ?

**Comment by Robinlovelace** [comment]
It's more that you won't need it - satellite layer is designed for high zoom levels so generally you'll only see one zone. And it is distracting - see my images here: https://github.com/npct/pct-shiny/issues/71 . May not be a 'blocker' but if it's easy to remove, just do it. I can have a go if you like but you seem to be getting pretty skilled with this shiny/R stuff :-)

**Comment by usr110** [comment]
I agree with @nikolai-b on this that the road network, when zoomed enough, doesn't look distracting to me. However, I still find it difficult to see the zone colours (and their boundaries) with the satellite map base. There are two things which can be done: either increase the opacity of zones when above a certain zone level, or introduce a new colouring schemes of zones which doesn't interfere with the base (non-green scheme). What do you think?

**Comment by JDWoodcock** [comment]
I would suggest this is also something that could be presented as  options for a Friday meeting. If there is a disagreement seems a good thing to take to meeting.

**Comment by Robinlovelace** [comment]
@usr110 as I've said [here](https://github.com/npct/pct-shiny/issues/73) I think we should re-add your sliders in an 'Additional controls' panel. This would address all issues and give the user more control beyond the (fairly sensible, but not universally appropriate) default settings. Sound good @npct/owners ?

**Comment by usr110** [comment]
@Robinlovelace Another point to discuss on Monday then.

**Comment by Robinlovelace** [comment]
:+1:
