### ISSUE TITLE
bug on landing page

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#726]
![image](https://user-images.githubusercontent.com/11028720/56952950-5bd99100-6b33-11e9-8407-f823c853a3c0.png)
you can't select scenario and layer on the landing page at the same time- either one or the other with the radio buttons
@nikolai-b @Robinlovelace

**Comment by RachelAldred** [comment]
This isn't showing as fixed yet on the live server although I can see it on the test server. Just waiting for it to be fixed to send the near market blog live.

**Comment by Robinlovelace** [comment]
Fixed now, thanks to @nikolai-b and @usr110 - see http://www.pct.bike/. Finally I think the near market blog is good to go.

**Comment by JDWoodcock** [comment]
thanks
