### ISSUE TITLE
App can be put into infinite loop

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#727]
By selecting School travel then Commuting from the Trip purpose dropdown, as illustrated below. Not sure if there other ways of triggering this undesirable behaviour. @nikolai-b do you know how to at least turn this off? An infinite loop has been running for a few minutes on 2 computers. When I refresh, it stops but not sure if the server is still in a loop.

![Peek 2019-04-30 10-37](https://user-images.githubusercontent.com/1825120/56953456-8c6dfa80-6b34-11e9-89f8-e235f7df09de.gif)

**Comment by Robinlovelace** [comment]
Update: de-prioritised as I cannot reproduce it. @layik suggests it may be a browser glitch. One test - please try to reproduce @nikolai-b and @usr110 .

**Comment by usr110** [comment]
Can't reproduce it, so closing it now

Please re-open if you can find it again @Robinlovelace

**Comment by Robinlovelace** [comment]
Cheers for testing @usr110 - it was quite an usual sequence of UI interactions in quick succession that caused that behaviour may have just been a one off.
