### ISSUE TITLE
Landing page map: layers are not turn off based on the selected scenario

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#729]
So glad that the [radio button bug](https://github.com/npct/pct-shiny/issues/726) was resolved - good job there @nikolai-b. Just testing it a bit more produced another bug. The travel layer (either `commute` or `school`) is not reactive based on the scenario a user has selected. So for instance it should disable `school` layer for `Gender Equality` scenario, which it doesn't. To reproduce it, select `commute` layer, and then select `Gender Equality` - this should disable `school` layer, but it doesn't. See below:

![image](https://user-images.githubusercontent.com/10958628/57011878-9d357380-6bfb-11e9-8478-49bceab46ff7.png)

**Comment by JDWoodcock** [comment]
it seems to work fine for me

**Comment by usr110** [comment]
@JDWoodcock you might be looking at the live server, not test.

**Comment by JDWoodcock** [comment]
yes I see the  problem well spotted

**Comment by Robinlovelace** [comment]
Well spotted Ali. One to fix before we update production.

**Comment by nikolai-b** [comment]
@usr110 great checking, I only checked disabling one way round (that School disable scenarios).

**Comment by usr110** [comment]
Now tested it on the test-server. Seems to work fine. Great job @nikolai-b :+1:
