### ISSUE TITLE
Link to near market blog on front page

### ISSUE THREAD

**Issue by RachelAldred** [npct/pct-shiny#734]
Hi @nikolai-b and @usr110 - would you be able to link to the new PCT blog from the front page? Thanks :) The link is https://blog.pct.bike/2019/05/02/new-pct-commute-layer-government-target-near-market/ and it should be linked from the text saying "New 'near market' scenario" at bottom right.

**Comment by usr110** [comment]
@RachelAldred I already have added this to the repo - waiting for it to be accepted by either @Robinlovelace or @nikolai-b  (see here: https://github.com/npct/pct-shiny/pull/733)

Should've dropped you an email about it - apologies.

**Comment by RachelAldred** [comment]
Thanks @usr110 .
