### ISSUE TITLE
LSOA image layer not there

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#736]
doesn't load on either main server or test server (LSOA clickable is fine)

**Comment by Robinlovelace** [comment]
Seems to be there for the[ Isle of Wight](http://www.pct.bike/m/?r=isle-of-wight): 

![image](https://user-images.githubusercontent.com/1825120/58207139-fd3ea780-7cd9-11e9-9c95-596289555878.png)

**Comment by Robinlovelace** [comment]
Also verified it's working for West Yorkshire. One question: what ISP were you using when it didn't work? It was failing on Eduroam for me on Monday, not sure if it was failing everywhere then.

**Comment by nikolai-b** [comment]
There was a problem with the SSL certificate renewal. The cert was out of date but only a month old. Not sure why. I deleted it and requested a new one.

**Comment by Robinlovelace** [comment]
Thanks for the explanation and quick fix.
