### ISSUE TITLE
pct down?

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#737]
PCT not loading for me, is it working for you? I get the front page but can't click on any region, it does not progress. Test server fine.
@Robinlovelace , @nikolai-b , @usr110

**Comment by nikolai-b** [comment]
The site is working for me. Is it still down for you @AnnaGoodman1 ?

**Comment by Robinlovelace** [comment]
Fine for me also, so closing for now.

![image](https://user-images.githubusercontent.com/1825120/59067623-09199480-88aa-11e9-891b-a48b2ac7d464.png)

**Comment by Robinlovelace** [comment]
Have also tried London. No other regions tested. Thanks for reporting, let us know if it happens again.

**Comment by AnnaGoodman1** [comment]
sorry, yes, now fine. not sure what happened

**Comment by Robinlovelace** [comment]
> now fine

Great. Closing for now.
