### ISSUE TITLE
rq data wrong in commute lsoa layer

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#738]
[anna working on fixing]

**Comment by Robinlovelace** [comment]
Thanks for heads-up. If there are more details/a fix by workshops this Thursday/Friday pls let us know. Heads-up @RachelAldred.

**Comment by AnnaGoodman1** [comment]
@Robinlovelace , @RachelAldred 

I have fixed the problem with the PCT rq data (sorry again), it is now just a case of loading the very large files from my laptop onto Github – which might take a day or two. I can prioritise any regions that will be particularly important for your training? Otherwise I will let you know when done

**Comment by Robinlovelace** [comment]
Isle of Wight please. And perhaps London if your 💻  can handle that early on. Many thanks for very quick fix.

**Comment by RachelAldred** [comment]
Hi Anna, if any chance it would be great to have Lancashire correct for tomorrow's training as that's the data we download for most of the exercises. People also look at their own areas but I can just flag up that we only just saw the problem and are fixing :)

**Comment by AnnaGoodman1** [comment]
geojson and csv download files for Lancashire fixed, I think, but not yet the R download and therefore LSOA rq data still not right on the interface (when you click the green lines it gives the rf distance)

**Comment by AnnaGoodman1** [comment]
downloads now fixed, will also be fixed on interface after this PR https://github.com/npct/pct-shiny/pull/741

**Comment by AnnaGoodman1** [comment]
just re-opening as a reminder to push the fix to live server - can you do this, @nikolai-b ?

**Comment by AnnaGoodman1** [comment]
@nikolai-b , re-reminding on this...could we push to live this week, before rachel trains next week?

**Comment by RachelAldred** [comment]
That would be great. My training is on Tuesday :)
