### ISSUE TITLE
tweaks to schools layer

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#739]
- [ ] - the dropdown box for ‘order lines by’ also exists for Census 2011 data, and it shouldn’t (there is no health benefit to order by). .

**Comment by Robinlovelace** [comment]
Heads-up @nikolai-b and @usr110 could either of you take a look? Can do but snowed under rest of this week.

**Comment by AnnaGoodman1** [comment]
@RachelAldred I was just having a look at this, but actually not sure what you mean? (text above was copied from your email) In the census layer it is correct that one can order by reduction in deaths, but I don't think one can order by that in the schools layer – e.g. see image below. Am I missing something/ looking in the wrong place?
![Untitled](https://user-images.githubusercontent.com/11818225/59879203-0d61a980-93a2-11e9-97dd-b540644c95f3.png)

You said there were also some other little point that you  noticed, if you want to put them here I/we can try to look at them really appreciate having your eye on this

**Comment by RachelAldred** [comment]
Hi Anna, sorry for confusion, I didn't mean the schools layer but the commute layer, where if you don't have a scenario on you can still order lines by increases in cyclists or benefits, but there aren't any as no scenario. See bottom right in image.
![image](https://user-images.githubusercontent.com/11818218/59904323-1894f380-93fb-11e9-88c8-a7af798dd79b.png)

**Comment by AnnaGoodman1** [comment]
Oh right, yes, I see - I think this pull request fixes the problem https://github.com/npct/pct-shiny/pull/741 . (Also, unrelatedly, fixes an inconsistent capitalisation issue that had been slightly annoying me)

**Comment by Robinlovelace** [comment]
Fixed in #741 - no dropdown:

![image](https://user-images.githubusercontent.com/1825120/60016544-6ff6c600-967e-11e9-8e9e-a6895b2675a7.png)
