### ISSUE TITLE
Cycling Flows disappear when either Scenario or Zone Attribute changes

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#74]
With the new changes, it seems, the lines (cycling flows) disappear when either scenario or zone attribute changes. It might have to do with this commit: https://github.com/npct/pct-shiny/commit/9e6a674d26f2e07123e37c337ced08d06195b023

**Comment by usr110** [comment]
Let me use an example to expand on this. So firstly I select gender-equality scenario with 4 four lines to display. 

![gender-equality](https://cloud.githubusercontent.com/assets/10958628/10078743/16021be0-62de-11e5-80d1-7dd44fdeeeb1.png)

And then when I change the scenario to the default one - census 2011, the lines disappear.
![census](https://cloud.githubusercontent.com/assets/10958628/10078758/38991302-62de-11e5-8be4-7964dc358c36.png)

**Comment by Robinlovelace** [comment]
Thanks for the clear reproducible example. @nikolai-b will probably take a look soon (we're meeting up)!

**Comment by usr110** [comment]
Great! Best of luck.

**Comment by usr110** [comment]
@nikolai-b The problem hadn't been fixed - still had issues with lines being not redrawn. I have fixed it (https://github.com/npct/pct-shiny/commit/077f8646eea66416dcabc00ef949591311099718). Please give it a try.

**Comment by Robinlovelace** [comment]
Many thanks for double-checking this - really important to have it working. I just tested on my computer and could reproduce. Then I pulled https://github.com/npct/pct-shiny/commit/077f8646eea66416dcabc00ef949591311099718 and it's fixed. I've pushed to production - feel free to close @usr110 if you're happy with it.

**Comment by usr110** [comment]
@Robinlovelace Great to know and thanks for testing it out.
