### ISSUE TITLE
App ran out of memory and it did not restart

### ISSUE THREAD

**Issue by nikolai-b** [npct/pct-shiny#742]
When @RachelAldred was demonstrating the pct it ran out of memory (RAM) it exited with an error but it was not automatically restarted #740 

### ~~Why did it run out of memory~~

See #746

### Why did it not restart?

Systemd monitors shiny-server and should restart it if it fails.  We are using a modified version of [shiny-server.service](https://github.com/rstudio/shiny-server/blob/v1.5.9.923/config/systemd/shiny-server.service) that is old.  We should update it and it should live inside this repo.

**Comment by Robinlovelace** [comment]
I'm not sure updating shiny-server will fix it - have you seen anything about restart rules in recent changes? There are only 150 commits since v1.5.1, which I guess was the latest version around the time we started: https://github.com/rstudio/shiny-server/releases/tag/v1.5.1.834

Good to update software in any case, and there is a continuum of changes from small (e.g. refactoring the '100 regions' code to large (e.g. switching to sf, which is faster and more memory efficient) which updating shiny-server somewhere in the middle. How about investigating why it ran out of memory as a first port of call? BTW I've tested running `pct-shiny` on the latest version of R and all the packages and it works fine, so another 'middle' option is to update R: 3.5.0 contains some performance enhancements. I did it in a docker container but re-installing it on the server is also an option.

**Comment by nikolai-b** [comment]
We are running the latest shiny-server 1.5.9.923 and R 3.3.3.  The R version is the version in the  debian packages and I would prefer to not alter that unless there is some compelling reason.

I think I identified the reason why it [didn't restart](https://github.com/npct/pct-shiny/issues/742#issue-460087175) but I'm unable to reproduce the memory increase.  I tried opening lots of regions and checked the memory usage on that server but it didn't seem to increase that much :thinking:, I'll retry and check locally then report back.

For completeness...

Here a the logs from shiny-server:

```
[2019-06-19T20:18:56.434] [INFO] shiny-server - Error getting worker: Error: The application exited during initialization.

<--- Last few GCs --->

[28160:0x2cc5720] 3898573185 ms: Mark-sweep 29.9 (46.2) -> 18.3 (28.8) MB, 17.5 / 0.1 ms  (+ 51.5 ms in 35 steps since start of marking, biggest step 10.0 ms, walltime since start of marking 70 ms) finalize incremental marking via task GC in old space req[28160:0x2cc5720] 3898574239 ms: Mark-sweep 18.3 (28.8) -> 18.3 (24.8) MB, 14.2 / 0.0 ms  (+ 38.0 ms in 43 steps since start of marking, biggest step 1.5 ms, walltime since start of marking 53 ms) finalize incremental marking via task GC in old space requ

<--- JS stacktrace --->

FATAL ERROR: NewArray Allocation failed - process out of memory
 1: node::Abort() [/opt/shiny-server/ext/node/bin/shiny-server]
 2: 0x8c21ec [/opt/shiny-server/ext/node/bin/shiny-server]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [/opt/shiny-server/ext/node/bin/shiny-server]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/opt/shiny-server/ext/node/bin/shiny-server]
 5: 0xa2f61b [/opt/shiny-server/ext/node/bin/shiny-server]
 6: v8::internal::RegExpStack::EnsureCapacity(unsigned long) [/opt/shiny-server/ext/node/bin/shiny-server]
 7: v8::internal::NativeRegExpMacroAssembler::GrowStack(unsigned char*, unsigned char**, v8::internal::Isolate*) [/opt/shiny-server/ext/node/bin/shiny-server]
 8: 0x1bc26d9daa1d
```

And the systemd logs:

```
# systemctl status shiny-server.service -l
● shiny-server.service - shiny-server
   Loaded: loaded (/etc/systemd/system/shiny-server.service; enabled)
   Active: active (running) since Mon 2019-05-06 11:58:05 BST; 1 months 14 days ago
 Main PID: 28160
   CGroup: /system.slice/shiny-server0.service
           ├─5478 su -s /bin/bash --login -p -- shiny -c cd \/var\/shiny\/pct-shiny\/regions\_www\/m && R --no-save --slave -f \/opt\/shiny-server\/R\/SockJSAdapter\.R
           ├─5479 -su -c cd \/var\/shiny\/pct-shiny\/regions\_www\/m && R --no-save --slave -f \/opt\/shiny-server\/R\/SockJSAdapter\.R
           └─5482 /usr/lib/R/bin/exec/R --no-save --slave -f /opt/shiny-server/R/SockJSAdapter.R

Jun 20 13:36:01 npt1 su[5478]: Successful su for shiny by root
Jun 20 13:36:01 npt1 su[5478]: + ??? root:shiny
Jun 20 13:36:01 npt1 su[5478]: pam_unix(su:session): session opened for user shiny by (uid=0)
Jun 20 13:41:30 npt1 su[5878]: Successful su for shiny by root
Jun 20 13:41:30 npt1 su[5878]: + ??? root:shiny
Jun 20 13:41:30 npt1 su[5878]: pam_unix(su:session): session opened for user shiny by (uid=0)
Jun 20 14:09:13 npt1 su[7816]: Successful su for shiny by root
Jun 20 14:09:13 npt1 su[7816]: + ??? root:shiny
Jun 20 14:09:13 npt1 su[7816]: pam_unix(su:session): session opened for user shiny by (uid=0)
Jun 20 14:54:28 npt1 bash[28158]: /bin/bash: line 1: 28160 Aborted                 /opt/shiny-server/bin/shiny-server --pidfile=/var/run/shiny-server-0.pid /etc/shiny-server/shiny-server-0.conf >> /var/log/shiny-server-0.log 2>&1
```

And here is graph of memory usage around the time the server ran out of memory 
![memory-restart](https://user-images.githubusercontent.com/6289830/60214141-d5a0a900-985c-11e9-96fa-f8d7da62b56f.png)

**Comment by Robinlovelace** [comment]
Thanks for the detail @nikolai-b. Don't have any follow-on suggestions.

**Comment by usr110** [comment]
@nikolai-b might be useful to test it more methodically using [`shinyloadtest`](https://rstudio.github.io/shinyloadtest/index.html)
