### ISSUE TITLE
New data cannot be read by R

### ISSUE THREAD

**Issue by nikolai-b** [npct/pct-shiny#744]
On London the LSOA's cause the test servers to crash (and will do on the production server) with:

> Error in readRDS: cannot read workspace version 3 written by R 3.6.0; need R 3.5.0 or newer

I can try to upgrade them but this makes the already complicated process of setting up a new server a bit more complicated.  We could also use the version in `saveRds`:

```R
saveRds(rdsfile, version = 2)
```

**Comment by Robinlovelace** [comment]
Yes re-saving the new data should do it.

**Comment by AnnaGoodman1** [comment]
oh no, what a pain. Yes I agree that re-saving is best, but it may take me several days to re-push all the files to git. in the meantime I have just pushed for avon region, @nikolai-b can you see if Avon runs on test server now? see https://github.com/npct/pct-shiny/pull/745

**Comment by Robinlovelace** [comment]
Heads-up @AnnaGoodman1 I'm up for doing it from work desktop with fast connection. Let me know if that would help.

**Comment by AnnaGoodman1** [comment]
Thanks Robin, very kind - I have now re-saved all the files and am starting to push them. So let's see how I go over the weekend, hopefully should be finished by Monday – but if looking unbearably slow we could rethink...

**Comment by Robinlovelace** [comment]
OK Anna, good luck with it. Just ping me here if you want me to push any/all of the files.

**Comment by AnnaGoodman1** [comment]
@nikolai-b , I think now ok? see here... https://github.com/npct/pct-shiny/pull/748
