### ISSUE TITLE
need to renew PCT cyclestreets server?

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#760]
Our annual licence to use the special PCT cycle streets server expires in August. I don't think we need to renew it, since we are not doing any more national builds in this current contract and so the existing rf/rq files should be all we need? But if anyone thinks they will want to use our server for any purpose we could ask for a half-year extension at half price - or indeed just pay an additional £1k for full extra year.  But if it isn't going to be used we might as well instead put that £1k towards eg Nikolai's time/mythic beasts costs of keeping the PCT websites running for longer into the future. 

this probably is mostly for @Robinlovelace , but cc-ing @mem48 & @usr110  in case

**Comment by Robinlovelace** [comment]
Thanks for raising this Anna, cannot think of any direct need and they may be flexible if we do decide we want to do something. Will have a think.

**Comment by AnnaGoodman1** [comment]
what do you think robin, shall I ask them to cancel it?

**Comment by mvl22** [comment]
Hi folks - just to say that we can do part of a year - Mythic Beasts can charge us on a monthly basis or cancellation part-way.

(The server does cost us real money to keep online, so we can't keep it running speculatively if there isn't income to do so.)

**Comment by Robinlovelace** [comment]
May be wise to extend it until the end of the contract, if we want to update the routing one last time in autumn. If not, no need to update the server is my thinking. Thanks for the info @mvl22

**Comment by AnnaGoodman1** [comment]
thanks v much @mvl22 . @Robinlovelace , I really don't want to do another national build - we did one just a couple of months ago and they are quite time consuming. ok if we decide now not to do another nat build and so don't renew?

**Comment by Robinlovelace** [comment]
Sounds like a good plan @AnnaGoodman1, was just wondering if it would be a plan to update it one more time before the end of the Phase III contract (we should think about what we do after that ends in March 2019). Agree it would be a lot of work for a relatively small benefit, compared with the previous rebuild. So closing for now.

**Comment by AnnaGoodman1** [comment]
great, yes, esp since contract actually ends 1 December 2019, not next March. We haven't promised DfT to do a further nat build, and I think if we were going to do a large amount of extra work it would be much better to focus on some other aspect of PCT, e.g. training or speeding up the interface. 

@mvl22 , perhaps you could decommission the server with mythic beasts? And let us know if there is any final (for now) amount we owe you to cover server costs and input.  And once again thank you so very much for having hosted this special server for us , it has been invaluable along the way. Hopefully we may work together again if or when further PCT stages, or similar projects,  are commissioned.

**Comment by mvl22** [comment]
No problem - can you just e-mail us formally to info@ at our domain and we'll decommission it and not renew the contract. Yes, it's been great being involved in this project!

**Comment by AnnaGoodman1** [comment]
great, done. Thanks Martin!
