### ISSUE TITLE
Deploy Go Cambridge scenario

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#764]
We should be able to do this next week with the tiles built (see image below, they just finished on my work desktop - see [here for .zip](https://github.com/npct/pct-scripts/releases/tag/0.0.2)) and these 2 PRs in place:

Changes to the UI: https://github.com/npct/pct-shiny/pull/752

Changes to the build script: https://github.com/npct/pct-scripts/pull/84

Still to do:

- [x] Check the updated rnet data (@AnnaGoodman1 , ~0.5 hours?)
- [x] Add the full and server rnets Rds files to the `pct-outputs-regional-R` repo (Robin, ~0.5 hours)
- [x] Add the full .geojson files to the `pct-outputs-regional-notR` repo (Robin, ~0.5 hrs)
- [x] Download, upload and test the new tiles on the server (@nikolai-b , ~1hr?)
- [x] update region stats files (@Robinlovelace , @AnnaGoodman1 , ~0.5 hours)
- [x] Update the front page map (@nikolai-b , ~0.5 hrs?)
- [x] Test the UI changes (@nikolai-b, 0.5 hrs?)
- [x] Merge and deploy to test server (@nikolai-b , 1hr?)
- [x] Test on test server (@AnnaGoodman1, @RachelAldred, @usr110 , 0.5 hrs total?)
- [x] Deploy to production (@nikolai-b 0.5 hours + checking logs?)

Heads-up @nikolai-b please find some time over the coming week to put the new tileset on the server + test the deployment. Also planning to close https://github.com/npct/pct-shiny/issues/704 when I upload all the new regional rnets.

![image](https://user-images.githubusercontent.com/1825120/61559407-861b5a80-aa61-11e9-8c7b-6429a9bcc250.png)

**Comment by Robinlovelace** [comment]
Update: I've pushed some test regional rnets for the Isle of Wight: https://github.com/npct/pct-outputs-regional-R/commit/2a9fdfb5e8eee0a4d07ca316cbd2fa8ff96aeea2

Heads-up @AnnaGoodman1 I plan to push this data for all regions by Weds next week so if you get a chance to download and check these files before then, that would be great.  Seem good to me:

```
rnet_single
class       : SpatialLinesDataFrame 
features    : 1040 
extent      : -1.54331, -1.07968, 50.58679, 50.76328  (xmin, xmax, ymin, ymax)
crs         : +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0 
variables   : 5
names       : local_id, bicycle, govtarget_slc, cambridge_slc, dutch_slc 
min values  :     9074,       3,             3,             3,         3 
max values  :   296168,      30,            58,           394,       829 
> rnet_to_serve
class       : SpatialLinesDataFrame 
features    : 982 
extent      : -1.54331, -1.07968, 50.58679, 50.76328  (xmin, xmax, ymin, ymax)
crs         : +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0 
variables   : 5
names       : local_id, bicycle, govtarget_slc, cambridge_slc, dutch_slc 
min values  :     9074,       3,             3,             3,         3 
max values  :   296168,      30,            58,           394,       829 
```

**Comment by AnnaGoodman1** [comment]
Hi @Robinlovelace ,

the shape file path looks good, but the attribute data I think is not quite right in terms of how you've done the anonymisation.

The code I sent you earlier to do it was:   

rnet@data$bicycle[rnet@data$bicycle>0 & rnet@data$bicycle<=2] <- NA
  for(i in c("govtarget_slc","cambridge_slc","dutch_slc")){
    rnet@data[[i]][is.na(rnet@data$bicycle) & rnet@data[[i]]<=2] <- NA
  }

i.e. 1 or 2 gets anonymized on 'bicycle', and any scenario gets anonymized if bicycle is 1 or 2 and the scenario value is <2 (i.e. 1). This fits with what we have at the moment.

But you seem to have NA also for bicycle==0 or scenario value==2. It is not a huge deal, but is a bit less informative, plus would require changing the UI and the user manual. Could you instead re-run the anonymized nation code on the full, private rnets to do it like we did before? (or I could if you share those). I think you could leave the .tif files unchanged...

Thanks!

**Comment by Robinlovelace** [comment]
Well spotted @AnnaGoodman1. I was overly conservative, converting *all* low values to NA. Just updated the code and the results are as below for national data. Please double check:

- Updated code in PR for school rnet build: https://github.com/npct/pct-scripts/pull/84/commits/ce1194875ca1cb8dbcefa6fb7615b4cde763cd8b
- New national data: https://github.com/npct/pct-outputs-national/commit/eeac7957525114e1d29ab6ba7da05b917c62da0d
- New test data for Isle of Wight: https://github.com/npct/pct-outputs-regional-R/commit/07d996d9de7762048649f5581c1b83e3f8b05d53

Assuming that's all good, and when @nikolai-b unzips and the new school tiles I think we can look to test the UI. One other change that Nikolai reminded me of today is the need to update the front page map.

Reminder to self: we'll also need to update the files in the 'notR' regional outputs repo.



```
summary(as.factor(rnet_all_sp$bicycle))
      0       3       4       5       6       7       8       9      10      11      12 
 232784   26626   19046   14238   11199    8589    6893    5640    4795    3896    3437 
     13      14      15      16      17      18      19      20      21      22      23 
   2921    2574    2267    2068    1783    1597    1373    1246    1142     947     912 
     24      25      26      27      28      30      29      32      31      33      34 
    851     763     732     645     633     553     550     467     452     427     371 
     36      37      35      38      40      39      41      43      46      45      44 
    348     346     337     307     273     262     245     217     217     216     211 
     42      49      47      48      51      52      58      50      53      57      59 
    209     194     169     159     143     141     138     137     129     114     114 
     54      56      55      61      62      69      64      60      68      66      63 
    108     108     106      95      95      86      85      84      74      73      71 
     67      65      76      71      72      73      74      77      90      78      85 
     71      65      64      60      59      58      52      52      49      48      48 
     70      80      84      89      75      79      82      91      94      87      93 
     47      47      47      46      40      40      40      34      34      32      32 
     95      83      86      97      92      81     103     104     111      88 (Other) 
     32      31      31      30      29      25      25      23      23      22     998 
   NA's 
 119629 
> summary(as.factor(rnet_all_sp$govtarget_slc))
      0       1       3       4       2       5       6       7       8       9      10 
  87808   56768   39253   31420   30749   25589   20929   17851   14945   12968   11393 
     11      12      13      14      15      16      17      18      19      20      21 
   9630    8684    7583    6635    5888    5177    4591    4136    3755    3485    3102 
     22      23      24      25      26      27      28      29      30      31      32 
   2794    2489    2325    2101    1959    1828    1661    1533    1465    1309    1217 
     34      33      35      36      38      37      39      41      40      42      43 
   1049    1046    1020     850     760     753     735     646     639     634     621 
     44      45      46      47      48      49      50      51      52      54      53 
    555     506     504     494     422     407     382     372     362     341     331 
     56      57      58      60      59      64      55      61      62      63      65 
    314     288     281     265     263     257     254     250     240     223     190 
     70      67      66      71      72      69      68      73      75      78      76 
    177     164     162     153     150     143     141     141     138     136     133 
     74      77      79      84      80      82      81      83      85      87      86 
    129     118     114     101      99      98      96      96      91      88      81 
     88      91      89      99      90      94      95      96      93      92 (Other) 
     81      80      72      64      61      60      60      58      57      56    2168 
   NA's 
  35151 
```

**Comment by Robinlovelace** [comment]
Heads-up all, I've added rough estimates of timing to try to work out when we'll be able to do this. I can do my tasks by Friday. It would be great @nikolai-b and all if you could also let us know if these seem doable next week. Thanks.

**Comment by nikolai-b** [comment]
Hi,

I can try and get some done Monday and Tuesday night.  I'll do my best to get my stuff done by Friday.  Is there a hard deadline?  Due to the seriousness of #759 I spent quite a bit of time on that hence this issue hasn't had my priority.

**Comment by Robinlovelace** [comment]
No hard deadline on this @nikolai-b and quality of work is more important than speed of work on this for sure.

**Comment by AnnaGoodman1** [comment]
looks good now @Robinlovelace . Only thing is the variable 'local_id' is still missing. But maybe we should just drop this variable altogether? I have checked and actually it is not a good variable in the commute rnet, since the same ID variable is replicated multiple times (e.g. 44 repetitions of ID 323). So I suggest either we regenerate a local ID variable both for the school and commute rnet_all files, with each ID being truly unique, or else I remove this variable from the commuting rnet files. Any preference? removing if from commute files probably less work...?

and please don't worry at all if it takes longer than this week to do your parts @nikolai-b  , as Robin says there is no firm deadline on this and I appreciate you have recently been spending lots of time fixing the much more important memory issues

**Comment by Robinlovelace** [comment]
Hi @AnnaGoodman1 I say let's remove the local ID variable, I cannot think of anyway that it could be useful to anyone.

**Comment by AnnaGoodman1** [comment]
Actually sorry @Robinlovelace , the data looks fine but the shiny app cannot run on them. I'm not completely sure why.  possibly they do need local_id after all (see line 254 of server.R)?  does that local_id tell R which segments to run, perhaps? does it need to match the ID inside the lines slot?

**Comment by AnnaGoodman1** [comment]
so maybe local_id is a variable we need, although not of use to outsiders - so perhaps we need it in the server-facing rnet.R files, but not in the public-facing download rnet_full files

**Comment by AnnaGoodman1** [comment]
(still seems potentially problematic to me that local_id values repeat themselves.... but maybe not bad enough to try to do anything about)

**Comment by AnnaGoodman1** [comment]
hi again (!). yes, issue is we need local_id. this code fixes it.  do you want to apply it to all your files, Robin?

rnet <- readRDS("C:/Users/Anna Goodman/Dropbox/GitHub/pct-outputs-regional-R/school/lsoa/isle-of-wight/rnet.Rds")
for (i in (1:nrow(rnet))) {
rnet@data$local_id[i] <- as.numeric(rnet@lines[[i]]@ID)
}
rnet@data <- rnet@data[, c(5,1:4)]

saveRDS(rnet, "C:/Users/Anna Goodman/Dropbox/GitHub/pct-outputs-regional-R/school/lsoa/isle-of-wight/rnet.Rds", version = 2)

**Comment by nikolai-b** [comment]
Yes, we used to generate the `id` on load but we changed it https://github.com/npct/pct-shiny/commit/3cad4e3068134bd26d7809df01126c1d376dd18e#diff-e742b53b5986fdf6e52477865d38ea79L101

We need an ID so we can highlight a section of the route network when clicked and as it is named in the download I'd be reluctant to change it now but I can check the rnet locally with: 

```diff
diff --git i/regions_www/m/server.R w/regions_www/m/server.R
index 0c86094..0d0c885 100644
--- i/regions_www/m/server.R
+++ w/regions_www/m/server.R
@@ -251,7 +251,7 @@ shinyServer(function(input, output, session) {
         rds <- readRDS(filepath)
         if(filename == "rnet.Rds") {
           if(!is.null(rds)){
-            rds$id <- rds$local_id
+            rds$id <- 1:nrow(rds)
           }
         }
         if(filename == "rq.Rds"){
```

and it looks fine.

**Comment by nikolai-b** [comment]
@Robinlovelace in https://github.com/npct/pct-scripts/releases/tag/0.0.2 there are two zip files:

new-school-tiles.zip 186 MB
school_cambridge_slc.zip 55.8 MB

Would you mind telling me exactly what you want me to do with them?  Am I just uploading the Cambridge SLC or the full new school tiles to the tile server?

**Comment by Robinlovelace** [comment]
Hi @nikolai-b use the `new-school-tiles.zip`, which contains the Cambridge tiles (I uploaded that for testing). Update all of them for #704 .

**Comment by Robinlovelace** [comment]
OK let's go back to having local IDs, they could be useful if people ever want to refer to a specific segment (although they will not be stable with each release). @AnnaGoodman1 first time round numbered from 1 to ~1 million across the national rnet. My default plan is to update the national and test IoW rnet files with a `local_id` column.

**Comment by AnnaGoodman1** [comment]
@Robinlovelace 

in terms of creating the region stats file, what thresholds are you using to subset rnet_full to rnet? In the commute layer, these two were identical for most regions but e.g. for greater Manchester you only included segments with at least 30 in go Dutch, for London you only included segments with at least 100 in go Dutch. I assume you are using the same sort of principle for the schools layer, if you give me the details I will update region stats.

**Comment by Robinlovelace** [comment]
@AnnaGoodman1 

Sure. In the process of building all route networks the thresholds are set on-the-fly. So far done the following regions. Update, with values for each, incoming.

```
Done for region london
Done for region greater-manchester
Done for region liverpool-city-region
Done for region south-yorkshire
Done for region north-east
Done for region west-midlands
Done for region warwickshire
Done for region west-yorkshire
Done for region cheshire
```

**Comment by Robinlovelace** [comment]
|region_name                  | rnet_lsoa_shiny_dutch_slc_min| rnet_lsoa_shiny_n_row| rnet_lsoa_full_n_row| build_start_time| build_end_time|
|:----------------------------|-----------------------------:|---------------------:|--------------------:|----------------:|--------------:|
|london                       |                           170|                 20362|                81333|       1563791239|     1563791279|
|greater-manchester           |                            30|                 19122|                28205|       1563791279|     1563791298|
|liverpool-city-region        |                             0|                 17206|                17220|       1563791298|     1563791314|
|south-yorkshire              |                             0|                 13342|                13359|       1563791314|     1563791330|
|north-east                   |                            10|                 19676|                23738|       1563791330|     1563791349|
|west-midlands                |                            30|                 20610|                29447|       1563791349|     1563791371|
|warwickshire                 |                             0|                  9445|                 9465|       1563791371|     1563791384|
|west-yorkshire               |                             0|                 22709|                22728|       1563791384|     1563791408|
|cheshire                     |                             0|                  9577|                 9590|       1563791408|     1563791423|
|lancashire                   |                             0|                 15832|                15856|       1563791423|     1563791441|
|humberside                   |                             0|                  7080|                 7087|       1563791441|     1563791451|
|north-yorkshire              |                             0|                  5925|                 5948|       1563791451|     1563791473|
|derbyshire                   |                             0|                 10510|                10528|       1563791473|     1563791490|
|leicestershire               |                             0|                 10010|                10021|       1563791490|     1563791505|
|nottinghamshire              |                             0|                 10734|                10752|       1563791505|     1563791519|
|hereford-and-worcester       |                             0|                  7477|                 7487|       1563791519|     1563791534|
|shropshire                   |                             0|                  3441|                 3448|       1563791534|     1563791544|
|staffordshire                |                             0|                 13165|                13187|       1563791544|     1563791563|
|avon                         |                             0|                 12146|                12204|       1563791563|     1563791576|
|devon                        |                             0|                  8478|                 8530|       1563791576|     1563791591|
|dorset                       |                             0|                  6431|                 6450|       1563791591|     1563791603|
|wiltshire                    |                             0|                  5861|                 5903|       1563791603|     1563791612|
|cambridgeshire               |                             0|                  6576|                 6631|       1563791612|     1563791623|
|bedfordshire                 |                             0|                  6101|                 6106|       1563791623|     1563791635|
|essex                        |                             0|                 14773|                14808|       1563791635|     1563791657|
|kent                         |                             0|                 14377|                14397|       1563791657|     1563791672|
|berkshire                    |                             0|                 10041|                10066|       1563791672|     1563791684|
|buckinghamshire              |                             0|                 10090|                10114|       1563791684|     1563791700|
|east-sussex                  |                             0|                  5878|                 5909|       1563791700|     1563791708|
|hampshire                    |                             0|                 17447|                17499|       1563791708|     1563791727|
|isle-of-wight                |                             0|                  1034|                 1040|       1563791727|     1563791732|
|cornwall-and-isles-of-scilly |                             0|                  2967|                 2977|       1563791732|     1563791741|
|cumbria                      |                             0|                  3302|                 3304|       1563791741|     1563791749|
|gloucestershire              |                             0|                  5007|                 5026|       1563791749|     1563791761|
|hertfordshire                |                             0|                 12128|                12145|       1563791761|     1563791779|
|lincolnshire                 |                             0|                  4224|                 4228|       1563791779|     1563791793|
|norfolk                      |                             0|                  6750|                 6785|       1563791793|     1563791802|
|northamptonshire             |                             0|                  6362|                 6367|       1563791802|     1563791813|
|northumberland               |                             0|                  2614|                 2621|       1563791813|     1563791822|
|oxfordshire                  |                             0|                  5727|                 5770|       1563791822|     1563791833|
|somerset                     |                             0|                  3977|                 3989|       1563791833|     1563791843|
|suffolk                      |                             0|                  5853|                 5879|       1563791843|     1563791855|
|surrey                       |                             0|                 12820|                12860|       1563791855|     1563791875|
|west-sussex                  |                             0|                  6930|                 6944|       1563791875|     1563791885|
|wales                        |                            NA|                    NA|                   NA|       1563791885|             NA|

**Comment by Robinlovelace** [comment]
In hindsight this csv (saved with .log extension, although is actually a CSV file - to be able to upload to github) is probably a more useful format. Happy for this to go into the pct-scripts repo although as it's a one off I think keeping it here in the issue tracker is also fine to keep the commit history cleaner. Heads-up @AnnaGoodman1 thanks for requesting this 👍 

[school-regional-rnet-build-log-2019-07-22.log](https://github.com/npct/pct-shiny/files/3416899/school-regional-rnet-build-log-2019-07-22.log)

**Comment by AnnaGoodman1** [comment]
thanks. have updated them here: https://github.com/npct/pct-scripts/blob/master/school/lsoa/build_params_pct_region.csv

**Comment by AnnaGoodman1** [comment]
Hi @Robinlovelace ,
I'm just updating the region stats page. At the moment we say that the route network includes all lines **that start or end** in the region in question. But actually I think we additionally include route segments that just intersect the region, e.g. start in Hackney, and end in Southwark and go via Westminster - we would include the cyclist within Westminster, correct? I think that did not used to be true, but would now be true since you are building the whole route network nationally including absolutely all flows, and then doing the cookie-cutter. Am I right?

**Comment by Robinlovelace** [comment]
Hi @AnnaGoodman1 yes the schools route network is different and the documentation should read more like this:

The school travel route network layer contains segments in and around the region up to a distance of 3 km. The values associated with each segment is the sum of cycling numbers for all routes that pass along it for any region.

That is now different from the commute layer but I think that's fine/appropriate as school travel tends to be shorter. An alternative would be to rebuild the school route networks again using the method I used for the commute data. Not keen on that.

**Comment by Robinlovelace** [comment]
Update on this: the new data is up! @nikolai-b I think #752 is ready to merge now for people without git knowhow to test.

**Comment by AnnaGoodman1** [comment]
Hi @Robinlovelace , I'm not very keen on you changing the method used to calculate the rnet without discussing it first – you have for example eliminated a 29% of the Go Dutch scenario cyclists that way, i.e. a nontrivial undercounting. Is it really not possible to go back to the previous method of using all rnet lines? Since the schools layer has fewer lines on the commute layer, I would think that it would be possible to replicate for the schools what we did for commutes. we had previously agreed you would do that here https://github.com/npct/pct-shiny/issues/704, and is what I thought you were doing this time...

On a smaller note, am I correct that for the commuting layer you generated it first nationally and then segmented it, i.e. it includes routes that intersect with local authorities even if they don't start when their

**Comment by Robinlovelace** [comment]
> you have for example eliminated a 29% of the Go Dutch scenario cyclists that way, i.e. a nontrivial undercounting

That was not my intention. Could you provide more details? Was hoping issues like this would be identified and sorted in the data checking stage in #766. To clarify: I've not changed the method of calculating the route network. I've changed the mechanism by which we subset flows outside the region in the regional route networks.

> I would think that it would be possible to replicate for the schools what we did for commutes

Certainly is. As stated above,

>  An alternative would be to rebuild the school route networks again using the method I used for the commute data. Not keen on that.

Note: the method should only affect the regional route network data *outside the region in question*. I didn't use the cookie cutter method for the commute data because the data volumes made it impossible for @mem48 to build a national route network, relating to your final question: 

>am I correct that for the commuting layer you generated it first nationally and then segmented it

No it's the other way around: I generated the regional route networks first for the commute data and then combined them to create a national route network dataset. For the school network it's possible on a desktop with 128 GB RAM to create the national route network in one go, which is what I did. 

Please clarify the data checks that reveal unexpected results and we can reopen #766 if there are definitely issues. Regarding the 'cookie cutter' vs 'flows that end in the region' approaches, let me know which you prefer. My preference is the 'flows that end in the region' approach but, as I say, wasn't keen on doing that after having rebuilt the regional rnets. But now I'm thinking it may be worth rebuilding them again. Apologies if I jumped the gun, perhaps should have provided more time for data checking on https://github.com/npct/pct-outputs-national/commit/d29fb31ec44974ac3a70d97642e2b7a4f6eb2499 and https://github.com/npct/pct-outputs-regional-R/commit/d57f25e07174d5da192c06415a717f5250f69816 which I put up specifically for testing. Maybe worth briefly chatting on the ☎️  on this as there's lots going on and there's potential for misunderstanding.

Many thanks for reporting issue with the new data in any case and look forward to working to identify the cause of it!

**Comment by Robinlovelace** [comment]
To clarify, when you said "looks good" in https://github.com/npct/pct-shiny/issues/766#issuecomment-514189488 @AnnaGoodman1 I thought you were referring to the national data and Avon but realise that may not have been the case. Definitely one to discuss.

**Comment by AnnaGoodman1** [comment]
Hi there, so in checking I was checking the anonymisation and that the files ran in the app and I did a couple of spot checks that the data were not crazy. But I hadn't appreciated that you were using a different process to choose what routes go into the rnet, and I did not do any testing around that. the 29% figure comes from me looking at the national scenario data file, and calculating that 29% is the proportion nationally of go Dutch cyclists on routes longer than 3km - which if I've understood you correctly are now being excluded by you?

If we could go back to using a method that allows us to include all the routes - which is what we have had previously for the school layer, and what we currently have the commuting layer - and that would seem definitely better to me.  If necessary building things by region and aggregating up to national, as for commuting. Is that possible? I appreciate a pain for you to redo things, but having the same method as before/elsewhere does seem like a good thing

**Comment by AnnaGoodman1** [comment]
But also maybe I have misunderstood, since the data for Isle of Wight does not look very different in the new version in the old version – more similar than I would have guessed if all routes >3km are excluded. Unless travel is particularly short on the Isle of Wight

**Comment by Robinlovelace** [comment]
> But also maybe I have misunderstood

I think so. The 3 km I mentioned refers to buffers around the regions, not the maximum distance of routes to include. That would indeed be crazy. If you could check the data for some other regions and share some results / screen shots from the checking process, that will probably help get to the bottom of this.

**Comment by Robinlovelace** [comment]
Update: I guess this is the cause of the confusion:

> The school travel route network layer contains segments in and around the region up to a distance of 3 km. The values associated with each segment is the sum of cycling numbers for all routes that pass along it for any region.

**Comment by Robinlovelace** [comment]
That could be re-written as: 

> The school travel route network layer shown in the interactive map, and downloadable from the Region data tab, contains all segments in the region in question, in addition to segments in surrounding regions up to a distance of 3 km from the region boundary, to highlight areas with cross-region flows. The values associated with each segment is the sum of cycling numbers for all routes that pass along it for any region.

**Comment by AnnaGoodman1** [comment]
yes, sorry, a misunderstanding. phew! can continue...

**Comment by Robinlovelace** [comment]
Heads-up: assuming the deploy works on the test server, the next priority is to update the tiles. Please find time to do this on Monday/Tuesday @nikolai-b - if not I can give it a try: just a case of using the following commands carefully on the server I believe:

```bash
wget # download the zip files
unzip # them
mv # them to the right location
```

**Comment by Robinlovelace** [comment]
And of course the tests that go alongside such an operation. I hope the new tiles I generated are good!

**Comment by AnnaGoodman1** [comment]
minimal go cambridge blog available via wordpress, and for us to see here: https://blog.pct.bike/2019/07/27/go-cambridge-a-new-scenario-in-the-schools-layer/ 
Edits welcome...

**Comment by Robinlovelace** [comment]
Hey @AnnaGoodman1 great work on making a blog post, can you change the availability or email it? Cannot see even though I'm logged in: 

![image](https://user-images.githubusercontent.com/1825120/62003505-f126fa00-b10f-11e9-9cc5-3486057247b7.png)

**Comment by Robinlovelace** [comment]
Regarding the deploy, the test server is now up to date. It crashes when you select school trips, which is as expected as didn't update the `region_data_sha`. Tested updating it locally and it works. Will do so on the test server and it should be working within the next 10 minutes or so!

**Comment by Robinlovelace** [comment]
> should be working within the next 10 minutes or so!

Confirmed: it's working now :+1:

**Comment by Robinlovelace** [comment]
@AnnaGoodman1, @RachelAldred, @JDWoodcock, @usr110 please can you test the schools layer on the test server? Updated tiles not yet up. Planning to deploy this to production by Wednesday evening so comments before Tuesday: most appreciated.

**Comment by JDWoodcock** [comment]
i find when looking at school network clickable the application often exits. the image data isn't there but I assume you know that?

**Comment by Robinlovelace** [comment]
Which regions did it fail for? Works OK for Isle of Wight for me, as shown below. The more details the better when reporting issues.

![image](https://user-images.githubusercontent.com/1825120/62005980-9bb01480-b132-11e9-9a48-44a90b5ab8bb.png)

**Comment by Robinlovelace** [comment]
> the image data isn't there but I assume you know that?

Yes, as mentioned [here](https://github.com/npct/pct-shiny/issues/764#issuecomment-515740249): 

> Updated tiles not yet up.

**Comment by JDWoodcock** [comment]
![image](https://user-images.githubusercontent.com/11028720/62006238-c8b1f680-b135-11e9-9184-dbd0f1c4d30f.png)
so Nottinghamshire - going past 30% route network. The reload button also doesnt always work.

**Comment by Robinlovelace** [comment]
I cannot reproduce that behaviour: 

![image](https://user-images.githubusercontent.com/1825120/62029773-70cdcb00-b1db-11e9-8faf-4b1ac82d8072.png)

**Comment by Robinlovelace** [comment]
Results for Go Cambridge example at 90% look awesome:

![image](https://user-images.githubusercontent.com/1825120/62029946-ca35fa00-b1db-11e9-93ad-27043ab199da.png)

@JDWoodcock can you try to reproduce the error again?

**Comment by AnnaGoodman1** [comment]
also worked for nottinghamshire for me

**Comment by JDWoodcock** [comment]
okay I tried again and still it crashes when trying for 50% or more. Also reload button on bottom doesnt help. I also find sometimes it appears then disappears! I think it is just struggling with the data rather than being a 'bug'

**Comment by nikolai-b** [comment]
The Cambridge tiles (and all the other new tiles @Robinlovelace put in https://github.com/npct/pct-scripts/releases/download/0.0.2/new-school-tiles.zip are up on the tileserver.  I can't recreate the bug you had @JDWoodcock but I have found one that should be fixed by #770

**Comment by RachelAldred** [comment]
I got Notts to work OK but when I moved to London, although it loads ok, I can't drag to another part of London but am stuck on NW London where I started. This would fit with James's comments re struggling with data rather than a specific bug.
![image](https://user-images.githubusercontent.com/11818218/62114466-a7284a80-b2ae-11e9-8f40-ed389189c56e.png). I also found the image data initially appeared then disappeared when I zoomed in a bit. 
![image](https://user-images.githubusercontent.com/11818218/62114616-ebb3e600-b2ae-11e9-87a5-6cd4ab88d786.png)

**Comment by Robinlovelace** [comment]
Thanks for the feedback. The amount of data loaded into the browser is the issue here. We thought carefully about the maximum network size to upload and have set it based on memory used: https://github.com/npct/pct-scripts/blob/master/07b.3-regional-rnets.R#L57

Could rebuild the networks based on a smaller number but I'm not keen on that at this stage. Hoping to get the new data before the workshop on Friday.

**Comment by AnnaGoodman1** [comment]
It works for me in London, but takes a while to load and move around. 

If it were causing many people to have crashing browsers, then re doing the rnet subset with a higher threshold would seem sensible to me (it shouldn't take too too long, Robin?). And/or just living with the fact that the the clickable route network isn't that great for big regions, and encouraging use of tiles intead

**Comment by Robinlovelace** [comment]
Happy with either approach. Most people don't crank up the slider to 90 so suspect relatively few people will have issues. Have created this as and issue: https://github.com/npct/pct-shiny/issues/772 - suggest we discuss +s/-s there but would er on the side of caution and a smaller rnet size post deploy.

**Comment by usr110** [comment]
I think the app crashes when you change inputs (or load a new region) while the data is still being populated. 

Following @RachelAldred and @JDWoodcock scenario, I wanted to recreate the same issue.  What I did was, using London, I loaded `route network  (clickable)` under `school` layer for `cambridge` scenario. While the data was being populated, I switched the purpose back to `commute` and then the app crashed with the following error:


> Listening on http://127.0.0.1:49021
> 
> Attaching package: ‘shinyjs’
> 
> The following object is masked from ‘package:shiny’:
> 
>     runExample
> 
> The following objects are masked from ‘package:methods’:
> 
>     removeClass, show
> 
> Warning: Error in round: non-numeric argument to mathematical function
>   53: paste0
>   52: popup_centroids
>   44: <observer> [/var/shiny/pct-shiny/regions_www/m/server.R#712]
>    1: runApp

**Comment by Robinlovelace** [comment]
Heads-up all, @AnnaGoodman1, @nikolai-b, @JDWoodcock, @mem48, @usr110 and @RachelAldred I think we're hours away from closing this issue. Please test on the test server and let us know here if you find any issues. If not, I think we should deploy this evening.

@usr110 I know you'd like to er on the side of caution but the +s of having the Go Cambridge data out there are great. If you find any issues on the test server, or other strong reasons not to deploy, please let me know and I'll happily delay it. Vested interest: I'm running a workshop tomorrow and think it would be great to show off the new scenario.

Thanks all, great to see this almost done¬

**Comment by Robinlovelace** [comment]
Now deployed. Great work everyone!
