### ISSUE TITLE
Update school rnet data

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#766]
Split out from #764 

- [x] Add id column to national rnet and upload
- [x] Update regional rnets
- [x] Update IoW rnet.Rds file for testing
- [x] Update IoW rnet_full.geojson file for testing
- [x] Upload all regional rnets in .Rds file
- [x] Upload rnet.geojson files

**Comment by Robinlovelace** [comment]
Heads-up @AnnaGoodman1 and @nikolai-b I've updated the IoW test data and the national rnet data (and the .geojson file for that region). Please can you test.

If I get a 👍 I'll upload the data for all regions.

Thanks!

**Comment by AnnaGoodman1** [comment]
@Robinlovelace , I had wondered if the local_id value needed to match the ID in the lines slot. That is true for the commute layer rnets, but isn't true in your new school data.... but it does seem to work. 

@nikolai-b , do you agree with @Robinlovelace Ok for the local_id to be unrelated to the ID in lines slot? that seems implied by your alternative code just doing 1:nrow(rnet) to create an id on the fly.

assuming you are both happy on this, seems good to me.

**Comment by Robinlovelace** [comment]
As discussed, we'll stick with the '1 id per route segment' nationwide.

**Comment by Robinlovelace** [comment]
Update on this: I've pushed downloads and shiny data for one more region (Avon). Please could you double check that this is OK @AnnaGoodman1 and works in the schools branch @nikolai-b. If so, I plan to push data for all regions tomorrow.

**Comment by AnnaGoodman1** [comment]
have checked, looks good to me!
