### ISSUE TITLE
Add print screen option

### ISSUE THREAD

**Issue by nikolai-b** [npct/pct-shiny#77]

**Comment by Robinlovelace** [comment]
@nikolai-b great it works, just tested. I think it would be even better if the output were a .png image, either copied to the desktop or opened separately. The step of 'print to file' is pretty simple, but will be a bridge to far for many users I suspect. Thoughts @usr110?

**Comment by Robinlovelace** [comment]
Re-opening having just seen this: http://mapbox.github.io/leaflet-image/
Is this possible to implement with our system @nikolai-b?
I imagine so.
