### ISSUE TITLE
New school tiles disappear above a certain zoom level

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#771]

**Comment by Robinlovelace** [comment]
Also affects production. Reproducible example: go to http://www.pct.bike/m/?r=isle-of-wight  and select the school image route net and zoom in. I see this:

![image](https://user-images.githubusercontent.com/1825120/62086564-a8c62400-b256-11e9-9f53-c9a553dde69a.png)

**Comment by Robinlovelace** [comment]
At the next zoom level they're gone:

![image](https://user-images.githubusercontent.com/1825120/62086602-c85d4c80-b256-11e9-9db8-798846043389.png)

**Comment by nikolai-b** [comment]
Yep, the new school tiles are missing the zooms 13 - 15, have you got the code you used to generate them?

**Comment by Robinlovelace** [comment]
Got the code, but its really production ready. Can tidy-up, re-run on work desktop on 8 corse and re-upload.

**Comment by nikolai-b** [comment]
I know things changed but https://github.com/npct/pct-lsoa-vis/blob/master/tile.sh is a simple bash script I use.

**Comment by Robinlovelace** [comment]
One to look at this eve I think. Would be good to re-purpose that script for GDAL 2.4 and updated more efficiently stored 10m rasters.

**Comment by Robinlovelace** [comment]
Update: have added the new compressed .tifs here: https://github.com/npct/pct-scripts/releases/tag/0.0.2

And the script that's currently running to add the higher zoom levels can be found here: https://github.com/npct/pct-scripts/commit/794e938aaeebda379491fcf94e92ab184ee7fa6d

**Comment by Robinlovelace** [comment]
Update: it's hammering 8 of my computers 12 cores and eating through them:

```

CONTAINER ID        NAME                    CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
b098708fd09b        jovial_ganguly          624.82%             43.82GiB / 96.92GiB   45.21%              1.53kB / 0B         54.4MB / 0B         18
46b2707adde0        compassionate_goodall   86.78%              223.8MiB / 96.92GiB   0.23%               1.05MB / 410kB      172MB / 184kB       11
cbe3a7f3d6d7        focused_colden          0.22%               4.031MiB / 96.92GiB   0.00%               1.78kB / 0B         40.7MB / 8.19kB     6
```

**Comment by Robinlovelace** [comment]
FYI these are the stats for the updated tileset - lots of files!

760,526 Files, 1,335 Folders

**Comment by Robinlovelace** [comment]
192 MB (202,248,192 bytes) for just one scenario.

**Comment by Robinlovelace** [comment]
Update @nikolai-b here is the complete tileset for the base scenario: https://github.com/npct/pct-scripts/releases/download/0.0.3/school_bicycle.zip

**Comment by Robinlovelace** [comment]
Very detailed and the same as the new commute tiles I think: 

![image](https://user-images.githubusercontent.com/1825120/62147279-16be2a00-b2ef-11e9-8967-a1f59b4f5908.png)

**Comment by Robinlovelace** [comment]
Update: next batch of tiles (cambridge scenario) can be found here: https://send.firefox.com/download/171f2c9793a8be98/#tMhWgwuNQKNm-QtfifGttw

**Comment by Robinlovelace** [comment]
Heads-up the new tiles are ready to go @nikolai-b. Please start with the largest tileset (1GB zipped!) and let me know if there are any issues: https://github.com/npct/pct-scripts/releases/download/0.0.3/school_dutch_slc.zip

**Comment by Robinlovelace** [comment]
Good news: I've now fixed this for the govtarget tiles. More to come

![image](https://user-images.githubusercontent.com/1825120/62201937-40736180-b380-11e9-83c7-71caccc8c59e.png)

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/62206243-402b9400-b389-11e9-9df3-b0656e8f7459.png)


Update: new network is there for baseline scenario.

**Comment by Robinlovelace** [comment]
Also working for Go Dutch: 

![image](https://user-images.githubusercontent.com/1825120/62207468-1d4eaf00-b38c-11e9-82f7-0ec17e62f788.png)

**Comment by Robinlovelace** [comment]
Heads-up the new tiles are ready to go @nikolai-b. Please start with the largest tileset (1GB zipped!) and let me know if there are any issues: https://github.com/npct/pct-scripts/releases/download/0.0.3/school_dutch_slc.zip

**Comment by Robinlovelace** [comment]
Update: there seem to be missing tiles for the govtarget scenario. E.g.:

![image](https://user-images.githubusercontent.com/1825120/62207821-0066ab80-b38d-11e9-9811-72c46ee42d50.png)


![image](https://user-images.githubusercontent.com/1825120/62207859-18d6c600-b38d-11e9-83c3-a31d270c4c85.png)

**Comment by Robinlovelace** [comment]
Seems this tile is also missing:

```
v2/dutch/15/16286/21766.png
```

**Comment by Robinlovelace** [comment]
Update on this: I think the issue was with the unzip process. Will look now.

**Comment by Robinlovelace** [comment]
Confirmed: the unzip process stopped, hence the holes in the tile pyramid in zoom level 15. Fixing now...

**Comment by Robinlovelace** [comment]
```
ls -R v2/dutch/ | wc
 889068  887543 8825842
```

That's more like it! Should be fixed online also now.

**Comment by Robinlovelace** [comment]
Govtarget tiles fixed now also:

![image](https://user-images.githubusercontent.com/1825120/62237842-a6380b80-b3c9-11e9-9c95-ecd474ef4115.png)

**Comment by Robinlovelace** [comment]
Still issues with Cambridge:

```
ls -R v2/olc/ | wc
889067  887542 8822774
ls -R v2/govtarget/ | wc
889067  887542 8831930
ls -R v2/cambridge/ | wc
581364  579839 5754900
ls -R v2/dutch/ | wc
889068  887543 8825842
```

**Comment by Robinlovelace** [comment]
Rebuilding the missing tiles...

**Comment by Robinlovelace** [comment]
Updated results on my local machine show it was indeed an issue with the tiling not completing first time around.

```
ls -R school_cambridge_slc | wc   
 889067  887542 8844137
```

**Comment by Robinlovelace** [comment]
Incidentally compressed using this, which is way faster than zip:

```
tar cf - school_cambridge_slc | pigz > school_cambridge.tar.gz
```

**Comment by Robinlovelace** [comment]
Looks good, result below showing high cycling to school potential in Leeds. Or what would happen in children in Leeds cycled to school as much as children in Cambridge. Ready to test:

![image](https://user-images.githubusercontent.com/1825120/62248216-7eec3900-b3df-11e9-842e-36a6e98fbbc1.png)
