### ISSUE TITLE
Pop-up for route networks under a specific case do not show up

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#775]
Hi, 

Just found another bug - which might be an artifact of the fix for #773.

The popup for route networks stop displaying when you follow these steps:

1) Swich purpose to `School`
2) Select `Go Cambridge` scenario
3) Select `route network (clickable)` flow
4) Change purpose back to `Commute` - which changes the default `scenario` to `commute`
5) Now `route network (clickable)` is working fine - thanks to the fix in #773, however, 
6) Switch `scenario` to any other than `census`, the popups for `route network (clickable)` will not work.

I know @nikolai-b you've been working quite diligently over such issues, and I have added a new one in your bucket. I think I may have some time later today to work on this one.

**Comment by Robinlovelace** [comment]
Good find @usr110, thanks for reporting. Would be great if you could work on a fix. Spoke to @nikolai-b , who said he can look at npct issues this evening and maybe at lunch. I'm working on #771 - let's aim to get all issues fixed by this evening if possible, ready for deploy tomorrow is my suggestion.

**Comment by usr110** [comment]
As I mentioned I may have some time later today @Robinlovelace 

Re deployment tomorrow, it's too soon, I think. Unless it's very crucial, we may need to delay it.

**Comment by Robinlovelace** [comment]
Great, thanks for the update @usr110, let us know how you get on. If we can fix this issue I see no reason not to deploy for tomorrow after some testing on the test server, which is a great place to identify issues like this.

**Comment by usr110** [comment]
> Great, thanks for the update @usr110, let us know how you get on. If we can fix this issue I see no reason not to deploy for tomorrow after some testing on the test server, which is a great place to identify issues like this.

Testing is the issue here. If you are talking about testing on the test-server, then it's fine. If not, I think it's quite early for prod.

**Comment by usr110** [comment]
I may have found the issue here @nikolai-b 

I think the problem lies in these lines:

https://github.com/npct/pct-shiny/blob/c9bc5dea75b6dfa4716780236c2b3f654eda10f9/regions_www/m/pct_shiny_funs.R#L429-L431

specifically 

https://github.com/npct/pct-shiny/blob/c9bc5dea75b6dfa4716780236c2b3f654eda10f9/regions_www/m/pct_shiny_funs.R#L74

For cambridge scenario, for instance, this function tries to find a non-existent variable called `cambridge_sivalue_heat` among these:

> "local_id"      "bicycle"       "govtarget_slc" "cambridge_slc" "dutch_slc"     "id"  

hence returns a `FALSE`, resulting in un-populated popups.

May be this function `scenario_data_missing` was written for variables present in straight lines and routes and not route-network.

**Comment by Robinlovelace** [comment]
Update on this - in testing for #776 I could reproduce this issue with just these steps:

1) Swich purpose to `School`
2) Select `Go Cambridge` scenario
3) Select `route network (clickable)` flow

The issue persists even after you go onto a different scenario and when you go back to the commute layer, e.g. as shown below - link selected but no pop-up as stated in the OP. 

![image](https://user-images.githubusercontent.com/1825120/62218618-b5589280-b3a4-11e9-8050-7249e9843181.png)
