### ISSUE TITLE
Use assertr for checking conditional pipelines are met

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#778]
You might like this @nikolai-b 

I think it's a good idea to make use of the [`assertr package`](https://cran.r-project.org/web/packages/assertr/vignettes/assertr.html) to verify if the data pipelines are met, before we populate any of the outputs (like pop-ups in https://github.com/npct/pct-shiny/issues/775)

**Comment by Robinlovelace** [comment]
Closing for now as it's gone stale. I would suggest using `checkmate` but I think it's not worth doing at this stage.
