### ISSUE TITLE
Lines disappear when you change scenario

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#78]
Reproducible example - show lines:

![selection_338](https://cloud.githubusercontent.com/assets/1825120/10165030/ec40832a-66b4-11e5-952f-5f70170718bc.png)

Then change scenario several times. The lines seem to disappear:

![selection_339](https://cloud.githubusercontent.com/assets/1825120/10165063/15efd572-66b5-11e5-97f9-54cfad0f3aeb.png)

**Comment by Robinlovelace** [comment]
Please can you reproduce and confirm if you get a few minutes @usr110 . Thanks

**Comment by usr110** [comment]
@Robinlovelace Can reproduce. So yes, it's a problem.
