### ISSUE TITLE
Speed-up load times

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#781]

**Comment by AnnaGoodman1** [comment]
If the input datasets were ,say,50% smaller then would we expect website loading speeds to be roughly x2 faster?  Should we experiment? One could reduce the input dataset size by e.g.

1.	Reducing the maximum length of lines – particularly since longer lines take more memory. Going from a maximum line length of 20km to 10km gets the following improvements in .Rds file size:
•	avon: 7.3 to 2.3MB
•	london 79.6MB to 37.3MB

2.	Reducing the number of attribute variables saved, e.g. I think there are 54/87 variables from the rf.Rds and l.Rds files that are in the downloads because potentially useful but not actually needed for the interface.  But this has much more modest effects
•	avon: 7.3 to 6.73MB
•	london 79.6MB to 73.2MB

3.	Possibly there would also be some other options e.g. around simplifying the rf/rq line shapes. 

In any of these cases, I would propose that the downloads were not changed and these simplifications only affected what one got in the online interface. This could e.g. be done by duplicating the regional R file repo such that the data download page pointed to a 'full version' repo (same as current) and the online interface/server only had a new 'smaller subset' repo.  I appreciate this duplication is not DRY ideal, but is the easiest way I can see to reduce the input dataset size while retaining the quality of the data downloads.

**Comment by AnnaGoodman1** [comment]
Hi all,

So I started having a go at my suggestion, by 
 - creating smaller l/rf/rq files (maximum fast route distance 10 km not 20 km); this roughly halves these file sizes
 - saving these at pct-outputs-regional-Rsmall (https://github.com/npct/pct-outputs-regional-Rsmall)
 - comparing load times on my laptop for the current system versus one that instead direct to these Rsmall files (via branch https://github.com/npct/pct-shiny/tree/test-small-datasets).

The regions that exist in this small state are LSOA versions of Avon, Hampshire, Isle of Wight and London

On my laptop thing seem to get a lot faster for London:

- loading region to get zones showing on screen: from 53 sec to 17 sec
- then loading straight lines: from 16 sec to 8 sec
- then switching to loading rf / rq lines: from 27 sec to 17 sec

@usr110 , @nikolai-b , @Robinlovelace : Do you think this smaller file size approach would plausibly solve our problems?  if so shall we try it more fully, by me generating small files for all regions and then we change what files are synced up on the server by changing the syncing repo?

**Comment by Robinlovelace** [comment]
> Do you think this smaller file size approach would plausibly make load times via the browser non-trivially faster?

I think so. I like this solution: simple, and builds on what we already do with the `rnet` and `rnet_full` files.

**Comment by mvl22** [comment]
You might also want to consider:

- Reduce co-ordinate precision. Some frameworks produce ludicrously high levels, e.g. down to the millimetre, when a precision of 10m is often fine. If you're sending a lot of geographical data, cutting out lots of numbers may save you perhaps 10-20% of the transfer size.

- Using ST_Simplify to apply the Douglas–Peucker algorithm to reduce the detail of lines/polygons sent. E.g. a boundary can often be very complex, but people don't need the exact shape of every island. An Island with hundreds/thousands of points giving the exact geometry can often be trimmed to even 10 points to get the rough shape.

- Trim out any fields in the data properties that the interface will never use. This is often a problem with databases, whereby people retrieve a complete row without specifying columns, and that data ends up all the way through to being sent to the interface but not all of it used.

**Comment by AnnaGoodman1** [comment]
Thanks @mvl22, v helpful. I agree on point 3, as per my first post this saves about 10% file size. I can do this if we go ahead with this small dataset approach

point 1 & point 2 - @Robinlovelace (or others), any thoughts? on point 1: It looks, if I am looking correctly, as if we have longitude and latitude to 5dp which according to this thread (https://gis.stackexchange.com/questions/8650/measuring-accuracy-of-latitude-and-longitude) is about 1.1m - so probably about right in terms of accuracy level? 

![image](https://user-images.githubusercontent.com/11818225/62778537-8c24ba00-baa8-11e9-95ab-c7643213803a.png)

**Comment by AnnaGoodman1** [comment]
@usr110 / @nikolai-b , are you happy with this suggestion - smaller datasets in a new 'Rsmall' repo? want to check before I keep working on it...

**Comment by usr110** [comment]
@AnnaGoodman1 seems like a good idea. Please go ahead.

**Comment by AnnaGoodman1** [comment]
OK I have uploaded small versions of all files, restricting line/route distances to rf=10km and used @data attribute variables. The new files are uploading overnight at https://github.com/npct/pct-outputs-regional-Rsmall

See this branch: https://github.com/npct/pct-shiny/compare/test-small-datasets?expand=1

Working well for me locally, and seeming quite a bit faster. This is NOT FOR MERGING yet but for testing on a branch by @nikolai-b / @usr110 and/or @Robinlovelace .  If it seems okay there then perhaps @nikolai-b can try out switching the server to be cloning 'Rsmall' not 'R' repo. (I tried to make the code modifications for that, but don't really understand the process so may have made some mistakes)

**Comment by nikolai-b** [comment]
Sorry I've been very quite on this.  Yes having smaller R files would hopefully speed things up quit a bit.  I had another plan as @Robinlovelace and I found that the [delete](https://github.com/npct/pct-shiny/blob/8a8883caef9f4b4d525f3a3a4c668bd0cb6ad605/regions_www/m/server.R#L235-L239) is quite slow, then I could move that into an observe so it doesn't slow down region loading, it could happen afterwards.  I've just not had time to implement it.  I think it saved 7s or so from London.

**Comment by AnnaGoodman1** [comment]
ok great, perhaps we can try both at once and hopefully that becomes enough. Thanks @nikolai-b !

**Comment by Robinlovelace** [comment]
Finally got round to reading this thread after great holidays in Slovenia. I think the twin pronged attack on the plague of slowness makes sense - if @nikolai-b looks into this https://github.com/npct/pct-shiny/blob/8a8883caef9f4b4d525f3a3a4c668bd0cb6ad605/regions_www/m/server.R#L235-L239 and I test the [test-small-datasets](https://github.com/npct/pct-shiny/compare/test-small-datasets?expand=1) branch, I think that will get us a good way to resolving this issue. FYI, it definitely seemed very slow to load the desire lines for west-yorkshire when I was demoing this last.

**Comment by AnnaGoodman1** [comment]
ust nudging on this.... when do you think you will be able to work on it @nikolai-b ? From Sept when people are back at work we expect there may be quite a bit more PCT use...

**Comment by Robinlovelace** [comment]
Thanks for the nudge @AnnaGoodman1 I second that. Coincidentally Nikolai and I discussed this briefly yesterday evening. We agreed he'd take a look at this and that I would take a look at your proposed changes, next week most likely. Sound like a plan? 

On a related note, it would be good to have a record of load times. Please could you or anyone add to the table below by clicking 'edit' in the ... Will give us a more objective way of seeing if our fixes work.

**Comment by Robinlovelace** [comment]
``` r
knitr::kable(read.csv(text = "region,initial_load,lsoa,lines,fast_routes,rnet_vector,\n                      west-yorkshire,12,,,,,"))
```

|region         | initial_load|lsoa |lines |fast_routes |rnet_vector |X  |
|:--------------|------------:|:----|:-----|:-----------|:-----------|:--|
|west-yorkshire |           12|NA   |NA    |NA          |NA          |NA |

<sup>Created on 2019-08-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by nikolai-b** [comment]
@AnnaGoodman1 would you mind creating a Pull Request for test-small-datasets? It will be easier to discuss it there, sorry it has taken so long to get back to you.

**Comment by Robinlovelace** [comment]
New PR here to reduce load times: https://github.com/npct/pct-shiny/pull/789

**Comment by Robinlovelace** [comment]
Update on this: I've tested #788 and it's definitely faster. I've tested on all layers locally and have approved the PR. Plan to merge to deploy on the test server later today.

**Comment by Robinlovelace** [comment]
Headline result shown below: it roughly halves load time on the test server according to my tests. Note I started loading the second window slightly after. Please @AnnaGoodman1, @RachelAldred, @JDWoodcock, @usr110 + @joeytalbot try out the test server and let us know of any issues. Assuming all good there are 2 options:

1. Merge this to production now
2. Merge #789 into master and then merge into production

Assuming @nikolai-b agrees I plan to go with 2.

![Peek 2019-09-04 11-09](https://user-images.githubusercontent.com/1825120/64246589-f5131c80-cf04-11e9-8310-0a3441ea4dd9.gif)

**Comment by JDWoodcock** [comment]
thanks, i did find it a bit quicker for London with route network layer commuting but it also crashed and had to reload a couple of times on test server before successfully loading London

**Comment by Robinlovelace** [comment]
Any details on why it crashed @JDWoodcock? Probably worth checking the logs @nikolai-b - shouldn't be crashing...

**Comment by JDWoodcock** [comment]
it was like when one of the servers is down. Clicked on London and it greyed out and had to reload which didnt work. I shut it down completely and then restarted and it was fine.

**Comment by Robinlovelace** [comment]
Great, thanks for the clear report. I suspect it's not due to the recent changes. Would be useful if you can try and reproduce the crash. Let us know if there are any further issues.

**Comment by AnnaGoodman1** [comment]
@nikolai-b , is the main site not just test server now runnng the new system of loading Rsmall datasets? If so there is one set of files (rnet.R, as opposed to rnet_full.R) that is redundant in the old file, for me to delete in due course

**Comment by Robinlovelace** [comment]
I don't think the changes have been merged into `production` yet. I just opened a PR that will do this and hopefully close this issue. Any other changes we should make on the test server (`master`) before we merge this?

**Comment by AnnaGoodman1** [comment]
none in this round, I think. thanks, Robin

**Comment by AnnaGoodman1** [comment]
ok thanks so - sorry to keep asking - is  the main site now runnng the new system of loading Rsmall datasets? @nikolai-b / @Robinlovelace 

If so can do the minor tidying of the repos, removing current file duplications

**Comment by AnnaGoodman1** [comment]
ok right, I see it isn't. @nikolai-b , could you let me know when you do merge https://github.com/npct/pct-shiny/pull/795 thanks

**Comment by Robinlovelace** [comment]
Tested and the load times have been halved. I got an initial (the most important) load time of ~5s for West Yorkshire, substantially better than reported in https://github.com/npct/pct-shiny/issues/781#issuecomment-526115424

Good work @nikolai-b. Note that production also suffers from the lines-not-updating bug #797 so we should update production again asap.

**Comment by JDWoodcock** [comment]
good
