### ISSUE TITLE
Go Cambridge Scenario vanishes in Avon

### ISSUE THREAD

**Issue by awjreynolds** [npct/pct-shiny#782]
During loading the scenario is available. Once the map is rendered the scenario vanishes.
<img width="1432" alt="Screenshot 2019-08-03 at 08 06 53" src="https://user-images.githubusercontent.com/1948692/62408774-c3392e00-b5c5-11e9-8219-f9961128e7ad.png">

**Comment by nikolai-b** [comment]
Thanks @awjreynolds bug report and for the screenshot.

The Go Cambridge scenario has only been calculated for school data, if you change the trip type to "School travel" you will be able to select it.

**Comment by Robinlovelace** [comment]
Follow-up from me: thanks for reporting @awjreynolds and glad it's not something that needs to be fixed while I'm away on holiday. As stated in the [blog](https://blog.pct.bike/2019/07/27/go-cambridge-a-new-scenario-in-the-schools-layer/) article introducing the new scenario, 

> We do not plan to introduce a Go Cambridge scenario for the commuting layer. This is because current cycle commuting rates in Cambridge are fairly similar to those seen in the Netherlands, and so the Go Cambridge scenario would not be very different to the existing Go Dutch scenario.

If you find any other issues, feel free to open issues Adam, especially if it's accompanied with a clear description and suggested solutions.

In any case, will enjoy my holidays even more now!
