### ISSUE TITLE
?Remove 'sl' variables in downloads?

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#790]
Hi @JDWoodcock @Robinlovelace @RachelAldred 

At the moment we show all scenario health/carbon impacts in two ways: one is the difference of the scenario versus baseline, the other is the difference of the scenario versus if there were no cycling at all in the population.  See below as an example of this for one of the codebooks.

govtarget_slco2	Change in CO2/year (kg) in Government Target (equality) versus 'no cycling'
govtarget_sico2	Change in CO2/year (kg) in Government Target (equality) versus Census 2011
govnearmkt_slco2	Change in CO2/year (kg) in Government Target (near market) versus 'no cycling'
govnearmkt_sico2	Change in CO2/year (kg) in Government Target (near market) versus Census 2011
gendereq_slco2	Change in CO2/year (kg) in Gender Equality versus 'no cycling'
gendereq_sico2	Change in CO2/year (kg) in Gender Equality versus Census 2011
dutch_slco2	Change in CO2/year (kg) in Go Dutch versus 'no cycling'
dutch_sico2	Change in CO2/year (kg) in Go Dutch versus Census 2011
ebike_slco2	Change in CO2/year (kg) in Ebikes versus 'no cycling'
ebike_sico2	Change in CO2/year (kg) in Ebikes versus Census 2011

As best I remember, the rationale was to make it consistent with what we have for numbers of cyclists with the 'sl' variables (e.g. dutch_slc) being the total number of cyclists above 0 and the 'si' variables (e.g. dutch_sic) being the number of cyclists above baseline. But it is starting to get a bit unwieldy in terms of numbers of health/carbon variables. This is particularly true now we have added one new near market scenario and now that James and I are creating some new health impact variables (years of life lost, sick leave, and the economic value of sick leave).

I wonder if we should delete these 'sl' variables? It is no more difficult from my perspective to provide them, just that I worry this large number of variables might be confusing for users. Plus it is not obvious to me that most users would want to compare to 'no cycling'. But equally if we think these variables are being used I'm very happy to keep them in.

 Do any of you, perhaps particularly Rachel, have a view on this?

**Comment by AnnaGoodman1** [comment]
I could potentially remove 5 'sl' variables and add in one 'census versus no cycling' variable that could be added to any 'si' variable to give current 'sl' value.  that is in practice how they are made. would reduce no. variables, but then perhaps not be as clear/possibly need tweaking to training material etc...so happy to stay with current situation if preferred!

**Comment by RachelAldred** [comment]
Hm, I don't have super-strong views on this. I agree that if people can generate them themselves (which they can) then it might make sense to remove the 'sl' variables, and we can change the training material accordingly. I was also wondering about whether there were variables that we wanted to add (sorry). We have for Census 2011 the numbers of car passengers, motorcyclists, train/tube commuters, bus commuters, and taxi/other commuters. We don't though provide the changes in these variables for any scenarios, but I wondered whether this was worth considering, at least for some of them (as these unlike the SLs are things people can't calculate themselves from the downloads). I know it will add a lot more variables in return - so maybe we would only want to add some! (For instance, could we have motorcyclists, car passengers, and public transport (train/tube/bus)? - which might be of most interest). I have had people ask about the total number switching from car for instance (not just drivers) or about mode shift from bus.

**Comment by JDWoodcock** [comment]
Are there any other options? to me having lots of variables is a bit overwhelming for people but at the same time its frustrating to not have what you want. Is there something more interactive than a simple download (sounds like I am creating work here...) ?

**Comment by Robinlovelace** [comment]
Thanks for raising this @AnnaGoodman1, it does seem excessive to have all those extra variables and, while it's interesting and potentially beneficial to have access to the benefit of current levels of cycling, it does increase the number of variables.

I think this is a good suggestion:

> I could potentially remove 5 'sl' variables and add in one 'census versus no cycling' variable that could be added to any 'si' variable to give current 'sl' value. that is in practice how they are made.

**Comment by AnnaGoodman1** [comment]
Ok, maybe remove those sl then. Suggest leave as is not trying interactive, James, just to keep things simple. 

Rachel, I could look into how much work that would be, I can def see potential use and I think/hope would not be too hard. So on same vein, at the moment we have two variables, scenario level of driving and scenario increase of driving. Or again redundant as one can let you get the other, but here I can at least see that scenario level SL variable is plausibly quite a useful thing, unlike for health. So I suggest if I can add them I would do it both ways, ie 2 variables * 3 new modes * 5 scenarios = 30. Yes?

**Comment by RachelAldred** [comment]
That sounds interesting Anna if it's not too much hassle. Thanks :)
