### ISSUE TITLE
IE11 compatibility mode

### ISSUE THREAD

**Issue by nikolai-b** [npct/pct-shiny#791]
We had a user say the site didn't work in IE11, it turned out that they had _compatibility_ mode on.  Microsoft has [an article](https://support.microsoft.com/en-us/help/17472/windows-internet-explorer-11-fix-site-display-problems-compatibility-v) about this but basically maybe we should have a warning / popup / something if we detect a user is in IE11 compatibility mode explaining that the site might not work with it on.

**Comment by mvl22** [comment]
I think you can disable this using

`<meta http-equiv="X-UA-Compatible" content="IE=Edge" />`

There is some complicated flowchart that shows all the various ways old IE's rendering and related modes interact, which I can't find right now, but this might be worth trying.

**Comment by nikolai-b** [comment]
Thank you @mvl22, that sounds very promising. I'll give it a go once I set up a IE virtual machine.
