### ISSUE TITLE
West Midlands download data is wrong

### ISSUE THREAD

**Issue by RachelAldred** [npct/pct-shiny#792]
Hi @AnnaGoodman1 @JDWoodcock @Robinlovelace @usr110 @mem48 - the West Midlands MSOA level data geojson seems to not be here http://pct.bike/m/?r=west-midlands. Instead the MSOA level geojson is a file for Cambridgeshire (which has some missing data BTW).
![image](https://user-images.githubusercontent.com/11818218/64246560-e593d380-cf04-11e9-9ce4-49d8eef9b9b6.png). The corresponding LSOA one looks fine.

**Comment by Robinlovelace** [comment]
Not good. Thanks for reporting. However, I couldn't reproduce the issue. I navigated to the location and clicked on the geojson object in these options:

```
Zones (MSOA): csv Rds geojson - Codebook 
```

That seems to point here: https://github.com/npct/pct-outputs-regional-notR/raw/master/commute/msoa/west-midlands/z.geojson

Which, as shown below, seems to be OK:

``` r
u = "https://github.com/npct/pct-outputs-regional-notR/raw/master/commute/msoa/west-midlands/z.geojson"
z = sf::read_sf(u)
plot(z)
#> Warning: plotting the first 9 out of 75 attributes; use max.plot = 75 to
#> plot all
```

![](https://i.imgur.com/K9sLkCF.png)

``` r
mapview::mapview(z)
```

![](https://i.imgur.com/70JpWed.png)

<sup>Created on 2019-09-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


Can you re-try and confirm?

**Comment by RachelAldred** [comment]
Thanks Robin! I was looking into it following a query about missing data, and I must have ended up confusing the z... file they sent me with the correct W Mids one. Not sure what they've done, but I think you're right, it's not our mistake :)

**Comment by Robinlovelace** [comment]
Thanks for quickfire follow-up @RachelAldred, glad it's not us, look forward to hearing how our tool is used to support cycle network development in the UK's 2nd biggest city : )
