### ISSUE TITLE
Please remove - additional features

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#8]
These are not currently accurate and not necessarily the ones we would choose.
Perhaps we could have a dummy heading in labelled health benefits & carbon savings- as these will be needed?

**Comment by nikolai-b** [comment]
By additional features do you mean cycle parking, collisions and cycle
shops? They are pulled in from open street map, in what way are they
inaccurate.
Happy to remove but the one transport planner I've shown this too in Leeds
liked the cycle parking option. That said it adds a fair bit of complexity
to the code so I'll remove for now.

**Comment by Robinlovelace** [comment]
It's the UI dropdown that needs to be removed - for now...
I know it goes against your religion @nikolai-b but I think it's work worth creating a folder called 'master-additional' that's got the additional features - just so we can show people what the additional layers look like when doing the user testing.
