### ISSUE TITLE
one server down?

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#800]
@nikolai-b @Robinlovelace 
i think one of the servers is down - as roughly half the time it disconnects immediately on clicking on a region- just got emailed about it.

**Comment by Robinlovelace** [comment]
Thanks for reporting. Cannot reproduce, but that may be because my browser always connects to the working server.

**Comment by mvl22** [comment]
Reproduced here.

You should add into the debugging a code representing the backend server so you can see immediately what has gone down. I don't know how to do that in R-Shiny myself though.

![Screen Shot 2019-09-18 at 11 34 44](https://user-images.githubusercontent.com/361423/65136638-38db4b00-da08-11e9-9788-f77bebcc104e.png)

**Comment by Robinlovelace** [comment]
Many thanks for confirming this @mvl22

**Comment by nikolai-b** [comment]
I couldn't even reboot it properly, sorry but I've no idea why this happened.  Nothing in the system logs or R logs :cry:

**Comment by nikolai-b** [comment]
The server works after restating but not fixed the underlying cause so I've removed the label
