### ISSUE TITLE
No lines are shown when sorted by 'increase in cyclists'

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#804]
When you sort `Order lines by` `Increase in cyclists`, no lines are displayed. I am not sure this is a feature. Seems like a bug. Please see it below:

![Screenshot_2019-10-01 Propensity to Cycle Tool - London](https://user-images.githubusercontent.com/10958628/65969946-8ec6de80-e45d-11e9-86ab-7b71a8d8e3d0.png)

(doesn't work for any flows - be it line or route)

Found it both on test and live server.

**Comment by usr110** [comment]
@AnnaGoodman1 
Checked `avon` data (from https://github.com/npct/pct-outputs-regional-Rsmall/blob/master/commute/msoa/avon/l.Rds), it seems there is no `sic` variable like `govnearmkt_sic`. Is it intentional? See the names here:

> [1] "id"                      "geo_name1"               "geo_name2"              
>  [4] "all"                     "bicycle"                 "car_driver"             
>  [7] "govtarget_slc"           "govtarget_sid"           "govnearmkt_slc"         
> [10] "govnearmkt_sid"          "gendereq_slc"            "gendereq_sid"           
> [13] "dutch_slc"               "dutch_sid"               "ebike_slc"              
> [16] "ebike_sid"               "govtarget_sideath_heat"  "govtarget_sivalue_heat" 
> [19] "govnearmkt_sideath_heat" "govnearmkt_sivalue_heat" "gendereq_sideath_heat"  
> [22] "gendereq_sivalue_heat"   "dutch_sideath_heat"      "dutch_sivalue_heat"     
> [25] "ebike_sideath_heat"      "ebike_sivalue_heat"      "govtarget_sico2"        
> [28] "govnearmkt_sico2"        "gendereq_sico2"          "dutch_sico2"            
> [31] "ebike_sico2"             "e_dist_km"               "rf_dist_km"             
> [34] "rf_avslope_perc"

**Comment by AnnaGoodman1** [comment]
right yes, my bad - missed that variable recently when creating Rsmall files. Now putting it back in, should be on git by the end of the day. Will that automatically sync to server? Thanks very much for finding this.

**Comment by Robinlovelace** [comment]
Hi @AnnaGoodman1 thanks for the quick (and Ali for spotting this). It won't automatically deploy, we'll need to update the sha here: 

https://github.com/npct/pct-shiny/blob/2632a0075c8064e2799da7588423f192a00e2987/outputs_regional_sha#L1

That currently links to this commit: https://github.com/npct/pct-outputs-regional-Rsmall/commit/dae58c795199df32d2f5541edc1be1c0667b5dcf

we should probably test this before updating the sha before deploying.

**Comment by Robinlovelace** [comment]
Update: I've just put in a PR for this https://github.com/npct/pct-shiny/pull/806

**Comment by usr110** [comment]
> 
> 
> right yes, my bad - missed that variable recently when creating Rsmall files. Now putting it back in, should be on git by the end of the day. Will that automatically sync to server? Thanks very much for finding this.

Thanks @AnnaGoodman1. All fixed in https://github.com/npct/pct-shiny/pull/806/commits/0612039237e7c92b5c60b822241506c6ce58797f, so closing it now.

**Comment by Robinlovelace** [comment]
This still affects production right? I suggest re-opening until fixed there. Heads-up @usr110.

**Comment by usr110** [comment]
> 
> 
> This still affects production right? I suggest re-opening until fixed there. Heads-up @usr110.

It does, indeed. I think the issue is fixed, so should be closed; the `production` branch just needs updating. I believe that's how we have dealt with almost all issues in the past, haven't we? What do you say?

**Comment by Robinlovelace** [comment]
I think it's best to close issues when they are fixed on production as a kind of sign-off. Re-opening for now as a reminder.

**Comment by usr110** [comment]
> 
> 
> I think it's best to close issues when they are fixed on production as a kind of sign-off. Re-opening for now as a reminder.

Sure, that's fine. Let make this as a standard practice then.

**Comment by usr110** [comment]
Fixed on `production` by https://github.com/npct/pct-shiny/pull/808, so closing it now.

**Comment by Robinlovelace** [comment]
Well spotted @usr110, thanks for spotting that and subsequently closing this issue.
