### ISSUE TITLE
update repo_sha

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#811]
I may remember wrong, but I think this needs to update? I have merged my TAG pull request and most things working except internal to pct-shiny references, e.g. downloading latest version of manual

**Comment by AnnaGoodman1** [comment]
NB BEFORE you change repo sha, though, please can we merge in thise minor PR: https://github.com/npct/pct-shiny/pull/812

**Comment by AnnaGoodman1** [comment]
(@nikolai-b / @Robinlovelace / @usr110 , whoever has time)

**Comment by usr110** [comment]
May be I am missing something here. Have you not already updated the sha for `pct-outputs-regional-Rsmall`, to the most recent changes, @AnnaGoodman1 ?

**Comment by AnnaGoodman1** [comment]
yes but, don't we have to update repo_sha too?

**Comment by AnnaGoodman1** [comment]
at the moment the manual page on the test server downloads the older versions of the manuals, not hte latest commit, and I think that is why

**Comment by AnnaGoodman1** [comment]
(I am not sure how to do update just on test server not main server, in the first instance...)

**Comment by usr110** [comment]
As long as the `master` branch is updated, only the `test-server` will be affected. 

Re the manual, I don't think it's linked with `repo_sha`. The manual links are static, so they always point to the latest version in the repo.

If you're talking about the `C1` manual stored at https://github.com/npct/pct-shiny/blob/master/regions_www/www/static/03a_manual/pct-bike-eng-user-manual-c1.pdf, I can see the same on the `manual` section of the app. 
![Screenshot_2019-11-19 The Propensity to Cycle Tool Manual](https://user-images.githubusercontent.com/10958628/69175882-85243380-0afc-11ea-8497-488702be20e7.png)


My understanding is that all the manual links are pointing towards the latest files stored here: https://github.com/npct/pct-shiny/tree/master/regions_www/www/static/03a_manual

Have I missed something?

**Comment by Robinlovelace** [comment]
Yes the manuals are static files that won't change with the data sha. The current commit of https://github.com/npct/pct-outputs-regional-Rsmall is f8576bc which is the same as

https://github.com/npct/pct-shiny/blob/2fa8a4a2bcef0f564d2ded7f1bcfa28933ee6a58/outputs_regional_Rsmall_sha#L1

**Comment by AnnaGoodman1** [comment]
so that makes complete sense to me, but I definitely thought that when we first merged this pull request and I did my initial testing I was still getting the old manual files when I clicked the link.... But I can't now replicate it.... Confusing  but anyway good it is working now, thanks both
