### ISSUE TITLE
change how lines ordered

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#813]
James suggests that now that we also monetise sickness absence benefit, we change this sorting by reduction in deaths to sorting by 'health economic benefit' ( physical activity impact on years of life + impact on sickness absence). Seems good to me, I should be able to make those changes this week - okay with @Robinlovelace and @RachelAldred ?
  
![Untitled](https://user-images.githubusercontent.com/11818225/69250359-6f1f7d00-0ba7-11ea-92f4-9b763485e8a7.png)

(note to self, need to update manual b and codebook od_small and all files in Rsmall repo and regional_sha_Rsmall if  we do this)

**Comment by Robinlovelace** [comment]
"Health economic benefit" definitely sounds more immediately policy relevant that reduction in deaths. Will the units be £? Great that we now account for the substantial benefits of cycling uptake in terms of health-related reduction in time off work.

**Comment by AnnaGoodman1** [comment]
yes the units are £, it is the sum of the two £ values shown in the popup of the picture
thanks @Robinlovelace !

**Comment by AnnaGoodman1** [comment]
(cc @JDWoodcock  in this thread)

**Comment by JDWoodcock** [comment]
I do suggest this but note of caution  do find health economic benefit produces a lot of confusion. the health economic benefit from ylls/ deaths is a welfare economic calculation while the sickness absence should be an economic benefit to employers.

**Comment by AnnaGoodman1** [comment]
if Rachel agrees we want to do this, can merge this PR https://github.com/npct/pct-shiny/pull/814

**Comment by RachelAldred** [comment]
I'm happy, see pluses and minuses either way & don't have very strong feelings either way.

**Comment by Robinlovelace** [comment]
Heads-up all, this is now on the test server. Please take a look. I'll put in a PR that puts this into production at which point this issue can be closed. Any considerations on timings for that let me know, especially @AnnaGoodman1 and @nikolai-b .

**Comment by usr110** [comment]
Thanks for this, @AnnaGoodman1. It's working fine. Good job!
Re closing the issue, as @Robinlovelace commented above, as a new standard practice, we only close issues when they are fixed on the `live` server as well, so opening it again. Hope that's fine with you.

**Comment by usr110** [comment]
> yes the units are £, it is the sum of the two £ values shown in the popup of the picture

Unlike all other order functions for lines, does it provide an easy understanding of the concept?
I think there should be some additional info some where what this represents.

**Comment by Robinlovelace** [comment]
Thanks for re-opening @usr110. I think it's covered in the manuals.

**Comment by usr110** [comment]
Thanks @Robinlovelace. Unless I missed something, my understanding is that these two concepts: 1) physical activity impact on years of life and 2) impact on sickness absence are mentioned separately (in `pct-bike-eng-user-manual-c1.pdf`), not combined.

**Comment by Robinlovelace** [comment]
Good point Ali, will let others comment on that. I think overall it's (unfortunately) easier for many people to relate to £ saved than deaths avoided in any case but agree we should be clear what those numbers mean.

**Comment by AnnaGoodman1** [comment]
I do state it is the combination in manual b. but I agree not totally clear  - suggestions @JDWoodcock ? seems ok-enough to me?

**Comment by usr110** [comment]
> 
> 
> I do state it is the combination in manual b. but I agree not totally clear - suggestions @JDWoodcock ? seems ok-enough to me?

Ah ok. Missed that somehow. Thanks @AnnaGoodman1. I think then it's fine. Although, personally, I'd prefer some sort of tooltip or info box as part of the interface, to display this info. What do you think?

**Comment by JDWoodcock** [comment]
i think ideally it would have a tool tip or similar- I notice with the line it gives the £ related to deaths but I think this should be ylls?

also in the line ordering could it say co2/car distance - as these are equivalent in terms of how we have calculated them.

**Comment by AnnaGoodman1** [comment]
@JDWoodcock : on the line, we agreed to have no. death and the YLL £ value associated with that - as deaths what people more familiar with. still ok?

**Comment by AnnaGoodman1** [comment]
@usr110 , are tool tips possible on the individual choices in drop-down lines?

**Comment by AnnaGoodman1** [comment]
see new PR for @usr110 .  

I thought could write **Health economic benefit (mortality+sick leave)**
  - @JDWoodcock , what message do you think? mortality was trying to fudge both deaths/YLL concept. Or we could swap to presenting YLL not deaths in lines, but that has own challenges & I think I like as is
  - @usr110, when we agree what the label should be, it currently is too narrow - can the dropdown box be wider? Or James any suggestion for a label that will fit?


![image](https://user-images.githubusercontent.com/11818225/69428705-c8afb500-0d29-11ea-965a-fa7a56209dec.png)'

**Comment by usr110** [comment]
I was thinking of a tooltip for the whole subsection - `Order lines by`. 
Re the width, that surely can be managed. Recently I've been looking at the [Food Environment Assessment Tool (FEAT)](https://www.feat-tool.org.uk/feat2/), and I noticed that they have a small information icon with each inputs. I was thinking on the same lines.

![Screenshot_2019-11-22 Feat2](https://user-images.githubusercontent.com/10958628/69430390-6bb5fe00-0d2d-11ea-847e-1561527a6a09.png)


> @usr110 , are tool tips possible on the individual choices in drop-down lines?

I don't think so, I am afraid.

**Comment by Robinlovelace** [comment]
Great to see discussion of this. I think a tooltip for the whole dropdown menu would be useful. It would also be useful to put a sentence on how reduction in CO2 was calculated.

**Comment by JDWoodcock** [comment]
Scenario: Government Target (near market)
--
Isle of Wight 002 - Isle of Wight 008
Total commuters: | 722

@AnnaGoodman1 - i think it should Changes in ylls/yr 
Cyclists (baseline): | 43 (6%)
Cyclists (scenario): | 78 (11%)
Change in drivers: | -28
Change in deaths/yr: | -0.015 (£23870)
Change in days sick leave/yr: | -44.6 (£6677)
Change in CO2e (t/yr): | -6.8
Distance (km): | 6

**Comment by JDWoodcock** [comment]
@JDWoodcock , what message do you think? mortality was trying to fudge both deaths/YLL concept. Or we could swap to presenting YLL not deaths in lines, but that has own challenges & I think I like as is
- i think we should be presenting ylls as this is the metric used in TAG

**Comment by AnnaGoodman1** [comment]
@JDWoodcock ok sure, instead this yes?
![image](https://user-images.githubusercontent.com/11818225/69460190-6a0b2b00-0d6b-11ea-86ea-121c5569836b.png)

**Comment by AnnaGoodman1** [comment]
> 
> 
> I was thinking of a tooltip for the whole subsection - `Order lines by`.
> Re the width, that surely can be managed. Recently I've been looking at the [Food Environment Assessment Tool (FEAT)](https://www.feat-tool.org.uk/feat2/), and I noticed that they have a small information icon with each input section. I was thinking on the same lines.
> 
> ![Screenshot_2019-11-22 Feat2](https://user-images.githubusercontent.com/10958628/69430390-6bb5fe00-0d2d-11ea-847e-1561527a6a09.png)
> 
> > @usr110 , are tool tips possible on the individual choices in drop-down lines?
> 
> I don't think so, I am afraid.

ok great, short tool tip for whole section and making wider sounds good. could you do taht on top of my open PR? https://github.com/npct/pct-shiny/tree/order-lines-tweaks

**Comment by usr110** [comment]
> ok great, short tool tip for whole section and making wider sounds good. could you do taht on top of my open PR? https://github.com/npct/pct-shiny/tree/order-lines-tweaks

Sure. Will have a look. Did you create a PR? For some reason, it's not appearing in the list: https://github.com/npct/pct-shiny/pulls

**Comment by AnnaGoodman1** [comment]
sorry, now here https://github.com/npct/pct-shiny/pull/816

**Comment by JDWoodcock** [comment]
yes that looks great. Minor point i think a comma - thousand separator would make the numbers easier to read. Ylls won't be widely understood but then 0.0002 of a death is not clear to people either and these are the metrics in use.

**Comment by JDWoodcock** [comment]
and I think having the sickness absence in a big plus

**Comment by AnnaGoodman1** [comment]
" Minor point i think a comma - thousand separator would make the numbers easier to read. "
@usr110 , is there an easy way to tweak the number presentation function/method to do this? if not lets not worry about it

**Comment by usr110** [comment]
> " Minor point i think a comma - thousand separator would make the numbers easier to read. "
> @usr110 , is there an easy way to tweak the number presentation function/method to do this? if not lets not worry about it

Done. Please see my comment in the PR - https://github.com/npct/pct-shiny/pull/816#pullrequestreview-321922713

**Comment by AnnaGoodman1** [comment]
Great, thanks @usr110 . As far as I am concerned this is now finished and PR ready to merge into the one that will be merged into production. Anyone object?!

**Comment by Robinlovelace** [comment]
No objections from me. Great work!

**Comment by usr110** [comment]
> Great, thanks @usr110 . As far as I am concerned this is now finished and PR ready to merge into the one that will be merged into production. Anyone object?!

Thanks. I've accepted your `PR`. Perhaps give sometime - an hour or so, to see if everything looks fine on the the `test-server`, and then merge the changes in the `production` branch.

**Comment by Robinlovelace** [comment]
Closing as not on production. The result looks like this:

![image](https://user-images.githubusercontent.com/1825120/69747238-e58b2480-113d-11ea-9378-4220a45e48d9.png)

**Comment by Robinlovelace** [comment]
I think the links between headings and values could be clearer (e.g. with coloured rows) and that the two rows shown in the table above are too far apart. Worth opening a separate issue @AnnaGoodman1 / @usr110 ? It's certainly a great improvement on what was there before but there is always potential to further improve things. Wish I'd spotted those minor issues ealier.
