### ISSUE TITLE
Add blogpost on commute-schools layer

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#819]
Heads-up @AnnaGoodman1 I'm writing this now...

Will use this image:

![image](https://user-images.githubusercontent.com/1825120/72727541-0e9ac500-3b83-11ea-918e-7757af43348e.png)

**Comment by Robinlovelace** [comment]
Correction, this one: 
![image](https://user-images.githubusercontent.com/1825120/72727608-443fae00-3b83-11ea-9dc1-90c50efac927.png)

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/72728008-435b4c00-3b84-11ea-927f-f39d3044f8dd.png)

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/72728631-baddab00-3b85-11ea-864b-b95e2fe552f3.png)

**Comment by Robinlovelace** [comment]
Heads-up, draft is available here (only visible to site admins): https://blog.pct.bike/2020/01/24/overlaying-commute-and-school-route-network-layers-to-estimate-whole-network-cycling-potential/

**Comment by Robinlovelace** [comment]
Also see #818 that updates the report.

**Comment by AnnaGoodman1** [comment]
ok great, remember to make PR linking to blog post from PCT landing page, under what's new, e.g. titled 'New reports and case studies'. RElevant file at https://github.com/npct/pct-shiny/blob/master/regions_www/index.html

**Comment by Robinlovelace** [comment]
Aha yes good point, can close this issue when that's done and this goes live. Was thinking of publishing on Thursday.

**Comment by AnnaGoodman1** [comment]
Great. @RachelAldred , Robin is writing this blog on the commute schools report. Do you want to write one on the case studies? No need for you too, but you could if you wanted  - or potentially add a para at end Robin's blog just to say 'also these are newly available'? Whatever you prefer...

**Comment by Robinlovelace** [comment]
Note to self, add the item to What's new. cc @nikolai-b (and feel free to add it to master + prod, sorry I forgot about this).

**Comment by Robinlovelace** [comment]
But will only go live on Monday, so suggest we save that until then, and then this issue can be closed.
