### ISSUE TITLE
interface is crashing and I am demoing at 2pm

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#82]
okay so Norfolk just crashes straight away from welcome page."application unexpectedly exited" .

GM works to start with then crashes when I zoom in.

**Comment by JDWoodcock** [comment]
thanks, Norwich is now working. But still crashes when one moves between areas on the map. However, I think we need a new solution here -as more areas get added. Perhaps we could have a little dot you click at the centre of each area that brings in the data- can open as new issue if now is right time to think about this?

**Comment by Robinlovelace** [comment]
Hi James, please open a new issue for this with screen shots and a reproducible example. That will make this new issue easier to diagnose and fix - suspect it's something more complex that @nikolai-b and @usr110 are better placed to fix than me. Hence renaming and re-closing this for now.
