### ISSUE TITLE
Advanced training webinar

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#841]
Opening this issue to discuss advanced training webinar. I plan to base it on an updated version of this: https://itsleeds.github.io/pct/articles/pct_training.html

Pencilled in for 22nd October.

Any comments welcome.

**Comment by nikolai-b** [comment]
Can we close this now @Robinlovelace ?

**Comment by Robinlovelace** [comment]
It's not been delivered yet, was postponed until 12th November - assuming that plan goes ahead.
