### ISSUE TITLE
Accessibility statement on production

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#848]
Superseding this: https://github.com/npct/pct-shiny/pull/847 

> This is a starter for 10. I think before merging it should have:

* [x]  Link from main page
 
* [x]  css?
 
* [x]  anything else?

**Comment by Robinlovelace** [comment]
Just checked on the test site and it looks great. Excellent work @nikolai-b! Will merge to master now, doubt there are many PCT users before 08:00!!

**Comment by nikolai-b** [comment]
This was merged into production in #849 with the link in the top nav:

![image](https://user-images.githubusercontent.com/1825120/93851970-0a422100-fca9-11ea-929b-254010feb3ed.png)

I missed the emails from @JDWoodcock, @RachelAldred and @AnnaGoodman1 that it would be better in the `about` page only, and not in the top nav.  I'm happy to move it there, where exactly on the `about` page do we want it?

**Comment by Robinlovelace** [comment]
Between the Scope and Contact sections I suggest: 

![image](https://user-images.githubusercontent.com/1825120/93910040-74ce7d80-fcf8-11ea-9714-5cb0091ab95d.png)

**Comment by nikolai-b** [comment]
So:

### Scope, limitations and liability
...

### Accessibility statement for pct.bike

The accessibility statment can be found [here](https://www.pct.bike/tabs/accessibility.html).

### Contact Us

...

**Comment by Robinlovelace** [comment]
Looks good to me. I think it (just about) deserves its own (very short) section!

**Comment by Robinlovelace** [comment]
> So:
> ### Scope, limitations and liability
> 
> ...
> ### Accessibility statement for pct.bike
> 
> The accessibility statment can be found [here](https://www.pct.bike/tabs/accessibility.html).
> ### Contact Us
> 
> ...

I suggest calling the section simply 

## Accessibility statement

Though

**Comment by mvl22** [comment]
Never make “here” or “click here” the clickable text... it is terrible for accessibility, because a screen readers will read through the available navigation links and just say “here” which means nothing.

Link texts should make sense standalone without having to read the whole paragraph around it.

**Comment by mvl22** [comment]
Use instead

Our _accessiblity statement_ for the site is available.

The the screen reader will read out “accessibility statement”.

**Comment by Robinlovelace** [comment]
Great advice @mvl22, thanks for the follow-up.

How about going a step further and suggest saying: 

## Accessibility statement

The accessibility statment can be found at https://www.pct.bike/tabs/accessibility.html.

?

And do you have any thoughts on the use of Jekyll? Seems to add complexity with limited benefits but open to hearing of other factors that may sway the benefit:cost ratio of the suggested change in the other direction: https://github.com/npct/pct-shiny/pull/851

**Comment by mvl22** [comment]
No, that's just as terrible. The speech reader's link list will now read out

h t t p s colon slash slash w w w dot p c t
etc.

as the link text...

Bare URLs as clickable links are a general no-no even for visual readers.

**Comment by Robinlovelace** [comment]
Point well made, agreed. So 

The [accessibility statement](https://www.pct.bike/tabs/accessibility.html) is available.

**Comment by Robinlovelace** [comment]
And there's still the question of using Jekyll for the website. I'm not convinced.

**Comment by mvl22** [comment]
> And there's still the question of using Jekyll for the website. I'm not convinced.

I suggest opening a separate issue on that, as that doesn't sound like it's got anything to do with the question of an accessibility statement.

**Comment by Robinlovelace** [comment]
Final follow-up on the most recent changes removing link form navbar. 

Before

![image](https://user-images.githubusercontent.com/1825120/94067037-319e0880-fde5-11ea-84db-092d03218225.png)


After

![image](https://user-images.githubusercontent.com/1825120/94067095-44184200-fde5-11ea-8613-8e2955fec0c2.png)


Before

![image](https://user-images.githubusercontent.com/1825120/94067159-5c885c80-fde5-11ea-8a0a-8112dee31db5.png)


After

![image](https://user-images.githubusercontent.com/1825120/94067261-85a8ed00-fde5-11ea-96a1-4fb84c8a0383.png)

**Comment by usr110** [comment]
Thanks for all the work and sorry for not being active.

Just saw the changes on the test-server. 

Might have already been discussed, so apologies in that case, but why isn't `accessibility statement` simply a subsection of `about` page? 

Right now it takes you to a different page which I find slightly confusing.

**Comment by AnnaGoodman1** [comment]
I see it is now under about section, that is great, thanks

**Comment by Robinlovelace** [comment]
Closing again as I think this has been done. Regarding your comments @usr110 

> Might have already been discussed, so apologies in that case, but why isn't accessibility statement simply a subsection of about page?

Yes this has been discussed. We were asked to provide a self-standing accessibility statement. If you have any further comments/suggested changes let me know and I'm happy to revisit this issue if there are any further issues.
