### ISSUE TITLE
Greater Manchester crashing

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#85]
hi, 
it was always a bit unstable but is now crashing instantly 

"The application unexpectedly exited.

Diagnostic information has been dumped to the JavaScript error console"

Given we have sent it to the TfGM people would be great if it could be a bit more stable.
james

**Comment by Robinlovelace** [comment]
Fixed by https://github.com/npct/pct-data/commit/f2021042d840993448bfe69d06511d3023d6d02b - may take a few minutes for the server to update.
