### ISSUE TITLE
Link of organizations uses a dead link on accessibility statement

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#855]
![Screenshot_2020-09-24 The Propensity to Cycle Tool Accessibility Statement](https://user-images.githubusercontent.com/10958628/94134122-7f545880-fe59-11ea-9c19-d85d743062de.png)

All three links point to https://www.pct.bike/tabs/about.html which doesn't exist

Was that intended?

**Comment by Robinlovelace** [comment]
Well spotted @usr110.

**Comment by Robinlovelace** [comment]
Heads-up @usr110 I've fixed it here: https://github.com/npct/pct-shiny/pull/856

Tested locally. We can double check on the test server when this is merged (please do so as appropriate, I noticed a superfluous html file in there, heads-up @nikolai-b also, we should have checked for deadlinks introduced by #851 I think).

**Comment by Robinlovelace** [comment]
Fixed on test server:

![image](https://user-images.githubusercontent.com/1825120/94270752-7ab2a180-ff38-11ea-9622-8d3e4a5f3912.png)


Reopening because it's not yet on production.
