### ISSUE TITLE
Region stats tab on PCT.bike shows wrong data

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#859]
https://www.pct.bike/m/?r=avon

![image](https://user-images.githubusercontent.com/1825120/96588643-d3791e00-12db-11eb-9032-7aca6fc038c5.png)

Heads-up @AnnaGoodman1 any ideas what the cause is?

**Comment by AnnaGoodman1** [comment]
Argh, sorry. That is not the message we want to send re gender equality.  Fixed here https://github.com/npct/pct-shiny/pull/860.  Could @Robinlovelace  / @nikolai-b  merge and push to live when convenient?

**Comment by Robinlovelace** [comment]
Great work @AnnaGoodman1, in the updated version I see this for Avon, a definite fix, great work. What caused the issue do you know?

![image](https://user-images.githubusercontent.com/1825120/96741751-14dffb00-13ba-11eb-8e3d-b1bb84d4943a.png)

**Comment by Robinlovelace** [comment]
Fixed on test server: 

![image](https://user-images.githubusercontent.com/1825120/96775008-c85ae680-13de-11eb-9d09-3751af476132.png)

**Comment by usr110** [comment]
Fixed on live server as well. Great work @AnnaGoodman1! Thanks for spotting and creating PRs @Robinlovelace
