### ISSUE TITLE
Highlight route network segment when the user clicks on it

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#86]
@nikolai-b you were right: we do need this for `rnet` also: it's currently not clear where one segment ends and the next begins. Please can you use your JS interface wizardry to look at this at some point (perhaps next time you find yourself heading to London :)

**Comment by usr110** [comment]
Partially resolved this issue by highlight only a segment of a route by: https://github.com/npct/pct-shiny/commit/15da107afd09151e971cc3156133d28905a6d2e4.
Further works needs to be done if we want to highlight the whole route or not.

**Comment by Robinlovelace** [comment]
Thanks @usr110 this is sufficient solution for now - closing but we can always re-open. And thanks for pushing to production!
