### ISSUE TITLE
Impact report 2020

### ISSUE THREAD

**Issue by nikolai-b** [npct/pct-shiny#863]
From @RachelAldred 

> The 2020 PCT impact report – it’s here: [2020-pct-impact-report.pdf](https://github.com/npct/pct-shiny/files/5592634/2020-pct-impact-report.pdf)
> 
> I’d suggest on the Manual page, under ‘Other reports’ – it could go above ‘Use of the PCT (Nov 2019)’ perhaps labelled ‘Use of the PCT (Nov 2020)’ We can leave the old version up so people can compare if they want. Once it’s online it’ll be easier for our various universities to point to it as part of their demonstration of ‘impact’.

**Comment by nikolai-b** [comment]
@RachelAldred given it is titled Impact report would you mind if I called it that in the link instead of "Use of the PCT"?  At first glance "use" reads like how to use the PCT instead of usages of the PCT.

**Comment by RachelAldred** [comment]
Yes this sounds good @nikolai-b , thank you :)
