### ISSUE TITLE
New case study on production

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#868]
This should just involve merging this: https://github.com/npct/pct-shiny/pull/867

However, I cannot see the update case study from #866 here: http://npct0.vs.mythic-beasts.com/manual.html#casestudies

Ideas @nikolai-b ?

**Comment by nikolai-b** [comment]
Yes, we need to use the Jekyll, see https://github.com/npct/pct-shiny/commit/f64ac2997f0ff0ea440309025416f5e8e9bf8954
