### ISSUE TITLE
Add IMD data layer to the map

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#87]
I think an additional layer with some combination of these will look great (thanks @oobrien for these):

The URL for the IMD 2015 choropleth is: http://tiles.oobrien.com/imd2015_eng/{z}/{x}/{y}.png 
The URL you need for the buildings is: http://tiles.oobrien.com/shine_urbanmask_dark/{z}/{x}/{y}.png 
The URL you need for the labels is:  http://tiles.oobrien.com/shine_labels_cdrc/{z}/{x}/{y}.png

You up for giving at a bash @usr110?

Otherwise happy to give it a go.

**Comment by usr110** [comment]
Added only the choropleth for now; haven't pushed it on the server. See here for details: https://github.com/npct/pct-shiny/commit/d9791a49be5eecc33171b4d22c82e3ccf5aee446

**Comment by Robinlovelace** [comment]
Great progress Ali - I've tested it and it works fine. Is it possible to add a hyperlyink/hover message to the label linking to this: http://maps.cdrc.ac.uk/#/geodemographics/imde2015/ ? I tried with `a()` but to no avail...

**Comment by oobrien** [comment]
If you are interested in the Scottish IMD for 2012 then it's now at http://tiles.oobrien.com/imd2012_sco/{z}/{x}/{y}.png

**Comment by JDWoodcock** [comment]
This needs a legend

**Comment by Robinlovelace** [comment]
One for @usr110 I think.

**Comment by usr110** [comment]
Completed it in: https://github.com/npct/pct-shiny/commit/23e8de84241e7fcea4a5d10f9da30af04e54dbe6

**Comment by Robinlovelace** [comment]
Great work Ali, will test asap.

**Comment by usr110** [comment]
Sure Robin. That'd be nice.

**Comment by Robinlovelace** [comment]
Confirmed: this looks fantastic. Ultimately I think only showing buildings would be ideal, but this is definitely good enough to be useful and to be considered 'job done' by me. + fast work!

**Comment by usr110** [comment]
Thanks Robin for testing it out.
