### ISSUE TITLE
IMD tileserver changes

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#884]
From @oobrien, many thanks for the heads-up on this, we can communicate on the issue and solution here.

Hi Robin

 

Many apologies, but the link to the IMD tiles basemap at [https://www.pct.bike/m/](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.pct.bike%2Fm%2F&data=05%7C01%7CR.Lovelace%40leeds.ac.uk%7C9d9b46afd192488a358a08daad161f01%7Cbdeaeda8c81d45ce863e5232a535b7cb%7C1%7C0%7C638012607767376563%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZbUFklu%2F81AT09KqY3pX1b%2Fp7J9YraWxBJoAH5FtZiM%3D&reserved=0)  has broken again. Liverpool have unexpectedly closed the firewall on our tile server, and won’t reopen it again as it’s old. As the tileset is legacy, and there’s quite a bit of work on our side needed to modernise it, it’s not something that I can get priority for currently.

 

Specifically, these are the URLs:

[https://cdrc-maps.liv.ac.uk/tiles/shine_labels_cdrc/[Z]/[X]/[Y].png](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdrc-maps.liv.ac.uk%2Ftiles%2Fshine_labels_cdrc%2F%255bZ%255d%2F%255bX%255d%2F%255bY%255d.png&data=05%7C01%7CR.Lovelace%40leeds.ac.uk%7C9d9b46afd192488a358a08daad161f01%7Cbdeaeda8c81d45ce863e5232a535b7cb%7C1%7C0%7C638012607767376563%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Ige73DK7Hpkq0UQeIVSF3rz%2BerIIayS89O7ehrKzZF8%3D&reserved=0)

[https://cdrc-maps.liv.ac.uk/tiles/shine_urbanmask_dark/[Z]/[X]/[Y].png](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdrc-maps.liv.ac.uk%2Ftiles%2Fshine_urbanmask_dark%2F%255bZ%255d%2F%255bX%255d%2F%255bY%255d.png&data=05%7C01%7CR.Lovelace%40leeds.ac.uk%7C9d9b46afd192488a358a08daad161f01%7Cbdeaeda8c81d45ce863e5232a535b7cb%7C1%7C0%7C638012607767376563%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vubjC3Sk5ISFcigCosQItmHgVkTXtx68fRjRKBhGXYI%3D&reserved=0)

[https://cdrc-maps.liv.ac.uk/tiles/imd2015_eng/[Z]/[X]/[Y].png](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdrc-maps.liv.ac.uk%2Ftiles%2Fimd2015_eng%2F%255bZ%255d%2F%255bX%255d%2F%255bY%255d.png&data=05%7C01%7CR.Lovelace%40leeds.ac.uk%7C9d9b46afd192488a358a08daad161f01%7Cbdeaeda8c81d45ce863e5232a535b7cb%7C1%7C0%7C638012607767376563%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=A3NhGseNggG11QKG4uH0EEXIUToX6euU5x3VgKUlsm0%3D&reserved=0)

[https://cdrc-maps.liv.ac.uk/tiles/imd2014_wal/[Z]/[X]/[Y].png](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcdrc-maps.liv.ac.uk%2Ftiles%2Fimd2014_wal%2F%255bZ%255d%2F%255bX%255d%2F%255bY%255d.png&data=05%7C01%7CR.Lovelace%40leeds.ac.uk%7C9d9b46afd192488a358a08daad161f01%7Cbdeaeda8c81d45ce863e5232a535b7cb%7C1%7C0%7C638012607767376563%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=KgACINLz1P40HVw697805OYibhJ4%2BPnjUwyjfJh4t78%3D&reserved=0)

 

The following replacements work:

[https://maps.cdrc.ac.uk/tiles/shine_labels_cdrc/[Z]/[X]/[Y].png](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmaps.cdrc.ac.uk%2Ftiles%2Fshine_labels_cdrc%2F%255bZ%255d%2F%255bX%255d%2F%255bY%255d.png&data=05%7C01%7CR.Lovelace%40leeds.ac.uk%7C9d9b46afd192488a358a08daad161f01%7Cbdeaeda8c81d45ce863e5232a535b7cb%7C1%7C0%7C638012607767376563%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jZli5q3osWORlbP%2F9nBYaxf4pLjVZGr0HMW4NOx2hCs%3D&reserved=0)

[https://maps.cdrc.ac.uk/tiles/shine_urbanmask_dark/[Z]/[X]/[Y].png](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmaps.cdrc.ac.uk%2Ftiles%2Fshine_urbanmask_dark%2F%255bZ%255d%2F%255bX%255d%2F%255bY%255d.png&data=05%7C01%7CR.Lovelace%40leeds.ac.uk%7C9d9b46afd192488a358a08daad161f01%7Cbdeaeda8c81d45ce863e5232a535b7cb%7C1%7C0%7C638012607767376563%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kbuOQHSFzEUzsTkBFRI4EUM%2FCKczmy%2B7B3z9uQVCClM%3D&reserved=0)

[https://maps.cdrc.ac.uk/tiles/imd2015_eng/[Z]/[X]/[Y].png](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmaps.cdrc.ac.uk%2Ftiles%2Fimd2015_eng%2F%255bZ%255d%2F%255bX%255d%2F%255bY%255d.png&data=05%7C01%7CR.Lovelace%40leeds.ac.uk%7C9d9b46afd192488a358a08daad161f01%7Cbdeaeda8c81d45ce863e5232a535b7cb%7C1%7C0%7C638012607767376563%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2Be5NH1NyfRErE2NNoHWOpXulc24WK5YVTqOUOodEsPc%3D&reserved=0)

[https://maps.cdrc.ac.uk/tiles/imd2014_wal/[Z]/[X]/[Y].png](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmaps.cdrc.ac.uk%2Ftiles%2Fimd2014_wal%2F%255bZ%255d%2F%255bX%255d%2F%255bY%255d.png&data=05%7C01%7CR.Lovelace%40leeds.ac.uk%7C9d9b46afd192488a358a08daad161f01%7Cbdeaeda8c81d45ce863e5232a535b7cb%7C1%7C0%7C638012607767376563%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kGo8R4fJ40eRPG06s2BSXyXSXgZfGLIHh7wkzH7NhMM%3D&reserved=0)

 

Working examples:

[https://maps.cdrc.ac.uk/tiles/shine_labels_cdrc/11/1001/672.png](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmaps.cdrc.ac.uk%2Ftiles%2Fshine_labels_cdrc%2F11%2F1001%2F672.png&data=05%7C01%7CR.Lovelace%40leeds.ac.uk%7C9d9b46afd192488a358a08daad161f01%7Cbdeaeda8c81d45ce863e5232a535b7cb%7C1%7C0%7C638012607767376563%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TRa6yeI6CngYItAeqbWb9pDLtxnwQ5NeITOXkF6ofqk%3D&reserved=0)

[https://maps.cdrc.ac.uk/tiles/shine_urbanmask_dark/11/1001/672.png](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmaps.cdrc.ac.uk%2Ftiles%2Fshine_urbanmask_dark%2F11%2F1001%2F672.png&data=05%7C01%7CR.Lovelace%40leeds.ac.uk%7C9d9b46afd192488a358a08daad161f01%7Cbdeaeda8c81d45ce863e5232a535b7cb%7C1%7C0%7C638012607767376563%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3KpFISu4ETb2KqI0s1m%2Fwq%2BSP4kI19GVTUUsFSdHeu4%3D&reserved=0)

[https://maps.cdrc.ac.uk/tiles/imd2014_wal/11/1001/672.png](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmaps.cdrc.ac.uk%2Ftiles%2Fimd2014_wal%2F11%2F1001%2F672.png&data=05%7C01%7CR.Lovelace%40leeds.ac.uk%7C9d9b46afd192488a358a08daad161f01%7Cbdeaeda8c81d45ce863e5232a535b7cb%7C1%7C0%7C638012607767376563%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lsIarplAyCTEgcGkHidlNrFtTVQzWvmbpLOJOWvyKsM%3D&reserved=0)

 

The link for the IMD tiles that were used on PCT.bike has changed once again (remember back in 2017 they broke) – however looking at the current version of PCT.bike, it looks like you removed them anyway a while back. Is this correct? If so I’ll update our notes here. If not, let me know and I’ll fix it so they are back for you again.

 

Both the English and the Welsh IMDs have had new versions of the data published, however unfortunately we don’t’ have tiles for those, as these we put our new mapping output on Mapmaker: [https://mapmaker.cdrc.ac.uk/#/index-of-multiple-deprivation](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmapmaker.cdrc.ac.uk%2F%23%2Findex-of-multiple-deprivation&data=05%7C01%7CR.Lovelace%40leeds.ac.uk%7C9d9b46afd192488a358a08daad161f01%7Cbdeaeda8c81d45ce863e5232a535b7cb%7C1%7C0%7C638012607767376563%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QIyhHIvgbmP1DJt2HZyWZf4w3qa2yp66Vfxr%2B4iIqc4%3D&reserved=0) - ideally you would be able to link to these instead, however they are PBF vector tiles.

**Comment by Robinlovelace** [comment]
As demonstrated below, the tiles no longer work: 

![image](https://user-images.githubusercontent.com/1825120/195598298-37d343fe-3831-4b46-87f0-7d29d35ba23d.png)

I think it's just a case of updating the links to 

> The following replacements work:
> 
> [https://maps.cdrc.ac.uk/tiles/shine_labels_cdrc/[Z]/[X]/[Y].png](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmaps.cdrc.ac.uk%2Ftiles%2Fshine_labels_cdrc%2F%255bZ%255d%2F%255bX%255d%2F%255bY%255d.png&data=05%7C01%7CR.Lovelace%40leeds.ac.uk%7C9d9b46afd192488a358a08daad161f01%7Cbdeaeda8c81d45ce863e5232a535b7cb%7C1%7C0%7C638012607767376563%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jZli5q3osWORlbP%2F9nBYaxf4pLjVZGr0HMW4NOx2hCs%3D&reserved=0)
> 
> [https://maps.cdrc.ac.uk/tiles/shine_urbanmask_dark/[Z]/[X]/[Y].png](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmaps.cdrc.ac.uk%2Ftiles%2Fshine_urbanmask_dark%2F%255bZ%255d%2F%255bX%255d%2F%255bY%255d.png&data=05%7C01%7CR.Lovelace%40leeds.ac.uk%7C9d9b46afd192488a358a08daad161f01%7Cbdeaeda8c81d45ce863e5232a535b7cb%7C1%7C0%7C638012607767376563%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kbuOQHSFzEUzsTkBFRI4EUM%2FCKczmy%2B7B3z9uQVCClM%3D&reserved=0)
> 
> [https://maps.cdrc.ac.uk/tiles/imd2015_eng/[Z]/[X]/[Y].png](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmaps.cdrc.ac.uk%2Ftiles%2Fimd2015_eng%2F%255bZ%255d%2F%255bX%255d%2F%255bY%255d.png&data=05%7C01%7CR.Lovelace%40leeds.ac.uk%7C9d9b46afd192488a358a08daad161f01%7Cbdeaeda8c81d45ce863e5232a535b7cb%7C1%7C0%7C638012607767376563%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2Be5NH1NyfRErE2NNoHWOpXulc24WK5YVTqOUOodEsPc%3D&reserved=0)
> 
> [https://maps.cdrc.ac.uk/tiles/imd2014_wal/[Z]/[X]/[Y].png](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmaps.cdrc.ac.uk%2Ftiles%2Fimd2014_wal%2F%255bZ%255d%2F%255bX%255d%2F%255bY%255d.png&data=05%7C01%7CR.Lovelace%40leeds.ac.uk%7C9d9b46afd192488a358a08daad161f01%7Cbdeaeda8c81d45ce863e5232a535b7cb%7C1%7C0%7C638012607767376563%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kGo8R4fJ40eRPG06s2BSXyXSXgZfGLIHh7wkzH7NhMM%3D&reserved=0)

**Comment by oobrien** [comment]
@Robinlovelace Ta I've put a PR on this.

**Comment by Robinlovelace** [comment]
Update here, does not seem to be working on test server: http://npct0.vs.mythic-beasts.com/m/?r=isle-of-wight

Any ideas why @nikolai-b or anyone?

**Comment by Robinlovelace** [comment]
I've done some tests with the network inspector in Firefox. It seems that the IMD tile endpoints are not alive, e.g.: https://cdrc-maps.liv.ac.uk/tiles/shine_labels_cdrc/10/512/344.png

Any idea what's going on here @oobrien ?

**Comment by Robinlovelace** [comment]
In case it helps identify anything obvious, here's the screenshot of the debugging effort. Missing anything? 
![image](https://user-images.githubusercontent.com/1825120/195641478-43d894b6-84d4-4963-b63b-01161c25b974.png)

**Comment by oobrien** [comment]
@Robinlovelace That's using the old URL that was bocked - my file replaces it with the new URLs, but maybe there's another file that needs to be configured.

**Comment by Robinlovelace** [comment]
Ah apologies, my bad.

**Comment by Robinlovelace** [comment]
It seems the test server is not auto updating. Will try merging to production... Heads-up @nikolai-b and @usr110.

**Comment by Robinlovelace** [comment]
This is now fixed :tada: 

Massive thanks to Ollie on this :pray: 

![image](https://user-images.githubusercontent.com/1825120/195706806-0587886c-51ab-48fe-b7b2-2c742f31fd23.png)
