### ISSUE TITLE
Network analysis default

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#89]
On the network analysis, could have the default be e.g. 50% of lines (if this can be fast enough).

Could also think of ways of tidying up the small fragments of lines near MSOAs/in general, e.g. have a minimum length of ?500metres

**Comment by Robinlovelace** [comment]
Good suggestions @AnnaGoodman1. Thanks for documenting them - I think both are good ideas.

**Comment by usr110** [comment]
Thanks @AnnaGoodman1 for the points. I now have changed the slider's default value to 50 percent for routes here - https://github.com/npct/pct-shiny/commit/f75d8521a8a2c9356c6e81646b8e89083a6b69f9

As for the other point, I believe, @Robinlovelace needs to change when the data is being produced to exclude routes closer to the MSOA's centroids.

**Comment by Robinlovelace** [comment]
Yes this is true - it's a data level problem, flagged here: https://github.com/npct/pct/issues/11

**Comment by Robinlovelace** [comment]
@usr110 please push to production so Anna can see this

**Comment by usr110** [comment]
@Robinlovelace Sorry but found a bug with the commit; hence removed it at: https://github.com/npct/pct-shiny/commit/c3e79e6d784761c0d5b3853cf405522f13f7a8da. Still need to figure out how to adjust the slider depending on the selected cycling flows.

**Comment by usr110** [comment]
@Robinlovelace as for production, I thought we were sticking towards a rather periodic push onto the server. Correct me if I am wrong? I personally prefer unless if not all, at least two of us test the new functionality out, then we can push to the server. What do you @nikolai-b think?

**Comment by Robinlovelace** [comment]
@usr110 I see your point. I think your suggested workflow is ideal for the Phase II production version. I envisage running a mirror of that on a test server (e.g. webarch.net) which we all push to - that way people without pct-shiny running locally like Rachel and Anna can take a peak and see that it's fixed. For big changes of course we should test but most of the recent commits are quite safe and minor and merit being pushed. That's my view - agree @nikolai-b your input would be welcome here. Ps ta for re-opening, in relation to the 500m short lines.

**Comment by nikolai-b** [comment]
I'd prefer to get things we are reasonably happy with out on the server.  If it breaks we can fix it.  I think I might have been in favor of a sign off thing before but it seems like a hassle (there is no way of marking a commit as signed off).  That said if someone comes up with an easy way of approving commits then lets do that.
I don't think a default of 50% is going to be technically easy, can we close this and come back to it if it gains importance?  The other thing is a data issue and Robin has a ticket for it already.

**Comment by Robinlovelace** [comment]
Agreed @nikolai-b - I suggest pushing to production. Nor is 50% sensible so we can close now that I've increased the default to 10.
