### ISSUE TITLE
Make number/% of lines text 

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#93]
This text

```
Number of lines or % of network
```

should change to

```
Number of lines or % of network
```

or 

```
% of network
```

depending on whether the route network is being displayed or not.

Thanks @usr110 for flagging this.

**Comment by usr110** [comment]
Fixed by making the label dynamic. If the flow is routes, the label changes into "percent of network", otherwise, it shows, "number of lines".

https://github.com/npct/pct-shiny/commit/f75d8521a8a2c9356c6e81646b8e89083a6b69f9

**Comment by Robinlovelace** [comment]
Amazing work Ali - I didn't know Shiny could do that. :+1:

**Comment by Robinlovelace** [comment]
P.s. @usr110 Please always push to production unless there is a reason not to (in which case add 'Not pushed to production' in the commit). @nikolai-b and all agreed that this is a good workflow, right? Great work in any case.
