### ISSUE TITLE
DfT logo & welcome page

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#97]
hi
please can you remove this from bottom of page (it just gets in way) and put a small logo on the top of right next to FAQs.

Also please put a blank line between paragraphs on the welcome page.

**Comment by usr110** [comment]
Removed the DfT logo from the main page - https://github.com/npct/pct-shiny/commit/3637fca489c2674a19b20016eccb1fd83a0efa50. Rest to be done.

**Comment by nikolai-b** [comment]
No logo's in the navigation please.

**Comment by Robinlovelace** [comment]
I second that @nikolai-b

**Comment by JDWoodcock** [comment]
okay agree- maybe remove for now and see if being on welcome and about pages is sufficient.
thanks,
